### ISSUE TITLE
Add the connection indicator to the Beam icon on the Assets Swaps screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-ui#1000]
Add the connection indicator (online Integrated Node, online Remote Node, Connection to BEAM node lost: {node address} etc.) to the Beam icon on the Assets Swaps screen.
![image](https://user-images.githubusercontent.com/83376495/194263313-d35a2666-9ec9-47e2-9ab1-9c1ea82987c1.png)
![image](https://user-images.githubusercontent.com/83376495/194263199-a9a321aa-5965-43fe-826f-152ac4be69b6.png)
![image](https://user-images.githubusercontent.com/83376495/194263253-51406157-ac03-4960-b7c7-84f79e771e00.png)
![image](https://user-images.githubusercontent.com/83376495/194263276-bf0d175b-4638-4bd5-b02e-5c900dcea2e9.png)

**Comment by KatsiarynaV** [comment]
Checked
