### ISSUE TITLE
Add token type to "show token" 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#101]
Need discuss about add "token type" in "show token" https://zpl.io/bPJjKvm
![8](https://user-images.githubusercontent.com/50007056/88658218-c208e700-d0db-11ea-9809-cccb34b7479a.png)

**Comment by anatolse** [comment]
fixed in https://github.com/BeamMW/beam-ui/commit/8aa3273a466a25ff80c483e01d296997438e81c9

**Comment by Roberrtt** [comment]
on design
Token type - Online\Offline and + counter
add Transaction expiration - one-time use\pernament
![Screenshot_123](https://user-images.githubusercontent.com/50007056/89511877-206c4e80-d7db-11ea-9a1e-d9bb7b6872ba.png)

**Comment by anatolse** [comment]
voucher counter should be solved with https://github.com/BeamMW/beam-ui/issues/133

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9485.3085
