### ISSUE TITLE
New Send screen - the amount doesn't change when switching to max. privacy

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#102]
**Bug description**
When you add all amount and change type transaction to max. privacy, the fee changes, but the amount (minus the fee) doesn't change. If the user did not change the amount manually after clicking the "add all" button, the amount should change automatically when the fee is changed.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to "Send" screen.
2. Open the "TRANSACTION FEE" section. The default value is 100 GROHT.
3. Click  "add all" button. Displayed the entire amount that is on the balance minus the fee.
4. Change switcher on "Max privacy".

 **Current behaviour:**
After the change, the transaction type, the transaction fee increases, but the amount has not changed.

**Expected behaviour:**
After changing the transaction type, the transaction fee increases, the amount displayed also changes taking into account the changed fee. 

**Platform and build:**

- Windows
- OS version: 10 pro
- BEAM Build number: 5.0.9332.2996.

**Video (if applicable)**
![2923470C-F5C9-494A-8D48-B4A3635D01AB](https://user-images.githubusercontent.com/45556620/88664041-211f2980-d0e5-11ea-91d1-3ebaec53cb1d.GIF)

**Comment by echoby** [comment]
not actual after 6.0

**Comment by KatsiarynaV** [comment]
When user add max in the amount field and switches from offline to regular transaction type the amount doesn't increase automatically. The fee is added to the change
![gif02](https://user-images.githubusercontent.com/68267190/121181703-f9ebc980-c86a-11eb-9fcf-f063805ea37d.gif)

**Comment by KatsiarynaV** [comment]
Checekd
