### ISSUE TITLE
New receive screen - pop-up for the Regular permanent token has blank and duplicate fields

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#105]
Pop-up for the **Regular** permanent token (never expired) has blank and duplicate fields
![image](https://user-images.githubusercontent.com/44496108/88768346-a0633a80-d183-11ea-9fad-3bba0382faea.png)
As it information common for the market we can remove blank fields as we don't give amounts for the market wallet.
Also the information into field **Token** has the same SBBS address as in the field **Address** this looks like an overload for pop-up and can cause inconvenience and misunderstanding for users.
Let's combine somehow these fields to one, for example, **Address/Token:**

**To DO:**
- delete blank fields
- combine 2 fields to one

Steps:
- open wallet
- navigate to receive screen
- Click "Switch to permanent token" under the QR code in the left corner
- Click "Show token"
- check field into the pop-up
AR: pop-up for the permanent token has blank and duplicate fields
EX: pop-up has enough information to give it to the market

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9371.3026
