### ISSUE TITLE
New Send screen - when you insert an offline token of the text overlaps each other.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#107]
**Note:** 
The version of the wallet that generated token -5.0.9335.3002.
The version of the wallet where the token is inserted -5.0.9332.2996.

**Bug description**
When inserting an offline token generated by another wallet in the "Transaction info" field the text overlaps with each other.

![image](https://user-images.githubusercontent.com/45556620/88774936-b9bcb480-d18c-11ea-8776-5633b83a9c91.png)
Example of an offline token:
6GLrAGZkaLSi7gCzzhbszxmv7M8GtoK7HftYk4NTA9woNQ65gNuSpCWATATPZ1CQFaXwTssteoFsCJ1FKNpjyzG85UB92XMSPj3zUTS7Xy7FXSCjJXBxaxMewqCwh23nq773TcnhQE8Go31MJBWdvc4LVMPAWeGBZxAX6YiJCamKeCgogPxPXAD93qUaHAJdqJ5bczZ3YBvG7pCY26cXL8U7q7m6JeVtzDQXvAYAj1e6zUrDnuHXXVK7PPqb1gT9NsDSxue8d9QbP44cFickDdBWLzu3tqR286NzQFYV3fgbpeaTNS25eBqa9fxUpsWSLRsT3smWSKAtdA411zomeX3SneLfNzWq42f1wbW1vFd4oRJkPGUxqkjVpZ2KtYPyCY55StgbahFvPMrfyBbur6dKRMznNEeeTDR1244wF4JrUFvw5DCZaXash4CoWGtWKjKVDvr9gLU2xoAG3FKEU3LC48SmcfzrfTQNFGbzUPkaSMfmAviDa2umWjd99zzsSuxQUZG1Nv1AsZF4vELaq8gvHXj6i4EtYt5PaNi5XnpGRdV2Ck4UYW17XH4AtRvavMu3cWM4znMhW9iu5bqcCyt9FdXfhJQaeq19Fe5nYuv15tBVctXY6MMzDpoUPx47UFKKeEGKcCm8W9UU1GfJW3b45X3LiYqUWsemfjQWdM7CFcJ82hweqMEfPCvYr1Pq6TucU1gRau2KCHekJG7oTetR27tLM4NBVZ5hBxAPGwCxRcB5SytEZGbCNZ3USw1C6mxUPd2kpjRPSbggrcTnLwD59kX6s7Y3kJrPnjzsk2iKVax9jUiN9VB21Y8QuuBgiu1W6KcL2BmTeuBq1g3gWnQHBjMJtScdWpxQToNrFPtGzBrPcLYyk3KtqFNrtxbSvCQuELoyxMVsxShMc4EPWeq3a7zqpuRkP9zPhCLvF7J8btCKCdZRDN4hzsP3nFSkoYQTHw9WzMuwEa8MSYkH3GZqeohaxLUFvfMCdcdFD5MJEDXBE3aJp8GR25Br9i25jEDAnfAPbh2WNxuacU2x6Pv1JxzhSrTFoXJBEt2hSkFRb4oXoNpUZieJfTcyVRghoKYNPRjkDNEbjFz8zQK8fwsMMyyBYNMAdpGSJKKxHcPJ1BmV9tq7KKPxnQPjJj6JxsQPr5kMnY9yCYfLkEWATz1SKm69qbMa7GoEEqPiY1dPh4ZuSHZRJ9E3ZbxAJdyn2pzGdqJou976e2JPDzfJsmrcuL8LTXVBSmNneumofNNutKCKxBvA1buNDch2Skq1sDAW3xQvvJVM4P7UuQYTcCX3qG4bg22bf73oBo5PqSytJbp45PhgZM2XajP6sAkdf6GhziikYUVpyTEx9URsSd8k7hYSwDuSbuuVYASAXzkR4yynUPGuhRPYzQET4iGaMNoxbVW1uc2btVQPchHqxSeV7oSsfJqeNLaeTx5aWknLWkK3nXib9G7VyvE7L3r3sic1FdpbC5nG7b1PD4dnkJ5CV1z5BoiGnTgc5vDdasBzEVYrMhA1tyyi2YPLbHbuq7NHkXC2U4DedXyvA1MkdaFnoov3VQ9t2HRQCqEHjyJsTXA718euTwFSCPQuJYZkHYFQaZnyw2M3o7ZixXGrdRa7myGydZxxW7pXb6cL5gULLcADdXKjFmcBuT7JG3bXtt12f5SigCoKFNJ4y5ic2D4eGR4dKAFzUP4Pby5khvmWdgQ8mEzjUSxPBPQsnEEhestD7BPwGL3ehnEPusw2C4AMd4xeGTwzmZTDYwKiiCYsat4iLanoopJY4UNK4SSftWhsrsbbYo9ZrqKitLnVZsPmzMtj9GDTS4DdSLXXDq3FTXL4hBVcgdsG8TLNKu8C3mJ2uiMUKG2qnPnPSEMPpQGmGhhcLVZg9fmNs9mFkAdGL2SXe9VLEJ1Y39BXX6QLUi93ceMgwZdN8vnkJuvjtDTmnK6dvYbWpAeKg3x3v362skuHUk5gPB2RrMe1N7qgkri3Sed8ytQmUgqLN8aRjYf7XJMALt9kM3GJb2uUVTVA4Cmo5PSPqeLX91RfaXRnjkj4e3gDsw86AasisZHzo3wkWQrDWy1ZwY36c7aZNLc1bfNYrdFxpbKnhyfcruqWY3js1ySZkCQtWQoqTkEH2QTQZpedka8dw4xeTfeR35zkdPQ4EmesVJA8LfGSTC3khgDSraswFrNJUdBHJF9joayac78U4LDZfpTGyV3uwhCTaE7j7yuprmM6NVEQnLYd7hsACKm1mh21fFVnGHJfZK1H3aTrJY6zyKButPPdkdXGu5bW12fpVsFQU6Bxoqx1k2iUY3khixgJK58FRARe5Aj9kJmEPUtLHLE94nTWjS5V6eZsqYfeD1snvrn57ByC6N19ZgkvH5hQq39Yi3fHoNAyRA4fyFzRNjpK9NkcWCky53CKUYhBAa9ZZPXNYcJySx6w6DMEZN5UF9Ff3n4obLdthxyMhyWUJ1uyrY6bUHohFJKCeSg4XkwaoBxujRZSmLy9YkcUrMRJxzZ4VE3XsQqcj1ZtKWEsoUMQvhmiS3GH3Y3Vri78CPLFcYqNJWNXZh9gY9rjKz3uzJG8UuCSbUo3dTYuaA7KiPC7dzAjwizDcyzqAUkENZwAVmSn7hqtk8YMJKieYc8SLdRnG6YfLWPbpudNQARJJQT2QdGTcyzUaNcxebjyrt8uWaPCkDQGZe9gSfbmwGX4HQ9hj8KqBkqku9EjDBWbn79ure4cmyuXMdwnUZ4QbsrWHmRhn1tQiBGTd7PkAu8wU1xK7Cqjq4UdKoXsuAzvakHKmUMLwAufc7sHPJCL6mKeVFdRQP7J4BCH3sVQxF425inhgHhNxFNTQWJBzrWABUZa5brxA2nBHAsJD7WLtDVm7SAYVkwNhbN59aPRdWrSJEP7MYjK2ftC98WURGuAxMtmhH7EyCP7tBPdeEQPm8Em17Lhvx9KZx6SDVgoQB6N2CvXus6MWDPQE5XFVtMRmV5WZ9jNi1bWziZfezSF8Qhi76zBUVgRV26oFaDXkugbWt4TkKKBQ4VcnoMMQJ3FjzZUstSX5XQYE8bfQdpJ77iePNkj6Vaxo7GWuZPX1YgfNZFLmS8cK2SDkd7FwH6FGUArbaEfApTuztRKtx1HvtqftXxzTDSd6Kp6XGcGTmXe8JDh4jkMVdmAd2UVRQkGossKuhWt4F6ya8AYjgYUvdFtWwbLNkuNoRnbzKvPpY5Sht6UQbdA48WTXGz8BFjaAaxfnp5A42Si4oDNkCMS5ebanWUTqmmD5ynovKrqkPMdrk

**Comment by KatsiarynaV** [comment]
checked on builds 5.0.9356.3014 and 5.0.9367.3016
