### ISSUE TITLE
New Send\Receive screen - don't display amount field if it is empty.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#108]
**Bug description**
If the user did not specify the amount in the "request" field, we should hide the amount field when "show token".
![image](https://user-images.githubusercontent.com/45556620/88780003-0c00d400-d193-11ea-939d-3935510a1652.png)
![image](https://user-images.githubusercontent.com/45556620/88780018-102cf180-d193-11ea-82c6-99d2ae2abf0d.png)

**Comment by Sergei-Beam** [comment]
Checked
Some checks are blocked by https://github.com/BeamMW/beam-ui/issues/106

**Comment by Sergei-Beam** [comment]
checked
