### ISSUE TITLE
Confirmation window when deleting an address

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#1083]
When we want to delete an address, there should be a confirmation window about the deletion

Steps;
- run wallet
- go to tab address
- click to 3 dot
- click delete
![Screenshot_285](https://user-images.githubusercontent.com/50007056/71765058-f1b68e80-2f00-11ea-90bc-81cef266eb73.png)

Expected: confirmation window about the deletion
Actual: address deleted

TODO:
- [x] create DeleteAddress.qml
- [x] add DeleteAddress.qml to qml.qrc
- [x] add Logic
- [x] remove expiration 
- [x] remove comment
- [x] center address
- [x] remove "Address"
- [x] use "delete address" qsTrId from the address book menu

**Comment by Maxnflaxl** [comment]
Looks like this right now: ![grafik](https://github.com/BeamMW/beam-ui/assets/63856008/34967e29-8c97-473b-a339-5212201dc325)

**Comment by Maxnflaxl** [comment]
looks like this now:
![grafik](https://github.com/BeamMW/beam-ui/assets/63856008/d047f7e5-8088-4c6a-9cb8-1933be821db2)

**Comment by Maxnflaxl** [comment]
final update: 
![grafik](https://github.com/BeamMW/beam-ui/assets/63856008/734efcd1-85d9-44f3-8360-aa6ea49ae8c9)

**Comment by Maxnflaxl** [comment]
![grafik](https://github.com/BeamMW/beam-ui/assets/63856008/b8381cc1-4b24-4699-a9da-406e172c189a)
