### ISSUE TITLE
Addres with the one-time use params doesn't expire after 2 hours

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#109]
If token was created with params one-time use and there were no transactions for it within 2 hours. Then after 2 hours the address should become expired

Step

- open receive screen
- copy token with params Regular and one-time use
- wait 2 hour
- go to address book

Actual: address is active
Expected: address is expired

**Comment by kazaryan-t** [comment]
Checked on master 5.0.9458.3072
