### ISSUE TITLE
Link to the faucet not working

### ISSUE THREAD

**Issue by dbadol** [BeamMW/beam-ui#1093]
**Bug description**
The link to the Faucet proposed when a new wallet is created does not work (dead link?).

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Desktop wallet
2. Create a new wallet
3. Click on the "get coins" link. Nothing happens...

**Current behaviour**
Nothing happens when clicking on "get coins".

**Expected behaviour**
The link should send us to the Beam faucet.

Remark: This issue is independent of the fact the the faucet might or might not be empty...

**Platform and build**
* Tested on Windows 10
* BEAM Build number: 7.5.13840

**Screenshots**
![image](https://github.com/BeamMW/beam-ui/assets/13353088/e2b2f78f-8413-4107-823b-205262e05c1b)

**Comment by Maxnflaxl** [comment]
That has been removed, see #1042
