### ISSUE TITLE
SBBS address note for mining

### ISSUE THREAD

**Issue by Maxnflaxl** [BeamMW/beam-ui#1099]
**Feature title**
SBBS address note for mining

**Describe the current situation we have**
"Use for CEX withdrawals"

**Describe the solution you'd like**
"Use for CEX withdrawals and mining"

**Additional context**
![grafik](https://github.com/BeamMW/beam-ui/assets/63856008/530f666f-b792-4def-985d-004cbc122717)

**Comment by kogawulf** [comment]
Can I work on this?
