### ISSUE TITLE
When "Connect other currency wallet to start trading" clicked, open the swap settings tab

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam-ui#11]
When user go to Atomic Swaps tab and click on "Connect other currency wallet to start trading"
![image](https://user-images.githubusercontent.com/28015224/71570995-21246000-2ae9-11ea-975c-4564d0804d39.png) 
it should open Swap settings
Actual: it opens General Settings tab

**Comment by chapati** [comment]
Settings were reworked, so now we have only node sections. These will be opened after click on 'Connect other currency...' link.

**Comment by Roberrtt** [comment]
Please make, if  1 of nodes is configured, button "Connect other currency wallet to start trading" will only open the settings of nodes that aren't configured.
For example,  BTC node's configured, then clicking on the "Connect other currency wallet to start trading" button opens only the settings for LTC and QTUM nodes

**Comment by Roberrtt** [comment]
The tab closes after clicking the "connect" button"

Precondition:

The wallet is running and  BTC node isn't configured 

Step:
- go to atomic swaps screen
- click on BTC button "connect other currency wallet to start trading"
- fill in the fields (node address,port,username,password)
- clik apply changes and connect

Expected: tab doesn't close
Actual. tab closes

[video.zip](https://github.com/BeamMW/beam-ui/files/4952270/video.zip)

**Comment by Roberrtt** [comment]
checked
