### ISSUE TITLE
Wallet screen - Statuses for Max privacy tx's + tx details

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#111]
1) Statuses for Max privacy tx's https://zpl.io/b6xJ58q

2) Wallet screen with new status (example) https://zpl.io/2ENXQ7M

3) Transaction details https://zpl.io/bzmYnqA

**Comment by VladislavKulyba** [comment]
1. The offline transaction stucks in waiting for receiver status when the receiver is offline.  
![Snag_1160e5f](https://user-images.githubusercontent.com/51320829/90243320-5b9ffa80-de37-11ea-8de1-e70ba2ab4539.png)
2. > 3\. Transaction details https://zpl.io/bzmYnqA

Transaction details aren't added

**Comment by VladislavKulyba** [comment]
> 1. The offline transaction stucks in waiting for receiver status when the receiver is offline.

This feature will be checked in #146

**Comment by VladislavKulyba** [comment]
Checked
