### ISSUE TITLE
Swaps stucked when amount less then fee

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam-ui#114]
https://github.com/BeamMW/beam/issues/1338

**Comment by VladislavKulyba** [comment]
Atomic Swaps are passed only if Transaction fee rate is 90000 sat/kb. In other cases swaps failed with this error message "Failed. Receiver signature is not valid, please send wallet logs to Beam support"

[beam_ui_20_08_19_09_54_02.log](https://github.com/BeamMW/beam-ui/files/5095826/beam_ui_20_08_19_09_54_02.log)
[beam_ui_20_08_19_09_53_10.log](https://github.com/BeamMW/beam-ui/files/5095828/beam_ui_20_08_19_09_53_10.log)

![image](https://user-images.githubusercontent.com/51320829/90624757-232a6300-e221-11ea-92c4-33d9f879ce24.png)

**Comment by VladislavKulyba** [comment]
checked
