### ISSUE TITLE
Atomic Swap  - Create offer screen new design

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#115]
Design: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5f22d698ec9b0c21456dda06

1) Only Comment block can be hidden by default

2) Create Swap Offer - All blocks are open https://zpl.io/bWOYgE1
![image](https://user-images.githubusercontent.com/47353570/89016551-92e3b700-d321-11ea-83bc-d64d90257201.png)

3) Create Swap Offer - fee errors - when wallet cant show fee rate from network https://zpl.io/VqoEKeG
![image](https://user-images.githubusercontent.com/47353570/89016564-98d99800-d321-11ea-891f-e0cc0ba69b81.png)

4) Show token https://zpl.io/bodxM6Z
![image](https://user-images.githubusercontent.com/47353570/89018406-83b23880-d324-11ea-9892-15b83ea67263.png)

**Comment by anatolse** [comment]
There is no design for an estimated transaction fee for BTC|LTC|QTUM on the receiver side
![image](https://user-images.githubusercontent.com/846272/89063763-72434d80-d371-11ea-91a1-ea13ef879ee4.png)

**Comment by Sergei-Beam** [comment]
@roman-strilets @gingervik please validate it
1. Looks like we are broken validation for creation offer without a fee (if one or both fields is blank)
![image](https://user-images.githubusercontent.com/44496108/89325030-e42cd700-d690-11ea-9881-37d4679fa45f.png)
Need to add:
- If one of the fee fields is blank - button publish offer should be disabled
- If beam fee less 100 GROTH - button publish offer should be disabled
- Not sure, that need to restrict for 3rd party network fee as we're going to  recommend it from the network and it can be different or even lost connection

2. I think we should add additional information that If user click "copy swap token" private swap will be created ( offer won't be published)
Currently, it is not clear
![image](https://user-images.githubusercontent.com/44496108/89328191-ae3e2180-d695-11ea-8c30-1f8a11307ba0.png)


3. Create Swap Offer - fee errors - when wallet cant show fee rate from network https://zpl.io/VqoEKeG
![image](https://user-images.githubusercontent.com/47353570/89016564-98d99800-d321-11ea-891f-e0cc0ba69b81.png)
Need to check it after https://github.com/BeamMW/beam/issues/1472 will be ready

**Comment by Sergei-Beam** [comment]
1. checked
2. moved to https://github.com/BeamMW/beam-ui/issues/66
