### ISSUE TITLE
Atomic Swap - Accept offer screen new design

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#116]
Design: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5f22d698ec9b0c21456dda06

1) Paste a token https://zpl.io/2v4YOWr
![image](https://user-images.githubusercontent.com/47353570/89018505-aba19c00-d324-11ea-869b-aa48ece102fc.png)

2) Pasted token https://zpl.io/adO7X0K
![image](https://user-images.githubusercontent.com/47353570/89018727-f4595500-d324-11ea-889d-5c1cf7b74b90.png)

3) Expired token https://zpl.io/VYOBp3d
![image](https://user-images.githubusercontent.com/47353570/89018766-00ddad80-d325-11ea-9cbf-e6340b259ea8.png)

4) Show token https://zpl.io/2ZWJD6q
![image](https://user-images.githubusercontent.com/47353570/89018806-0e933300-d325-11ea-871b-fa4204e35f03.png)

**Comment by Sergei-Beam** [comment]
2. Paste the wrong token 
Step:
- create an offer and copy token
- add any additional symbol to token
- try to paste token to another wallet
_Note: the system is validated as the wrong token_
- delete added symbol
Expected: System is validated token as correct and open Send form
Actual: System is validated token as correct but didn't open Send screen even If I try to click "enter"
![image](https://user-images.githubusercontent.com/44496108/89327346-797d9a80-d694-11ea-92dd-73aa5ff1f8a6.png)

3. Button **swap** should be disabled if 3d party fee field is blank
![image](https://user-images.githubusercontent.com/44496108/89328093-85b62780-d695-11ea-8700-a1609b14ad73.png)

**Comment by Sergei-Beam** [comment]
4. There is no message that token already expired according to new design
**Actual:** ![image](https://user-images.githubusercontent.com/44496108/89383740-b2a22300-d705-11ea-8c96-d784909df378.png)
**Design:** ![image](https://user-images.githubusercontent.com/44496108/89383785-c9e11080-d705-11ea-8310-cfc149b5eeee.png)

**Comment by anatolse** [comment]
I think that p3 should be in a separate ticket, since, as I know, the same behavior we have on EE5.0

**Comment by Sergei-Beam** [comment]
checked
for additional case in p.2 created a separate ticket
https://github.com/BeamMW/beam-ui/issues/138
