### ISSUE TITLE
[GUI Wallet] - Settings - Manual added peer disappears from the peer list after deleting default peers

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#12]
Steps to reproduce the behaviour:
1. Restore wallet using seed phrase
2. During restoring on Setup node connectivity screen fill-in a peer in the peer field with different from default working peer 
3. After successful restoring go to Settings screen
4. Delete all default peer and press apply. Connection status should change from online to connection error
5. When connection status changes to online, switch to main screen and than go to Settings screen again.

Expected: Only this peer storage in the peer list.
Actual: There are only default peers.

[2019-12-02_15-38-47.zip](https://github.com/BeamMW/beam/files/3911558/2019-12-02_15-38-47.zip)

**Comment by echoby** [comment]
Not relevant
