### ISSUE TITLE
Max-privacy - After rescan , transaction is updated with  time

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#121]
When there are different transactions in the wallet, after rescan, the transactions(Max-privacy)are updated in time and displayed first

We need to decide how to display them
![bandicam-2020-08-04-12-57-31-787](https://user-images.githubusercontent.com/50007056/89281844-58488a00-d653-11ea-8b08-5298a9606769.gif)

**Comment by anatolse** [comment]
after this fix, all newly created max privacy tx will not change the timestamp, and will not be duplicated on the wallet rescan

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9489.3089
