### ISSUE TITLE
After restoring the wallet, max-privacy transactions are displayed in transactions list

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#122]
If you restore the wallet where max-privacy transactions were made, they are displayed in the transactions list

Precondition:
There are 2 wallets A and B

Step:
- from wallet A send to wallet B 2 Regular transactions 
- from wallet A send to wallet B 3-4 max-privacy transactions
- restore wallet A
- pay attention transactions list 

Max privacy transactions are displayed in transaction list

**Comment by anatolse** [comment]
it was decided to show max privacy and mw transaction during restore.

**Comment by Denis-Asipenko** [comment]
During the discussion, it was decided not to restore the MW transactions. If the user received shielded coins, then only they will be displayed after the wallet is restored.

**Comment by Denis-Asipenko** [comment]
checked
