### ISSUE TITLE
User should not be able to send max privacy tx on sbbs address

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#124]
When a user insert sbbs address in transaction info section instead of max privacy switcher where should be text "This type of address does not support max privacy transactions"
![image](https://user-images.githubusercontent.com/28015224/89391472-f0f10f80-d710-11ea-834b-78f07fbc0bc1.png)

**Comment by kazaryan-t** [comment]
Checked on Master 5.0.9462.3080
