### ISSUE TITLE
Сolor of the amount changes when you click 2 mouse button on it

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#126]
Сolor of the amount changes when you click 2 mouse button on it , for received transactions. Color must not change.
![bandicam-2020-08-05-16-46-23-234 (1)](https://user-images.githubusercontent.com/50007056/89420473-6bcf2000-d73b-11ea-9dce-ad575149719f.gif)

**Comment by kazaryan-t** [comment]
Checked on master 5.0.9458.3072
