### ISSUE TITLE
Send button isn't active if you correct the amount after clicking the "add all" button

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#127]
When we click the "add all" button and change the amount, the send button becomes inactive on the send screen.

Step:
- go to send screen
- insert the address 
- click on "add all" button
- change amount or delete 1 number from amount

Note:
1.Also pay attention to the calculation table after correcting the amount.The table doesn't calculate correctly.
2. After changing the amount, there are no restrictions for entering the amount and you can enter letters.

![bandicam-2020-08-05-17-07-53-503](https://user-images.githubusercontent.com/50007056/89422736-62938280-d73e-11ea-8d1b-bbe172aeb0a0.gif)

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9458.3072
