### ISSUE TITLE
Change filed "from" for received shielded tx

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#128]
If user received max privacy tx in field From should be "sheilded pool
<img width="1023" alt="Снимок экрана 2020-08-06 в 11 34 10" src="https://user-images.githubusercontent.com/28015224/89510463-442e9500-d7d9-11ea-941c-abd71ad539f7.png">
"

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9458.3071

**Comment by echoby** [comment]
<img width="1025" alt="Untitled" src="https://user-images.githubusercontent.com/1681548/89649897-2c830980-d8ca-11ea-8f0a-ccb9f021e81a.png">
The same bug on notifications screen

**Comment by KatsiarynaV** [comment]
cheked on build 5.0.9462.3080
