### ISSUE TITLE
Disable max privacy option for receiver connected not to his own node

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#129]
If a user is connected not to his own node please disable for him max privacy switcher on Receive screen 
<img width="1023" alt="Снимок экрана 2020-08-06 в 11 41 19" src="https://user-images.githubusercontent.com/28015224/89510967-f0707b80-d7d9-11ea-9148-54b41c8c1563.png">
and add text "Connect to integrated or own node to enable sending max privacy transactions"

**Comment by KatsiarynaV** [comment]
cheked on build 5.0.9462.3080
