### ISSUE TITLE
The regular transaction is being sent, not max privacy

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#131]
When we send max-privacy transaction to regular addresses.The regular transaction is being sent, and not the max privacy

Step:
- (B) go to  receive screen
- (B) copy token with params (Regular\one-time use)
- (A) go to send screen 
- (A) insert token , entered amount and switch the slider to max-privacy
- (A) send transaction

Actual:
Wallet B received regular transaction

Expected:
Wallet B received max privacy transaction
[wallet A logs.zip](https://github.com/BeamMW/beam-ui/files/5033851/wallet.A.logs.zip)
[wallet B logs.zip](https://github.com/BeamMW/beam-ui/files/5033854/wallet.B.logs.zip)

Transaction ID:
f8260fb45f66455baa1858cd26a029a3

![Screenshot_124](https://user-images.githubusercontent.com/50007056/89513971-e9e40300-d7dd-11ea-84a3-87d6855e971e.png)

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9474.3081
