### ISSUE TITLE
Assets coins shows up on UTXO view

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam-ui#132]
1) receive asset in cli
2) restore UI wallet with assets from seed phrase
![photo_2020-08-06_16-13-14](https://user-images.githubusercontent.com/1681548/89535943-ccc02c00-d7ff-11ea-9c4c-f16f5d898f5a.jpg)
![photo_2020-08-06_16-13-24](https://user-images.githubusercontent.com/1681548/89535945-cdf15900-d7ff-11ea-99a2-de502bdf11f8.jpg)

**Comment by Roberrtt** [comment]
checked
