### ISSUE TITLE
Need to add additional text with a counter for offline transaction

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#133]
Currently, according to design (https://zpl.io/2GKeWkE) we should have additional text with a counter for the offline transaction under the token field, but the text is absent 
Design: ![image](https://user-images.githubusercontent.com/44496108/89617464-e6f71a00-d892-11ea-9020-ddf39db7ec50.png)
Actual: ![image](https://user-images.githubusercontent.com/44496108/89617483-ececfb00-d892-11ea-8ae0-aaa78410a331.png)

The same counter need to add in Show Token pop-up https://zpl.io/bPJjKvm
![image](https://user-images.githubusercontent.com/44496108/90413447-1d187300-e0b7-11ea-9491-342234f8d1da.png)

**Comment by gingervik** [comment]
Example: offline transactions remaining 7

**Comment by Sergei-Beam** [comment]
When the receiver is offline and sender already sent 10 transactions (spent 10 vouchers):
-  in next transactions, the counter disappears
![image](https://user-images.githubusercontent.com/44496108/91485315-5b7e1100-e8b3-11ea-9858-6a7f7d3aa6d9.png)
I think we need to show some message here
- in show token popup wrongly still be shown 10 vouchers
![image](https://user-images.githubusercontent.com/44496108/91485494-9ed87f80-e8b3-11ea-92fa-508fc5c242df.png)

**Comment by kazaryan-t** [comment]
Checked on master 5.0.9522.3133
https://github.com/BeamMW/beam-ui/issues/167
