### ISSUE TITLE
New Send screen - Fee for sending transactions with shielded coins

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#136]
**Bug description:** 
In the wallet with shielded coins when we insert regular address and click the "add all" button fee doesn’t changed from 100 to 1200000

**Precondition:** 
There are 2 wallets A and B. Wallet A have shielded coins

**Steps to reproduce the behavior:**
(B) Copy regular address
(A) Insert copied address in the send screen 
(A) Click the button “add all”

**Current behavior:**
Fee doesn’t change from 100 to 1200000

**Expected behavior:**
Fee changed from 100 to 1200000

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9458.3072.
![addallfee](https://user-images.githubusercontent.com/68267190/89644701-2177ab80-d8c1-11ea-8d01-5b05f2476603.gif)

**Comment by KatsiarynaV** [comment]
When we insert a token and change  fee, in the field amount automatically added all and errors are displayed
![200](https://user-images.githubusercontent.com/68267190/91535797-63be6680-e91c-11ea-812f-45ae2c84a02e.gif)

**Comment by KatsiarynaV** [comment]
1.If wallet doesn't have shielded coins, when we insert max privacy token and amount, fee does not change to 1200000
![300](https://user-images.githubusercontent.com/68267190/91552559-ad1ab000-e934-11ea-8fe0-0488bfb4f9f8.jpg)
![301](https://user-images.githubusercontent.com/68267190/91552562-adb34680-e934-11ea-8b9c-97a2d5da2371.jpg)

2. If wallet have one shelded coin, when we insert token and click button "add all" fee changes to 1000020 and button "send" isn't active. When we click "add all" one more time or manually change fee to 1200000 an warning is displayed: "Insufficient funds: you would need 0 to complete the transaction
![400](https://user-images.githubusercontent.com/68267190/91555362-8dd25180-e939-11ea-9934-fe6117038190.jpg)
![402](https://user-images.githubusercontent.com/68267190/91555364-8f037e80-e939-11ea-974b-b8426c97be42.gif)
![403](https://user-images.githubusercontent.com/68267190/91555366-8f037e80-e939-11ea-992b-59cf048f014a.gif)

**Comment by KatsiarynaV** [comment]
1. Incorrect fee  when sending transaction to max privacy token and using several shielded coins. 
**Case 1:**
When we first insert max privacy token and then amount with 3 shieded coins - fee 4200000 is displayed
![1003](https://user-images.githubusercontent.com/68267190/91692867-cdd04900-eb72-11ea-949b-111d5027ef04.jpg)
![1000](https://user-images.githubusercontent.com/68267190/91692642-60241d00-eb72-11ea-87b3-f81d4c50b229.gif)

**Case 2:**
When we first insert amount with 3 shielded coins and then max privacy token - fee 1200000 is displayed
![1001](https://user-images.githubusercontent.com/68267190/91693215-5bac3400-eb73-11ea-8c5e-28e174f82735.gif)

2. When max privace transaction with several shieded coins is done fee is different from chosen when creating transaction
![1004](https://user-images.githubusercontent.com/68267190/91694311-1a1c8880-eb75-11ea-9d4c-c2d5f28e5732.jpg)
![1005](https://user-images.githubusercontent.com/68267190/91694334-1f79d300-eb75-11ea-8fd0-592ed2a7d106.jpg)
![1006](https://user-images.githubusercontent.com/68267190/91694338-20126980-eb75-11ea-99a4-13187ccf059b.jpg)

3. Incorrect fee when sending transaction with one shielded coin to regular token. Button "send" isn't active
![1008](https://user-images.githubusercontent.com/68267190/91695788-57821580-eb77-11ea-9ef2-88789c799ee8.jpg)
![1007](https://user-images.githubusercontent.com/68267190/91695619-1c7fe200-eb77-11ea-8526-55420c375be2.gif)

4. When regular transaction with one shieded coins is done fee is different from chosen when creating transaction
![1009](https://user-images.githubusercontent.com/68267190/91696441-3ff75c80-eb78-11ea-9369-d488a14eebf5.jpg)
![1010](https://user-images.githubusercontent.com/68267190/91696443-408ff300-eb78-11ea-9070-d3b15f8c3ed5.jpg)

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9519.3128.

**Comment by KatsiarynaV** [comment]
If there are only regular coins in the wallet, when we click "add all"  button the fee isn't deducted from amount and an error appears about insufficient funds
![001](https://user-images.githubusercontent.com/68267190/92369867-39ca2880-f102-11ea-9687-bf1da2d1dd00.jpg)
![002](https://user-images.githubusercontent.com/68267190/92369878-3cc51900-f102-11ea-99ec-127c91ca0b19.jpg)
![003](https://user-images.githubusercontent.com/68267190/92369893-3f277300-f102-11ea-847a-85f2de466661.jpg)

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9547.3161

**Comment by echoby** [comment]
Need to recheck cases with max privacy "on"

**Comment by echoby** [comment]
Also need recheck "max privacy" token paste event

**Comment by KatsiarynaV** [comment]
1. If there are 2 or more shielded coins in the wallet when user insert max privacy address and click "add all" button incorrect fee is displayed 
![01](https://user-images.githubusercontent.com/68267190/92691622-7f2d6680-f34b-11ea-98fd-f579f1cff47d.jpg)
![02](https://user-images.githubusercontent.com/68267190/92691632-818fc080-f34b-11ea-9531-96653d220c24.jpg)
2. When user insert max privacy address and click "add all" button several times the fee increases with each click
![03](https://user-images.githubusercontent.com/68267190/92691740-b7cd4000-f34b-11ea-8254-8110132a9862.gif)
3. When user first click "add all" button and then insert max privacy address the amount is calculated incorrectly
![05](https://user-images.githubusercontent.com/68267190/92692385-bfd9af80-f34c-11ea-8c1e-2748c5eaf747.gif)
**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9556.3169.

**Comment by KatsiarynaV** [comment]
If there are only regular coins in the wallet when user first click "add all" button and then insert max privacy address the amount is calculated incorrectly
![07](https://user-images.githubusercontent.com/68267190/92714223-9d539080-f364-11ea-963c-7d3719520065.jpg)
![08](https://user-images.githubusercontent.com/68267190/92714288-b3615100-f364-11ea-9f04-249ab1a69939.gif)

**Comment by KatsiarynaV** [comment]
If there are some shielded coins in the wallet when user insert max privacy address, amount and then change amount to the different one the fee increases with every change
![10](https://user-images.githubusercontent.com/68267190/92734673-6c358900-f381-11ea-874f-2a2112d66300.gif)

**Comment by KatsiarynaV** [comment]
Checked on build 5.0.9562.3179

**Comment by KatsiarynaV** [comment]
If there are shielded coins in the wallet when we insert max privacy address and in the field "amount" insert two-digit number  the fee increases by 1000000 groth
![21](https://user-images.githubusercontent.com/68267190/93177018-cd22df80-f73a-11ea-8e44-ffd21390ee1c.jpg)
![20](https://user-images.githubusercontent.com/68267190/93177029-d0b66680-f73a-11ea-8b83-ab93df9fd01a.gif)
If there are shielded coins in the wallet when we insert max privacy address and insert a  decimal in the field "amount"  the fee increases by 1000000 groth with every number afetr point 
![22](https://user-images.githubusercontent.com/68267190/93179038-ca75b980-f73d-11ea-95fb-727de6367d1a.gif)

**Comment by KatsiarynaV** [comment]
If we insert fee greater than amount to send and then click "add all" button incorrect amount is displayed and we can send transaction that is failing
![40](https://user-images.githubusercontent.com/68267190/93202116-d8860300-f75a-11ea-903f-4dcf6f846fbb.gif)

**Comment by KatsiarynaV** [comment]
Checked
