### ISSUE TITLE
User can get several txs on one-time use token

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#139]
**Description:**
Can send several transactions to a one-time use token. This is reproduced for regular and max privacy transactions.
**Pre-conditions:** 
Wallet A and wallet B are installed and running
**Steps to reproduce:**
1. In the wallet A create a one-time use token.
2. Send some beams from wallet B to wallet A through this token
3. Send another transaction to this token.
**Expected:** The only first transaction is passed.
**Actual:** All transactions are passed.

**Attachments:** 
![Snag_13fea31](https://user-images.githubusercontent.com/51320829/90246651-bf2d2680-de3d-11ea-900a-c04da6e1acd0.png)

**Comment by gingervik** [comment]
not relevant
