### ISSUE TITLE
Misunderstanding with concepts of online and offline tokens

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#140]
Online tokens for max privacy should work only when wallets are online. Right now there is such a situation. The receiver creates an online token, the sender sent some beams while the receiver was online. All other transactions to this token will be passed, never mind if receiver online or offline.
The same issue with offline tokens. The transactions can be sent online.

Need to be discussed

**Comment by gingervik** [comment]
irrelevant
