### ISSUE TITLE
Add ability to search transactions by tokens

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#145]
As a user, I should be able to find all related transactions by pasting Token to search field.
Search should work for both token's types:
- Regular
- Max privacy

![image](https://user-images.githubusercontent.com/44496108/90606001-d9814e80-e207-11ea-9284-0f8be1361a8e.png)

**Comment by VladislavKulyba** [comment]
The searching by Addresses (used to be Tokens) made only for Sender side. Need to be discussed what we should show on receiver side.

**Comment by gingervik** [comment]
@KatsiarynaV please, recheck

**Comment by KatsiarynaV** [comment]
Irrelevant for addresses in a new format
