### ISSUE TITLE
A transaction through offline token stucks in waiting for receiver status while the receiver is offline

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#146]
**Description:**
Any transaction through offline token stucks in waiting for receiver status while the receiver is offline. The transaction is started and changes status to "in progress" when the receiver becomes online.

**Pre-conditions:**
There are two running Wallets A and B

**Steps to reproduce:**
1. In wallet A open receiver window.
2. In Transaction info section switch to max privacy
3. Press on Copy and close button in Offline token section
4. Paste Offline token in the sender screen from Wallet B
5. Enter some amount (for example, 45)
6. Push to send and confirm it in the popup

**Expected:** Transaction is started and after few seconds changes status from "waiting for receiver" to "in progress". 
**Actual:** The transaction stucks in waiting for receiver status.

**Attachments:**
![Snag_55b664e](https://user-images.githubusercontent.com/51320829/90613323-ddb26980-e211-11ea-85dc-f3fd12f01721.png)
[beam_ui_20_08_19_11_31_35.log](https://github.com/BeamMW/beam-ui/files/5095146/beam_ui_20_08_19_11_31_35.log)
Tx_id: 4ec57a10ca1548b99f43ddb6bb5d4a5e

**Comment by Denis-Asipenko** [comment]
checked
