### ISSUE TITLE
Two identical transactions are displayed when we send regular transaction to offline wallet which we tnen reopen

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#148]
**Bug description:**
When we send a regular transaction from wallet A to wallet B that is not online, and then we open wallet B, two identical transactions appear. One transaction with status “receiving”, second with status “waiting for sender”. Then statuses changed: one transaction to “received” and second to “in progress”. Second transaction “in progress” disappears after a while

**Precondition:** 
There are 2 wallets A and B. 

**Steps to reproduce the behavior:**
1. In the wallet, B go to the "receive" screen and copy regular one-time use or permanent token.
2. Close the wallet B
3. Go to the wallet A and send transaction to the copied from wallet B token 
4. Reopen the wallet B

**Current behavior:**
In the wallet B two identical transactions are displayed. One with status “receiving”, second with status “waiting for sender”. Then statuses changed: one to “received” and second to “in progress”. Second transaction “in progress” disappears after a while

**Expected behavior:**
In the wallet B one transaction is displayed with status “in progress” and then “received”

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9490.3090.
![12](https://user-images.githubusercontent.com/68267190/90768949-25132580-e2f8-11ea-9945-22bb73b514ad.jpg)
![13](https://user-images.githubusercontent.com/68267190/90768960-293f4300-e2f8-11ea-9751-9eea96a92765.jpg)
![14](https://user-images.githubusercontent.com/68267190/90768970-2cd2ca00-e2f8-11ea-9562-e236e30f066e.jpg)

Wallets
[Beam wallet masternet receiver.zip](https://github.com/BeamMW/beam-ui/files/5102918/Beam.wallet.masternet.receiver.zip)
[Beam Wallet Masternet sender.zip](https://github.com/BeamMW/beam-ui/files/5102920/Beam.Wallet.Masternet.sender.zip)
Password for wallets - 1

**Comment by Denis-Asipenko** [comment]
checked
