### ISSUE TITLE
Notifications screen - notifications are displayed incorrectly for max privacy transactions.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#149]
**Bug description**
On "Notifications" screen transactions sent or received by the max privacy are displayed with the same icon and the notification table of contents. 
![image](https://user-images.githubusercontent.com/45556620/90879560-c4472400-e3af-11ea-9ca0-66d78419488b.png)
![image](https://user-images.githubusercontent.com/45556620/90879659-e93b9700-e3af-11ea-8268-67bda6e7ea5d.png)

**Comment by KatsiarynaV** [comment]
Incorrect notification when sending a regular transaction with regular UTXO.  The addres should be specified, not shielded pool.
![notific](https://user-images.githubusercontent.com/68267190/91270594-8d8f5600-e781-11ea-9b49-589716891092.jpg)

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9505.3108
