### ISSUE TITLE
Lose connection to btc node during transation

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#154]
**Description**
Sometimes during Atomic Swap transaction, BTC node changes its status from "Transaction in progress" to "Cannot connect to peer..."

**Steps to Reproduce**
1. Create an offer in Wallet A
2. Accept the offer in Wallet B
3. Watch on Atomic Swaps screen

Expected: There is a strong connection to the BTC node during the transaction
Actual: Lose connection to BTC node during the transition, status changing sometimes to "Cannot connect to peer..."

**Attachments**
With wrong connection:
![Snag_10ddad3](https://user-images.githubusercontent.com/51320829/91167414-98dc7600-e6dc-11ea-9b94-0ca24447153c.png)
Few seconds later:
![Snag_1112e43](https://user-images.githubusercontent.com/51320829/91167712-199b7200-e6dd-11ea-8891-2e07f0a99faf.png)

Wallets Version: 5.0.9500.3097

**Comment by kazaryan-t** [comment]
Checked on Master 5.0.9512.3115.
