### ISSUE TITLE
Atomic Swap - incorrect btc transaction fee rate

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#155]
When we create a swap offer sometimes an incorrect btc transaction fee rate is displayed when connecting to electrum random node
![20](https://user-images.githubusercontent.com/68267190/91301090-08219b00-e7ad-11ea-985d-a1af700fd8f2.jpg)

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9505.3111.

**Comment by roman-strilets** [comment]
Look at https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-estimatefee
"If the daemon does not have enough information to make an estimate, the integer -1 is returned."

Added a fee check for less than 0

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9514.3119
