### ISSUE TITLE
Atomic swap - Disable the ability to create swap offer when user dosen't have bitcoins

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#156]
When user wants to excnahge btc to beam he can create swap offer if he dosen't have bitcoins. Disable this ability 
![30](https://user-images.githubusercontent.com/68267190/91302433-2dafa400-e7af-11ea-98c4-70ad398852d6.jpg)
**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9505.3111.

**Comment by kazaryan-t** [comment]
Checked on Master 5.0.9514.3119.
