### ISSUE TITLE
 Offline max privacy transaction is stuck

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#159]
Somehow 1 from 10 transactions to an offline wallet is stuck
**Tx_id** c93d2e39190c4f6383e4598cf6c867ad
**Kernel_id** 2e3c3d9c6078d505429e4ba2d549b2bf6ffb5758a18475eb2752623b7521d561
![image](https://user-images.githubusercontent.com/44496108/91486239-a64c5880-e8b4-11ea-8284-0ffae4e5c762.png)
![image](https://user-images.githubusercontent.com/44496108/91486264-ae0bfd00-e8b4-11ea-817a-d81fb944c7eb.png)

Wallet version : 5.0.9513.3117
OS: Windows 10 x64

Sender's Db+logs
[sender.zip](https://github.com/BeamMW/beam-ui/files/5138370/sender.zip)

Receiver's Db+logs
[receiver.zip](https://github.com/BeamMW/beam-ui/files/5138378/receiver.zip)

**Comment by anatolse** [comment]
for this transaction we get TxStatus::InvalidContext
the reason comes from NodeProcessor::IsShieldedInPool
		if (m_Extra.m_ShieldedOutputs > krn.m_WindowEnd + r.Shielded.MaxWindowBacklog)
			return false; // large anonymity set is no more allowed, expired
it seems that selected shieleded coin is not valid anymore

**Comment by anatolse** [comment]
https://github.com/BeamMW/beam/commit/853fc3126a6d93415f9564547a33e4fa4346b48b
https://github.com/BeamMW/beam/commit/8d7ae0b2432f696a1e25e83fa167b9562cd478ca
fixed shielded inputs
@Sergei-Beam, please, try to reproduce

**Comment by Sergei-Beam** [comment]
checked, now it works as expected
