### ISSUE TITLE
Publish and copy token buttons are active when fee rate not indicated

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#160]
**Description**
Publish and copy token buttons are active when the fee rate not indicated

**Steps to Reproduce**

1. Go to Create offer screen
2. Set Send Amount as Beam, Receiver Amount - BTC
3. Enter some amount for send and receive, fee rate field are not filled in

**Expected**: Publish and copy token buttons are disabled
**Actual**: Publish and copy token buttons are active

**Attachments**
![Snag_103ba7c7](https://user-images.githubusercontent.com/51320829/91548069-85741980-e92d-11ea-89e8-4f746816393e.png)

version: 5.0.9515.3120

**Comment by VladislavKulyba** [comment]
Please, disable copy token button in show token submenu when  the fee rate isn't indicated
![Snag_1118dc61](https://user-images.githubusercontent.com/51320829/91572396-45be2980-e94f-11ea-91c5-952253c9c34f.png)

**Comment by Aleksandr-Starun** [comment]
Partly not relevant anymore. New behaviour described here #166

**Comment by VladislavKulyba** [comment]
1. Checked

2. Not relevant because of the new design.
The old design was removed
> Please, disable copy token button in show token submenu when the fee rate isn't indicated
> ![Snag_1118dc61](https://user-images.githubusercontent.com/51320829/91572396-45be2980-e94f-11ea-91c5-952253c9c34f.png)
