### ISSUE TITLE
Online max privacy transaction is stucked

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#161]
**Bug description:** 
When sending online max privacy transaction using one shielded coin with fee 1200000 transaction stucks "in progress" and fee in transaction info and logs changes to 200000

**Precondition:**
There are two wallets A (sender) and B (receiver). There is one shielded coin in wallet A.

**Steps to reproduce the behavior:**
1. In wallet B copy max privacy online token
2.  In wallet A go to the send screen, insert this token, add amount with shilded coin, check that fee is 1200000 and send transaction
3.  See the transaction info

**Current behavior:** 
Transaction is stucked "in progress", fee is changed to 200000

**Expected behavior:** 
Fee isn't changed and transaction status is "sent max privacy"

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.0.9516.3121

![502](https://user-images.githubusercontent.com/68267190/91563157-14d9f680-e947-11ea-83e2-253dfe0157b4.gif)
![600](https://user-images.githubusercontent.com/68267190/91563169-186d7d80-e947-11ea-8248-a928d47c764d.jpg)

Sender's db and logs
[Sender.zip](https://github.com/BeamMW/beam-ui/files/5142158/Sender.zip)

Receiver's db and logs
[Receiver.zip](https://github.com/BeamMW/beam-ui/files/5142160/Receiver.zip)

**Comment by anatolse** [comment]
the problem with fee "jumping" to the lower value was solved in another issue

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9541.3152
