### ISSUE TITLE
The "Copy token" button from show token popup should have the same behaviour as "copy swap token" button

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#164]
**Description**
The "Copy token" button in the show token should have the same behavior as the "copy swap token" button. When you press on the "copy token" button from show token popup it should close create offer screen and create swap transaction. 
Right now, if you click on copy token and the close screen with swap (close and back on swaps screen, or just change menu in a wallet), the transaction won't be created.

**Steps to reproduce**
1. Go to Create offer screen
2. Set Send Amount as Beam, Receiver Amount - BTC
3. Filled in all necessary fields
4. Press on "show token" 
5. Press the "copy token" button

**Expected**:  Create offer screen has been closed and swap transaction was created
**Actual**: Token was copied. Transaction wasn't created

**Attachments**:
![Snag_151074c](https://user-images.githubusercontent.com/51320829/91725198-0f7ae700-eba7-11ea-9725-4679729efe65.png)

**Comment by alexandrashelenkova** [comment]
Not relevant anymore. New behaviour described here https://github.com/BeamMW/beam-ui/issues/166
