### ISSUE TITLE
The wrong balance after swap with shielded utxo

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#165]
**Description**
When swap failed, a balance didn't become actual. On the UTXO screen, there is shielded UTXO, but its value is missed from balance. The balance fixed only by a rescan.

**Pre-conditions**
There are a shielded coin in the wallet and a connection to BTC node. 

**Steps to Reproduce**

1. Go to UTXO screen, checked that you've got a shielded coin, and make sure that you will choose exactly this coin (pic. 1).
2. Look and remember what is the balance in the wallet. 
3. Go to Create offer screen and create some offer with this shielded coin.  
4. Accept offer in another wallet. The transaction should fail.
5. When the swap transaction will be failed look to the balance.

**Expected**: Balance should the same as before swap
**Actual**: There is no amount of shielded coin in the balance.

**Attachments**
logs:
[beam_ui_20_08_31_11_34_25.zip](https://github.com/BeamMW/beam-ui/files/5151030/beam_ui_20_08_31_11_34_25.zip)
[beam_ui_20_08_31_11_31_49.zip](https://github.com/BeamMW/beam-ui/files/5151032/beam_ui_20_08_31_11_31_49.zip)
tx_ID: 5d3f329123344bae93caf6db94ecabdc

Picture 1. 
![Snag_1a5472b](https://user-images.githubusercontent.com/51320829/91734701-ea40a580-ebb3-11ea-92fa-7d648a735705.png)

**Comment by Aleksandr-Starun** [comment]
Fixed at rev. 5f7f5d9b1393bf92c758cc63796211e9e1ef738c
Current bug related to all transactions which works with shielded coins. Please test them too.

**Comment by Denis-Asipenko** [comment]
checked
