### ISSUE TITLE
Atomic Swap - "Copy token" behaviour fixes

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#166]
1. Remove button "Copy token" from dialogue https://zpl.io/bodxM6Z 
![create swap offer - show token v3](https://user-images.githubusercontent.com/7249484/91800791-40692380-ec5c-11ea-87ec-c0160342129e.png)

2. If some fields are empty or not valid, do not show "Show token" button in next to swap token field https://zpl.io/VqoEKeG
<img width="846" alt="Screenshot at Sep 01 14-04-46" src="https://user-images.githubusercontent.com/7249484/91800778-334c3480-ec5c-11ea-86a2-91b0f4674cb0.png">

3. Add "copy token and close" button next to "Publish offer button" https://zpl.io/bWOYgE1
![create swap offer - all open v3](https://user-images.githubusercontent.com/7249484/91800667-fbdd8800-ec5b-11ea-834a-9d203602eb2f.png)

**Comment by Denis-Asipenko** [comment]
checked
