### ISSUE TITLE
Wrong removing values from amount field

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#168]
**Description**
If you enter a fractional number, which consists of 0 (zero) and some numeral at the end, when you delete this last stand numeral it will remove all value.  If there are some numerals after that numeral, they will be removed one by one. Reproduce for all amount fields.

**Steps to reproduce**
1. Open wallet
2. Go to Send screen
3. Enter some value, for example, 0.00001
4. Push a Backspace

**Expected**: Only last stand numeral (1) was removed
**Actual**: All value (0.00001) was removed.

**Attachments**
[video_bug.zip](https://github.com/BeamMW/beam-ui/files/5154802/video_bug.zip)

**Environment**:
Windows 10 Pro 
Version: 1909
OS Build: 18363.1016

Wallet version: 5.0.9520.3131

**Comment by kazaryan-t** [comment]
Checked on Master 5.0.9523.3138.
