### ISSUE TITLE
Public offline address UI

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#171]
Please, add design

**Comment by dariatarakanova** [comment]
1) Add "show public offline address" to settings (block utilities) https://zpl.io/aBJr0wO
2) Show public offline address popup https://zpl.io/bovMywv

**Comment by Roberrtt** [comment]
Settings aren't visible
Build -5.2.9631.3221 Linux
![Screenshot_247](https://user-images.githubusercontent.com/50007056/94790606-2c414f00-03df-11eb-81e1-ce4e2afa0639.png)

**Comment by Roberrtt** [comment]
@sasha-abramovich add  design for transactions to public address
Now the "To" field is empty
![Screenshot_250](https://user-images.githubusercontent.com/50007056/94800777-bee8ea80-03ed-11eb-9eee-c860b87211e7.png)

**Comment by Roberrtt** [comment]
1. Change text in popup from "public offline address' to "Publishing this address will allow you to be identified"
![Screenshot_258](https://user-images.githubusercontent.com/50007056/95066904-b523f780-070b-11eb-8bf7-649d68f2aa70.png)
2. Transactions don't come to the wallet if you send coins to this address.
3. In the "show address" popup, the address type is specified online - it must be offline and transaction type - offline
![Screenshot_259](https://user-images.githubusercontent.com/50007056/95066875-ac332600-070b-11eb-844e-b75591497410.png)
4. The Feeis written in 100 GROTH but the confirm transaction details indicate the correct one in 1000100
![Screenshot_260](https://user-images.githubusercontent.com/50007056/95066890-b1907080-070b-11eb-9997-891b3b9943be.png)

**Comment by Roberrtt** [comment]
1.Need to write an error if we are trying to send to own public address "Can not sent max privacy transaction to own address"
2.After sending to a public address, empty lines are added to contacts
![Screenshot_264](https://user-images.githubusercontent.com/50007056/95310639-525e6780-0895-11eb-9655-6abbde5936aa.png)
3. 4 item not fixed
4. Change  text under the send field 
![Screenshot_265](https://user-images.githubusercontent.com/50007056/95310627-4f637700-0895-11eb-82ae-090f32b9a05d.png)

**Comment by dariatarakanova** [comment]
> @sasha-abramovich add design for transactions to public address
> Now the "To" field is empty
> ![Screenshot_250](https://user-images.githubusercontent.com/50007056/94800777-bee8ea80-03ed-11eb-9eee-c860b87211e7.png)

1) Display the address in the "To" field, as usuall
2) In transaction details please add "Address type" field and place there "Public offline address" https://zpl.io/VDLg79W

**Comment by anatolse** [comment]
fixed 2,4

p.1 won't fix (@bigromanov)

**Comment by KatsiarynaV** [comment]
1. Add text under the address field: Public offline address
![01](https://user-images.githubusercontent.com/68267190/96980613-192a2680-1528-11eb-89d1-7383668fb94f.jpg)
2. Remove text on the confirmation pop-up 
![02](https://user-images.githubusercontent.com/68267190/96982651-9bb2e600-1528-11eb-9730-785bc89776f9.jpg)
3. Remove field "transaction type". Change address type to 'public offline'
![03](https://user-images.githubusercontent.com/68267190/96985620-72468a00-1529-11eb-9940-3dfc5544f23b.jpg)
4. Change stasuses to 'sent public offline', 'received public offline, and 'sent to own address public offline'.
![07](https://user-images.githubusercontent.com/68267190/96986512-67d8c000-152a-11eb-921f-26c28aae5ca9.jpg)
build 5.2.9715.3278

**Comment by anatolse** [comment]
fixed p3-4

I propose to make a separate issue for the statuses of loopback transaction

**Comment by KatsiarynaV** [comment]
Issue for the statuses of loopback transaction #241 
Receiver identity for public offline txs is wrong #237 
Remove Sending address for incoming public offline txs #238

**Comment by KatsiarynaV** [comment]
Contacts: when we send another transaction to the public offline address and change the comment to the different one on the send screen it dosen't change on the contacts
![08](https://user-images.githubusercontent.com/68267190/97418817-53296d00-191a-11eb-99ec-9181c3b9e8c2.jpg)
![09](https://user-images.githubusercontent.com/68267190/97418955-8409a200-191a-11eb-8b34-ff19ba8e7b54.jpg)

**Comment by KatsiarynaV** [comment]
Checked on build 5.2.9723.3300
