### ISSUE TITLE
Migration error on debug

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#176]
There is an error for migration on debug

qrc:/start.qml:693: ReferenceError: migrateColumn is not defined
qrc:/start.qml:692: ReferenceError: migrateColumn is not defined

![image](https://user-images.githubusercontent.com/51320829/92903663-ea019f00-f42a-11ea-9f28-a677b6468e75.png)

**Comment by Denis-Asipenko** [comment]
checked
