### ISSUE TITLE
Add message for user when a user tries to send max privacy transaction to one-time use address.

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam-ui#180]
We should notify user when he tries to send max privacy transaction to one-time use address.
[Video.zip](https://github.com/BeamMW/beam-ui/files/5223295/Video.zip)

**Comment by sasha-abramovich** [comment]
We will discuss it as a part of address book initiative. @alexandrashelenkova @dariatarakanova I'll explain it during our next meeting.

**Comment by dariatarakanova** [comment]
Only receiver can decide what type of address he is going to use. Sender can't change address type on send screen.
So in this case we don't need any notifications/errors.

This problem will be resolved here https://github.com/BeamMW/beam-ui/issues/222
