### ISSUE TITLE
Wallet doesn't see small shielded coins

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#181]
1. If there are only small shielded coins in the wallet (f.ex. 0.003, 0.004) we can insert any amount and send transaction that is failing
![41](https://user-images.githubusercontent.com/68267190/93203464-2865c980-f75d-11ea-8aaf-9b6ba2d0d8e1.gif)

2. If there are only small shielded coins in the wallet (f.ex. 0.003, 0.004) when we click "add all" button an error is displayed. 
![35](https://user-images.githubusercontent.com/68267190/93203135-86de7800-f75c-11ea-9b88-062339a7e483.jpg)
![36](https://user-images.githubusercontent.com/68267190/93203137-87770e80-f75c-11ea-91f0-cbb97c10aeeb.jpg)

3. If there is small shielded coin in the wallet when we click "add all" button and send transaction this shielded coin isn't sending 
![31](https://user-images.githubusercontent.com/68267190/93203778-a32ee480-f75d-11ea-9d71-f7af18b46829.jpg)
![32](https://user-images.githubusercontent.com/68267190/93203781-a32ee480-f75d-11ea-84b3-236b6c2c5304.jpg)
![33](https://user-images.githubusercontent.com/68267190/93204112-336d2980-f75e-11ea-982e-76840730ca99.jpg)

**Comment by echoby** [comment]
Fixed at https://github.com/BeamMW/beam/commit/858aa40609eb388b43f49322d4ceb41edd3f71d2
Shielded fee paid from self coin. In case when coin amount smaller 1000000 groth, this coin will stuck in pull. Now wallet don't calculate stucked coins as available.

**Comment by Denis-Asipenko** [comment]
checked
