### ISSUE TITLE
The transaction has been stuck in progress status despite it has sent status in the sender wallet

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#182]
**Description**
From a wallet A has been sent a transaction to a wallet B. In the wallet A transaction has status sent.  In the wallet B transaction has status in progress. The transaction ID is c609cf93e92d4510844169ed631b86ed. For this transaction in the wallet B logs there are two different kernels ID. For one of them transaction was accepted, for other - stuck in progress. In the wallet B displayed 'in progress' transaction. After closing this wallet the dump file was created. 

**Attachments**

![Snag_1f475e79](https://user-images.githubusercontent.com/51320829/93322651-39294480-f81c-11ea-8801-f2470b776652.png)

[Wallet A_1.zip](https://github.com/BeamMW/beam-ui/files/5231345/Wallet.A_1.zip)

[Wallet B_1.zip](https://github.com/BeamMW/beam-ui/files/5231342/Wallet.B_1.zip)

**Enviroment**

Windows 10 Pro
Version: 1909
OS Build: 18363.1082

Wallets version: 
Wallet A - 5.1.9574.3191
Wallet B - 5.1.9573.3187

**Comment by anatolse** [comment]
added some cleanup to avoid tx reincarnation. Please, try to reproduce

**Comment by VladislavKulyba** [comment]
Can't reproduce after fix
