### ISSUE TITLE
Atomic Swap screen - 3 different styles for button "connect more currencies" 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#185]
In the design process we were faced with a choice how to display button "connect more currencies (wallets)". 
We have 3 different versions and we need to choose what is the best for user.

Version 1: "plus" icon with not-connected currencies icons
![atomic swap v1](https://user-images.githubusercontent.com/47353570/93335803-a2ff1980-f82f-11ea-9369-d63e0310ac24.jpg)

version 2: just "plus" icon
![atomic swap v2](https://user-images.githubusercontent.com/47353570/93335819-a72b3700-f82f-11ea-9240-7aa44f7e2cad.jpg)

Version 3: "plus" icon with the text
![atomic swap v3](https://user-images.githubusercontent.com/47353570/93335824-a85c6400-f82f-11ea-9b29-c4d46eff1b26.jpg)

**Comment by beam-mw** [comment]
Please implement Version 3

**Comment by dariatarakanova** [comment]
1/4 view - https://zpl.io/V1Dl1l4
1/3 view - https://zpl.io/2pXKmOo
1/2 view - https://zpl.io/aN1oXjQ

**Comment by anatolse** [comment]
there is a problem with the rendering of dashed ShapePath on different versions of Qt, so I did the solid line. I propose to postpone the dashed line for the future.

**Comment by kazaryan-t** [comment]
The button **"connect more currencies"** should be hidden when the wallet is connected to all available currencies.

![2110](https://user-images.githubusercontent.com/68247034/96714952-967c5c80-13ab-11eb-8e35-cfc3e952328d.png)

**Comment by kazaryan-t** [comment]
Checked on master 5.2.9717.3281
