### ISSUE TITLE
The highlighting of 'apply changes' button is cut for Beam Remote Node

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#186]
Now the highlighting of 'apply changes' button is cut for Beam Remote Node from Settins menu.
![image](https://user-images.githubusercontent.com/51320829/93444556-5b34cc80-f8d9-11ea-9616-c4fd459b3460.png)

The highlighting should be done as it's done for Bitcoin submenu:
![image](https://user-images.githubusercontent.com/51320829/93444961-79023180-f8d9-11ea-8fcf-7034ce78d285.png)

**Comment by anatolse** [comment]
fixed

**Comment by VladislavKulyba** [comment]
checked
