### ISSUE TITLE
Add button to wallet status "cannot connect to: (node _address)" when specific node is selected

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#188]
Design: https://zpl.io/VQk9pA5

When wallet cannot connect to specific/Integrated node please show this status + button "change". Button leads to settings/node, so user can change the node manually

![image](https://user-images.githubusercontent.com/47353570/93603811-30c43b80-f9cd-11ea-878b-eb7ca7ed603f.png)

**Comment by dariatarakanova** [comment]
**If 1 node lost connection:**

1) Wallet screen - Change wallet status to "connection to DASH/BITCOIN/etc node lost: 1.2.3.4" and change color to **red** also add button "reconnect" that leads to settings/node block https://zpl.io/VQk9pA5

2) Atomic Swap screen - https://zpl.io/V1Dl1l4

3) Settings screen - https://zpl.io/bJJrJeE (in the bottom)

**If 2+ nodes lost connection:**
1) Wallet screen - Change wallet status to "lost connection to nodes" and change color to **red** also add button "reconnect" that leads to settings/node block (first - to the first node in the list) https://zpl.io/aXerrkE

2) Atomic swap screen - https://zpl.io/agjDDwN

3) Settings screen - https://zpl.io/bJJrJeE (in the bottom). 


Bottom line:
green status - all good
red status - 1 or more nodes not connected (lost connection)
yellow status - reconnecting

**Comment by kazaryan-t** [comment]
Please, fix the error on the UTXO screen.

![Beam Wallet Masternet 2021-06-09 17 11 32](https://user-images.githubusercontent.com/68247034/121372803-3b51a700-c947-11eb-964e-08b43c5f80f0.png)

**Comment by KatsiarynaV** [comment]
When the wallet lost connection to Beam node the button "change settings" should open beam node block in settings
![gif04](https://user-images.githubusercontent.com/68267190/122373342-11f9d200-cf6a-11eb-9d2d-37abcaf4c1ca.gif)

**Comment by KatsiarynaV** [comment]
Checked
