### ISSUE TITLE
Wrong kernels Id for received max privacy transactions on linux

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#190]
**Description**

Wrong kernels Id for received max privacy transactions on latest testnet build for linux

**Pre-conditions:**
There are Wallet A and Wallet B with enough funds.

**Steps to reproduce:**
1. From Wallet A sent Max privacy transaction through online address
2. Wait until transaction will be received in the wallet B
3. Open transaction details in wallet B

**Expected**: There is an appropriate kernel Id 
**Actual**: 
![image](https://user-images.githubusercontent.com/51320829/93455985-bf5d8d80-f8e5-11ea-84af-d9ded6d608c4.png)

**Attachments** 

![image](https://user-images.githubusercontent.com/51320829/93455494-1c0c7880-f8e5-11ea-8529-785399c62ae1.png)

Environment
OS Name: Ubuntu 20.04.1 LTS
OS Type: 64-bit
Gnome version: 3.36.3

Wallet version: 5.1.9763.3213

**Comment by VladislavKulyba** [comment]
It doesn't show Kernel_Id at all. Please, fix it

![Snag_3c33953](https://user-images.githubusercontent.com/51320829/93581685-280e3e00-f9aa-11ea-9d63-b909ffd43685.png)


Wallet version: 5.1.9580.3194
EE_RC 5.1

**Comment by anatolse** [comment]
it's ok, incoming max privacy transaction doesn't have the kernel ID
