### ISSUE TITLE
Make the additional text for Max privacy transactions as it's done for regular

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#192]
Make the additional text for Max privacy transactions as it's done for regular
![Snag_3602bb8](https://user-images.githubusercontent.com/51320829/93570011-0b1e3e80-f99b-11ea-9533-0b28309f4f27.png)

There is no any additional text for max privacy transactions:
![Snag_36a09c8](https://user-images.githubusercontent.com/51320829/93571037-8df3c900-f99c-11ea-874a-86b7b015d817.png)

**Comment by dariatarakanova** [comment]
Let's add the same text as for regular transaction: The transaction is usually expected to complete in a few minutes.

**Comment by KatsiarynaV** [comment]
Checked on build 5.2.9709.3260
