### ISSUE TITLE
Background issues on master

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#196]
**Description** 
When you open the sender or receiver screen the wallet remember its background and use for all other screens.

**Steps to Reproduce**
1. Open wallet
2. Open Receiver screen (or Send screen)
3. Push Back button

**Expected**: Main screen background is default
**Actual**: Main screen background is the same as for Receiver screen (or Send screen).

**Attachments**
[2020-09-18_10-15-54.zip](https://github.com/BeamMW/beam-ui/files/5244414/2020-09-18_10-15-54.zip)

**Environment**
Environment
OS Name: Windows 10 Pro
Version: 1909
OS Build: 18363.1082

Wallet version: 5.2.9586.3215

**Comment by gingervik** [comment]
irrelevant
