### ISSUE TITLE
Cosmetic fixes in Receive dialog UI

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam-ui#198]
1, Change 'Max privacy' to 'Offline'

In the 'Max privacy' mode:

2. Remove Online Address (for wallet) pane
3. Remove 'Online address (for exchange and mining pool) pane
4. Change min fee to '~0,01 BEAM' 
5. Remove the 12 hours text at the bottom
6. Remove the 'Transaction is slower' text (Leave receiver pays fees)
7. Change the 'OFFLINE ADDRESS (for wallet)' text to just 'OFFLINE ADDRESS'

In the 'Regular' mode

7. Add 'for exchanges and pool below the  'Permanent address' toggle
8. Remove the ONLINE ADDRESS for exchanges and pools pane
9. Change 'ONLINE ADDRESS (for wallet)' text to 'ONLINE ADDRESS'

![Receive1](https://user-images.githubusercontent.com/37414225/93598994-25214680-f9c6-11ea-89c4-cb6508b32efa.PNG)
![Receive2](https://user-images.githubusercontent.com/37414225/93598997-26527380-f9c6-11ea-836c-197807d26d53.PNG)

**Comment by gingervik** [comment]
№4 is still needed to be fixed
<img width="1023" alt="Снимок экрана 2020-09-19 в 20 23 38" src="https://user-images.githubusercontent.com/28015224/93680043-46616000-fab6-11ea-8a43-2cdeb3187a35.png">

**Comment by gingervik** [comment]
checked

**Comment by Maxnflaxl** [comment]
typo in commit message, didnt mean to tag this issue
