### ISSUE TITLE
Create offer - when user first of all enter rate there is an error

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#2]
STR:
- open create offer screen
- put pointer in rate field
- enter rate
Actual: there is an error about invalid rate as there is no receive and sent amounts
Expected: there should not be an error
![invalid rate](https://user-images.githubusercontent.com/28015224/70858954-9c4c1a80-1f1c-11ea-8fde-f8a5a5ae1ba2.gif)

relates to #1053

**Comment by Roberrtt** [comment]
checked
