### ISSUE TITLE
The" edit your seed phrase" popup is not visible when all tabs with nodes are open

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#201]
When all the tabs with nodes(BTC,LTC,QTUM) are open and click on the "edit your seed phrase" button, the popup is located at bottom.

Step:
- go to settings screen
- open all the tabs with node
- switch to electrum in Bitcoin node
- click generate new seed phrase
- click Edit your seed phrase

Expected: pop-up is in the center.
Actual: popup is located at bottom
![bandicam-2020-09-22-12-12-37-154](https://user-images.githubusercontent.com/50007056/93892869-ad208c80-fcf5-11ea-82f1-4add8b834c1a.gif)

**Comment by anatolse** [comment]
fixed in https://github.com/BeamMW/beam-ui/commit/c2ea6060e109da3f623ba87f64cad6660523a84c

**Comment by KatsiarynaV** [comment]
Checked
