### ISSUE TITLE
Long value is inserted when "add all" button is clicked

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#203]
If the wallet has only 0.01 shielded coin, then when you click the "add all" button on the send screen, a long value will be inserted

Precondition:
There are 2 wallets A and B. In wallet there is only 0.01 shielded coin.

Step:
- B go to receive screen 
- B switch to offline and copy offline address
- A go to send screen
- insert copied address
- click  "add all" button

Actual long value is inserted
![ezgif com-crop](https://user-images.githubusercontent.com/50007056/93938650-3ce42c00-fd32-11ea-9876-5af5f5883c96.gif)

**Comment by KatsiarynaV** [comment]
If there are only regular coins in the wallet when we click the 'add all' button the fee isn't deducted from amount. And when we insert an offline address the fee isn't changed automatically to 1000100
![01](https://user-images.githubusercontent.com/68267190/95548818-8d37db00-0a0e-11eb-9880-bdb3fa3ed814.jpg)
![gif01](https://user-images.githubusercontent.com/68267190/95548822-8dd07180-0a0e-11eb-9e68-e1f29d81684f.gif)

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.2.9684.3240.

**Comment by KatsiarynaV** [comment]
If the wallet has only a coin smaller tnan fee for offline transactions (0.01 f.ex.), when you click the "add all" button and then insert an offline address on the send screen, a long value will be inserted

**Precondition:**
There are 2 wallets A and B. In the wallet A there is only 0.01 regular coin.

**Steps to reproduce:**
In the wallet B go to the receive screen and copy an offline address
In the wallet A go to send screen
Click "add all" button
Insert copied offline address

**Actual:** long value is inserted
![02](https://user-images.githubusercontent.com/68267190/95826451-fdaa6900-0d3a-11eb-8382-16408e3892e6.jpg)
![gif02](https://user-images.githubusercontent.com/68267190/95826464-00a55980-0d3b-11eb-9286-62675b3b234f.gif)

**Comment by KatsiarynaV** [comment]
Checked on build 5.2.9694.3249
