### ISSUE TITLE
Rename 'Request' to 'Requested amount' in Receive dialog

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam-ui#205]
Should be: Request amount (optional)

**Comment by dariatarakanova** [comment]
Design: https://zpl.io/2p6ZGOr 

Please pay attention only on "Request amount" block design.

Example:
![image](https://user-images.githubusercontent.com/47353570/94010893-38118d80-fdaf-11ea-9526-0524b10bfa72.png)

**Comment by kazaryan-t** [comment]
Need to rename "Request amount" to "Request**ed** amount".

![Beam Wallet Masternet 2020-10-07 10 21 46](https://user-images.githubusercontent.com/68247034/95300465-dd386580-0887-11eb-932d-251458cd38b7.png)
![Rename 'Request' to 'Requested amount' in Receive ](https://user-images.githubusercontent.com/68247034/95300481-e295b000-0887-11eb-8162-ce2c4fb26e52.png)

**Comment by kazaryan-t** [comment]
Checked on master 5.2.9684.3240.
