### ISSUE TITLE
Anonymity set

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#209]
1) Add "anonymity set" to Privacy settings https://zpl.io/bWzZxQk
2) Green line when coins can be spent immediately - https://zpl.io/bLeZlND
3) Yellow line when coins expected to spent less than in 2 days https://zpl.io/2jDAnz4
4) Red live when coins expected to 64k in more that 2 days and these coins can be spent in 48 hours https://zpl.io/bzrKgKE

**Comment by gingervik** [comment]
irrelevant
