### ISSUE TITLE
Estimated fee in UI different from the one that is sent to the network

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#210]
**Bug description**
When accepting a swap in the UI wallet, the amount of the evaluation fee is indicated higher than the one that is sent to the network. When decrypting, you can see that the amount sent to the network is much lower than what was displayed in the UI wallet.
![image](https://user-images.githubusercontent.com/45556620/94251186-dfff9600-ff2a-11ea-8426-0191948faf01.png)
![image](https://user-images.githubusercontent.com/45556620/94251464-3a98f200-ff2b-11ea-8c8c-753dfe11e788.png)
**The base of the wallet and the logs file**
[sender.zip](https://github.com/BeamMW/beam-ui/files/5282277/sender.zip)
[recipient.zip](https://github.com/BeamMW/beam-ui/files/5282422/recipient.zip)

**Comment by roman-strilets** [comment]
fixed

**Comment by Denis-Asipenko** [comment]
checked
