### ISSUE TITLE
Max Privacy UI

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam-ui#217]
In the Receive dialog there is a single toggle switch between: 'Regular' and 'Max Privacy'

In the Regular mode, on the right there are three panes:
1. Online address (for wallets)
2. Online address (for pools and exchanges)
3. Offline address

There are no QR codes on the panes. QR codes should be moved inside the show address dialog

In the 'Max Privacy' mode there is a single pane on the right saying 'Max Privacy Address'

**Comment by dariatarakanova** [comment]
Receive screens: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5f7f40a75591dd5918d39ed8

1) Transaction info rename to "Address Type" https://zpl.io/aRelvBK
2) Regular/Permanent (no need word "address" here) move to "Online address" block https://zpl.io/aRelvBK
3) Add "Copy" and "QR Code" icons near the addresses
4) "Show address" rename to 'More details"
5) Regular | one-time use https://zpl.io/aRelvBK
6) Regular | Permanent https://zpl.io/2j6Bn7A
7) Max privacy https://zpl.io/bJeowvK
8) Make text "Min transaction fee to send Max privacy coins is 0.01 BEAM." grey, not white
9) Regular address details (open when click on more details) https://zpl.io/Vkd4xEM . Please use the same text/fields as here
10) Max privacy address details https://zpl.io/2jDNoWx

**Comment by VladislavKulyba** [comment]
In the **Receiver screen** for each **Address details** window, the button 'copy address' should be changed to 'copy and close' as it's done in the design. https://zpl.io/Vkd4xEM. The button should copy the address and close the **Receiver screen**, which activates an address. Now, there are several methods to copy an address: by the icon, by clicking on the right-button and copy, by click on the 'copy address' button.

![Snag_91d311e](https://user-images.githubusercontent.com/51320829/96463817-cbfc3b00-122f-11eb-85d6-ef2445cfb37f.png)

**Comment by dariatarakanova** [comment]
@VladislavKulyba @anatolse 
updated screen for address details
- online for exchanges https://zpl.io/a8L63Yx
- online for wallets https://zpl.io/bl9yn9X

**Comment by VladislavKulyba** [comment]
Any comment can't be saved for sections Online Address (for exchanges or mining pool) and Offline Address (for wallet). Please, add the ability to save comments to these addresses.

![Snag_5500299](https://user-images.githubusercontent.com/51320829/96975696-7a033000-1523-11eb-86fc-d8ce739aadad.png)

For Online address (for wallet) one-time use|permanent and Max privacy address comments are saved.

**Video**: [bug_comments.zip](https://github.com/BeamMW/beam-ui/files/5428266/bug_comments.zip)

**Build version**: 5.2.9715.3278

**Comment by kazaryan-t** [comment]
Checked on master 5.2.9721.3292.
