### ISSUE TITLE
Display swap offers in blockchain explorer

### ISSUE THREAD

**Issue by beam-mw** [BeamMW/beam-ui#219]
From LilBit (https://t.me/beam_traders/146075)
"If we can display atomic swap offers on the Beam explorer or a website, new telegram members can check them anytime without loading up a wallet and be encouraged + informed on atomic swaps"

**Comment by sasha-abramovich** [comment]
@iscander01 which info exactly can be displayed? We'll design it.

**Comment by dariatarakanova** [comment]
It was done here https://github.com/BeamMW/blockex/issues/60
