### ISSUE TITLE
Send screen - max privacy UI

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#222]
All screens: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5f7f47ed43fead38120c420e

1) Please make non-active button more visible https://zpl.io/bPewozm
![image](https://user-images.githubusercontent.com/47353570/95734310-fc6e3300-0c8b-11eb-903d-5cc76fb34f0b.png)
2) One-time-use address https://zpl.io/V078nPQ . Rename "show address" to "more details"
3) Offline address https://zpl.io/bl9QR1k
4) Permanent https://zpl.io/bovwy0k
5) Max privacy address https://zpl.io/2vwvdnr
6) Max privacy address details https://zpl.io/2ZelvJJ
7) regular address details https://zpl.io/amoPErD

**Comment by VladislavKulyba** [comment]
1. In the **Send screen** for each **Address details** popups (open by *'more details'*), the button 'copy address' should be changed to 'copy and close' as it's done in the design. https://zpl.io/amoPErD. The button should copy the address and close the popup. 
![Snag_4741870](https://user-images.githubusercontent.com/51320829/96581283-438aa280-12e2-11eb-85c9-ab8adca0d367.png)

2. There is no error message if you're trying to send an offline transaction to yourself. the message should be: 
*Cannot send to your own offline address.*

![Snag_47569d7](https://user-images.githubusercontent.com/51320829/96581422-76cd3180-12e2-11eb-853b-a44e7a48a859.png)

3. Change **Type** to appropriate **Address Type** in the 'Confirm transaction details' popup. Probably, it's better to rename this name to **Address Type** either.

![Snag_47c4ff4](https://user-images.githubusercontent.com/51320829/96582136-8436eb80-12e3-11eb-8c54-cba71d96235c.png)

4. Please, add **0 (zero)** to the **Send screen** when you've just opened it. https://zpl.io/bPewozm
When you navigate to the field **Amount** to change a value, it should change to the cursor. 
Now, this field is empty.

![Snag_47c9589](https://user-images.githubusercontent.com/51320829/96582166-8ef18080-12e3-11eb-99df-89913be737bf.png)

**Comment by anatolse** [comment]
1,3,4 done
2 - won't fix (@bigromanov)

**Comment by VladislavKulyba** [comment]
4. In this field **0 (zero)** should be a placeholder.  When you navigate to the **Amount** field to change a value, it should change to an empty field with the cursor.

Right now, **0 (zero)** doesn't hide.
![Snag_b265ad](https://user-images.githubusercontent.com/51320829/96863198-2afbc300-146f-11eb-802d-22448a02a707.png)

**Comment by anatolse** [comment]
fixed

**Comment by VladislavKulyba** [comment]
If put a new-created offline address to the Send screen, the number of payments has value 0, instead of 10 payments. 
It blocks any offline transactions. 

![Snag_5322c98](https://user-images.githubusercontent.com/51320829/96972243-ec254600-151e-11eb-8a93-0055d42c31a9.png)

In the address details (open by more details), the number of payments has the correct value.

![Snag_5336ce8](https://user-images.githubusercontent.com/51320829/96972376-1d057b00-151f-11eb-9955-6c21ef53a6c9.png)

**Video**: 
[bug_payments.zip](https://github.com/BeamMW/beam-ui/files/5428140/bug_payments.zip)

**Build version**: 5.2.9715.3278

**Comment by KatsiarynaV** [comment]
1. Add text under the address field for **own offline address**
![07](https://user-images.githubusercontent.com/68267190/97305568-51a26b00-186e-11eb-8fc8-e2051e41c50e.jpg)
2. Cannot send offline transaction to own address
![08](https://user-images.githubusercontent.com/68267190/97306274-50257280-186f-11eb-8b2b-5741f35149d2.jpg)
**Build:** 5.2.9721.3291

**Comment by anatolse** [comment]
@KatsiarynaV, @gingervik, I've simply allowed this type of transaction in the wallet. Sending to own max privacy or offline address is a matter of dispute, so, I propose to open a separate issue on 5.3

**Comment by KatsiarynaV** [comment]
Checked on build 5.2.9723.3300
