### ISSUE TITLE
Add statuses for max privacy transactions to exported csv file

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#224]
**Description:**
Right now, statuses for "Sent max privacy", "In progress max privacy", "Received max privacy" displays into csv file the same as for regular transactions (Sent, in progress, received). Please, change these statuses to the appropriate for the csv file.

**Screenshot:** 
![Snag_136ce249](https://user-images.githubusercontent.com/51320829/96119015-06469f00-0ef5-11eb-9553-17f4c297ab53.png)

**Build version:** 5.2.9696.3254

**Comment by KatsiarynaV** [comment]
In statuses for maximum anonymity transactions change "max privacy" to "maximum anonymity"
![21](https://user-images.githubusercontent.com/68267190/133389416-eba89cca-1149-4cc0-8eab-0eef8f9010de.jpg)
![22](https://user-images.githubusercontent.com/68267190/133389969-e3ca0799-d770-4c90-b508-9323fed8cfc5.jpg)

**Comment by KatsiarynaV** [comment]
Checked
