### ISSUE TITLE
The min fee for coins isn't specified correctly on "accept offer" screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#227]
The minimum fee is displayed as for the Beam coin

Precondition:
There're 2  wallets A and B, nodes are configured for any coin in 2 wallets

Step:
- A create the offer (send BEAM,receive DOGE)
- B accept this offer
- B pay attention to the message( about  minimum fee) under the transaction fee field

Actual: Fee is specified for Beam coins
Expected: fee is specified for DOGE coins

Build: 5.2.9710.3261
![Screenshot_285](https://user-images.githubusercontent.com/50007056/96433880-f9d08800-120d-11eb-93af-bfc080e82805.png)

**Comment by roman-strilets** [comment]
It's fixed already

**Comment by Roberrtt** [comment]
checked
