### ISSUE TITLE
Notification displayed on the icon even if they are disabled. 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#23]
After disable notifications on  Setting screen notifications are still displayed on the icon.
Str:
1. Go to the wallet.
2. Go to the Settings screen.
3. Disable notifications. 
4. Send transaction on expired address or deleted address another wallet.
5. Cancel the sent transaction when it receives the "waiting for receiver" status.
6. Close and open the wallet again.
Expected: notifications don't display on the icon.
Actual: displayed notifications on the icon.
![image](https://user-images.githubusercontent.com/45556620/83106022-6a8ed080-a0c4-11ea-99f7-c9e5ccd9227e.png)
![image](https://user-images.githubusercontent.com/45556620/83106046-737fa200-a0c4-11ea-8777-bbf721ff11ad.png)

**Comment by echoby** [comment]
Notifications count displayed on main view. Main view defined in _"[your path]\beam-ui\ui\view\main.qml"_
Model for main view: _"[your path]\beam-ui\ui\viewmodel\main_view.h"_
Model implementation: _"[your path]\beam-ui\ui\viewmodel\main_view.cpp"_

`qmlRegisterType<MainViewModel>("Beam.Wallet", 1, 0, "MainViewModel");`

Method to get count of new notifications:
`int getUnreadNotifications() const;`

Class MainViewModel has member:
`WalletSettings& m_settings;`
Defined in _"[your path]\beam-ui\ui\model\settings.h"_

Following methods returns notifications mode.
```
// Notifications settings
bool isNewVersionActive() const;
bool isBeamNewsActive() const;
bool isTxStatusActive() const;
```

_MainViewModel::getUnreadNotifications()_ must consider this values.

Also instance of **MainViewModel** must listen some signal from _m_settings_, need to implement this sending of this on following methods in _WalletSettings_ class:
```
    void setNewVersionActive(bool isActive);
    void setBeamNewsActive(bool isActive);
    void setTxStatusActive(bool isActive);
```
On _MainViewModel_ instance receive signal from _m_settings_ need emit _unreadNotificationsChanged_ signal to update notifications count.

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9485.3085

**Comment by echoby** [comment]
Unused code removed, need recheck

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9489.3089
