### ISSUE TITLE
The "to" field on beam side is empty

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#231]
The "to" field on beam side is empty on atomic swaps tab

Precondition:
There're 2 wallets A and B, nodes are configured for any coin in 2 wallets

Step:

- A create offer (send BTC, receive BEAM)
- B accept this offer
- B pay attention "To" field  

Actual: filed is empty
Expected; There's address 
Build:  5.2.9713.3273

![Screenshot_301](https://user-images.githubusercontent.com/50007056/96873570-cd22a780-147d-11eb-811c-7420db7c1681.png)

**Comment by roman-strilets** [comment]
it's fixed in https://github.com/BeamMW/beam-ui/issues/234

**Comment by Roberrtt** [comment]
checked
