### ISSUE TITLE
Automatically connect to Atomic Swap nodes

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#233]
On Setup node connectivity screen add checkbox that allows to automatically connect to Atomic Swap nodes (Bitcoin, Litecoin, Qtum) via Electrum.
<img width="977" alt="Screenshot at Oct 26 17-51-17" src="https://user-images.githubusercontent.com/7249484/97158337-3c690600-17b4-11eb-801f-83495e7d1d85.png">

Design is here https://zpl.io/2p6B5Qr

**Comment by dariatarakanova** [comment]
it won't be implemented right now

**Comment by dariatarakanova** [comment]
duplicate https://github.com/BeamMW/beam/issues/1320
