### ISSUE TITLE
Remove text in the settings for Dogecoin about switching to electrum

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#236]
When the swap is in progress, there is a text about switching to electrum in  Dogecoin node settings. Remove this text for the Dogecoin node
![Screenshot_309](https://user-images.githubusercontent.com/50007056/97359776-571fa580-18ae-11eb-81d0-80ab64fae6b9.png)

**Comment by roman-strilets** [comment]
For dogecoin use the next text "Swap in progress, cannot disconnect."
For other coins use the next text "Swap in progress, cannot disconnect or switch connection type."

@dariatarakanova please update design

**Comment by Roberrtt** [comment]
checked
