### ISSUE TITLE
Loading screen - fix the text "estimated time" - REWARD 150 BEAM

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#24]
Please fix the text. 
It should be **Estimated** time, not estimate (this screenshot from design)
![image](https://user-images.githubusercontent.com/47353570/83390574-c2964180-a3fa-11ea-9353-114c76e2faaa.png)

**Comment by echoby** [comment]
To define UI for loading screen we use _"loading.qml"_ file. You can find it in _"[your path]\beam-ui\ui\view\loading.qml"_.
Firs step is to find "broken" string. Search in _"loading.qml"_ was unsuccesfull.
But we see that "broken" string betwen **"Loading wallet..."** text label and **progress bar**.
After serching for _"Loading wallet..."_ we found a code that responsible for this message 
<img width="510" alt="1" src="https://user-images.githubusercontent.com/1681548/83517252-3ca0f600-a4e1-11ea-9eb1-14b6967e7614.PNG">

Text for this message provided by _"viewModel.progressMessage"_.
Id "viewModel" defined at this file as instance of _"LoadingViewModel"._
In _"[your path]\beam-ui\ui\ui.cpp"_ registered all custom qml types that Beam use.
And _"LoadingViewModel"_ registered as 
`qmlRegisterType<LoadingViewModel>("Beam.Wallet", 1, 0, "LoadingViewModel");`
C++ class **LoadingViewModel** defined in _"[your_ path]\beam-ui\ui\viewmodel\.loading_viewh" and implemented in _"[your path]\beam-ui\ui\viewmodel\loading_view.cpp"_

_"viewModel.progressMessage"_ defined as:
`Q_PROPERTY(QString progressMessage READ getProgressMessage WRITE setProgressMessage NOTIFY progressMessageChanged)`


Implementation for setter and getter:
```
const QString& LoadingViewModel::getProgressMessage() const
{
    return m_progressMessage;
}

void LoadingViewModel::setProgressMessage(const QString& value)
{
    if (m_progressMessage != value)
    {
        m_progressMessage = value;
        emit progressMessageChanged();
    }
}
```
"setProgressMessage" called from _"void LoadingViewModel::updateProgress()"_ method
And we see that this method responsible for generation progress message string.

By this 2 lines generates translated string with placeholder.
```
//% "Estimate time: %s"
QString estimateStr = qtTrId("loading-view-estimate-time");
```

You can read about function **"qtTrId"** in official qt documentation.
https://doc.qt.io/qt-5/qtglobal.html#qtTrId

To fix this issue we nead just edit comment
before:
`"//% "Estimate time: %s""`
after:
`"//% "Estimated time: %s""`

After cmake configuring and generating done all translation files will updates.
You can find translation files in:
_"[your path]\beam-ui\ui\i18n"_
In localized files you must find message with id **"loading-view-estimate-time"** and edit translation for your languages.
And delete property _'type="unfinished"'_, also you can remove tag _"oldsource"_.
Enjoy.

**Comment by SomethingGettingWrong** [comment]
'type="unfinished"' and "oldsource". I didnt see that for "ID "loading_view_estimate_time" when i searched

**Comment by echoby** [comment]
> 'type="unfinished"' and "oldsource". I didnt see that for "ID "loading_view_estimate_time" when i searched

Not related to this task, it is general recommendation.

**Comment by Roberrtt** [comment]
Checked
