### ISSUE TITLE
Statuses for transactions sent to own address

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#241]
Transactions sent to own address (offline, max privacy, public offline): please, add design for statuses 
![10](https://user-images.githubusercontent.com/68267190/97417829-2d4f9880-1919-11eb-84e7-064466815445.jpg)

**Comment by dariatarakanova** [comment]
Statuses for:

- sent max privacy to own address
- sending max privacy to own address
- sent offline to own address
- sending offline to own address

https://zpl.io/b6xJ58q

![image](https://user-images.githubusercontent.com/47353570/115454183-2a2ec880-a229-11eb-9da0-a204901f83fa.png)

**Comment by AndreyDyakonov** [comment]
Irrelevant
