### ISSUE TITLE
Estimated transaction fee isn't calculated on create offer screen 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#245]
Estimated transaction fee isn't calculated  on create offer screen 
![Screenshot_330](https://user-images.githubusercontent.com/50007056/97709587-a262cf80-1acb-11eb-99c9-baacea945824.png)

**Comment by roman-strilets** [comment]
fixed at rev # 546708e8b3693ee4dbeb28a856e334b1b1b67aaa

**Comment by Roberrtt** [comment]
checked
