### ISSUE TITLE
Qt warning: model size is less than 0

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#246]
There is annoying Qt warning  "Model size of -xxx is less than 0" right after opening main screen and when opening receive view. Need to investigate and fix. Probably it is connect to transactions table. This is present for a long long time already.

**Comment by anatolse** [comment]
I've found this https://bugreports.qt.io/browse/QTBUG-72543
It should be fixed, but I reproduce it on 5.15

**Comment by chapati** [comment]
Since this is qt issue and not ours, and it cannot be fixed until fix is backported by qt devs let's consider this closed/won't fix.
