### ISSUE TITLE
Update the text for extended transaction statuses

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#25]
Atomic Swap:
1) The swap is expected to complete in 10 minutes at most
2) If nobody accepts the order in 10 minutes at most, the offer will be automatically canceled
3) Swap failed, the money is being released back to your wallet

Regular transactions:
1) If the receiver doesn't get online in 10 minutes, the transaction will be canceled.
2) It is taking longer than usual. In case the transaction could not be completed it will be canceled automatically in 10 minutes.

![image](https://user-images.githubusercontent.com/47353570/83518089-b08fce00-a4e2-11ea-87b7-1b95db9f4801.png)

**Comment by Roberrtt** [comment]
checked
