### ISSUE TITLE
Assets UI: send preselect asset

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#250]
Need to preselect currently selected asset in the send view. Currently always beam is selected even if the user has selected an asset in the assets pane on the main screen.

**Comment by Roberrtt** [comment]
checked

**Comment by Roberrtt** [comment]
This is reproduced on build 6.0.10467.3809 win (beamx / 01.29)

**Comment by kazaryan-t** [comment]
Checked on build 6.0.10779.3975
