### ISSUE TITLE
Assets: icons

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#267]
At the moment we display several predefined asset icons. Need

1) Download real icon from asset info (address privacy implications) & extract colors from icons - **moved to 6.1**
2) Add more default icons & colors - **done**
3) May be add OPT_COLOR to asset meta - **done**

**Comment by chapati** [comment]
2. Done

**Comment by chapati** [comment]
To test create asset with OPT_COLOR=color in hex format like #FFA021 fo example and check that this color is used in UI.
Move task to 6.1 afterwards beacuse of task #1.

**Comment by Roberrtt** [comment]
checked 2 and 3

**Comment by chapati** [comment]
Need to discuss with romanov if we want to implement this. If for all assets or for verified ones. How to deliver icon (read url directly, which is privacy-leaking or distribute via SBBS) &c. Do not implement until all these moments are discussed. For verified assets we have a separate task.
