### ISSUE TITLE
Applications: privacy

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#268]
Need to implement privacy warning screen for the applications section

**Comment by chapati** [comment]
Done in #569

**Comment by chapati** [comment]
Added privacy warning

![gnome-shell-screenshot-88CO50](https://user-images.githubusercontent.com/12074933/123278854-f9f8f400-d50f-11eb-976b-d0fd798e3d3d.png)

And section in setting

![gnome-shell-screenshot-JHWU50](https://user-images.githubusercontent.com/12074933/123278939-1137e180-d510-11eb-945b-410001d4172e.png)

Behavior is the same as for external links opening.

**Comment by Sergei-Beam** [comment]
checked
