### ISSUE TITLE
Applications: icons

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#269]
Need to add

1) Default application icon (when there is no icon provided by developer)
2) Development app icon (this application is added only locally when being developed. Make it clearly visible)

**Comment by chapati** [comment]
Now red envelope, faucet & vault should have non-default icons

**Comment by chapati** [comment]
![gnome-shell-screenshot-M4XIY0](https://user-images.githubusercontent.com/12074933/108073577-42436980-7079-11eb-8337-e28cec5d108c.png)

**Comment by KatsiarynaV** [comment]
Checked
