### ISSUE TITLE
Applications: title

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#274]
Need to add back button & title for the loaded application
![gnome-shell-screenshot-ZZ2PT0](https://user-images.githubusercontent.com/12074933/98278858-3a6c2780-1faa-11eb-93d3-6b60303f601d.png)

**Comment by chapati** [comment]
Now UI shows app title itself. Remove from html.

![gnome-shell-screenshot-AL8IW0](https://user-images.githubusercontent.com/12074933/102815806-0de76000-43de-11eb-9a84-88ca6e6c7b76.png)

**Comment by Roberrtt** [comment]
checked
