### ISSUE TITLE
Applications: loading

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#275]
1. Need to handle application loading errors.
2. Need to review loading screen font. May be use the same as for app title.

**Comment by chapati** [comment]
How to test

1. In settings.ini add the following
[devapp]
name=Bad App
url=http://example1.com213
2. Open 'Bad App' in dapps section
Expected Result: error screen should be show in BeamX colors (not default browser error page):

![gnome-shell-screenshot-93ZFX0](https://user-images.githubusercontent.com/12074933/104941824-9e589680-59c4-11eb-9fd0-6bcbb43756fe.png)

**Comment by Roberrtt** [comment]
checked
