### ISSUE TITLE
Wallet views list highlight

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#278]
Selected view highlight (vertical line at the very left) disappears when focus is lost. For example open wallet/send. Need always display it.

Wallet/send opened:

![gnome-shell-screenshot-M56IV0](https://user-images.githubusercontent.com/12074933/102531101-db262a80-40b2-11eb-91ba-bebc62550649.png)

Expected:
![gnome-shell-screenshot-2NMNT0](https://user-images.githubusercontent.com/12074933/98281249-908e9a00-1fad-11eb-860b-d1fdd7b279cd.png).

**Comment by Roberrtt** [comment]
checked
