### ISSUE TITLE
There is no text for nodes (BTC, QTUM, LTC, DASH) in the settings(Linux)

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#288]
There is no text in the node settings on Linux
![Screenshot_362](https://user-images.githubusercontent.com/50007056/99241149-81f67d00-280e-11eb-82cb-af70a1f1a387.png)

**Comment by Denis-Asipenko** [comment]
Not fix on testnet 5.2.9965,3378
![image](https://user-images.githubusercontent.com/45556620/99377758-a4a09880-28d7-11eb-8670-7ede781b90ce.png)

**Comment by Denis-Asipenko** [comment]
checked on testnet 5.2.9965.3380
