### ISSUE TITLE
When you first launch the wallet, the "Red envelope" doesn't open

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#291]
When we open the wallet for the first time after creating or restoring it and try to open the "Red envelope", the screen is empty

Note: If you switch tabs and re-open, then open

Step:
- create\restore wallet
- open the "DAPP Store" tab
- click  launch button for Red Envelope

Actual: the screen is empty
![bandicam-2020-11-17-14-16-36-585](https://user-images.githubusercontent.com/50007056/99384195-1d0b5780-28e0-11eb-9445-13a48d95f5ec.gif)

**Comment by chapati** [comment]
This is fixed, please test now.

**Comment by Roberrtt** [comment]
not fixed 
build 5.3.10209.3566 (Windows)

**Comment by Roberrtt** [comment]
not fixed 
build: 6.0.1033.3676 BeamX

**Comment by chapati** [comment]
Looks like something inside JS: WebSocket connection to 'ws://3.136.182.25/ws' failed: WebSocket is closed before the connection is established.

Bro, would you please take a look.
You need.

1) Restore wallet
2) Load envelope

This is reproduce only once, only after restore. On the second, third &c. run is not reproduced.
