### ISSUE TITLE
Contacts: two contacts are created with different addresses and with the same comment and identity

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#298]
**Bug description**
When we send transaction to a contact from contacts tab and change the comment on the send screen two contacts are created with different addresses and with the same comment and identity 

There are 2 or more contacts in the address book
**Steps to reproduce the behavior:**
1. Go to the address book: contacts tab
2. Send transaction to an contact and change the comment to the different one on the send screen
3. Go to the address book: contacts tab

**Current behavior:**
Two contacts are created with different addresses and with the same comment and identity

**Expected behavior:**
The comment is updated

**Platform and build:**
Windows
OS version: 10 pro
BEAM Build number: 5.2.10079.3379 (mainnet_rc).

![04](https://user-images.githubusercontent.com/68267190/99631082-08e46900-2a4c-11eb-8896-9231ae8a226a.jpg)
![05](https://user-images.githubusercontent.com/68267190/99631084-097cff80-2a4c-11eb-9912-abebbe69f50e.jpg)
![06](https://user-images.githubusercontent.com/68267190/99631087-0a159600-2a4c-11eb-8e34-231989e6b8cb.jpg)

**Comment by kazaryan-t** [comment]
Checked.
