### ISSUE TITLE
Investigate why the Mac wallet sometimes crashes

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#300]
**Bug description**
The Mac wallet sometimes crashes and there is no specific case in which the crash was reproduced. However, there are reports after these crashes.
**Platform and build:**

- MacOS
- OS version: Catalina 10.15.7
- BEAM Build number: 5.2.10079.3379(mainnet_rc).
**Reports files**
[reports.zip](https://github.com/BeamMW/beam-ui/files/5573958/reports.zip)

**Comment by beam-mw** [comment]
Irrelevant
