### ISSUE TITLE
Incorrect fee display for swap the LTC 

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#301]
**Bug description**
The wallet displays an incorrect fee for swap the LTC  which can cause the transaction to get stuck.
**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/45556620/99824920-69b49400-2b67-11eb-9f4c-07bd53518dc3.png)
![image](https://user-images.githubusercontent.com/45556620/99824979-7f29be00-2b67-11eb-8a65-2768b0540ece.png)

**Comment by Denis-Asipenko** [comment]
The recommended fee isn't displayed when connecting to the node
![image](https://user-images.githubusercontent.com/45556620/99977918-53504780-2db6-11eb-8873-c0f5dc4c53b9.png)

**Comment by gingervik** [comment]
error is not on our side
