### ISSUE TITLE
Red Envelope - design

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#303]
1. When you first launch the Red Envelope, change the text and only the "Deposit" button is available, but if there are no coins in wallet, the button isn't active
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f6df7eac279882e7ef33456
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f74fa90676cba31df106bb7
![Screenshot_396](https://user-images.githubusercontent.com/50007056/99939063-47469480-2d7a-11eb-96d8-593966aadb57.png)

2. When the coins were sent, the text should be " Deposit successful"
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f6df7ecf5f58889ad21a6cf
![Screenshot_400](https://user-images.githubusercontent.com/50007056/99944824-972a5900-2d84-11eb-9dc1-41aff3f2d99d.png)

3. When we have caught the coins , change the picture of congratulations
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f7383de04b8a95feb765610
![Screenshot_402](https://user-images.githubusercontent.com/50007056/99945587-efae2600-2d85-11eb-87b2-f30fbcb0a47b.png)

4. Add the amount for the text in 'Withdraw' popup
![Screenshot_405](https://user-images.githubusercontent.com/50007056/99945931-91ce0e00-2d86-11eb-9e2b-bfa0809fbf1c.png)

5. Add the "catch BEAM" button when we send the coins again
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f74fa927c5d8837465800c1
![Screenshot_409](https://user-images.githubusercontent.com/50007056/99949079-816c6200-2d8b-11eb-8b02-3da90f070872.png)

6. Change the image when withdraw coins
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f6df7f0f0fd738a6053d43a
![Screenshot_411](https://user-images.githubusercontent.com/50007056/99949864-c80e8c00-2d8c-11eb-833b-19ee30062286.png)

**Comment by chapati** [comment]
1. 

This state should be displayed when there is 0 in envelope
![gnome-shell-screenshot-09NMU0](https://user-images.githubusercontent.com/12074933/100137822-1a8b9d80-2e9e-11eb-9dcc-0f46bff727a8.png)

This state should be displayed when there is a) >0 in envelope b) you did not catch any beam in the current round
![gnome-shell-screenshot-25OJU0](https://user-images.githubusercontent.com/12074933/100137958-5aeb1b80-2e9e-11eb-9deb-d3ab8c59dc7c.png)


Use wallet_status from API to display this
![gnome-shell-screenshot-SP3OU0](https://user-images.githubusercontent.com/12074933/100137869-37c06c00-2e9e-11eb-8159-1caab2cdcdcb.png)

**Comment by Sergei-Beam** [comment]
Closed as irrelevant
