### ISSUE TITLE
Locked Max privacy amounts

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#304]
Locked dropdown https://zpl.io/bz4rJMX
![image](https://user-images.githubusercontent.com/47353570/99959575-ef1c8c00-2d93-11eb-883c-844ba42707c4.png)

More details https://zpl.io/VxEEkWE
![image](https://user-images.githubusercontent.com/47353570/99959602-fba0e480-2d93-11eb-8695-1a4b5f52593c.png)

**Comment by Denis-Asipenko** [comment]
1. When the user received max privacy transactions and opens " More details"  the received amount is duplicated.
2. Default sorting DESC and if the user changes it to ASC and then closes the window and opens again then sorting stayed ASC.
![image](https://user-images.githubusercontent.com/45556620/100852414-8b7f1680-3497-11eb-9830-3cefaffaf491.png)
![image](https://user-images.githubusercontent.com/45556620/100852425-9043ca80-3497-11eb-9247-0f142ed24194.png)

**Comment by Denis-Asipenko** [comment]
checked
