### ISSUE TITLE
Settings - add "Max privacy lock time limit" to Privacy section

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#305]
Add to Privacy section "Max privacy lock time limit" 
default view https://zpl.io/bWzZxQk
![image](https://user-images.githubusercontent.com/47353570/99959508-d2805400-2d93-11eb-811c-02f4dec882d0.png)

selected view https://zpl.io/adZd95R
![image](https://user-images.githubusercontent.com/47353570/99959527-dc09bc00-2d93-11eb-8fbf-bec13a61afdb.png)

**Comment by Roberrtt** [comment]
Remove the arrow to open a box
![Screenshot_28](https://user-images.githubusercontent.com/50007056/100861808-62fd1980-34a3-11eb-8dbf-4b25519ececd.png)

**Comment by Roberrtt** [comment]
checked
