### ISSUE TITLE
[Red Envelope] Remove the by default "5" in the Deposit

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#307]
When sending a Deposit, the default amount in  pop-up is 5
Expected: empty string
![Screenshot_415](https://user-images.githubusercontent.com/50007056/99957816-58eb6480-2d99-11eb-9e90-d55f1327cd0e.png)

**Comment by chapati** [comment]
It is done intentionally, default amount is 5

**Comment by Roberrtt** [comment]
checked
