### ISSUE TITLE
The balance is displayed incorrectly if the wallet has a created asset

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#309]
If you create an asset in CLI wallet and open this wallet in UI, the balance is displayed incorrectly
![Screenshot_394](https://user-images.githubusercontent.com/50007056/99997035-a4b80100-2dcd-11eb-8890-860738f4ff97.png)

**Comment by Roberrtt** [comment]
Asset names are not fully visible on the send screen
![Screenshot_426](https://user-images.githubusercontent.com/50007056/100112333-2cf6de80-2e80-11eb-8a6d-edc122f160c8.png)

**Comment by chapati** [comment]
First issue fixed. Commit https://github.com/BeamMW/beam-ui/commit/85d348a7c0fa9d598bf22c3967c86c3c2632ea5c
Create a separate bug for the second issue please.

**Comment by Roberrtt** [comment]
Remove the "-" under the amount
![Screenshot_430](https://user-images.githubusercontent.com/50007056/100194439-c1a41f80-2f06-11eb-92e6-0cd8f0c7d0fa.png)

**Comment by Roberrtt** [comment]
checked
