### ISSUE TITLE
Fix the transaction/address details pop-up 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#310]
When you click details on transaction, the buttons are shifted down
![Screenshot_423](https://user-images.githubusercontent.com/50007056/100056337-94883c00-2e36-11eb-92b6-3144f911617a.png)
In the "receive" tab, the address details popup
![Screenshot_422](https://user-images.githubusercontent.com/50007056/100056554-e6c95d00-2e36-11eb-9042-12e7f699841b.png)

**Comment by Roberrtt** [comment]
not fixed for receive screen 
build: 6.0.1033.3676 BeamX

**Comment by chapati** [comment]
Please test now on the latest build.

**Comment by Roberrtt** [comment]
not fixed
build 6.0.10414.3740 BeamX
![Screenshot_181](https://user-images.githubusercontent.com/50007056/105017448-d60f1f00-5a54-11eb-9212-3482eece7fee.png)
![Screenshot_182](https://user-images.githubusercontent.com/50007056/105017456-d6a7b580-5a54-11eb-97d8-e4f29041ba7e.png)

**Comment by chapati** [comment]
Looks like win-only bug. Need help from somebody with windows.

**Comment by chapati** [comment]
Duplicate #493

**Comment by chapati** [comment]
Please check on BeamX

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.10801.3985
