### ISSUE TITLE
Settings - notification: wallet updateS, not update (spelling)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#312]
Please change  "wallet update" "wallet update**S**" in Notification settings https://zpl.io/bLlyKeJ

In current implementation
![image](https://user-images.githubusercontent.com/47353570/101765896-a3374a00-3aea-11eb-9e3f-27fc7d96d479.png)

Correct spelling 
![image](https://user-images.githubusercontent.com/47353570/101765916-acc0b200-3aea-11eb-853d-5832a0c35ca4.png)

**Comment by kazaryan-t** [comment]
Checked on 5.3.10045.3503.
