### ISSUE TITLE
Wallet screen - Add "wallet" icon+text when no transactions in wallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#317]
Now if there are no transactions in the wallet we can see just empty space.

![image](https://user-images.githubusercontent.com/47353570/100063268-a15a5f00-2e39-11eb-9c8e-5b8e4af61068.png)

Please add icon and text "Your transaction list is empty" as here https://zpl.io/bWmYp9

![image](https://user-images.githubusercontent.com/47353570/101143611-cf9d2300-361f-11eb-9c43-7372367234a8.png)

**Comment by anatolse** [comment]
it's not relevant anymore

**Comment by kazaryan-t** [comment]
Checked.
