### ISSUE TITLE
Receive screen - add prefilled text "Comments are local and won't be shared." on comment field

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#318]
Please add text "Comments are local and won't be shared." to comment field, the same as it now already implemented on Send screen.

Receive screen:

![image](https://user-images.githubusercontent.com/47353570/101347369-a6d09400-3892-11eb-85f7-c432a5ea7cec.png)

Send screen:

![image](https://user-images.githubusercontent.com/47353570/101347327-96201e00-3892-11eb-8d52-d4c4db30400a.png)

**Comment by kazaryan-t** [comment]
Please, implement the font and font size as in the design:

![create swap offer - assets - 01 Desktop Wallet - Z](https://user-images.githubusercontent.com/68247034/121204088-4ccf7c00-c87f-11eb-9263-a12c307e3a8f.png)

![Beam Wallet Masternet 2021-06-08 17 31 51](https://user-images.githubusercontent.com/68247034/121204082-4c36e580-c87f-11eb-8721-3133da3ff38e.png)

![create swap offer - assets - 01 Desktop Wallet - ZOIUHG](https://user-images.githubusercontent.com/68247034/121204196-640e6980-c87f-11eb-9d44-319058c4d117.png)

**Comment by gingervik** [comment]
opened a separate task for font issue #677

This can be closed
