### ISSUE TITLE
Receive screen - change design for Regular/Max privacy switcher

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#319]
In current implementation switcher has old design. Please change switcher design according to design https://zpl.io/aRelvBK

Current implementation:
![image](https://user-images.githubusercontent.com/47353570/101152486-d336a700-362b-11eb-8249-dd58f1ba7ee6.png)

Design:
![image](https://user-images.githubusercontent.com/47353570/101152436-c1ed9a80-362b-11eb-9b0e-0fd2895f1ebb.png)

**Comment by gingervik** [comment]
irrelevant
