### ISSUE TITLE
Add information about unlinked funds 

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#32]
Show panel with volumes of unlinked and linked UTXOs new Available.
Please pay attention on separator line. Now it is between Available and other sections
![image](https://user-images.githubusercontent.com/47353570/83146150-89aa5400-a0fe-11ea-8a2a-83c82614750f.png)

**Comment by Denis-Asipenko** [comment]
It will be checked when the Lantus is added to UI.

**Comment by gingervik** [comment]
irrelevant
