### ISSUE TITLE
"Create Swap Offer" screen - Move button "copy token and close"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#322]
Move button "copy token and close" to box https://zpl.io/2p5NQrQ

In current implementation:
![image](https://user-images.githubusercontent.com/47353570/101183929-c41a1e00-3658-11eb-8033-2a44e1091521.png)

New position: 
![image](https://user-images.githubusercontent.com/47353570/101184066-f0ce3580-3658-11eb-8ab2-1ca072aa1cc4.png)

**Comment by dariatarakanova** [comment]
Ot will be resolved in https://github.com/BeamMW/beam-ui/issues/329

**Comment by kazaryan-t** [comment]
Please, rename **Show token** button to **More details** as in the design https://zpl.io/2p5NQrQ

![0 1](https://user-images.githubusercontent.com/68247034/102326829-f4858480-3f95-11eb-99c1-3d530fda40cf.png)

![0 2](https://user-images.githubusercontent.com/68247034/102326970-1e3eab80-3f96-11eb-8bf1-2553f20a3e97.png)

**Comment by Aleksandr-Starun** [comment]
We have a separate task for this - https://github.com/BeamMW/beam-ui/issues/420

**Comment by kazaryan-t** [comment]
Checked.
