### ISSUE TITLE
Contract Apps: errors handling

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#333]
We need to add at least some minimal errors handling & displaying for all apps. Add at least div wit the red text & reconnect after 10 seconds. For now for example if you try to run contract apps on master you would get the following:

![gnome-shell-screenshot-ZQWIU0](https://user-images.githubusercontent.com/12074933/100156393-dad2af00-2eb9-11eb-8d25-dc346ba271cc.png)

App is unable to check the contract id (empty cid list is returned) and it just silently dies.
This is not the only case. When app is loaded and something bad happens need to display error div as well.

**Comment by Roberrtt** [comment]
Make  text in the center, and change "id" to " cid" for Vault
![Screenshot_519](https://user-images.githubusercontent.com/50007056/112797145-a4798c00-9073-11eb-8b62-b38116dc8713.png)

**Comment by chapati** [comment]
Please also check that errors are correctly handled when tx_send + small fee/not enough BEAM is handled (and errors from other requests)

**Comment by Roberrtt** [comment]
checked
