### ISSUE TITLE
Assets with a 0 balance are displayed in the UI

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#335]
If we create assets in a CLI and open its db via the UI. Then assets with 0 balance will be displayed
![Screenshot_431](https://user-images.githubusercontent.com/50007056/100207877-26687580-2f19-11eb-83ae-6be916b1ca31.png)
Pass 1
[wallet.zip](https://github.com/BeamMW/beam-ui/files/5595674/wallet.zip)

**Comment by chapati** [comment]
Only assets with any 0-zero value will be displayed now. It is possible that asset entry in assets pane would be still 0 if asset for example is 'receiving' or 'maturing' or 'sending'. Though only registered assets would be not displayed. If you had an asset and sent all the amount to somebody it will be displayed while sending > 0 but removed when sent completely. Translations with 100% spent asset would be still visible in the transactions table.

**Comment by Roberrtt** [comment]
checked
