### ISSUE TITLE
Remote node do not support max privacy and offline addresses

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#341]
1) Show comment "To support Max privacy and offline transactions please connect to integrated node or to own node configured with your owner key." when user connects to remote node. And disable Show offline public address in Utilities block https://zpl.io/bojAj8v
![image](https://user-images.githubusercontent.com/47353570/100236290-23c84900-2f36-11eb-9167-b6ed05c68de0.png)

2) When remote node connected show status "online: connect to integrated or owned node to enable max privacy and public offline transactions" and button https://zpl.io/VOZyZ0Q
![image](https://user-images.githubusercontent.com/47353570/100236316-2c208400-2f36-11eb-8faf-a09b399e4ca2.png)

3) Receive screen - Disable Max Privacy in switcher and Offline address block https://zpl.io/2yNoNGG
![image](https://user-images.githubusercontent.com/47353570/100237787-1318d280-2f38-11eb-9944-7876874722be.png)

**Comment by gingervik** [comment]
@anatolse please, implement point 1 for now only

**Comment by gingervik** [comment]
p.3 was fixed in a compromise way with current design
p.2 won't fix now

**Comment by Denis-Asipenko** [comment]
When a user creates a wallet with a connection to a random node, a new design must be applied.
![image](https://user-images.githubusercontent.com/45556620/100360753-6d826380-300a-11eb-8355-8f7c9f06867b.png)
![image](https://user-images.githubusercontent.com/45556620/100360794-78d58f00-300a-11eb-8ddf-810f0c6de298.png)

**Comment by anatolse** [comment]
@Denis-Asipenko , please, re-check on newer version

**Comment by Denis-Asipenko** [comment]
checked
