### ISSUE TITLE
Letter A in "Available" section looks bold

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#345]
Currently in testnet 5.2 and BeamX letter A looks bolder.
![image](https://user-images.githubusercontent.com/47353570/100596269-a4a38e00-3304-11eb-93e2-d67d59251a93.png)

Correct view https://zpl.io/bz4rJMX

![image](https://user-images.githubusercontent.com/47353570/101157813-632c1f00-3633-11eb-9be9-c3ccd5b06656.png)

**Comment by anatolse** [comment]
it's no longer relevant

**Comment by kazaryan-t** [comment]
Irrelevant.

Currently, the word Available is not displayed on the main screen.
![Beam Wallet Masternet 2021-06-04 15 17 30](https://user-images.githubusercontent.com/68247034/120799774-d57cae00-c547-11eb-8482-86d4045d3009.png)
