### ISSUE TITLE
Fix assets icons

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#347]
Please upload new icons for assets https://zpl.io/belryQD
1) It should be correct triangle, not crashed as in current implementation.
2) Icons should be with gradient inside (the same color as icon border)
![image](https://user-images.githubusercontent.com/47353570/110922168-0cb43800-8328-11eb-956f-1b7a1f4dbab3.png)

Current implementation
![image](https://user-images.githubusercontent.com/47353570/110922085-f27a5a00-8327-11eb-9729-fab45e08723f.png)

![image](https://user-images.githubusercontent.com/47353570/110704228-58b68e00-81fd-11eb-900d-014f75d6fff9.png)

**Comment by chapati** [comment]
1. Images are with 'crashed' triangle in design. Please fix it in design first. Triangle in red circle is OK, in blue is misplaced

![gnome-shell-screenshot-UW6D00](https://user-images.githubusercontent.com/12074933/111374154-d53de680-86ad-11eb-89c5-a197647ef22b.png)

2. Radial gradient is rendered incorrectly by QT. We cannot fix this. Need to rework image somehow
```
<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 26 26">
    <defs>
        <radialGradient id="yxlkbuwbka" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
            <stop offset="0%" stop-color="#9F56C2"/>
            <stop offset="100%" stop-color="#103051"/>
        </radialGradient>
    </defs>
    <g fill="none" fill-rule="evenodd">
        <g>
            <g>
                <g>
                    <g transform="translate(-341 -258) translate(90 148) translate(231 85) translate(20 25)">
                        <circle cx="13" cy="13" r="11.636" fill="url(#yxlkbuwbka)" stroke="#D785FF" stroke-width="2"/>
                        <g fill="#FFF">
                            <path d="M5.44 0l5.438 8.962H0L5.438 0v2.817L2.664 7.466l2.775-.001 2.776.001L5.44 2.817V0zM3.72 6.923l1.72-2.952 1.72 2.952-1.72-.003-1.72.003z" transform="translate(7.15 7.54)"/>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```
When radialGradient includes cx="50%" cy="50% it is not rendered by QT

**Comment by chapati** [comment]
As discussed with daria, for now we'll leave icons without gradient. Only #1 should be fixed.

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.10849.4036
