### ISSUE TITLE
Vertical screen indicator (near screen icon) sometimes disappears

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#349]
When using other applications/programs on mac and then go back to wallet vertical screen indicator disappears.
It happened few times on Testnet 5.2 and BeamX. I couldn't find the exact ways to reproduce it.

![image](https://user-images.githubusercontent.com/47353570/101160755-3b8b8580-3638-11eb-9b04-8c759450511c.png)

Correct view
![image](https://user-images.githubusercontent.com/47353570/100983815-84690e80-3552-11eb-85eb-57f61c1a5915.png)

**Comment by gingervik** [comment]
won't fix
