### ISSUE TITLE
Add UI item for UnlinkFundsTransaction

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#35]
1. Unlink transaction actions view https://zpl.io/advJqoK  (all actions https://zpl.io/aBJBzN0)
![image](https://user-images.githubusercontent.com/47353570/83392769-53bae780-a3fe-11ea-81dd-0dc0a137dcaf.png)

2. Stop unlinking popup https://zpl.io/amAZrmr  
Stop action should be similar to Cancel
![image](https://user-images.githubusercontent.com/47353570/83393038-cb891200-a3fe-11ea-9aac-25a8dfa7d5f9.png)

3. Create new statuses for lelantus transaction https://zpl.io/aBJBzN0
![image](https://user-images.githubusercontent.com/47353570/83392583-050d4d80-a3fe-11ea-9bec-42cac2e8c16c.png)

**Comment by gingervik** [comment]
irrelevant
