### ISSUE TITLE
Receive notification when asset was received/sent

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#350]
I didn't receive any notification about Raskuls transaction

![image](https://user-images.githubusercontent.com/47353570/101151299-1e4fba80-362a-11eb-9147-e4772a8855f5.png)

I have only Beam transaction notification

![image](https://user-images.githubusercontent.com/47353570/101145159-11c76400-3622-11eb-92ed-f83dbdf20c5a.png)

All notifications should be delivered

![image](https://user-images.githubusercontent.com/47353570/101161309-1f3c1880-3639-11eb-9b4a-ef459ad9782c.png)

**Comment by Roberrtt** [comment]
not fixed
build: 6.0.1033.3676 BeamX

**Comment by Roberrtt** [comment]
checked
