### ISSUE TITLE
Adjust BeamX color scheme

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#353]
**Please change following colors:**
1) bg color  https://zpl.io/2vxYzzj

2) top gradient https://zpl.io/2vxYzzj
3) add bottom gradient https://zpl.io/2vxYzzj
![image](https://user-images.githubusercontent.com/47353570/105193971-cde0dd80-5b41-11eb-9ea7-b3c4ac094cc2.png)

4) dialog box color and dropdowns  https://zpl.io/2jDOY8p
![image](https://user-images.githubusercontent.com/47353570/105191277-8e18f680-5b3f-11eb-87f6-755b74e0ca80.png)

5) table title box https://zpl.io/V17rDpZ
![image](https://user-images.githubusercontent.com/47353570/104938684-12407200-59b8-11eb-8d6d-aa34449eca63.png)

6) extended tx details https://zpl.io/V17rDpZ
![image](https://user-images.githubusercontent.com/47353570/104938753-284e3280-59b8-11eb-8bfe-8df5bfeb7877.png)

7) Please add BeamX logo on side menu https://zpl.io/bAedOYp
![image](https://user-images.githubusercontent.com/47353570/104938904-64819300-59b8-11eb-845a-e599ef92da99.png)

8) Please change text to "Confidential DeFi Platform" on loading screen https://zpl.io/2vxYzzj
![image](https://user-images.githubusercontent.com/47353570/105193916-b73a8680-5b41-11eb-8134-e9c0c1c68241.png)

9) Please add X icon on background and leave Beam logo https://zpl.io/2vxYzzj
![image](https://user-images.githubusercontent.com/47353570/105194200-02549980-5b42-11eb-8360-14b29a53ac74.png)

**Comment by gingervik** [comment]
irrelevant for master branch
