### ISSUE TITLE
App is closing if don't use it for a 20-30 mins (around)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#356]
BeamX was launched on background and after 20 (around) mins it closed by itself.

It was reproduced 3 times on Mac.
Error description text  https://docs.google.com/document/d/1FC4Uvd31XvRW8CrEj6LvHlF9TVSYF_PBk5Zvt7zLKsc/edit?usp=sharing

![image](https://user-images.githubusercontent.com/47353570/101161713-e9e3fa80-3639-11eb-8fb3-9848d3e90e6b.png)

Mac OS X 10.15.7
[beamx_crash.txt](https://github.com/BeamMW/beam-ui/files/5670862/beamx_crash.txt)

**Comment by Denis-Asipenko** [comment]
Not reproduced on masternet.
