### ISSUE TITLE
Send screen. Remove line under currency name

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#357]
Please Remove line under currency name

![image](https://user-images.githubusercontent.com/47353570/100983226-b5950f00-3551-11eb-992d-afeb3f93abad.png)

Correct view https://zpl.io/2Zednxw

![image](https://user-images.githubusercontent.com/47353570/101158622-af2b9380-3634-11eb-9e41-56dd570707ad.png)

**Comment by Roberrtt** [comment]
checked
