### ISSUE TITLE
Implement details control for Unlink funds transaction

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#36]
1. Unlinking transaction details https://zpl.io/bPJjK7x
![image](https://user-images.githubusercontent.com/47353570/83393094-e2c7ff80-a3fe-11ea-9fec-c15d43835414.png)

2. Unlinked transaction details https://zpl.io/a8ooEmw
![image](https://user-images.githubusercontent.com/47353570/83393126-f2474880-a3fe-11ea-99b6-3a9ec396ee2f.png)

**Comment by gingervik** [comment]
irrelevant
