### ISSUE TITLE
Notification screen. Make button "Details" leads to extended transaction details on wallet screen.

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#361]
1) When click "Details" on notification let's open details (extended) for this transaction.
![image](https://user-images.githubusercontent.com/47353570/101142771-bf387880-361e-11eb-96f3-9b1a8bbf5125.png)

Button should open this
![image](https://user-images.githubusercontent.com/47353570/100875240-6d70e080-34ae-11eb-91b4-2da77774bb7b.png)

2) **If transaction was deleted. 3 variants:**

2.1) Delete notification after deleting transaction

2.2) notification is visible, but after click non "details" user sees alert that transaction deleted - https://zpl.io/aXlLe6l
![image](https://user-images.githubusercontent.com/47353570/101386324-b3221480-38c5-11eb-97bb-8c52f35ae5e8.png)

2.3) Notification is disabled + comment "transaction deleted" - https://zpl.io/bPwWeOy
![image](https://user-images.githubusercontent.com/47353570/101386423-d8af1e00-38c5-11eb-8b03-982b36e227df.png)

**Comment by chapati** [comment]
This might be not relevant. We plan to move all extended details to dialog. I suggest not fixing this until we decide about dialog.

**Comment by KatsiarynaV** [comment]
Dapps notifications: click on the "open the app" button should open Dapp's transactions screen with unfolded transactions details https://zpl.io/br3m1lW (task #604)

**Comment by chapati** [comment]
Task 1 is not relevant after #590 
Need to open dialog instead.

**Comment by KatsiarynaV** [comment]
1. Сlick on the "open the dapp" button should open the Dapp screen (in this case "Faucet") with opened transactions details dialog
![05](https://user-images.githubusercontent.com/68267190/125634483-3fbd8a95-fff6-4223-9fc1-5fa1246f807f.jpg)
![06](https://user-images.githubusercontent.com/68267190/125634488-085c2153-4068-40db-b14c-b1e5a93b5dc6.jpg)

2. If transaction was deleted – not done. Delete notification after deleting transaction

**Comment by echoby** [comment]
1 - Сlick on the "open the dapp" button will open the Dapp list screen with opened transactions details dialog

**Comment by gingervik** [comment]
@dariatarakanova @sasha-abramovich FYI it's hard to implement opening dapp from notifications (need to keep in mind all scenarios with deleted dapp and etc.) So for now it's implemented as was described above "Сlick on the "open the dapp" button will open the Dapp list screen with opened transactions details dialog"

**Comment by gingervik** [comment]
@KatsiarynaV please, test this ticket

**Comment by KatsiarynaV** [comment]
1. Сlick on the "open the dapp" button isn't working
![gif01](https://user-images.githubusercontent.com/68267190/126480355-fffb3346-75c3-4235-b116-670504e170de.gif)

2. Move the notification to read after viewing the transaction details
![gif02](https://user-images.githubusercontent.com/68267190/126481047-2a2bc6dd-a77e-4b23-9fb2-fcf718c72e6b.gif)

**Comment by KatsiarynaV** [comment]
Checked
