### ISSUE TITLE
UTXO screen. Align datas in columns "Status" and "Type" to the left side

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#362]
Now "Status" and "Type" aligned by right side, but should be align by left side

![image](https://user-images.githubusercontent.com/47353570/101143139-30782b80-361f-11eb-9527-7aa95afcf852.png)

Should be as in design https://zpl.io/V4lOkwp

![image](https://user-images.githubusercontent.com/47353570/101143249-4be33680-361f-11eb-9d48-a2b67dc1fe22.png)

**Comment by KatsiarynaV** [comment]
Checked
