### ISSUE TITLE
No asset name if shielded asset was received

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#370]
If you send an asset to offline address, it will be displayed in the wallet as an asset with id number
![Screenshot_441](https://user-images.githubusercontent.com/50007056/100349299-496a5680-2ff9-11eb-80c7-faabee53fbdf.png)

**Comment by chapati** [comment]
Also in transactions list BEAM displayed instead of asset

![gnome-shell-screenshot-FUUGW0](https://user-images.githubusercontent.com/12074933/103020266-2465f680-4559-11eb-9c35-e978e5f28f41.png)

**Comment by Roberrtt** [comment]
checked
