### ISSUE TITLE
When sending, the asset name is not displayed in  "in progress" field

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#371]
When we send an asset, assets are written in the "in progress" field.

![Screenshot_444](https://user-images.githubusercontent.com/50007056/100350231-9bf84280-2ffa-11eb-9268-f78142d70a97.png)

Expected: The asset name is written in the "in progress" field

Note :The receiver displays the asset name

**Comment by chapati** [comment]
It is correct behavior. When many assets are 'in progress' we cannot show just beam/Grin. We show 'ASSETS'. You can hower with mouse and see the detailed breakdown.

**Comment by Roberrtt** [comment]
checked
