### ISSUE TITLE
Settings screen redesign

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#38]
New design: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5ece326f33cc444a8874b004 

1) New design for all open cards https://zpl.io/advgAZn .
2) At one moment can be opened only 1 card:
general https://zpl.io/aXA0vLE
notification https://zpl.io/bLlyKeJ
utilities https://zpl.io/aBJr0wO
privacy https://zpl.io/bWzZxQk
beam integrated node https://zpl.io/bLlyl4d
beam remote node https://zpl.io/aNJrgA4
3) Statuses for AS nodes in different colors https://zpl.io/aXA0vLE
4) Search: it should be smart search and display also synonyms for the typed word.
 _Example:_ If type "node" also should display results with "peer".
Display blocks always open

4.1) If results from 2 blocks (Wallet and Connectivity here) display it in 2 columns https://zpl.io/2ZQZzdX
4.2) If results from 1 block (Troubleshooting here) display it in 1 columns (left align) https://zpl.io/bPJZJgp
4.3) If there are results from 1 block (Connectivity here) but they take too much place - display it in 2 columns  to avoid long scroll https://zpl.io/VYg3g1J

5) AS conditions https://zpl.io/bJJrJeE
6) Remove current wallet alerts https://zpl.io/ag4wArN and https://zpl.io/a79rMJj
7) Export https://zpl.io/br5Dwl7
8) Import  https://zpl.io/aRJZOx0 and alerts https://zpl.io/br5DwMr , https://zpl.io/bzE4m63
9) Clear local wallet data https://zpl.io/b6dqLDW , https://zpl.io/aRJZeXN , https://zpl.io/VKZre6R

Screenshot: 
![image](https://user-images.githubusercontent.com/47353570/83027605-f8bd7500-a038-11ea-88e9-191c1aa7ef20.png)

**Comment by Roberrtt** [comment]
1. Align the slider for (Allow acces to beam.mw and blockchaing explorer
![Screenshot_58](https://user-images.githubusercontent.com/50007056/88528454-52c1c300-d007-11ea-837e-1c914facfff3.png)
2.Make the "cancel" button darker if you haven't entered any changes
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5f1eb224af220c37fb657573
![Screenshot_63](https://user-images.githubusercontent.com/50007056/88534589-11361580-d011-11ea-90d5-6c67a9a07f2e.png)

**Comment by Roberrtt** [comment]
Rename tabs 'REPORT PROBLEM' to 'REPORT A PROBLEM'.
And remove "to report a problem"  as in the design
![Screenshot_92](https://user-images.githubusercontent.com/50007056/88915913-c82ecd00-d26d-11ea-9c04-126758663a06.png)

**Comment by Roberrtt** [comment]
checked
