### ISSUE TITLE
API: contracts in wallet API

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#380]
Need to discuss if we need contracts support in default API and implement if necessary.

**Comment by chapati** [comment]
![gnome-shell-screenshot-FJ38X0](https://user-images.githubusercontent.com/12074933/106191623-2d7f5e80-61bc-11eb-8486-9382304bbdb8.png)

Before this change there were 2 folders in AppData (with spaces and without). One was used for apps cache. Please test that now only one folder present and 'appcache' folder is inside it.

**Comment by chapati** [comment]
Added new method invoke_contract. Docs are updated.
Please test the new method, also test all the API (a lot of changes).
Need to consider automation (@beam-mw )

**Comment by Roberrtt** [comment]
Change the letter "H" in Shader from uppercase to lowercase.
![Screenshot_446](https://user-images.githubusercontent.com/50007056/111134638-dcb99e80-858c-11eb-8683-8b8bfb1829ce.png)

**Comment by Roberrtt** [comment]
checked
