### ISSUE TITLE
Installer: linux

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#383]
UI installer for linux doesn't include qt deps. Need to support  AppImage or Flatpak and get rid of deb.

**Comment by chapati** [comment]
Done. Provides AppImage file. Need to add executable attribute to it after download (chmod a+x ./filename or using rightclick + properties in file explorer) Should work on most not old linux distros, not only on ubunty. 

Ubuntu 16 is not supported oficially anymore. To run on ubuntu 16 need to execute:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update && sudo apt-get upgrade libstdc++6

**Comment by Roberrtt** [comment]
checked
