### ISSUE TITLE
Contracts: transactions list

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#385]
At the moment we have incorrect data in transactions table. Need to

1) Add amounts
2) Meaningful comments (via apps comments passthroug)
3) Error message on errors
4) Need add general 'Contract icon'

**Comment by chapati** [comment]
2. Done, meaningful comments added 

![Screenshot-20210114234839-706x436](https://user-images.githubusercontent.com/12074933/104647533-1112fa80-56c3-11eb-9f1e-53bef3ef198a.png)

**Comment by dariatarakanova** [comment]
duplicate of https://github.com/BeamMW/beam-ui/issues/458
