### ISSUE TITLE
Assets: remove CLI --assets flag

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#386]
Assets now would be displayed in CLI by default. Remove --assets flag.

**Comment by chapati** [comment]
--assets flag is removed, --asset_id is still present (show info about particular asset)
--enable_assets removed for cli (assets on by default), still present and false by default for API

Changes are discussed with Romanov.

**Comment by Roberrtt** [comment]
Remove "--enable_assets"  parameter from  cli helper 
![Screenshot_399](https://user-images.githubusercontent.com/50007056/109828978-30072500-7c4e-11eb-8a8a-674560d17def.png)

**Comment by chapati** [comment]
As I've described above
--enable_assets removed for cli (assets on by default), still present and false by default for API
Removing the flag can break existing scripts. It is made 1 (true) by default.

**Comment by Roberrtt** [comment]
checked
