### ISSUE TITLE
The field with assets expands when you click the search icon

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#387]
![bandicam-2020-11-26-17-39-15-083](https://user-images.githubusercontent.com/50007056/100364197-d79d0780-300e-11eb-8af4-37a9ae03399e.gif)

**Comment by Roberrtt** [comment]
not fixed 
build: 6.0.1033.3676 BeamX

**Comment by Roberrtt** [comment]
not fixed
build: 6.0.10414.3740 BeamX

**Comment by chapati** [comment]
Looks like win-only bug. Need somebody with windows to help.

**Comment by chapati** [comment]
This is not relevant anymore. Search field is removed according to the new design.
