### ISSUE TITLE
Receive Max privacy. Comment "can take up to XX days"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#390]
Add comment for Max privacy transactions "Max Privacy transaction can last up to 2 days."
https://zpl.io/bJeowvK

![image](https://user-images.githubusercontent.com/47353570/100739995-ac386500-33e0-11eb-89e3-3ef0dffe5040.png)

**Comment by gingervik** [comment]
"...at least 2 days"

**Comment by Roberrtt** [comment]
checked
