### ISSUE TITLE
Remove " < " in the asset table when the amount is less than 1

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#409]
![Screenshot_30](https://user-images.githubusercontent.com/50007056/100988730-15df7d00-3561-11eb-8a2d-a798bac40e79.png)

**Comment by chapati** [comment]
This is intended behavior. Assets item in assets panel has not enough space to display long values, so values are rounded up sometimes and < sign is added to fit in the available space. For example 0.06 can become < 0.1

**Comment by Roberrtt** [comment]
checked
