### ISSUE TITLE
A transaction with a large amount of asset is failed

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#411]
We need to change the logic of the "add all" button on the send screen
If the amount of the asset in the wallet = 3-4 * max_int 64, then the "add all" button takes all the coins, but the transaction fails with the "Key keeper malfunctionedr"

Note:  In CLI we maximum supported amount 184467440737 BEAMs 9551615 GROTH.
![Screenshot_33](https://user-images.githubusercontent.com/50007056/100990970-8ab3b680-3563-11eb-89d1-7b2cb52e7105.png)

**Comment by chapati** [comment]
By romanov: limit amount per transaction

**Comment by chapati** [comment]
In UI we historically have 100M limit per transaction. So 'add all' now is 'add max' and max value is 100M even if the wallet has more assets.

**Comment by Roberrtt** [comment]
checked
