### ISSUE TITLE
Error types in connection status: Wallet cannot connect to node(s) 

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#414]
1) Wallet cannot connect to 1 node https://zpl.io/2jzdEqQ
- wallet status "connection to BITCOIN CASH node lost: 1.2.3.4" and button "Change settings"
- "Change settings" leads to settings screen and required node (here: Bitcoin cash) settings open. 

![image](https://user-images.githubusercontent.com/47353570/101616448-0b692b80-3a18-11eb-86af-bf91c655df49.png)

2) Wallet cannot connect to 2 nodes or more https://zpl.io/aw8M9EK
- wallet status "lost connection to nodes: BTC, LTC" and button "Change settings"
- "Change settings" leads to settings screen and open first in order node settings. 

![image](https://user-images.githubusercontent.com/47353570/101620060-c267a600-3a1c-11eb-8fe9-4add9e3a6993.png)

3) Wallet cannot connect to BEAM node and another nodes (BTC, LTC etc) please display info about BEAM first in the status
https://zpl.io/2pp0DvM

![image](https://user-images.githubusercontent.com/47353570/101619948-9a784280-3a1c-11eb-84ff-e3d6917c131a.png)

**Comment by gingervik** [comment]
need to be discussed

**Comment by echoby** [comment]
implemented as part of #188

**Comment by dariatarakanova** [comment]
@Roberrtt 

please make text similar for all error types:

1 node lost connection: "connection to BITCOIN CASH node lost: 1.2.3.4"
2+ nodes lost connection: "connection to BTC, LTC nodes lost"

current implementation is a bit different "lost connection to nodes: BTC, LTC"

**Comment by Roberrtt** [comment]
1.If the wallet is connected to electrum , the node settings are displayed in error 
![Screenshot_284](https://user-images.githubusercontent.com/50007056/121349536-4e0db100-c932-11eb-92e6-1b47986f6ee3.png)

2."Change settings" leads to settings screen and open first in order node settings.- Not done

3 -Change to full name of the node if wallet cannot connect to 1 node
![Screenshot_286](https://user-images.githubusercontent.com/50007056/121351076-0ab44200-c934-11eb-8e65-32d56fa07046.png)

4.When all nodes were connected with errors, then after disconnecting them, the error remains on them
- Connect all nodes to the network not working
- Make a discount and delete all data except 1 node
- Connect the node to a non-working network
![Screenshot_287](https://user-images.githubusercontent.com/50007056/121352011-0fc5c100-c935-11eb-8e07-d964e6b70f4f.png)

5 When the wallet was connected to 2 nodes and make changes in 1 node, there is no error about another connection
![Screenshot_288](https://user-images.githubusercontent.com/50007056/121355830-f6bf0f00-c938-11eb-9587-fe86f83c5e45.png)

**Comment by Denis-Asipenko** [comment]
1. if at least one node has lost connection, the public offline address isn't available
![image](https://user-images.githubusercontent.com/45556620/122353811-15d12880-cf59-11eb-8ccc-19acc347850e.png)

2.when one of the nodes has lost the connection, and the second node is connection at this time, the indicator displays the online status of the integrated node. during the connection of the second node, the indicator should show that it cannot connect to the first node
![image](https://user-images.githubusercontent.com/45556620/122355998-0b179300-cf5b-11eb-8207-29ec24d780bc.png)
![930A2E2C-97AD-480D-9B37-434E0BF5E4FD](https://user-images.githubusercontent.com/45556620/122357046-07d0d700-cf5c-11eb-9480-a044295144ec.GIF)

**Comment by Denis-Asipenko** [comment]
checked
