### ISSUE TITLE
Update icon for "no active offers"case on Atomic Swap screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#415]
Please update the icon on empty screen https://zpl.io/VQ1BnX9
Correct view

![image](https://user-images.githubusercontent.com/47353570/100341868-d3a8bf80-2fe5-11eb-9b2a-3e67234ce2ab.png)

In current implementation it has border

![image](https://user-images.githubusercontent.com/47353570/101189712-11e65480-3660-11eb-9b5b-45fd21a93a21.png)

**Comment by roman-strilets** [comment]
fixed at d370492f96cd243ef314ab1bb142ddb662bedbaa

**Comment by KatsiarynaV** [comment]
Checked on build 5.3.9926.3448
