### ISSUE TITLE
Add loading animation when active offers are loading

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#418]
When offers are loading - please show loading animation https://zpl.io/VY30Eew 

![image](https://user-images.githubusercontent.com/47353570/101618024-14f39300-3a1a-11eb-905c-9f593f9d3c92.png)

Example for animation (left top and left bottom) https://codepen.io/yoksel/pen/fjcvA

**Comment by kazaryan-t** [comment]
Checked on 5.3.10045.3503.
