### ISSUE TITLE
Rename button "show token" and make changes on it's popup

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#420]
1) Rename button "show token" to "More details".  
![image](https://user-images.githubusercontent.com/47353570/101184657-a600ed80-3659-11eb-901c-116279679fbc.png)

2) "More details" popup for Create offer screen https://zpl.io/VDeQrG3 and Accept offer screen https://zpl.io/aRZKjmg

2.1) Add "copy" icon near token 
2.2) Rename button to "copy and close"

![image](https://user-images.githubusercontent.com/47353570/101184835-d6e12280-3659-11eb-921c-6678d61e3529.png)

3) If Amount fields not filled - lets display "show token" (new name "More details") as disabled button. https://zpl.io/aRlrmxg

![image](https://user-images.githubusercontent.com/47353570/101345515-cdd99680-388f-11eb-825c-76c23926a651.png)

In current implementation button "show token" (new name "More details") in not displaying at all.
![image](https://user-images.githubusercontent.com/47353570/101345575-e3e75700-388f-11eb-9cac-17b6479421d2.png)

4) If Amount fields filled - display "show token" (new name "More details") as active button. https://zpl.io/2p5NQrQ
![image](https://user-images.githubusercontent.com/47353570/101345978-899ac600-3890-11eb-8838-8b178752afa0.png)

**Comment by dariatarakanova** [comment]
Please ignore point No.2 in this task. 

On "More details" dialog leave only "close button"

**Comment by kazaryan-t** [comment]
Checked.
