### ISSUE TITLE
Remove dot in wallet version after "v" (example v. 5.3.10249.3581)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#421]
1) Version should be display as "v 5.3.10249.3581" without "." after "v". 

Current view
![image](https://user-images.githubusercontent.com/47353570/101475156-aef10800-3954-11eb-97d8-9eafb5b58380.png)

2) Please make version number looks the same across the wallet "v 5.3.10249.3581" 
2.1) Loading wallet screen https://zpl.io/bAq0P56 , https://zpl.io/2vxYzzj
![image](https://user-images.githubusercontent.com/47353570/101476358-50c52480-3956-11eb-9848-306b83fb1bb2.png)

2.2) Settings https://zpl.io/aXA0vLE
![image](https://user-images.githubusercontent.com/47353570/101480992-1f9c2280-395d-11eb-8c8e-8021c980fce7.png)

2.3) Notifications  https://zpl.io/awXx1Eg
![image](https://user-images.githubusercontent.com/47353570/101481032-2f1b6b80-395d-11eb-9381-db8f20e0b6f5.png)

2.4) In-app notification https://zpl.io/2519rXW
![image](https://user-images.githubusercontent.com/47353570/101481079-478b8600-395d-11eb-803f-625b05d92e5c.png)

**Comment by kazaryan-t** [comment]
1. Please, add a space between the letter "v" and version number.
2. Fix the date and time format in the notification.

Design: https://zpl.io/awXx1Eg
Current view:
![2](https://user-images.githubusercontent.com/68247034/105148705-bbe84600-5b13-11eb-8b69-9f36512d824e.png)

**Comment by Denis-Asipenko** [comment]
checked
