### ISSUE TITLE
Add button "save wallet logs" to "failed to start node" error

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#422]
1) please change text on "failed to start node" error to "Failed to start node. Please save wallet logs and contact support." https://zpl.io/VQl06RR

2) Please add button "save wallet logs" to line with error 
![image](https://user-images.githubusercontent.com/47353570/101482639-b073fd80-395f-11eb-8dfb-1479cac399a1.png)

**Comment by KatsiarynaV** [comment]
Checked on build 5.3.10045.3500
