### ISSUE TITLE
Change message colour on AS USD value 

### ISSUE THREAD

**Issue by RaFuN** [BeamMW/beam-ui#424]
on AS when USD value is not available, better use normal colour rather than the red one now (which indicate an error in most cases).

pic:  https://drive.google.com/file/d/14UiQ_yIsSb1s2zVNeF9ayixmQKlPKD28/view?usp=sharing

**Comment by dariatarakanova** [comment]
Design https://zpl.io/Vkgwzn5

Please adjust style for text  "Exchange rate to USD is not available." as a comment - grey color, italic.
![image](https://user-images.githubusercontent.com/47353570/102205519-f71fa580-3ed3-11eb-9c04-c304935a8232.png)

**Comment by KatsiarynaV** [comment]
checked on build 5.3.9950.3458
