### ISSUE TITLE
There is no USD value for Dash and Doge

### ISSUE THREAD

**Issue by RaFuN** [BeamMW/beam-ui#425]
when creating an AS, the USD value is only visible for the sending coin, and is missing on the receiving coin.

pic: https://drive.google.com/file/d/1VxIFRGtmoZP9QvKHhtd2vj558sOVqJ6r/view?usp=sharing

**Comment by iscander01** [comment]
notifications (DASH, QTUM, DOGE, LTC) added in [commit](https://github.com/BeamMW/notification-script/commit/7f3aab9e949684b0ac98820885e3e3c7bc89135b). Needs to be added to the broadcaster

**Comment by Aleksandr-Starun** [comment]
Please add notifications for Ethereum, Dai, USDT and WBTC.

**Comment by kazaryan-t** [comment]
checked exchange rates
