### ISSUE TITLE
Rename button "Copy" to "Copy and close" when generate new seed phrase in node settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#427]
Please rename button "Copy" to "Copy and close" Design: https://zpl.io/bPwXzvp

Current implementation
![image](https://user-images.githubusercontent.com/47353570/102341152-1552d780-3fa0-11eb-884a-4a93b9a89976.png)

Updated design:
![image](https://user-images.githubusercontent.com/47353570/102342802-6bc11580-3fa2-11eb-91fc-f318bf0c4a3a.png)

**Comment by KatsiarynaV** [comment]
Checked
