### ISSUE TITLE
Atomic swap screen -  BETA 2 indicator

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#43]
Please change "BETA" to "BETA 2"
https://zpl.io/VKy7WAP

![image](https://user-images.githubusercontent.com/47353570/84257240-b78b9180-ab1d-11ea-97a7-952145ad5e1e.png)

**Comment by VladislavKulyba** [comment]
Font in this element should be the same as on previous version
Please, make width of this element bigger.

![Snag_54d7d84](https://user-images.githubusercontent.com/51320829/85528588-c3468000-b614-11ea-9890-7d65cd60bfea.png)

**Comment by VladislavKulyba** [comment]
checked
