### ISSUE TITLE
The wallet address isn't copied in the coin settings

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#430]
![bandicam-2020-12-17-13-35-30-468](https://user-images.githubusercontent.com/50007056/102477070-f0786600-406c-11eb-8e09-1046d2845a17.gif)

**Comment by Aleksandr-Starun** [comment]
Done at 8794cbfa74496a3969b15d0e16b572f57ee4085d

**Comment by Roberrtt** [comment]
checked
