### ISSUE TITLE
Wallet crashes with active swap ,when switching from inactive node to active 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#432]
When there is an active swap, and if you close\open the wallet and the node will not be active. We can disconnect from the coin node, and when the node becomes active the wallet crashes

step:
- accept offer with ethereum
- switch to inactive node 
- close wallet
- open wallet
- go to the settings of the ethereum node, click disconnect
- enter the correct node address and connect

Actual: wallet crashes 
[dum file.zip](https://github.com/BeamMW/beam-ui/files/5734228/dum.file.zip)
[VIDEO.zip](https://github.com/BeamMW/beam-ui/files/5734213/VIDEO.zip)
![bandicam-2020-12-23-11-31-45-366](https://user-images.githubusercontent.com/50007056/102978954-691c6e00-4516-11eb-87e6-63435a0b1d2d.gif)

**Comment by beam-mw** [comment]
Whatever
