### ISSUE TITLE
Swap with USDT gives error " Side chain bridge has internal error"

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#434]
If we make an exchange with USDT it gives error " Side chain bridge has internal error"
id : e43f699e10c74558b0bfe0460da3767c
![Screenshot_93](https://user-images.githubusercontent.com/50007056/102982045-f5309480-451a-11eb-9bc0-23876b406538.png)
[logs.zip](https://github.com/BeamMW/beam-ui/files/5734392/logs.zip)

**Comment by Aleksandr-Starun** [comment]
Done at rev. 5ca910fd0c9c86c3a5b6db27fd8e136bd031d740

**Comment by Roberrtt** [comment]
checked
