### ISSUE TITLE
Restore wallet: assets

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#436]
Asset info is not updated on wallet restore (when only non-shilded coins, for shielded it is updated).
Net to retrieve actual asset info on restore.

**Comment by chapati** [comment]
Now when you restore wallet and have any assets inside info should be automatically received

- in UI red asset info panes (ASSET1...N) should be replaced to actual asset name & colors. It can take a while, wait 10-30 seconds
- in CLI wallet should "listen" to node (not just restore). Restore command in CLI only creates and empty database.

Please check also that this automatic info retrieval restores 'asset owned/not owned' state correctly. "You own this asset" should be printed in log if you own this asset after the asset info.

**Comment by chapati** [comment]
Additional fix: now info should be refreshed faster (no 10+ seconds delay)

**Comment by Sergei-Beam** [comment]
checked
