### ISSUE TITLE
The amount is erased if 7 numbers are entered after the dot

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#437]
![bandicam-2020-12-29-13-30-19-477](https://user-images.githubusercontent.com/50007056/103277540-586a6d00-49da-11eb-9c06-2317aab7fda4.gif)

**Comment by Roberrtt** [comment]
Do the same for cli and api.
If you create  offer in CLI where the amount of USDT is 0.0000001, then the UI can accept this swap and it looks like 0 USDT 
![Screenshot_177](https://user-images.githubusercontent.com/50007056/104938749-88e16d80-59c0-11eb-8570-adaea2b30c4b.png)
![Screenshot_176](https://user-images.githubusercontent.com/50007056/104938746-8848d700-59c0-11eb-9ef9-874f38cb182a.png)

**Comment by Aleksandr-Starun** [comment]
Done at. b8643f55b6d8c891e86a59ae509ee8881ba56dba

**Comment by Roberrtt** [comment]
checked
