### ISSUE TITLE
Contracts tx: total amount includes fee

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#439]
At the moment in tx list table Total contract amount includes fee. Need to display without it.

![gnome-shell-screenshot-17QWW0](https://user-images.githubusercontent.com/12074933/103795173-b6d8c080-5056-11eb-833d-c0312314d526.png)

On the picture receiving is correct: 4.98
Tx list is incorrect: 5

**Comment by Roberrtt** [comment]
not fixed 
build: 6.0.1033.3676 BeamX

**Comment by Roberrtt** [comment]
checked

**Comment by Roberrtt** [comment]
This is reproduced on build 6 for the vault contract
![Screenshot_444](https://user-images.githubusercontent.com/50007056/111117483-a2460680-8578-11eb-8fab-a60237028a4f.png)
![Screenshot_445](https://user-images.githubusercontent.com/50007056/111117488-a2de9d00-8578-11eb-93e1-b66babfa3ad3.png)

**Comment by chapati** [comment]
This is correct behavior. We will not +- fee in contracts transactions to amount. The same as for regular transactions.

**Comment by Denis-Asipenko** [comment]
checked
