### ISSUE TITLE
The wallet shows "accept" option for your own offer on the Swap board

### ISSUE THREAD

**Issue by VladislavKulyba** [BeamMW/beam-ui#44]
Some offers changing currencies on board after creating.
Just create some offers and some of them will be with this status.
![Snag_64a61d0](https://user-images.githubusercontent.com/51320829/78550056-183fda80-780c-11ea-8069-fb47dba311e9.png)
[2020-04-03_17-13-45.zip](https://github.com/BeamMW/beam/files/4437769/2020-04-03_17-13-45.zip)
[beam_ui_20_04_03_14_30_58.log](https://github.com/BeamMW/beam/files/4437770/beam_ui_20_04_03_14_30_58.log)

**Comment by Roberrtt** [comment]
checked
