### ISSUE TITLE
Contract transaction: no fees in details

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#440]
Contract transactions do not display fees in details. Should show.

![gnome-shell-screenshot-W2QQW0](https://user-images.githubusercontent.com/12074933/103798562-f1dcf300-505a-11eb-8e9c-82f0e55d76d1.png)

**Comment by Roberrtt** [comment]
not fixed for vault and faucet contracts 
build: 6.0.1033.3676 BeamX
![Screenshot_144](https://user-images.githubusercontent.com/50007056/104015879-54063700-51c6-11eb-8fe6-17cfbb9182aa.png)

**Comment by Roberrtt** [comment]
checked
