### ISSUE TITLE
Displaced main panel

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#442]
1. Have some 'in progress' amount
2. Close and open wallet 
Top panel has incorrect size:

![gnome-shell-screenshot-2VFTW0](https://user-images.githubusercontent.com/12074933/103802201-d7594880-505f-11eb-958e-8068462613b5.png)

**Comment by Roberrtt** [comment]
not fixed
build: 6.0.1033.3676 BeamX
![Screenshot_145](https://user-images.githubusercontent.com/50007056/104025815-3e007280-51d6-11eb-8600-64e33415cfb7.png)

**Comment by Roberrtt** [comment]
checked
