### ISSUE TITLE
After sending all the coins of the asset, it remains selected

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#447]
If we send all the coins of the asset, then after sending it remains selected.
If you go to the send screen, the selected coins will have beam, but we will not be able to send it.
![bandicam-2021-01-11-16-54-26-760](https://user-images.githubusercontent.com/50007056/104191448-9467ee00-542e-11eb-9ab3-775661d3e01f.gif)

**Comment by chapati** [comment]
Now when selected asset is fully sent selection should reset to 'nothing selected'

**Comment by Roberrtt** [comment]
checked
