### ISSUE TITLE
Ethereum settings - make smaller the pop-up with Ethereum wallet addresses

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam-ui#452]
When we click on the "show wallet addresses" button, the pop-up with Ethereum wallet addresses appears but there is a lot of blank space under the address. Please, delete the blank space on the pop-up.

Wallet version - 5.3.10045.3502.

![Beam Wallet Masternet 2021-01-18 12 14 47](https://user-images.githubusercontent.com/68247034/104899679-35edc300-598c-11eb-9612-4ab46a5b7609.png)

https://user-images.githubusercontent.com/68247034/104900053-a5fc4900-598c-11eb-800c-5ea5e13319e5.mp4

**Comment by KatsiarynaV** [comment]
Please, delete the blank space on the pop-up under the address for ethereum.
![Эфир_1](https://user-images.githubusercontent.com/68267190/105330228-1dc3b100-5be3-11eb-840f-f591eaf5ac47.jpg)
![Эфир](https://user-images.githubusercontent.com/68267190/105328276-eeac4000-5be0-11eb-95f8-1915e38f63f2.jpg)

Wallet version - 5.3.10048.3510

**Comment by kazaryan-t** [comment]
Checked.
