### ISSUE TITLE
Transaction list for Send/Receive

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#456]
Design: https://zpl.io/bAedOYp
![image](https://user-images.githubusercontent.com/47353570/105166527-34550400-5b20-11eb-9791-a656173d7294.png)

1) Remove "from" and "to" columns as in current implementation.
![image](https://user-images.githubusercontent.com/47353570/105166892-ac232e80-5b20-11eb-9931-54fb8fe3169d.png)

2) Add "coin" column with icon and name. Display coin name only here, no need to add it after amount for each transaction. Coin sorts by name (A-Z, Z-A).
![image](https://user-images.githubusercontent.com/47353570/105166782-81d17100-5b20-11eb-9dc4-1ec0aa8a2ea3.png)

3) Amount should be without coin name, only digits
![image](https://user-images.githubusercontent.com/47353570/105168409-c52cdf00-5b22-11eb-86e7-742f2c666a21.png)

4) Add "USD Value" (or BTC Value) column. display only amount without coin name. If asset doesn't has usd value - make field empty.
![image](https://user-images.githubusercontent.com/47353570/105166798-872ebb80-5b20-11eb-9378-47f20929a46e.png)

5) Add tab "contracts" near "received" tab.
![image](https://user-images.githubusercontent.com/47353570/105166993-d2e16500-5b20-11eb-8381-e87a6efa311f.png)

**Comment by Sergei-Beam** [comment]
checked

Related to exchange rates bugs were opened separately
https://github.com/BeamMW/beam-ui/issues/550
https://github.com/BeamMW/beam-ui/issues/551
