### ISSUE TITLE
Notification for contracts

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#457]
Design: https://zpl.io/25X0oln
![image](https://user-images.githubusercontent.com/47353570/105201764-e81eb980-5b49-11eb-8b75-d2e499299c66.png)

1) Please add notification for Contract transaction completed 
2) Please add notification for Contract transaction failed 
3) Please add notification for Contract transaction expired 

No need to add notification for canceled transactions, cuz only user by himself can cancel transaction. it can't be canceled by blockchain/node, and user doesn't need notification for action that user did by himself

**Comment by Denis-Asipenko** [comment]
1. Need to change the text and font(marked in green) according to design.
![image](https://user-images.githubusercontent.com/45556620/110800534-53088900-828d-11eb-8bd5-0f9a6515cd2a.png)
2. In desktop wallet we shouldn't be showing the notification "create contract". 
![image](https://user-images.githubusercontent.com/45556620/110801347-3456c200-828e-11eb-8175-99e10a2b6d30.png)
3. In the notification screen not showing notifications with status failed although there are transactions.
![image](https://user-images.githubusercontent.com/45556620/110802551-5735a600-828f-11eb-98e8-1db13707fb0f.png)
- Windows
- OS version: 10 pro
- BEAM Build number: 6.0.10821.4001.
**The base of the wallet and the logs file**
password 1
[wallet.zip](https://github.com/BeamMW/beam-ui/files/6123706/wallet.zip)

**Comment by chapati** [comment]
1. Title changed
2. It is technically impossible to know if it was create or not. Do not use wallet.db from CLI in UI. It is discussed many times that copying wallet.db should not be done.

**Comment by Roberrtt** [comment]
Please change the comment in contracts from lowercase to capital letter 
![Screenshot_476](https://user-images.githubusercontent.com/50007056/112106162-5de0e900-8bbe-11eb-86b5-fc98def16b3a.png)

**Comment by chapati** [comment]
Fixed. Also fixed title for failed contract transaction -> "Contract transaction failed"

**Comment by Roberrtt** [comment]
checked
