### ISSUE TITLE
Transaction list for Contracts

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#458]
Design: https://zpl.io/V17rDpZ
![image](https://user-images.githubusercontent.com/47353570/105205631-24ecaf80-5b4e-11eb-92fd-7cd763e3e226.png)

1) Table titles: Coin | Created on | Description | Amount | Status
![image](https://user-images.githubusercontent.com/47353570/105205696-35048f00-5b4e-11eb-81df-edb8c881503b.png)

2) In "Coin" column for multiple amounts please display max 3 icons. if there are more assets - display extra coins as number ( +1, +2 etc)
![image](https://user-images.githubusercontent.com/47353570/105205731-3d5cca00-5b4e-11eb-8d54-81aff5e972a4.png)

3) In "Amount" column display only digits, without asset name or text "Multiple assets".
![image](https://user-images.githubusercontent.com/47353570/105205807-4f3e6d00-5b4e-11eb-8a9e-bcbf9bc859f9.png)

4) Extended transaction details
![image](https://user-images.githubusercontent.com/47353570/105205978-7f860b80-5b4e-11eb-8e34-27d0ca12363b.png)

**Comment by Denis-Asipenko** [comment]
1. Add the Contract ID field
2. Delete field Receiving address, Contract, Address type

![image](https://user-images.githubusercontent.com/45556620/114723213-2ab7f280-9d43-11eb-8aaf-dbaabed93575.png)

**Comment by Roberrtt** [comment]
checked
