### ISSUE TITLE
CLI wallet doesn't see shielded assets

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#477]
The available assets in the UI are different from cli. Cli wallet doesn't see shielded assets
![Screenshot_229](https://user-images.githubusercontent.com/50007056/105726085-bdae7100-5f3a-11eb-835b-979e4207984a.png)
Pass = 1 [wallet.zip](https://github.com/BeamMW/beam-ui/files/5867556/wallet.zip)

**Comment by KatsiarynaV** [comment]
Shielded assets are not added to the "Total unspent" balance
![14](https://user-images.githubusercontent.com/68267190/109964531-d90d5880-7cfe-11eb-978f-ff9985337fc3.jpg)
![15](https://user-images.githubusercontent.com/68267190/109964538-da3e8580-7cfe-11eb-95eb-3202bf690f15.jpg)

**Comment by KatsiarynaV** [comment]
Max privacy assets are not added to the "Maturing" balance
![16](https://user-images.githubusercontent.com/68267190/110446775-9964b900-80d0-11eb-960c-424e2f608ba8.jpg)

**Comment by KatsiarynaV** [comment]
Checked
