### ISSUE TITLE
Rate settings fields in node,shifts to the right as you enter values

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#48]
Make the field fixed .
Make it possible to enter only once the digit 0 if it is the first.
[Video2.zip](https://github.com/BeamMW/beam/files/3976928/Video2.zip)
![Screenshot_340](https://user-images.githubusercontent.com/50007056/71061587-63f54800-2179-11ea-85dd-dc6dfc0865ce.png)

**Comment by Denis-Asipenko** [comment]
The first point still needs to be fixed.
![65F3813A-B064-4CC5-A871-63621ED39626](https://user-images.githubusercontent.com/45556620/87667842-b6303300-c773-11ea-8db6-d61ac85efb2e.GIF)
> Both seems to be fixed in new settings. Please check that it is OK now.
> Though there are more issues.
> 
> 1. fee rate input is moved when rate is short
>    Long:
>    ![DeepinScreenshot_select-area_20200608201158](https://user-images.githubusercontent.com/12074933/84060157-6451fb80-a9c4-11ea-99b7-fce1a3a8f5d9.png)
>    Short:
>    ![DeepinScreenshot_select-area_20200608201146](https://user-images.githubusercontent.com/12074933/84060315-aaa75a80-a9c4-11ea-9d62-e33016fd44d3.png)

**Comment by Roberrtt** [comment]
Checked
