### ISSUE TITLE
Color palette for assets

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#482]
Color palette here: https://zpl.io/V4gl8Zy

Plea use only 7 general colors an their analogous (from gradient)
![image](https://user-images.githubusercontent.com/47353570/106146674-9eecec00-617f-11eb-896f-0638467f48dc.png)

This triangle zone on color picker is safety zone. You can take any color from triangle. And it works for each color.
![image](https://user-images.githubusercontent.com/47353570/106146974-fee39280-617f-11eb-8dc7-4b6d24f16f11.png)

**Comment by dariatarakanova** [comment]
@chapati please use these colors for assets https://zpl.io/V4gl8Zy
![Uploading image.png…]()

**Comment by KatsiarynaV** [comment]
Two colors are missing
![22](https://user-images.githubusercontent.com/68267190/111614559-c9a70880-87f0-11eb-86f9-020824e2a198.jpg)

Two colors are duplicated
![21](https://user-images.githubusercontent.com/68267190/111612418-7d5ac900-87ee-11eb-8338-21ddf4d9643f.jpg)

build 6.0.10849.4036

**Comment by chapati** [comment]
Colors are not missing. To test that color are displayed, you need to have assets with IDs from 1 to 21. We display like this:

id1 -> color 1
id2 -> color 2
...
id21 -> color1

If you asset ids are not consequent colors would be duplicated. if "assetId mod 20" gives the same value for two assets, colors would be the same. Please check which ids have assets with duplicated colors.

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.10849.4036
