### ISSUE TITLE
Receive screen (simplified version)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#487]
New designs
https://zpl.io/2EnyBjY

<img width="965" alt="Screenshot 2021-02-24 at 10 13 25" src="https://user-images.githubusercontent.com/7249484/108935581-f13f0100-7688-11eb-97f7-a98f700640a8.png">

Changes:
1. "Address type" section rename to "Transaction type" and rework tabs view
Current implementation 
<img width="469" alt="Screenshot 2021-02-24 at 14 25 27" src="https://user-images.githubusercontent.com/7249484/108957273-26107f80-76ac-11eb-942c-9dcef46caf73.png">
Design 
<img width="471" alt="Screenshot 2021-02-24 at 14 26 24" src="https://user-images.githubusercontent.com/7249484/108957334-47716b80-76ac-11eb-96e8-76bac2542761.png">

2. In the request amount section add currency choice and dropdown 
<img width="769" alt="Screenshot 2021-02-25 at 14 54 25" src="https://user-images.githubusercontent.com/7249484/109115105-88838180-7779-11eb-9b50-2e74069dad0b.png">

3. Remove 3 different types of addresses in the right column and leave only one 
Design
<img width="474" alt="Screenshot 2021-02-24 at 14 29 38" src="https://user-images.githubusercontent.com/7249484/108957601-bc44a580-76ac-11eb-87d1-133902d5103d.png">

4. Move "Copy and close" button to the bottom of the screen
<img width="780" alt="Screenshot at Feb 24 14-31-31" src="https://user-images.githubusercontent.com/7249484/108958201-9a97ee00-76ad-11eb-80df-7115fb3a4481.png">

5. Add "Contact" section above "Trasaction type"
5.1. Empty state
<img width="420" alt="Screenshot 2021-02-24 at 14 36 20" src="https://user-images.githubusercontent.com/7249484/108958271-b7342600-76ad-11eb-87bc-0af161fdb8c3.png">
5.2. After user started to enter symbols, show dropdown list of existing contacts with search results
<img width="418" alt="Screenshot 2021-02-24 at 15 24 40" src="https://user-images.githubusercontent.com/7249484/108962946-6c69dc80-76b4-11eb-8a23-b35e7fc6d474.png">
5.3. Entered new name 
<img width="410" alt="Screenshot 2021-02-24 at 15 26 01" src="https://user-images.githubusercontent.com/7249484/108963073-9c18e480-76b4-11eb-80a3-b5565098ace3.png">
Header of address section on the right should change accordingly inputed symbols
<img width="832" alt="Screenshot at Feb 24 15-33-31" src="https://user-images.githubusercontent.com/7249484/108963857-aab3cb80-76b5-11eb-8a85-8a81bbead82b.png">
Long name case
<img width="410" alt="Screenshot 2021-02-24 at 15 31 42" src="https://user-images.githubusercontent.com/7249484/108963689-66c0c680-76b5-11eb-9268-369a57d23010.png">
5.4. Choosen existing contact
<img width="412" alt="Screenshot 2021-02-24 at 15 27 16" src="https://user-images.githubusercontent.com/7249484/108963220-c8346580-76b4-11eb-9a6b-b8ee80bb159a.png">
X icon resets address (this screen https://zpl.io/2G8AqRj)

5.5. Create new address button generates new address fot existing contact
<img width="423" alt="Screenshot 2021-02-24 at 15 29 25" src="https://user-images.githubusercontent.com/7249484/108963465-16496900-76b5-11eb-91e4-eae452163b0b.png">
After the button had been pressed, show toast notifiction
<img width="920" alt="Screenshot at Feb 24 15-30-44" src="https://user-images.githubusercontent.com/7249484/108963608-4abd2500-76b5-11eb-8b1c-929850959719.png">

**Comment by chapati** [comment]
As discussed with Alex Romanov we will not implement new address book & contact search for 6.0. Only simplify the receive screen to have less options:

1. Always new address is created
2. Address is valid for 2 months. Validity is automatically extended when transaction is received for this address
3. If 'Regular' is selected, then token includes regular address + 1 offline token
4. If 'Max privacy' is selected, then token includes 1 max privacy token
5. Addres details dialog in address book: validity dropdown is removed, active/inactive switch is added. If address was inactive and it becomes active then it is again set valid for 2 months.

New task for 'search' & 'address book' redesign is created for v6.0

**Comment by chapati** [comment]
For 2 & 5 above new task is created.

**Comment by Sergei-Beam** [comment]
checked
