### ISSUE TITLE
Address book flow on Send screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#488]
New design https://zpl.io/2GP7M8E

1) Empty screen https://zpl.io/VxAMMAW:
- add icon "address book" that opens dropdown list with address book https://zpl.io/29mqq7e
- in field user can paste address or search.
![image](https://user-images.githubusercontent.com/47353570/121854453-d6a59c00-ccfa-11eb-99b7-cca6e9f2ae28.png)

2) New Address pasted https://zpl.io/25PnnPQ
- if new address pasted - display field for entering name for saving or search from existing contacts
![image](https://user-images.githubusercontent.com/47353570/121855678-4d8f6480-ccfc-11eb-8ff8-77d131bd6d08.png)

3) Search contact by name https://zpl.io/bAxjPRB
- highlight entered letters
![image](https://user-images.githubusercontent.com/47353570/121855742-5d0ead80-ccfc-11eb-91cb-07f0a36d234b.png)

4) Paste address that already saved as contact https://zpl.io/2E5X3pe
- in this case automatically display contact name and address type
![image](https://user-images.githubusercontent.com/47353570/121855804-6dbf2380-ccfc-11eb-8779-42bd7ee0317a.png)

_Regarding transaction type._

5) If receiver request Max Privacy transaction type - in address book creates only 1 address type: Max Privacy. 
- In this case no need to display Transaction Type block.
- Comment "Max Privacy address" below contact name is required https://zpl.io/aNNl3M9
![image](https://user-images.githubusercontent.com/47353570/121855901-892a2e80-ccfc-11eb-94c3-6954fc340e06.png)

6) If receiver request Regular transaction type - in address book creates Regular address: https://zpl.io/2E5X3pe
- In this case Transaction Type has 2 switch position: regular and offline
- Comment "Regular address" below contact name is required
![image](https://user-images.githubusercontent.com/47353570/121855976-a19a4900-ccfc-11eb-8628-1f4e8b12051d.png)

7) If receiver request regular transaction type at first time and then request max privacy - sender can assign this 2 addresses to 1 contact. And in address book creates 2 address types: Regular (online and offline) and Max Privacy. So sender can select what transaction type to use. https://zpl.io/29pKdLp
- In this case sender can select between this 3 addresses in Transaction Type block
- Comment "Regular address" or "Max Privacy address" below contact name is not required 
![image](https://user-images.githubusercontent.com/47353570/121857118-ed99bd80-ccfd-11eb-9300-9d0290bf5e5e.png)

8) Long contact name https://zpl.io/VDglljw
![image](https://user-images.githubusercontent.com/47353570/121857181-01ddba80-ccfe-11eb-9661-02163b0a6962.png)

9) Add Available in "Amount" block https://zpl.io/VDglljw
![image](https://user-images.githubusercontent.com/47353570/121857227-10c46d00-ccfe-11eb-9e19-b56477802680.png)

10) Add "Copy" icon next to SBBS address, remove identity and place transaction type in the title https://zpl.io/bJ85B46
![image](https://user-images.githubusercontent.com/47353570/121857286-2043b600-ccfe-11eb-98c5-4b5a109fd62f.png)

11) Select coins. Please make it sorted by recently used coins by default https://zpl.io/VQJ73q4
![image](https://user-images.githubusercontent.com/47353570/121937245-23b55c80-cd53-11eb-87e9-b3e55ea0cc76.png)

**Comment by Denis-Asipenko** [comment]
selection сoin implemented and checked, all other will be implemented in 6.1.
> 
> 10. Select coin
>    https://zpl.io/bJMwPR6
