### ISSUE TITLE
Fix the popup for transaction details [linux]

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#493]
Reduce the size of the "more details" popup
reproduced on:
- receive screen for all addresses 
- atomic swap screen accept and create swap offer
- payment proof details

![Screenshot_286](https://user-images.githubusercontent.com/50007056/107224532-9c647f00-6a28-11eb-8d75-e52402b67bef.png)

**Comment by Roberrtt** [comment]
Not fixed for:
- on create a swap offer screen for "more details"
- for details transaction

And reduce the size window for max_privacy
![Screenshot_312](https://user-images.githubusercontent.com/50007056/107523091-6f010800-6bc5-11eb-9a63-05b1e4ac0dab.png)
![Screenshot_313](https://user-images.githubusercontent.com/50007056/107523355-aec7ef80-6bc5-11eb-8b5f-b34beb912016.png)
![Screenshot_311](https://user-images.githubusercontent.com/50007056/107523359-af608600-6bc5-11eb-98b3-759f4375b147.png)

**Comment by chapati** [comment]
Merged to beamX. Everything is good now

**Comment by Roberrtt** [comment]
checked
