### ISSUE TITLE
Currency selection combo redesign

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#494]
If have time according to the new design:

1) Square corners
2) New selection highlight
3) Location of the currency name should be in the middle of amount (not at the bottom)

Design: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/6005adf246010c1393d1bf05

**Comment by chapati** [comment]
Design is here. For now only general look changed. 'Other assets' would be added after verfiied assets is implemented. Search is opened for 6.1

**Comment by chapati** [comment]
https://github.com/BeamMW/beam-ui/issues/542 - search

**Comment by Denis-Asipenko** [comment]
Need to move the scroll bar to the right as shown in the screenshot
![image](https://user-images.githubusercontent.com/45556620/111459712-1d9be980-872c-11eb-9535-46f34ec95b1a.png)

**Comment by Denis-Asipenko** [comment]
сhecked
