### ISSUE TITLE
Incorrectly sorted by status and type on the utxo screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#495]
When sorting the ASC, the Maturing status is below the spent
Expected: Available > Maturing > Spent
https://beam.testquality.com/project/5267/plan/9325/run/145118/result/2243614
![Screenshot_294](https://user-images.githubusercontent.com/50007056/107338947-2c5c0480-6acd-11eb-9f8c-5cfaa9a58c01.png)
When sorting the DESC, type of the shielded is found after the change
Expected: Shielded > Regular > Change
https://beam.testquality.com/project/5267/plan/9325/run/145118/result/2243615
![Screenshot_295](https://user-images.githubusercontent.com/50007056/107338971-3120b880-6acd-11eb-91c9-9060024e399f.png)

**Comment by Denis-Asipenko** [comment]
checked
