### ISSUE TITLE
Qt 5.15.2 incorrect height calculation

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam-ui#499]
#493 fixed with incorrect way
Need to find a reason of incorrect behavior and fix it

**Comment by chapati** [comment]
Looks like a bug in QT, not our issue. Let's consider this very low priority and fix when have time / move to next versions.

**Comment by echoby** [comment]
@chapati 
https://github.com/BeamMW/beam-ui/commit/caf9630719bd8cbb46fe1002c8543c2bf7aab661
review, pls

**Comment by chapati** [comment]
Let's consider this fixed. Thanks.
