### ISSUE TITLE
Active and inactive buttons: improvements

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#50]
1) Please make inactive state brighter for buttons "send", "publish offer" and "apply changes" (as in INACTIVE column, not as in CURRENTLY IN WALLET.) https://zpl.io/bLJKylG
![image](https://user-images.githubusercontent.com/47353570/126535490-10b2df17-6906-4d5c-8d4f-13c1a0ac394d.png)

2) Make hover shadow the same color as button. In current implementation it ios white.

Current version:
![image](https://user-images.githubusercontent.com/47353570/126536903-9a538a3c-5e67-442e-8af7-9b65bec92b4a.png)

Correct design:
![image](https://user-images.githubusercontent.com/47353570/126536308-8377192f-5547-4657-816f-be1222ffc89f.png)

2.1) For transparent buttons (close/cancel button) make opacity 20%(not 10%) and add shadow for on hovered buttons.

3) On "show owner key" and "show seed phrase" -  make "x" icon in white

Correct design:
![image](https://user-images.githubusercontent.com/47353570/126536719-9961bbb4-60e8-4efc-9da0-57b3554fe1b8.png)

Current version:
![image](https://user-images.githubusercontent.com/47353570/126536608-141567ef-40b0-439e-98f5-0970fc2a663d.png)
![image](https://user-images.githubusercontent.com/47353570/126536626-82dbb196-0e95-4b1e-88bc-124714425e22.png)

4) When "rescan" and "confirm tx detail" popups are opening, button "cancel" looks like on-hovered. They should be as regular active buttons.

Correct design:
![image](https://user-images.githubusercontent.com/47353570/126537283-371d8d75-3da7-464c-902f-53d253bce13b.png)

Current version:
![image](https://user-images.githubusercontent.com/47353570/126537107-bd49d085-603d-472d-ae27-01375917e4c5.png)

5) Add icons to buttons on "change password" popup https://zpl.io/VqQKDmm

Current version:
![image](https://user-images.githubusercontent.com/47353570/126537530-89762591-941b-4523-a3d3-0784b478bb86.png)

Correct design:
![image](https://user-images.githubusercontent.com/47353570/126537588-8cc16701-6bdf-415e-9725-1feb7afc659c.png)

6) In Nodes (all currencies) settings make "x" icon and "cancel" with the same oppacity.

Current version:
![image](https://user-images.githubusercontent.com/47353570/126537703-fcebdd44-34ea-43c1-b5aa-60f47d87fd4b.png)

Correct design:
![image](https://user-images.githubusercontent.com/47353570/126537960-216f04a0-7bf4-4a58-ba6d-cd4c2573de90.png)

7) Add shadow to "detail" button on the Notification screen https://zpl.io/bLJKylG

Correct design:
![image](https://user-images.githubusercontent.com/47353570/126538425-e7f0363e-69d6-4174-b2f8-2cf9ec0156ad.png)

Current implementation
![image](https://user-images.githubusercontent.com/47353570/126538371-07e5e701-7ccf-4d88-81b8-006ce6495077.png)

**Comment by kovaletskaterina** [comment]
1. Incorrect opacity of icon on the inactive "copy and close" button at the "Create a Swap offer" screen. The copy icon should be with the same opacity as the button's text.
![image](https://user-images.githubusercontent.com/83376495/152500635-0e198d9d-21c0-44dc-af44-059276bcf1fb.png)

3. Incorrect colour for the "x" icon on the "cancel" button on the "Show owner key" pop-up, the icon should be white.
![image](https://user-images.githubusercontent.com/83376495/152499758-9a22cf4d-f11b-4bd1-9a58-96286fd3442f.png)
The colour of the "x" icon on the "cancel" button on the "Edit seed phrase" pop-up is incorrect. The "x" icon should be white.
![image](https://user-images.githubusercontent.com/83376495/152499853-4bd67a5a-b95a-4071-a6bf-92287769e1ae.png)
The colour of the "x" icon on the "cancel" button on the"Show seed phrase" pop-up is incorrect, The "x" icon should be white.
![image](https://user-images.githubusercontent.com/83376495/152499887-eaf114a4-77e7-4fad-8f06-02b103bc3546.png)
The colour of the "x" icon on the "cancel" button on the "Clear seed phrase" pop-up is incorrect. The "x" icon should be white.
![image](https://user-images.githubusercontent.com/83376495/152499940-a6858bcd-0c29-475e-80a2-389f3764cb2b.png)

**Comment by kovaletskaterina** [comment]
Checked
