### ISSUE TITLE
Applications: docs

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#508]
Need to create documentation for apps development.

**Comment by chapati** [comment]
Need to mention dev console from task #522

**Comment by bravogeorge** [comment]
Hello, I am an aspiring technical writer. I would love to help you guys with creating new documentation or updating old documentation if you are still in need.

**Comment by beam-mw** [comment]
> Hello, I am an aspiring technical writer. I would love to help you guys with creating new documentation or updating old documentation if you are still in need.

@bravogeorge please contact me on Telegram (@bigromanov)
