### ISSUE TITLE
BeamAmount: refactoring

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#516]
Need to refactor BeamAmount control and get rid of maxPaintedWidth. 

1. Use elide on UnitName and detect if need to shorten amount automatically, 
2. maxPaintedWidth: this.width in TxDetails causes freeze of animation if multiple assets

**Comment by chapati** [comment]
Please test that amounts with unit (like "10 BEAM", "20.21 BeamX" &c) are displayed correctly

**Comment by gingervik** [comment]
please, check all amount fields in the wallet

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.10830.4004
