### ISSUE TITLE
Settings: address expiration notification

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#52]
1. Need to implement address expiration notification & setting
![DeepinScreenshot_select-area_20200608134147](https://user-images.githubusercontent.com/12074933/84021755-dd822c00-a98d-11ea-829b-91978da8edf9.png)
2. Also change "Wallet version" to "Wallet updates"

**Comment by chapati** [comment]
This was removed from design and from code.
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece31fc60d9694b7d0d31c6

**Comment by Denis-Asipenko** [comment]
invalid
