### ISSUE TITLE
Cannot select generated address and copy it using Ctrl+C.

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam-ui#520]
**Bug description**
Cannot select generated address from _Address details_ and copy it using Ctrl+C. Also, it's impossible to copy token from _Swap token_ using Ctrl+C or right mouse click and button copy.

**To Reproduce**
Steps to reproduce:
1. Run the UI Wallet.
2. Click on _Recieve_ button.
3. Click _More details_ button.
4. Try to select the text of the generated address and copy it using Ctrl+C.
5. On Atomic swap screen click _Create swap_ and create a new swap.
6. Click _Show token_ button.
7. Try to select the text of the generated token and copy it using Ctrl+C or right mouse click and button copy.

**Actual**
The address text is not selected and not copied.

**Expected**
The address or token text is selected and copied.

**Platform and build**
* Windows 10

![1](https://user-images.githubusercontent.com/68247034/91563526-afd2d080-e947-11ea-9fee-0499e048c74b.gif)
![Beam Wallet Masternet 2020-12-16 11 40 41](https://user-images.githubusercontent.com/68247034/102332664-7200c300-3f9d-11eb-9622-219c5701248a.png)

**Comment by chapati** [comment]
We never supported Select + Ctrl+C for this controls and will not. Only copy via right click menu. Please test that right click menu works.

**Comment by kazaryan-t** [comment]
Checked om Master 6.0.10856.4046

Cannot select generated token of atomic swap and copy it using right mouse click and copy button.

https://user-images.githubusercontent.com/68247034/111759050-3df3b180-88ae-11eb-8670-f3826332cae4.mp4

**Comment by kazaryan-t** [comment]
Checked on Master 6.0.10856.4046.
