### ISSUE TITLE
Change statuses for contracts from completed to received/sent

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#521]
When send\receiv to the Vautl\Faucet, the transaction has the status completed
![Screenshot_13](https://user-images.githubusercontent.com/50007056/100605792-85fbc200-3319-11eb-8df6-3f3bc300c93d.png)

**Comment by chapati** [comment]
Here should be completed. Contracts are not always send/receive. Actually there is not way to understand for contracts what particular transaction does.

**Comment by Roberrtt** [comment]
checked
