### ISSUE TITLE
Applications: disable right-click browser menu

### ISSUE THREAD

**Issue by iscander01** [BeamMW/beam-ui#523]
![Безымянный](https://user-images.githubusercontent.com/44571357/98846572-38014600-2460-11eb-9677-3fc04b2ca08b.png)

**Comment by chapati** [comment]
Menu would be available now only for copying selected text and for edit controls

**Comment by KatsiarynaV** [comment]
When we select all and right click on the image or link, the browser menu opens
![01](https://user-images.githubusercontent.com/68267190/109813730-c7fd1280-7c3e-11eb-96da-842ce0778a1f.jpg)
![04](https://user-images.githubusercontent.com/68267190/109814117-288c4f80-7c3f-11eb-82c3-709a1b1b4387.jpg)
![03](https://user-images.githubusercontent.com/68267190/109813735-c895a900-7c3e-11eb-8848-0d8447c328bf.jpg)

**Comment by chapati** [comment]
Disabled for images & links

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.10801.3985
