### ISSUE TITLE
Settings: Get BEAM from faucet

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#53]
Need to implement Get Beams from Beam Community Faucet action
![DeepinScreenshot_select-area_20200608134358](https://user-images.githubusercontent.com/12074933/84021941-2afe9900-a98e-11ea-8fdb-9f46adda5f2d.png)

**Comment by chapati** [comment]
Need to discuss if we need to mention community website here: 

![gnome-shell-screenshot-7KHWM0](https://user-images.githubusercontent.com/12074933/85345706-e16c8d00-b4fb-11ea-9e79-96f9f3e144d8.png)

And change text here:

![gnome-shell-screenshot-Z3WVM0](https://user-images.githubusercontent.com/12074933/85345697-d580cb00-b4fb-11ea-9d18-3be5caeb8285.png)

If yes, then please provide updated texts. If no, then then this is done.

**Comment by gingervik** [comment]
@sasha-abramovich could you help with text,please?

**Comment by gingervik** [comment]
irrelevant
