### ISSUE TITLE
The wallet has delays when there is asset with long name

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#530]
When the wallet has  registered asset with  long name, then when you select it on the wallet screen and go to the send screen, there are delays ,also when you enter the amount of asset
pass=1
[wallet.zip](https://github.com/BeamMW/beam-ui/files/6066614/wallet.zip)
https://user-images.githubusercontent.com/50007056/109609656-b2072900-7b3c-11eb-95b1-d5de93b6ea94.mp4

**Comment by chapati** [comment]
Please test now, should be much better.

**Comment by Roberrtt** [comment]
There's  delay when switching from any tab to wallet tab
https://user-images.githubusercontent.com/50007056/111268859-e7347080-863e-11eb-94cc-3dd545728a73.mp4

**Comment by KatsiarynaV** [comment]
There's delay when switching to the UTXO tab
![gif01](https://user-images.githubusercontent.com/68267190/111456841-86816280-8728-11eb-9bdf-3f2d62851fa6.gif)

**Comment by chapati** [comment]
Check if it is better now please

**Comment by Roberrtt** [comment]
There is a delay:
- on the sending screen when you click on the send button
- when opening transaction details

[wallet.zip](https://github.com/BeamMW/beam-ui/files/6726616/wallet.zip) = pass 1

https://user-images.githubusercontent.com/50007056/123644137-c4b11680-d82d-11eb-8303-8cbd44d9bec1.mp4


https://user-images.githubusercontent.com/50007056/123644143-c5e24380-d82d-11eb-8864-b170ebd70c3e.mp4

**Comment by chapati** [comment]
Check now please

**Comment by AndreyDyakonov** [comment]
If in wallet there are transactions (received assets) with name is long and all letter are capital, through max privacy then when you click button "more details" tab open with delay

steps

- make some transactions with assets and max privacy
- click button balance
- click button "more details" 

Actually:
Tab "more details" is open with a delay 

note: the more coins in the locked state, the biggest the delay

Expected:
The tab opens without delay

[wallet.zip](https://github.com/BeamMW/beam-ui/files/6740497/wallet.zip)
pass =1 
https://user-images.githubusercontent.com/85252690/123953806-50eb4700-d9b0-11eb-8cec-e1dee16aca99.mp4

**Comment by AndreyDyakonov** [comment]
Checked
