### ISSUE TITLE
An invalid address is copied on the receive screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#535]
When we copied the address(for exchange or mining pool) by clicking on the "copy and close" button on receive screen, this address was copied
- 11c3b54ca54f6d2811dd083f34c87d8b0f6286e450205023e5b595271180f2d99795271180f2d997 -this address isn't passed for validity

If we copy it in address book this address is copied
- 11c3b54ca54f6d2811dd083f34c87d8b0f6286e450205023e5b595271180f2d997

Happened on MacOS

**Comment by chapati** [comment]
Send screen has been significantly changed. Please try to reproduce on the latest version. If not reproduced close.

**Comment by Denis-Asipenko** [comment]
сhecked
