### ISSUE TITLE
Add Regular and Max Privacy funds to Balance popup

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#536]
Design https://zpl.io/awzLzj1

![image](https://user-images.githubusercontent.com/47353570/109919889-1b647480-7cc2-11eb-8cb8-742e363abfe1.png)

1) Please Rename "Amount" to "Balance"

Previous design
![image](https://user-images.githubusercontent.com/47353570/109919948-3636e900-7cc2-11eb-98ab-0a92deefc7f4.png)

Updated design 
![image](https://user-images.githubusercontent.com/47353570/109920000-4cdd4000-7cc2-11eb-88df-9e5f71b56cd6.png)

2) Split popup to 2 sections by a line: Available and Locked. 
Available and Locked have total amount and then split into parts: regular, max privacy, maturing, change and max privacy (in progress)
![image](https://user-images.githubusercontent.com/47353570/109920110-7c8c4800-7cc2-11eb-9de6-2192c92a59cc.png)

**Comment by chapati** [comment]
"Max Privacy" renamed to "Shielded" in available: it is impossible to distinguish Max Privacy and Offline outputs which both are shielded. So leaving here 'max privacy' is misleading.

**Comment by Denis-Asipenko** [comment]
1.If the popup is open at the time of receiving the shielded(max privacy) asset, the "more details" button doesn't appear. Only after reopening this popup, the button appear.

![image](https://user-images.githubusercontent.com/45556620/112468500-62053600-8d79-11eb-815f-14dded76358f.png)

2.If the popup is open at the time of receiving the shielded coins(sending them to a public offline address), the amount isn't updated in the popup, the "More details" button isn't pressed, and there is also a lot of empty space at the bottom of the window (marked in blue). After reopening this popup the bugs disappear.

![image](https://user-images.githubusercontent.com/45556620/112475920-65e98600-8d82-11eb-9a61-6e67c1befd40.png)

3. received max privacy assets are displayed along with the beam.
![image](https://user-images.githubusercontent.com/45556620/112467743-7d237600-8d78-11eb-8808-9f151ada0426.png)

**Comment by chapati** [comment]
3. Should be fixed
1-2. In this versions once shown popup should not change. Open task for v6.1 to dynamically update popup

**Comment by Denis-Asipenko** [comment]
checked
