### ISSUE TITLE
Settings: import & export wallet data

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#54]
Need to implement import & export actions
![DeepinScreenshot_select-area_20200608134536](https://user-images.githubusercontent.com/12074933/84022049-57b2b080-a98e-11ea-9162-ec1df0d416e2.png)

Dialogs:
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece69024e891629849cfff4
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece69024e891629849d00a3

(It is better to specify which data (tx, addresses&c), now it is not clear
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece69054e891629849d015c

https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece69008d964547a8ba83df

**Comment by Denis-Asipenko** [comment]
After discussion, it was decided not to implement this function in 5.1 and implement it in a future release.

**Comment by beam-mw** [comment]
Irrelevant
