### ISSUE TITLE
Leave the field empty in the transaction details if comment wasn't entered

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#540]
Leave the field empty in the transaction details if comment wasn't entered on send\receive screen 
![Screenshot_416](https://user-images.githubusercontent.com/50007056/109984744-21d00c00-7d15-11eb-8939-3894fe80e619.png)

**Comment by KatsiarynaV** [comment]
When we add a comment to the **max privacy or offline address** on the receive screen it's not displayed in the transaction details (for receiver)
![18](https://user-images.githubusercontent.com/68267190/110471223-efdff080-80ec-11eb-894c-c0eda462afca.jpg)
![19](https://user-images.githubusercontent.com/68267190/110471226-f0788700-80ec-11eb-9125-cff50bcc6ff3.jpg)
![20](https://user-images.githubusercontent.com/68267190/110471227-f1111d80-80ec-11eb-9900-82945045abbe.jpg)

**Comment by chapati** [comment]
This comment is only for address, this behavior will stay for 6.0 (discussed with romanov)

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.10817.3995
