### ISSUE TITLE
Add letters for the asset amount

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#541]
Add letters to indicate the number of assets
![Screenshot_413](https://user-images.githubusercontent.com/50007056/109987117-63fa4d00-7d17-11eb-9e6c-6f3758e27e5a.png)

**Comment by chapati** [comment]
Now billion (B) is the last on. Should add more.

**Comment by chapati** [comment]
![gnome-shell-screenshot-03P730](https://user-images.githubusercontent.com/12074933/121088958-23670f80-c7ef-11eb-9896-e9b6e60868e1.png)
Added like this. Should be enough

**Comment by Roberrtt** [comment]
checked
