### ISSUE TITLE
Wallet crashed after opening

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#543]
The user came up with a wallet problem.
His wallet crashed after opening it.
"so i have a problem that the beam wallet is always crashing when i try to restore a wallet or to open my wallet on windows" 

 Beam Wallet UI 5.3.10410.3657 (mainnet)

Logs from dump file:

>  Beam Wallet.exe!QFontEngineMulti::ascent(void)  C++
   Beam Wallet.exe!QFontMetricsF::height(void)  C++
   Beam Wallet.exe!QQuickTextPrivate::lineHeightOffset(void)  C++
   Beam Wallet.exe!QQuickText::updatePaintNode(class QSGNode *,struct QQuickItem::UpdatePaintNodeData *)  C++
   Beam Wallet.exe!QQuickWindowPrivate::updateDirtyNode(class QQuickItem *)  C++
   Beam Wallet.exe!QQuickWindowPrivate::updateDirtyNodes(void)  C++
   Beam Wallet.exe!QQuickWindowPrivate::syncSceneGraph(void)  C++
   Beam Wallet.exe!QSGRenderThread::sync(bool,bool)  C++
   Beam Wallet.exe!QSGRenderThread::syncAndRender(class QImage *)  C++
   Beam Wallet.exe!QSGRenderThread::run(void)  C++
   Beam Wallet.exe!QThreadPrivate::start(void *)  C++
  [Inline Frame] Beam Wallet.exe!invoke_thread_procedure(unsigned int(*)(void *)) Line 91  C++
   Beam Wallet.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115  C++
   [Frames may be missing, no binary loaded for kernel32.dll]  
   kernel32.dll!00007ffe419d7974()  Unknown

DmpFile:
[Beam Wallet12.zip](https://github.com/BeamMW/beam-ui/files/6109105/Beam.Wallet12.zip)
System:
![Screenshot_423](https://user-images.githubusercontent.com/50007056/110484209-7f8c9b80-80fb-11eb-999b-acb7d72c25f5.png)

**Comment by anatolse** [comment]
it seems that user has a problem with video drivers

**Comment by anatolse** [comment]
closing
