### ISSUE TITLE
Design for empty screens (transactions, addresses etc)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#544]
Atomic Swap (active offers) https://zpl.io/VQ1BnX9
![image](https://user-images.githubusercontent.com/47353570/110691770-3a956180-81ee-11eb-83e2-4047c3770a66.png)

Atomic Swap (my offers) https://zpl.io/add0MJp
![image](https://user-images.githubusercontent.com/47353570/111767947-f9691580-88af-11eb-9e46-a224aeecc02e.png)

Atomic Swap (transactions) https://zpl.io/VQPDqGk
![image](https://user-images.githubusercontent.com/47353570/111768407-9166ff00-88b0-11eb-96ce-514f1797750c.png)

Address book https://zpl.io/aXOkDL8
![image](https://user-images.githubusercontent.com/47353570/110693511-2fdbcc00-81f0-11eb-8f3e-d0395bd232b5.png)

No contacts in address book https://zpl.io/aRndNnv
![image](https://user-images.githubusercontent.com/47353570/111767308-3bde2280-88af-11eb-924c-5f17b98e5b24.png)

Transaction https://zpl.io/bWmYp97
![image](https://user-images.githubusercontent.com/47353570/111766878-b8243600-88ae-11eb-9a26-51d15a0e950b.png)

No in progress (sent/received) transactions https://zpl.io/Vk40YP8
![image](https://user-images.githubusercontent.com/47353570/111766450-3a602a80-88ae-11eb-9fb8-1f85e2079be1.png)

Notifications https://zpl.io/aXOkDwx
![image](https://user-images.githubusercontent.com/47353570/110694084-db851c00-81f0-11eb-91ea-7b895ba1571e.png)

UTXO https://zpl.io/2GDokMY
![image](https://user-images.githubusercontent.com/47353570/110696028-3ae42b80-81f3-11eb-8151-ac4eda0b0d23.png)

**Comment by kazaryan-t** [comment]
1. Please, change the text for empty _Atomic swaps - My offers_ screen as in the design:
https://zpl.io/add0MJp
Actual:
![Beam Wallet Masternet 2021-03-29 15 16 38](https://user-images.githubusercontent.com/68247034/112835314-ca1d8a00-90a1-11eb-9feb-498573f6ece6.png)

2. Change the text for empty _Atomic swaps - Transactions_ screen as in the design:
https://zpl.io/VQPDqGk
Actual:
![Beam Wallet Masternet 2021-03-29 15 20 50](https://user-images.githubusercontent.com/68247034/112835658-3b5d3d00-90a2-11eb-923c-525e0e5da13f.png)

**Comment by kazaryan-t** [comment]
Checked.
