### ISSUE TITLE
Transactions details: comment for max privacy and offline transactions

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#545]
When we add a comment to the max privacy or offline address on the receive screen it should be displayed in the transaction details (for receiver)
![18](https://user-images.githubusercontent.com/68267190/110636728-a7dcce80-81bd-11eb-863d-3a725f64d59b.jpg)
![19](https://user-images.githubusercontent.com/68267190/110636731-a90dfb80-81bd-11eb-8131-8350d6c47a6b.jpg)
![20](https://user-images.githubusercontent.com/68267190/110636732-a90dfb80-81bd-11eb-8606-fb9a4b998999.jpg)

**Comment by Maxnflaxl** [comment]
Comments are local and aren't shared with the receiver.
