### ISSUE TITLE
The swap token doesn't switch to "accept swap offer" screen via the "send" screen

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#549]
When we insert the swap token, in the address field on the send screen, there is no switch to the "accept swap offer" screen.

https://user-images.githubusercontent.com/50007056/110822579-42164280-82a2-11eb-895c-3070b564f9ee.mp4

token:
5G2G97ScTvdZz3z5vxCYzJQjNvyZ2jSp2JczLii52hWDbnk3Zk2q2r7wf8GhHVX29V5umiTEjdeX1QhUXbGru51UnbdETAiNwtGY8MoZ5TtEiQSysc5MjUWZhi7ULoXTCFxieNQWSMgcCad6JZsJuCCdRXVgUZ6gFmAc3bj5jWnY8RcQ9iXQq53ppSNZV4vkRroRbMerzU5mRdBG1PDn8wDDeJkkRuxMDgaEE15AZn

**Comment by chapati** [comment]
New send dialog has been reworked. Should be OK now. Though the token above is not detected as swap token. This one is detected: 

5G2G97ScTvdZz3z5vxCYzJQjNvyZ2jSp2JczLii52hWDbnk3Zk2q2r7wf8GhHVX29V5umiTEjdeX1QhUXbGru51UnbdETAiNwtGY8MoZ5TtEiQSysc5MjUWZhi7ULoXTCFxieNQWSMgcCad6JZsJuCCdRXVgUZ6gFmAc3bj5jWnY8RcQ9iXQq53ppSNZV4vkRroRbMerzU5mRdBG1PDn8wDDeJkkRuxMDgaEE15AZn

I do not know where you've taken that one token above. Try to test on tokens from the latest version.

**Comment by chapati** [comment]
Fixed, pls test.

**Comment by Roberrtt** [comment]
checked
