### ISSUE TITLE
Old exchange rates are not stored in the wallet

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#550]
Previously, we stored the exchange rates for each received transaction so that the user could go back and see how much previously in the equivalent he received, but now the exchange rates update all the old transactions with each change.
In addition, the hint under the currency exchange rate has disappeared too.
**Before:** ![image](https://user-images.githubusercontent.com/44496108/110830593-70981b80-82aa-11eb-81f7-c5fd312028e0.png)
**Now:** 
![image](https://user-images.githubusercontent.com/44496108/110831089-f6b46200-82aa-11eb-8ab8-3d70234629f3.png)

**Comment by Sergei-Beam** [comment]
1. Need to remove Total value from tx details in BEAM transactions and leave it just for contracts
Design: ![image](https://user-images.githubusercontent.com/44496108/111541157-2ec31580-8781-11eb-9280-f98e9c0736ca.png)
Master: 
![image](https://user-images.githubusercontent.com/44496108/111541201-384c7d80-8781-11eb-922c-6abe6d09c98b.png)
2. Need to add some message when the rate wasn't broadcasted or wasn't saved for old transactions (Or as variant hide this field)  because currently, it looks strange (@dariatarakanova need your attention I suppose)
![image](https://user-images.githubusercontent.com/44496108/111541749-e9ebae80-8781-11eb-8ebb-60e72f499826.png)

**Comment by chapati** [comment]
1. Total value is displayed for contracts only now
2. We had similar warning in previous version, so no need to change design: "Exchange rate to %1 was not available at the time of transaction"

**Comment by Sergei-Beam** [comment]
checked
