### ISSUE TITLE
Add text "For the day of transaction" to tx details

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#553]
https://zpl.io/29plloy
Please add text as comment below USD value 
![image](https://user-images.githubusercontent.com/47353570/111173722-8ca00380-85af-11eb-8c03-62b7e2a478e9.png)

For contracts https://zpl.io/V17rDpZ
![image](https://user-images.githubusercontent.com/47353570/111173976-b9ecb180-85af-11eb-9f20-223e57db14b3.png)

**Comment by chapati** [comment]
1. If asset has rate info broadcasted rate includes date notification:
![gnome-shell-screenshot-JAKI00](https://user-images.githubusercontent.com/12074933/111357169-1c21e100-869a-11eb-8fe7-71403c4f3477.png)

2. Total value is displayed only if rate is broadcasted for each asset. If rate is not broadcasted for each asset there is no way to calculate the total value. Also if there is only 1 asset/BEAM tota

**Comment by gingervik** [comment]
@chapati please, remove "for the day of transaction" line from everywhere except "USD/BTC value" for regular txs and "Total value" in contracts. we don't need this line everywhere. It should be like on Daria's screen
Thank you

**Comment by Sergei-Beam** [comment]
Checked within https://github.com/BeamMW/beam-ui/issues/550
