### ISSUE TITLE
New addresses: expiration

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#557]
1. New address is valid for 2 months. Validity is automatically extended when transaction is received for this address
2. Addres details dialog in address book: validity dropdown is removed, extend/disable buttons added. Address should be extended for 2 months.

**Comment by chapati** [comment]
1. Check new edit address dialog in address book.
2. Check that address is prolonged when transactions are made using this address. Check expiration date & time, send transaction/receive transaction. Check that address is extended.

**Comment by Denis-Asipenko** [comment]
Bugs:
1. when you click "Extend" the expiration date of the address changes to the date and time at the time you click.
![2E6E7472-CB6F-4FCF-AA9A-9D6A0D16CEEA](https://user-images.githubusercontent.com/45556620/112982681-69f01c00-9165-11eb-8b4c-68f0f1551faa.GIF)
2. when the address expires, it is not displayed in the "my expired addresses" tab.
[2021-05-30_12-07-45.zip](https://github.com/BeamMW/beam-ui/files/6228768/2021-05-30_12-07-45.zip)
**Platform and build:**

- Windows
- OS version: 10 pro
- BEAM Build number: 6.0.10928.4080.
**The base of the wallet and the logs file**
Password - 1
[wallet.zip](https://github.com/BeamMW/beam-ui/files/6228771/wallet.zip)

**Comment by Denis-Asipenko** [comment]
1.On the "CONTACTS tab when you go to the send screen, the address isn't inserted in "send to".
![F434F8C9-7B33-407D-8F36-F0EC358B7293](https://user-images.githubusercontent.com/45556620/113710707-b9e25c00-96ec-11eb-8927-6e29a5240a03.GIF)
2. On the "MY ACTIVE ADDRESSES" tab when you go to the receive screen, the wallet is closed. Addresses with the same comment and identity are also created.
![image](https://user-images.githubusercontent.com/45556620/113712219-87396300-96ee-11eb-9b85-c888e04040e2.png)

![2C291A58-51E8-46A6-8E05-5C9F111C2DAC](https://user-images.githubusercontent.com/45556620/113712049-522d1080-96ee-11eb-93b8-9fca5a87212e.GIF)


> 4. Check that recevie/send in context menu in address book works. For receive - new token is generated but inside should be the same SBBS address (check in 'more details')

**Comment by Denis-Asipenko** [comment]
For a desktop wallet, you also need to make the default address must never expire
https://github.com/BeamMW/beam-ui/issues/558#issuecomment-814911514

**Comment by KatsiarynaV** [comment]
Address isn't saved when switching from receive screen to another one (not using the"back" button). Also if copying address on the "address details" screen and switching  to another screen  (not using the"back" button)

![gif05](https://user-images.githubusercontent.com/68267190/114144612-30b26b80-991e-11eb-9773-c43d74d7a7ef.gif)

**Comment by Sergei-Beam** [comment]
Wallet crashes after trying to go to receive a page from address book for max privacy address
Steps:
- create or restore wallet
- go to receive screen and create Max privacy address
- click copy and close
- navigate to the Address book and find created address
- click on three dots and click on receive button
Actual: Wallet crashes

**Comment by Sergei-Beam** [comment]
checked

**Comment by Sergei-Beam** [comment]
**Reproduced again**
_On the "MY ACTIVE ADDRESSES" tab when you go to the receive screen. Addresses with the same comment and identity are also created._
![image](https://user-images.githubusercontent.com/44496108/115676758-922ffc80-a358-11eb-9a63-a19403ea6590.png)

**Comment by Roberrtt** [comment]
checked
