### ISSUE TITLE
New address: api & cli

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#558]
1. Offline token in v 6.0 by default triggers regular transaction
2. Add additional options to start offline transaction

**Comment by chapati** [comment]
CLI

* default address generated by the UI includes 1 offline voucher (enables 1 offline payment)
* CLI get_address --offline switch is renamed to --offline_count
* to make offline payment via the send command --offline switch should be added. Specified address should allow offline payments, i.e. be and offline address generated by the CLI/API or be a regular default address provided by the UI.
* Offline address by design includes all the info necessary to make regular online payment and without the --offline switch the send command would execute a regular online transaction

**Comment by Denis-Asipenko** [comment]
1.both regular and offline transactions are not sent to the address of the new format from the desktop wallet.
![image](https://user-images.githubusercontent.com/45556620/113412425-e5013e80-93c0-11eb-9a6b-a1daddcc4293.png)
![image](https://user-images.githubusercontent.com/45556620/113412441-f4808780-93c0-11eb-865b-a32fa0adaf33.png)
2.When creating an address in a new format, need to display the created address in the new format to the API logs.
![image](https://user-images.githubusercontent.com/45556620/113412580-4f19e380-93c1-11eb-8def-5ec2884ef4ac.png)
3. When sending a transaction to an address of a new format from a desktop wallet, the SBBS address is displayed in the API logs, and not the address of the new format.
![image](https://user-images.githubusercontent.com/45556620/113412742-bdf73c80-93c1-11eb-98d6-557160fca7df.png)


> **v6.0 API changes**
> 
> Test that
> 
> * all addresses pas `validate_address`
> * `tx_send` using an offline (CLI & API) addresses and default regular address from UI trigger an online transaction without `"offline":true` and an offline transaction with `"offline": true`

**Comment by echoby** [comment]
Also, default address must never expire

**Comment by Denis-Asipenko** [comment]
CLI wallet: using the command to generate a public offline address, an offline address is generated
![image](https://user-images.githubusercontent.com/45556620/113885160-49107200-97c8-11eb-9912-a8198c1c6b75.png)
Mainnet:
![image](https://user-images.githubusercontent.com/45556620/113885188-4f9ee980-97c8-11eb-96af-6033b5925e42.png)

**Comment by Denis-Asipenko** [comment]
When creating a regular(new format) address, offline address, public offline address, max privacy address, need to display the created address in the new format to the API logs.
![image](https://user-images.githubusercontent.com/45556620/114881025-4c7cac80-9e0b-11eb-826e-71b297b93205.png)
![image](https://user-images.githubusercontent.com/45556620/114881076-56061480-9e0b-11eb-8726-eac274b9986e.png)
![image](https://user-images.githubusercontent.com/45556620/114881090-59999b80-9e0b-11eb-9949-0368b5f29cc0.png)

**Comment by Denis-Asipenko** [comment]
1.This issue is fixed for the API , but the CLI wallet now duplicates the address information.
![image](https://user-images.githubusercontent.com/45556620/115409176-2fc0ea00-a1fa-11eb-8c1e-e91982593372.png)
> When creating a regular(new format) address, offline address, public offline address, max privacy address, need to display the created address in the new format to the API logs.
> ![image](https://user-images.githubusercontent.com/45556620/114881025-4c7cac80-9e0b-11eb-826e-71b297b93205.png)
> ![image](https://user-images.githubusercontent.com/45556620/114881076-56061480-9e0b-11eb-8726-eac274b9986e.png)
> ![image](https://user-images.githubusercontent.com/45556620/114881090-59999b80-9e0b-11eb-9949-0368b5f29cc0.png)

**Comment by Denis-Asipenko** [comment]
2.It isn't possible to send assets to another wallet.
![image](https://user-images.githubusercontent.com/45556620/115406441-d8217f00-a1f7-11eb-9490-b43d77cb15f6.png)

**Comment by Denis-Asipenko** [comment]
It isn't possible to send assets to another wallet using the CLI wallet 
![image](https://user-images.githubusercontent.com/45556620/115435033-17f56000-a212-11eb-8446-f587ef539f54.png)

**Comment by Denis-Asipenko** [comment]
checked
