### ISSUE TITLE
Send screen- reset the amount to 0 if the user clicks the "add maximum" button on one coin and then selects another coin.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#562]
**Bug description**
if the user clicks the "add maximum" button on one coin and then selects another coin then the amount doesn't reset.

**To Reproduce**
1. Go to the Send screen. The BEAM coin is selected by default
2. Tap add max button.
3. Select another coin.

 **Current behavior:**
the amount doesn't reset.

**Expected behavior:**

 the amount resets to 0.

**Note:** 
the wallet has some assets.
**Platform and build:**

- Windows
- OS version: 10 pro
- BEAM Build number: 6.0.10857.4048

**Screenshots (if applicable)**
![5F889D74-4544-496F-BE18-27BC00F77EFE](https://user-images.githubusercontent.com/45556620/112163931-8a1c5a00-8bfe-11eb-9846-f3612f0977be.GIF)

**Comment by chapati** [comment]
There was a bug in the code: when asset id is changed code supposed to  ALWAYS rest amount to "0" but but because there was a bug it did not work. Fifxed: on asset changed amount is always reset to "0".

**Comment by Denis-Asipenko** [comment]
checked
