### ISSUE TITLE
When select BTC pair, the WBTC offers are displayed

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#563]
When we select BTC pair, the WBTC offers are displayed
This is reproduced only by the creator of offer
Pass =1 [wallet.zip](https://github.com/BeamMW/beam-ui/files/6198674/wallet.zip)

![Screenshot_504](https://user-images.githubusercontent.com/50007056/112311588-ea6ed280-8cb6-11eb-99fb-0817974d4690.png)

**Comment by KatsiarynaV** [comment]
Checked
