### ISSUE TITLE
Add placeholder for DApp Store that will be available after Hard Fork

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#569]
Please add placeholder to DAPPs screen that all apps will be available after fork https://zpl.io/VxAoRNg
![image](https://user-images.githubusercontent.com/47353570/114372622-6fe4f480-9b8a-11eb-9440-e7b183458bfc.png)

**Comment by KatsiarynaV** [comment]
Checked on build 6.0.11144.4164
