### ISSUE TITLE
Add Faucet flow after first wallet installing

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#570]
Let show this message after first installing "See the wallet in action. Get a small amount of Beams from the Faucet DAPP." 

Button leads to Faucet DAPP

design https://zpl.io/an3BloJ
![image](https://user-images.githubusercontent.com/47353570/118183180-7b099980-b442-11eb-91c0-4ae90b96f82e.png)

**Comment by dariatarakanova** [comment]
@echoby full flow here https://github.com/BeamMW/beam-ui/issues/756

**Comment by AndreyDyakonov** [comment]
Checked
