### ISSUE TITLE
Send screen UI: changes is Amount block

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#572]
Please make following changes according to updated design

1) Add available to Amount block
![image](https://user-images.githubusercontent.com/47353570/113207824-c3e20600-9279-11eb-8ea0-5ac0c0971acb.png)

2) Make titles in white color (send to, amount, comment, transaction fee) and subtitles in grey color (available in amount block) https://zpl.io/2jNAKyA
![image](https://user-images.githubusercontent.com/47353570/113207884-d3f9e580-9279-11eb-93c5-af750e13b5d3.png)

This task is part of https://github.com/BeamMW/beam-ui/issues/488

**Comment by KatsiarynaV** [comment]
1. When choosing an other currency the available balance is displayed in Beam
![01](https://user-images.githubusercontent.com/68267190/120787191-c42ba580-c537-11eb-85d4-6ce0540f6f09.jpg)
![02](https://user-images.githubusercontent.com/68267190/120787198-c55cd280-c537-11eb-83d0-bfbb44888629.jpg)

2. If user enters an amount and then erase it, the first number is still displayed in Amount to send field (actual only for assets)
![gif01](https://user-images.githubusercontent.com/68267190/120787724-4f0ca000-c538-11eb-8b0f-4cffc5ad472a.gif)

**Comment by KatsiarynaV** [comment]
Checked

**Comment by KatsiarynaV** [comment]
Available amount shouldn't change when entering an amount to send. It should just show the actual balance before sending
![03](https://user-images.githubusercontent.com/68267190/124425547-632f0180-dd71-11eb-922f-dd4ad7d14ee0.jpg)
![04](https://user-images.githubusercontent.com/68267190/124425551-64602e80-dd71-11eb-923b-e87280a2bf31.jpg)

**Comment by KatsiarynaV** [comment]
Checked
