### ISSUE TITLE
Dao Core App v1 (without Voting)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#578]
1. DAO Core screen (with Investor Allocation section)
https://zpl.io/boJJRgm
![dao core v1](https://user-images.githubusercontent.com/7249484/124744713-9f20bd00-df51-11eb-9e1f-81a67e99792c.png)

DAO Core screen (without Investor Allocation section)
https://zpl.io/amLLE83
![dao core v1 small](https://user-images.githubusercontent.com/7249484/124744782-b069c980-df51-11eb-973e-6ce04e95e945.png)

Info popups
https://zpl.io/2yDpv8J
![dao core v1 small info](https://user-images.githubusercontent.com/7249484/124744748-a8118e80-df51-11eb-9a69-5b9420b3252a.png)

2. Staking widget states 
- nothing deposited yet
- nothing farmed yet
- already farmed
https://zpl.io/VOLQwDr
![staking-states](https://user-images.githubusercontent.com/7249484/124744888-ca0b1100-df51-11eb-9290-8cf754d5f294.png)

4. Public key dialog
https://zpl.io/agm1l49
![dao core public key](https://user-images.githubusercontent.com/7249484/124744919-ce372e80-df51-11eb-9a03-7323ee3d264a.png)

5. Deposit dialog
https://zpl.io/VOLzGYj
![dao core deposit](https://user-images.githubusercontent.com/7249484/124744957-d7c09680-df51-11eb-9860-53535fab55c1.png)

Deposit confirmation
https://zpl.io/VOLzwdQ
![dao core deposit confirmation](https://user-images.githubusercontent.com/7249484/124744976-ddb67780-df51-11eb-8c89-54be4c91fa6a.png)

6. Withdraw dialog
https://zpl.io/agmMJZO
![dao core withdraw](https://user-images.githubusercontent.com/7249484/124744999-e5761c00-df51-11eb-8259-27c1b7293085.png)

Withdraw confirmation
https://zpl.io/bJ8YJ7W
![dao core withdraw confirmation](https://user-images.githubusercontent.com/7249484/124745020-ec049380-df51-11eb-953e-d6d334111cfd.png)

7. Claim dialog
https://zpl.io/2vjGZmv
![dao core claim](https://user-images.githubusercontent.com/7249484/124745032-f161de00-df51-11eb-8c45-75c157bc4d07.png)

8. TX notifications progress
https://zpl.io/anBWJGv
![dao core v1 small notifications](https://user-images.githubusercontent.com/7249484/124745051-f6269200-df51-11eb-91a1-17eacbc89727.png)

By click on Show details button, open transaction list and highlight transaction from progress popup for a few seconds
https://zpl.io/VxpJre3
![wallet-v10-suite-highlighted transaction](https://user-images.githubusercontent.com/7249484/124434034-fd10a180-dda5-11eb-8609-f00881749fd7.png)

**Comment by sasha-abramovich** [comment]
For the estimated transaction time please use the weighted average of the block emission time considering ~10 samples lookback window (when available). The older a block, the less weight it should have.

Whenever a transaction is accomplished faster than the estimated time - the indicator should accelerate to 100%.
Whenever a transaction takes longer than the estimated time - the indicator should start behaving exponentially from 90-95% (to your choice).

**Comment by alexandrashelenkova** [comment]
Divided into separate tasks
https://github.com/BeamMW/beam-ui/issues/686
https://github.com/BeamMW/beam-ui/issues/685
https://github.com/BeamMW/beam-ui/issues/690
https://github.com/BeamMW/beam-ui/issues/697
https://github.com/BeamMW/beam-ui/issues/691
https://github.com/BeamMW/beam-ui/issues/689
https://github.com/BeamMW/beam-ui/issues/688
https://github.com/BeamMW/beam-ui/issues/687
https://github.com/BeamMW/beam-ui/issues/692
