### ISSUE TITLE
Settings: swap

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#58]
Need to check if anything should be changed according to the new design
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece5c6b06615d48635e24da

Please note that "node:port" input change would be implemented in another task

**Comment by Denis-Asipenko** [comment]
- Change the warning messages to match the design.
![image](https://user-images.githubusercontent.com/45556620/85563310-ef262d80-b635-11ea-9829-124e7b3e8fa6.png)
![image](https://user-images.githubusercontent.com/45556620/85563327-f2b9b480-b635-11ea-9fac-f4a28c998279.png)
![image](https://user-images.githubusercontent.com/45556620/85563344-f64d3b80-b635-11ea-8100-4aaaabfb8de5.png)

- Change the button text to match the design.
![image](https://user-images.githubusercontent.com/45556620/85563540-23015300-b636-11ea-8d7a-a2edec6855ef.png)
![image](https://user-images.githubusercontent.com/45556620/85563550-25fc4380-b636-11ea-9968-9e25288c5468.png)

- The seed phrase is not displayed. The "close" and "copy" buttons have moved down when the user is connected to the electrum.
![image](https://user-images.githubusercontent.com/45556620/85563637-3e6c5e00-b636-11ea-9883-1cb23df209fd.png)

- If the user was connected to a specific electrum node, this address is saved when connecting to a random electrum node.

![14B6C5F7-FB4E-440B-B680-C2C01F07A1B8](https://user-images.githubusercontent.com/45556620/85566273-94da9c00-b638-11ea-927d-4c56c1dcdc30.GIF)

**Comment by Roberrtt** [comment]
1.If user entered the address and port for the node specifics and accepted changes, after switching slider to random node and back. Address and port are erased
Expected:  Address and port aren't erased
![bandicam-2020-08-05-11-54-08-065](https://user-images.githubusercontent.com/50007056/89393211-25fe6180-d713-11ea-8d2b-06320df4963f.gif)

2. When you entered address and port for  specific node, switch  slider to random node and click connect, address and port from  specific node will be shown
Expected: address and port from  specific node doesn't show
![bandicam-2020-08-05-12-12-45-137](https://user-images.githubusercontent.com/50007056/89394829-3b748b00-d715-11ea-813b-aa4fb83088bc.gif)

3. When connected to random node, if switch slider to specific node and back. The address and port  are missing 
![bandicam-2020-08-05-12-16-32-004_1](https://user-images.githubusercontent.com/50007056/89398939-6f9e7a80-d71a-11ea-932b-0b8641297928.gif)

**Comment by Denis-Asipenko** [comment]
1. Open the settings for connecting to the node, connect to a random electrum node - the server is displayed. Go to another screen, and then return - the server isn't displayed.
![320CC873-FC91-4ADC-841E-CA1712C83A66](https://user-images.githubusercontent.com/45556620/91067423-8f4f0180-e63b-11ea-8448-e41159d0b9b7.GIF)
2. After connecting to a special node, server data isn't saved if you connect to a random node\disconnect and switch to connecting a special node again.
![1BD2CE51-BE41-40F4-81B9-7F746D071EFC](https://user-images.githubusercontent.com/45556620/91068557-28324c80-e63d-11ea-93b7-5d14028fd824.GIF)
3. Align "disconnect" button according to design.
![image](https://user-images.githubusercontent.com/45556620/91068701-544dcd80-e63d-11ea-8d5b-e7fd4d85f33d.png)
4. Align status according to design.
![image](https://user-images.githubusercontent.com/45556620/91068862-895a2000-e63d-11ea-9364-301607b105a1.png)

**Comment by KatsiarynaV** [comment]
checked on build 5.0.9512.3115
For p.2 an additional issue is created #158
