### ISSUE TITLE
Receive screen: on the address details screen the amount is displayed in Beam when requesting other currencies

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#581]
**Bug description**
Receive screen: on the address details screen the amount is displayed in Beam when requesting other currencies 

**To Reproduce**
1. Go to the receive screen 
2. Choose another currency (not Beam)
3. Insert an amount
4. Open address details screen

**Current behaviour:** the amount is displayed in Beam

**Expected behaviour:** the amount is displayed in chosen currency 

**BEAM Build number:** 6.0.11019.4111

![gif04](https://user-images.githubusercontent.com/68267190/114023399-7e29cc80-987b-11eb-92a5-91924f340382.gif)

**Comment by KatsiarynaV** [comment]
The wallet closes when deleting the requested amount
![gif06](https://user-images.githubusercontent.com/68267190/114350002-49ff2600-9b71-11eb-9c3d-c90ab8aaac2e.gif)

**Comment by echoby** [comment]
fixed with #584 
https://github.com/BeamMW/beam-ui/commit/b40dbc12f38138ee2d5faaa9f3854a8e6aef0b40

**Comment by KatsiarynaV** [comment]
Checked
