### ISSUE TITLE
Confidential assets swap UI

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#585]
1) Please transform "Atomic Swap" screen to "Swap" https://zpl.io/254e0d8
2) Change "Atomic swap" icon 
![image](https://user-images.githubusercontent.com/47353570/115059057-ad30e580-9eee-11eb-984c-aa48258dc668.png)

3) Add tiles with Confidential assets to balances https://zpl.io/254e0d8
![image](https://user-images.githubusercontent.com/47353570/115059356-1e709880-9eef-11eb-8f73-43fb080e6671.png)

4) Replace columns in transaction table according to updated design https://zpl.io/254e0d8
![image](https://user-images.githubusercontent.com/47353570/115059466-45c76580-9eef-11eb-883f-c008ebbe4d53.png)

5) Add grey icons  next to coins in table. They show what swap it is: assets or atomic
![image](https://user-images.githubusercontent.com/47353570/115059631-7c04e500-9eef-11eb-81e7-4e8e5c32a5b9.png)

6) Remove "Beta 2" icon
![image](https://user-images.githubusercontent.com/47353570/115059703-917a0f00-9eef-11eb-85ae-0847caa0ad76.png)

7) Create ATOMIC swap offer https://zpl.io/aX7GnGx 
Only 1 change here: add "ATOMIC" to title.
![image](https://user-images.githubusercontent.com/7249484/130991883-1586c1fb-a9df-41e1-84ed-4e6803d2d5cc.png)

8) Create ASSET swap offer https://zpl.io/ag39yGD
- Add "ASSET" to the title.
- No need for fee blocks. Show BEAM fee only in the "copy token" block (right down corner)
![image](https://user-images.githubusercontent.com/7249484/131136509-f3125061-00b5-48fb-81e9-596d01b7793c.png)

9) Rename "More details" to "Token details" 
![image](https://user-images.githubusercontent.com/47353570/115060186-43b1d680-9ef0-11eb-8684-4fa42ac6c18c.png)

**Comment by AndreyDyakonov** [comment]
Checked
