### ISSUE TITLE
Make QR code bigger on receive screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#586]
Please make QR code bigger. It is not readable now.
https://zpl.io/2G8AqRj

Bigger size:
![image](https://user-images.githubusercontent.com/47353570/114375691-9a847c80-9b8d-11eb-93b3-34e45a14c64b.png)

Previous size: 
![image](https://user-images.githubusercontent.com/47353570/114375818-bb4cd200-9b8d-11eb-81cd-ede059dff8ae.png)

**Comment by Denis-Asipenko** [comment]
checked
