### ISSUE TITLE
Missing icon in AmountInput + max button

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#588]
1. When only beam in wallet (no asset) amount input doesn't display an icon.

![photo_2021-04-14_17-23-19](https://user-images.githubusercontent.com/12074933/114736018-6906df00-9d4e-11eb-859b-259a16bc7250.jpg)

Should add an icon.

![gnome-shell-screenshot-0P2T10](https://user-images.githubusercontent.com/12074933/114736073-758b3780-9d4e-11eb-816d-a2b46d052733.png)

2. Rename 'add max' -> 'max'

**Comment by KatsiarynaV** [comment]
Checked
