### ISSUE TITLE
Transactions list changes

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#589]
1. Rework transaction list everywhere in the app.
- add column "Source" (value could be "Wallet" for wallet transactions and name of the dapp for contract transactions)
<img width="1044" alt="Screenshot at Apr 20 15-56-58" src="https://user-images.githubusercontent.com/7249484/115359547-5cbccf00-a1f1-11eb-9ceb-dd647997be17.png">
- change the order of columns to the following: Coin, Amount, USD Value, Originator, Created on, Status
Design https://zpl.io/2Gjp7NY

**Comment by chapati** [comment]
Source will be displayed only for new apps transactions. All old apps transactions would have an empty source.

**Comment by Denis-Asipenko** [comment]
When withdrawing coins from the BEAM RED Envelope in the transaction list the source column displays the "wallet".
![image](https://user-images.githubusercontent.com/45556620/115710814-725e0000-a37b-11eb-86ea-0451b11900ed.png)

**Comment by Denis-Asipenko** [comment]
it's will be fixed in the next sprint.
> When withdrawing coins from the BEAM RED Envelope in the transaction list the source column displays the "wallet".
> ![image](https://user-images.githubusercontent.com/45556620/115710814-725e0000-a37b-11eb-86ea-0451b11900ed.png)


checked
