### ISSUE TITLE
Make TX details as dialog

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#590]
Open transaction details in pop up instead of unfolding the transaction list (could be scrollable). 

**1. Wallet transactions with payment proof**
Show info into 2 separate tabs:

1.1. General info https://zpl.io/bzdlAW4
![transaction-detail-v2-general](https://user-images.githubusercontent.com/7249484/124969179-fa89a280-e058-11eb-91cd-9994a1230524.png)

Fields order:
- Sending address
- Receiving address
- Amount 
- Transaction fee
- USD value
- Comment (if empty - hide this field)
- Transaction ID
- Kernel ID

Changes:
- Replace Transaction fee and USD Value fields
<img width="920" alt="Screenshot at Jul 07 12-51-32" src="https://user-images.githubusercontent.com/7249484/124739014-10f60800-df4c-11eb-8a99-5d5cf315cf0c.png">

1.2. Payment proof https://zpl.io/2E4EPAv
![transaction-detail-v2-payment-proof](https://user-images.githubusercontent.com/7249484/124969198-ffe6ed00-e058-11eb-8dc3-2dd25737d006.png)

Fields order:
- Sending address
- Sender identity
- Receiving address
- Receiver identity
- Amount 
- Kernel ID
- Code

1.3 Add coin icon and copy buttons everywhere where relevant (addresses and tx ids, pp code)
<img width="840" alt="Screenshot at Jul 07 12-29-12" src="https://user-images.githubusercontent.com/7249484/124735752-ec4c6100-df48-11eb-860c-6466de0519f2.png">
<img width="816" alt="Screenshot at Jul 07 12-43-48" src="https://user-images.githubusercontent.com/7249484/124737940-071fd500-df4b-11eb-915c-726cb526cb47.png">

**2. Contract transactions (without payment proof)**
https://zpl.io/2p3Br3l
![transaction-detail-v2](https://user-images.githubusercontent.com/7249484/124741687-8ebb1300-df4e-11eb-8a1f-19004e292b31.png)

Fields order:
- Amount 
- Transaction fee
- USD value
- DAPP name
- Application shader ID
- Description (instead of Comment field in wallet transactions (if empty - hide this field))
- Transaction ID
- Kernel ID

Changes:
- Contract ID rename to Application shader ID, move below USD Value field
- Comment rename to Description
- Replace Transaction fee and USD Value fields
- Add DAPP name field
<img width="935" alt="Screenshot at Jul 07 12-34-51" src="https://user-images.githubusercontent.com/7249484/124737061-3124c780-df4a-11eb-989c-db7b81925b10.png">
- Add Confidential asset ID next to CA amounts
- Add coin icon and copy buttons everywhere where relevant (addresses and tx ids)
<img width="974" alt="Screenshot at Jul 07 12-37-58" src="https://user-images.githubusercontent.com/7249484/124737075-3550e500-df4a-11eb-8483-22e53df3721d.png">

**3. In tx list highlight transaction on hover. Open transaction details popup through action menu**
https://zpl.io/2Gjp7NY
![wallet-v10-suite](https://user-images.githubusercontent.com/7249484/124737462-8e207d80-df4a-11eb-841c-c06afd1b3320.png)

**4. External link alert here should be the only place in the wallet where we use popup over other popup**
https://zpl.io/V0rlR0m
![transaction-detail-v2-external-link-alert](https://user-images.githubusercontent.com/7249484/124969226-05dcce00-e059-11eb-9bf9-7048daa130d6.png)

**Comment by gingervik** [comment]
please, update designs

**Comment by alexandrashelenkova** [comment]
The screens were fixed in accordance with the comments above, the designs were updated in the task description.

**Comment by alexandrashelenkova** [comment]
"Sender's / receiver's identity" was renamed into "Sender's / receiver's wallet signature", the designs were updated in the task description.

**Comment by alexandrashelenkova** [comment]
Updated design to avoid disagreements in the screenshots and descriptions above.
USD value field should be below Amount and Transaction fields. Comment about USD rate should be underline USD amount.
<img width="963" alt="Screenshot at Jul 12 15-05-35" src="https://user-images.githubusercontent.com/7249484/125285099-dd045380-e34c-11eb-865e-1141c1467a91.png">

**Comment by KatsiarynaV** [comment]
1. Hide Comment field if it's empty
![02](https://user-images.githubusercontent.com/68267190/125282170-c0055b80-e31f-11eb-98a9-5024cdaa29f2.jpg)

2.Remove payment proof tab for transaction where it’s not available (contracts, waiting for receiver, in progress, failed, expired, cancelled,  sent to own address, sending to own address, received, in progress max privacy, in progress offline, in progress public offline)

3. Remove USD value field. Add the text “For the day of the transaction to the Amount field
![13](https://user-images.githubusercontent.com/68267190/125295457-eb8f4280-e32d-11eb-88a6-0a362b393c49.jpg)
![14](https://user-images.githubusercontent.com/68267190/125295460-ecc06f80-e32d-11eb-80b0-4a28fb15a4c8.jpg)
![12](https://user-images.githubusercontent.com/68267190/125295499-f3e77d80-e32d-11eb-8538-5c06bebd38f6.jpg)

4. Shader ID rename to Application shader ID
![06](https://user-images.githubusercontent.com/68267190/125295574-0792e400-e32e-11eb-8553-928b6b573cd8.jpg)
![15](https://user-images.githubusercontent.com/68267190/125295634-18dbf080-e32e-11eb-8807-f27e8c8a4c78.jpg)

5. Add copy button to the “Confidential asset ID:” field
![07](https://user-images.githubusercontent.com/68267190/125295692-24c7b280-e32e-11eb-86fb-bae9abddba16.jpg)
![08](https://user-images.githubusercontent.com/68267190/125295706-2a24fd00-e32e-11eb-9393-2e59281a0246.jpg)

6. In tx list highlight transaction on hover. Open transaction details popup through action menu – not done
![16](https://user-images.githubusercontent.com/68267190/125296693-39f11100-e32f-11eb-8828-9a30437879e5.jpg)

7. Change the External link alert popup as in the design
![10](https://user-images.githubusercontent.com/68267190/125296797-52612b80-e32f-11eb-819d-adfe5dc130e1.jpg)
![11](https://user-images.githubusercontent.com/68267190/125296816-5725df80-e32f-11eb-9b36-2ad015ba7871.jpg)

8. Remove the blank space
![09](https://user-images.githubusercontent.com/68267190/125296949-77559e80-e32f-11eb-93ab-8ef4f4b34bd0.jpg)
![17](https://user-images.githubusercontent.com/68267190/125297025-89cfd800-e32f-11eb-8347-43c95cf72ec6.jpg)

**Comment by KatsiarynaV** [comment]
1. Remove wallet signatures from general info tab both for sender and for receiver. 
![01](https://user-images.githubusercontent.com/68267190/126314567-0fa8f6fb-56a2-43af-a0fd-07daa78747d7.jpg)
![03](https://user-images.githubusercontent.com/68267190/126314583-4fa3e5cd-6c8d-440e-9878-2268ff30a2d3.jpg)
2. Remove addresses from payment proof
![02](https://user-images.githubusercontent.com/68267190/126314667-0f1b6765-b218-460e-8691-106efd3501ca.jpg)
![04](https://user-images.githubusercontent.com/68267190/126314676-ab7d0af0-1aef-4628-b036-5bfb858282ff.jpg)
3. Rename "sender wallet's signature" to "sender's wallet signature" and "receiver wallet's signature" to "receiver's wallet signatuer"
![06](https://user-images.githubusercontent.com/68267190/126315495-e6240dad-64ff-4d9c-b2bd-8bca75bd17f3.jpg)
![05](https://user-images.githubusercontent.com/68267190/126315511-70f93a97-825c-41c9-8599-2f0e4d58d122.jpg)
4. Remove payment proof for transactions "sent to own address"
![23](https://user-images.githubusercontent.com/68267190/126313857-97f68051-c74f-45d5-ac65-eb100e0141c8.jpg)
5. Rename “Open external link” popup to “External link”.  Change the button “proceed” to “open” 
![21](https://user-images.githubusercontent.com/68267190/126313770-5fcc699c-ed16-4ae1-8e55-7fb6f345283a.jpg)
![22](https://user-images.githubusercontent.com/68267190/126313774-38383d09-1389-4ce6-b1b7-9283f707a3d8.jpg)

**Comment by KatsiarynaV** [comment]
Payment proof: increase a little the indent between code and "close" button (max privacy and offline/public offline transactions)
![32](https://user-images.githubusercontent.com/68267190/126468275-b5ac0052-0bf6-4418-bb2b-04033a8d07e4.jpg)

**Comment by KatsiarynaV** [comment]
Not fixed for max privacy and offline/public offline transactions in assets
![33](https://user-images.githubusercontent.com/68267190/126597181-4c725381-00e5-44dc-a275-e323871ffad7.jpg)

**Comment by KatsiarynaV** [comment]
For transacions without payment proof remove text "general info" 
![35](https://user-images.githubusercontent.com/68267190/126651296-00c69a28-1863-4fb8-be97-ddfe7bfe998b.jpg)
![36](https://user-images.githubusercontent.com/68267190/126651300-0f0e3ba4-fb2e-4689-908c-c54d85ba0f7b.jpg)
![34](https://user-images.githubusercontent.com/68267190/126651308-49f7ac8a-885f-4588-98bf-81392de1f71b.jpg)

**Comment by KatsiarynaV** [comment]
1. The transaction fee amount should be bold and displayed in white color
![37](https://user-images.githubusercontent.com/68267190/126961225-c5a2b348-63e9-4045-83e9-b0040c9a6d2a.jpg)
![38](https://user-images.githubusercontent.com/68267190/126961228-e96bbdbb-3ba4-4f98-a476-fc573462a254.jpg)

2. Add second currency to the transaction fee amount for assets transactions 
![39](https://user-images.githubusercontent.com/68267190/126961601-62341dcc-16a1-452f-838a-2be476d8c4a8.jpg)

**Comment by KatsiarynaV** [comment]
Checked
