### ISSUE TITLE
Display USD value as X.XX (2 digits after dot) and coins as X.XXXXXX (6 digits after dot)

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#591]
1) For USD value let's make only 2 signs after "."
Example: 2.25 USD

Red border - incorrect view
Green border - correct view

![image](https://user-images.githubusercontent.com/47353570/115054350-ce8ed300-9ee8-11eb-8b22-8add2354b03b.png)

2) For coins let's make 6 signs after ".". 
Example: 0.123456 BTC

https://zpl.io/bL9LB3G

Red border - incorrect view
Green border - correct view

![image](https://user-images.githubusercontent.com/47353570/115054863-6b517080-9ee9-11eb-963d-8de9f746ed46.png)

**Comment by KatsiarynaV** [comment]
Checked
