### ISSUE TITLE
Amount not restored from token in receive screen

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#592]
When token is saved to address book, then token menu -> receive.
Receive screen opened. Amount, address type &c is restores. Currency is not.

**Comment by chapati** [comment]
Should be OK, please test.

**Comment by KatsiarynaV** [comment]
Currency is not restored
![gif03](https://user-images.githubusercontent.com/68267190/121501673-1eb97b80-c9e8-11eb-8326-59501adf8478.gif)

**Comment by KatsiarynaV** [comment]
Currency is not restored on the Send screen
![gif04](https://user-images.githubusercontent.com/68267190/122220597-2336d600-ceb9-11eb-9011-36e2cb080e09.gif)

**Comment by chapati** [comment]
This task is only for receive screen. We never modify someone's else address. If your friend gave you address to receive 10 BEAM it would be save in address book exactly as provided, as 10 BEAM, even if you choose to send 10 Yan.

**Comment by KatsiarynaV** [comment]
Checked
