### ISSUE TITLE
Asset's selection lost

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#593]
1. Wallet tab
2. Select asset
3. Switch to other tab
4. Come back to wallet

Nothing is selected. Asset selection should stay as before.

**Comment by chapati** [comment]
1. Send view should not save asset id. Asset in send should be the same as selected here or BEAM if nothing selected

![gnome-shell-screenshot-8CF330](https://user-images.githubusercontent.com/12074933/120964696-5fa55c00-c76c-11eb-911c-6f9fc1627000.png)

2. This task was about saving selection in assets section in the wallet, not in send view. Here for example Shekel is selected but this selection is not saved if you switch from wallet view to another tab and then switch back
3. 
![gnome-shell-screenshot-TI1530](https://user-images.githubusercontent.com/12074933/120964778-82d00b80-c76c-11eb-9787-78b62ca9289d.png)

**Comment by KatsiarynaV** [comment]
Checked
