### ISSUE TITLE
Add asset ID to TX details

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#596]
https://zpl.io/VDgn3o3
For assets with CA add show "Confidential Asset ID" field in transactions details next to amount
<img width="1056" alt="Screenshot 2021-04-26 at 17 25 35" src="https://user-images.githubusercontent.com/7249484/116060392-6c865880-a6b4-11eb-88c5-879985aa0de2.png">

**Comment by Roberrtt** [comment]
checked
