### ISSUE TITLE
Add icon "Copy" to TX details

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#597]
https://zpl.io/2p3Br3l
Add "Copy and close" button in tx details popup (implement after that task https://github.com/BeamMW/beam-ui/issues/590)
<img width="1038" alt="Screenshot 2021-04-22 at 16 17 19" src="https://user-images.githubusercontent.com/7249484/115680895-91ae5a80-a386-11eb-9b07-9effe6a8f5d5.png">

**Comment by alexandrashelenkova** [comment]
Merged with https://github.com/BeamMW/beam-ui/issues/590
