### ISSUE TITLE
Default address has become expiring after open it on receive screen

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#599]
**Steps:**

1. create or restore wallet
2. navigate to the Address book and find the Default address
3. Click on three dots and click on receive button
4. Go back to the Address book
5. open to editing Default address
**Expected:** Default address still be never expired
**Actual:** Default address has become expiring
![image](https://user-images.githubusercontent.com/44496108/115306342-5cc8ba80-a170-11eb-8b9a-dfc119952c16.png)

Also need to remove **Extend** button from Default address edit dialog as never expired address not need to extend
![image](https://user-images.githubusercontent.com/44496108/115307062-5f77df80-a171-11eb-9a32-f5de17692d9f.png)

**Comment by chapati** [comment]
Check also please 

- that after these changes new addresses generated via receive screen expire in 2 months.
- that after receiving transaction to default address it is still never expires, all 2-month addresses should be extended for another 2 months
- that in CLI & API default address is also generated as never expired

**Comment by Sergei-Beam** [comment]
checked
