### ISSUE TITLE
Settings UI: beam node section

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#60]
1. Add peer already exists error
![DeepinScreenshot_select-area_20200608140326](https://user-images.githubusercontent.com/12074933/84023475-d6a8e880-a990-11ea-987a-1d2216478a7c.png)

2. Remote node -> address:port to a single control
![DeepinScreenshot_select-area_20200608140403](https://user-images.githubusercontent.com/12074933/84023591-0952e100-a991-11ea-9c32-5354c7dc1bcd.png)

**Comment by Roberrtt** [comment]
Move the port input fields closer to field name, for Integrated and remote node  as in the design
Integrated node -https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece31fb53feee488e26984b -
Remote node - https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/5ece68fd8d964547a8ba82ec 
![Screenshot_62](https://user-images.githubusercontent.com/50007056/88534212-3e35f880-d010-11ea-88a9-918b2b95bbd5.png)

**Comment by Roberrtt** [comment]
Wallet doesn't switch from integrated to remote node.
Button 'apply changes' doesn't work 
![bandicam-2020-07-27-14-34-29-593](https://user-images.githubusercontent.com/50007056/88537571-7a6c5780-d016-11ea-98dc-dd368d9201a9.gif)

**Comment by Roberrtt** [comment]
Not done:
Move the port input fields closer to field name, for Integrated and remote node as in the design

**Comment by KatsiarynaV** [comment]
For remote node move the port input field closer to field name and change the field name from 'Remote node address' to 'Node address' as in the design
![node settings](https://user-images.githubusercontent.com/68267190/89008394-46917a80-d313-11ea-8b71-3f103baf8c35.jpg)

**Comment by KatsiarynaV** [comment]
checked on build 5.0.94583071
