### ISSUE TITLE
Add transactions list on the Dapp Store screen.

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#602]
1. Add transactions list on the Dapp Store screen. 
https://zpl.io/2v3yMy7
https://zpl.io/aNxBwBD

- the list should show only contract transactions
<img width="1044" alt="Screenshot at Apr 20 15-57-29" src="https://user-images.githubusercontent.com/7249484/115359608-6e05db80-a1f1-11eb-8edd-808b40a2076e.png">
- the list should be foldable (default state - folded)
<img width="1047" alt="Screenshot at Apr 16 13-03-41" src="https://user-images.githubusercontent.com/7249484/114974082-4db5e400-9eb4-11eb-990c-14cbbac6e124.png">
- the list should unfold only for a part of the screen (30% of the screen)

2. Add transactions list in every Dapp where needed
https://zpl.io/29mN0BY
https://zpl.io/aR4mpyg
https://zpl.io/br3m1lW

- the list should show only transactions of chosen contract
- the "Source" column should be hidden
- Transactions details should have "DAPP name", "Application Shader ID" and "Description fields".
<img width="968" alt="Screenshot at Apr 20 15-58-50" src="https://user-images.githubusercontent.com/7249484/115359700-837b0580-a1f1-11eb-9bff-cc90c64d2f85.png">
- the list should be foldable (default state - folded)
- the list should unfold only for a part of the screen (30% of the screen)

**Comment by Roberrtt** [comment]
1. Please change from 'Shader Id' to "Application Shader ID"
![Screenshot_373](https://user-images.githubusercontent.com/50007056/123664149-c1bf2180-d83f-11eb-85dc-f990205c368d.png)

2. Make the entire zone clickable (highlighted in red), now only in the middle(highlighted in green)
![Screenshot_367](https://user-images.githubusercontent.com/50007056/123664182-caaff300-d83f-11eb-8729-7cd41dd8f83e.png)


3. Change the direction of the arrow, as the table opens up and closes down.
![Screenshot_374](https://user-images.githubusercontent.com/50007056/123664210-d00d3d80-d83f-11eb-9d36-10b5cdf8543d.png)

![Screenshot_375](https://user-images.githubusercontent.com/50007056/123664205-cf74a700-d83f-11eb-850e-b5310df821f2.png)

**Comment by chapati** [comment]
1. Is correct now, it is Shader ID. Application shaders do not have ID.

**Comment by Roberrtt** [comment]
checked
