### ISSUE TITLE
Remove "off" position from switcher in Settings "show amounts in"

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#603]
Please, remove off position from this switcher
it should be only USD/BTC
<img width="462" alt="Screenshot 2021-04-21 at 07 24 29" src="https://user-images.githubusercontent.com/28015224/115496569-9e418e80-a272-11eb-9c6f-4bb2368cb840.png">

related to https://github.com/BeamMW/beam-ui/issues/587

**Comment by gingervik** [comment]
please, compare design with https://github.com/BeamMW/beam-ui/issues/595

**Comment by KatsiarynaV** [comment]
Checked
