### ISSUE TITLE
Dapps notifications - change text + button

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#604]
Design https://zpl.io/25X0oln 
1. For DAPPs transactions rename "contract transaction ..." to " dapp transaction ..." in header of notifications.
2. Change "details" button to "open the app" button (click on that button should open Dapp's transactions screen with unfolded transactions details https://zpl.io/br3m1lW)
<img width="1046" alt="Screenshot at Apr 26 17-12-26" src="https://user-images.githubusercontent.com/7249484/116059086-12d15e80-a6b3-11eb-8bf3-dc52c7dc4be4.png">

**Comment by gingervik** [comment]
why dapp-app?
what if app/dapp was removed?

**Comment by alexandrashelenkova** [comment]
Let's keep "dapp" everywhere. Fixed the design https://zpl.io/25X0oln
<img width="810" alt="Screenshot 2021-05-28 at 16 25 21" src="https://user-images.githubusercontent.com/7249484/119990720-42012580-bffb-11eb-895c-946442fb8d9f.png">

**Comment by KatsiarynaV** [comment]
Rename "app" to "dapp" and change the icon as in the design
![01](https://user-images.githubusercontent.com/68267190/121854927-6f3c1c00-ccfb-11eb-8e2b-bf101de05a85.jpg)
![02](https://user-images.githubusercontent.com/68267190/121854928-6fd4b280-ccfb-11eb-9326-fa6b7d974950.jpg)

**Comment by KatsiarynaV** [comment]
Make the icon as in the design
![04](https://user-images.githubusercontent.com/68267190/121887821-e71c3d80-cd1f-11eb-8ab3-b15fedaf8a74.jpg)
![03](https://user-images.githubusercontent.com/68267190/121887825-ea172e00-cd1f-11eb-9bbe-2f5d80ada5a7.jpg)

**Comment by KatsiarynaV** [comment]
click on the "open the app" button should open Dapp's transactions screen with unfolded transactions details https://zpl.io/br3m1lW - added to the task #361

**Comment by KatsiarynaV** [comment]
Checked
