### ISSUE TITLE
Send screen: fee is displayed incorrectly

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#608]
**Bug description**
On the Send screen fee is displayed incorrectly for transactions with shielded coins

**To Reproduce**
There are some shielded coins in the wallet
1. Go to the send screen
2. Click the "max" button
3. Check the sending amount and the fee

The amount to send is calculated correctly, but the displayed fee is incorrect (in my case the fee should be 0.020001)

[wallet.zip](https://github.com/BeamMW/beam-ui/files/6376840/wallet.zip)
Password: 1

![03](https://user-images.githubusercontent.com/68267190/116062712-d5f27100-a68c-11eb-8edc-04c88bb7b01c.jpg)
![05](https://user-images.githubusercontent.com/68267190/116062715-d68b0780-a68c-11eb-9881-d49fd10fcd05.jpg)

**Comment by chapati** [comment]
Fixed on RC branch only. Will stay on testnet for a while.

**Comment by KatsiarynaV** [comment]
Fee for transactions with shielded coins is incorrect in the transaction info
![06](https://user-images.githubusercontent.com/68267190/116358824-bc753480-a806-11eb-96a0-c88aeaa0b85a.jpg)
![07](https://user-images.githubusercontent.com/68267190/116358828-bd0dcb00-a806-11eb-95c0-4ff677aec7b3.jpg)

**Comment by KatsiarynaV** [comment]
Checked
