### ISSUE TITLE
opengl32sw.dll

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#610]
please, revert opengl32sw.dll in installer and more.

from our CMakelists:
            install(FILES ${CMAKE_PREFIX_PATH}/bin/opengl32sw.dll DESTINATION .)
            install(FILES ${CMAKE_PREFIX_PATH}/bin/libEGL.dll DESTINATION .)
            install(FILES ${CMAKE_PREFIX_PATH}/bin/libGLESv2.dll DESTINATION .)

**Comment by Webonnix** [comment]
Done
