### ISSUE TITLE
ExchangeRates - fixes & updates

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#611]
1. Remove Fork2 protocol & implement TODOs

2. Revert tests to single version of rates (for F3, commit d1800594c132578f6220b810977c77bac192c477 implemented test for both old & new)

3. Now the same rates come to the manager and are parsed dozens of times on app start. Need to check if it is possible to reduce number of incoming messages.

**Comment by anatolse** [comment]
Please, re-check:
- swap offers
- exchange rates
- broadcaster

**Comment by Roberrtt** [comment]
checked
