### ISSUE TITLE
Applications: add minversions

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#614]
Add minversion to appslit json. Show update warning if client version is too low.

**Comment by chapati** [comment]
Added minApiVersion to appslit.json.
If api version is not supported the following is shown:

![gnome-shell-screenshot-2Y6L50](https://user-images.githubusercontent.com/12074933/123290728-2d408080-d51a-11eb-8e2a-ff8a39589b46.png)

Talk to me, I'll explain how to test.

**Comment by Sergei-Beam** [comment]
checked
