### ISSUE TITLE
Applications: dev enchancements

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#615]
Add dev mode (settings.ini) + refresh button

**Comment by chapati** [comment]
Partially done. Setting in settings ini added, refresh button added.

**Comment by chapati** [comment]
![gnome-shell-screenshot-TFGR90](https://user-images.githubusercontent.com/12074933/133776827-eafbe909-a8da-4f8c-b119-2581f1cdc9f9.png)
Fixed. 1) Dev mode Refresh button added. 2) On refresh apps are correctly reloaded

**Comment by KatsiarynaV** [comment]
Checked
