### ISSUE TITLE
Linux-when changing the file name, the update is incorrect

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#616]
If the user changes the file name, a new folder is created after the update(when migrating from 5.1 or 5.2 to 6.0), which doesn't transfer the node and settings.ini files.

**Comment by chapati** [comment]
As we have discussed

1. Folder name should be 'Beam Wallet', 'Beam Wallet Masternet' &c
2. 5.2, 5.3 folders were without space. v6.0 should find and migrate wallet.db correctly in this case
3. settings.ini in case of #2 would be lost, wallet will be unable to connect. As we have discussed should open sperate task for this situation for 6.1 - show start ui to choose settings. 
4. Should take into account https://github.com/BeamMW/beam/issues/1570 with saved peers in wallet.db. Ui has no chance to know about these.

**Comment by Sergei-Beam** [comment]
checked
