### ISSUE TITLE
Applications: consider convenience functions

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#617]
It might be a good idea to add some useful function for UI accessible in apps, for example:

isConnected
isLocalNode
getWalletVersion
&c.

**Comment by chapati** [comment]
We've added all the new stuff to the API.
Here are new changes described:  https://github.com/BeamMW/beam/wiki/Beam-wallet-protocol-API-v6.1

**Comment by Roberrtt** [comment]
event : id_sync_progress
Incorrect transmission of the value to the total.
If the total is the received new block for sync. Then in the screenshot we see that total =2 , and after total=2 and completed=2, the height changed by 1 block and not by 2
[event_logs.txt](https://github.com/BeamMW/beam-ui/files/6936724/event_logs.txt)
[api_21_08_03_16_14_41.log](https://github.com/BeamMW/beam-ui/files/6936725/api_21_08_03_16_14_41.log)
![Screenshot_437](https://user-images.githubusercontent.com/50007056/128312796-e797e6d1-0b82-4bc3-9b5b-64ba8c96f87f.png)

**Comment by chapati** [comment]
Since wallet_status is blocked for dapps there is no way to get blockchain height. Need to add get_system_status / get_system_height.

**Comment by chapati** [comment]
> event : id_sync_progress
> Incorrect transmission of the value to the total.
> If the total is the received new block for sync. Then in the screenshot we see that total =2 , and after total=2 and completed=2, the height changed by 1 block and not by 2
> [event_logs.txt](https://github.com/BeamMW/beam-ui/files/6936724/event_logs.txt)
> [api_21_08_03_16_14_41.log](https://github.com/BeamMW/beam-ui/files/6936725/api_21_08_03_16_14_41.log)
> ![Screenshot_437](https://user-images.githubusercontent.com/50007056/128312796-e797e6d1-0b82-4bc3-9b5b-64ba8c96f87f.png)

Here was a mistake in docs, total is not number of blocks but total number of sync requests / objects to download: Utxo, Kernels, States, Block body &c. So here everything is normal. This number can be the way bigger than total number of new blocks. Docs are updated.

**Comment by Roberrtt** [comment]
checked
