### ISSUE TITLE
v5.3.10410.3657 does not work on macOS Mojave

### ISSUE THREAD

**Issue by jonathancross** [BeamMW/beam-ui#618]
![Screen Shot 2021-05-10 at 5 09 27 PM](https://user-images.githubusercontent.com/5115470/117681751-b1c98080-b1b2-11eb-9665-2678ff27722e.png)

**Comment by htcl2k20-PMN** [comment]
same here on macOS 10.13.6 (High Sierra)

**Comment by jonathancross** [comment]
Friendly ping @chapati @gingervik

**Comment by gingervik** [comment]
Please, update your mac os

**Comment by jonathancross** [comment]
@gingervik I saw _"Return ability to run Beam Wallet on old versions of Operation Systems"_ in the [v5.3.10410.3657 release notes](https://github.com/BeamMW/beam-ui/releases/tag/beam-5.3.10410.3657) -- but it seems this was not meant to apply to macOS Mojave?  Was there some discussion of dropping support?

There are good reasons for staying with this version of macOS as newer versions break compatibility with many apps including Adobe Creative Suite.

**Comment by htcl2k20-PMN** [comment]
@gingervik - I saw the same as Jonathan and share kind of similar issues upgrading. 
I know Apple makes it difficult to build applications for not cutting edge OS versions by intend, but apps should not require them if there is no specific reason (absolutely needed GUI libaries or whatever). 
But to accomplish this one needs to build on an older Mac OS system, there are some "compatibility" switches but as it seems they don't work as intended.
The "old OS versions" statement was maybe meant for Linux (where it works) and/or Win* (no idea)?
