### ISSUE TITLE
beam-wallet.cfg for Linux 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#619]
Give me info about beam-wallet.cfg for linux

**Comment by chapati** [comment]
Fixed beam-wallet.cfg inside appimage

As we have discussed

1) The most easy way is to create xxxx.AppImage.home folder near the executable
2) Unpack as before for .deb (--appimage-extract) - added beam-wallet.cfg to the package

**Comment by Roberrtt** [comment]
checked
