### ISSUE TITLE
Cannot see the letters correctly

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam-ui#623]
<img width="915" alt="Screen Shot 2564-05-13 at 15 07 45" src="https://user-images.githubusercontent.com/44961099/118097845-6525b580-b3fd-11eb-84fc-0f14af905fe4.png">

**Comment by chapati** [comment]
Please provide more info - OS, selected language, branch (testnet, master)

**Comment by sasha-abramovich** [comment]
@chapati Testnet branch, M1, MacOS Big Sur 11.3.1 (I use the stable version, **not** beta), English language

**Comment by anatolse** [comment]
it seems we have https://bugreports.qt.io/browse/QTBUG-89379 here
