### ISSUE TITLE
Change the text in the node settings if the address and port fields are empty

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#628]
For example, in the case of a task https://github.com/BeamMW/beam/issues/1570 when our fields are empty, you should show the prompt "Please enter the address", " Please enter the port" rather than display the error that the address is invalid.
![image](https://user-images.githubusercontent.com/45556620/118305383-8ca97a80-b4f0-11eb-8f4a-018274f88912.png)

**Comment by kazaryan-t** [comment]
Checked.
