### ISSUE TITLE
Unable to Start GUI on Ubuntu 20.04 - unrecognised option 'Fork1'

### ISSUE THREAD

**Issue by breadsax** [BeamMW/beam-ui#634]
I compiled from source code successfully. Then cd to ui directory.

Then run ./BeamWallet and I receive a pop-up window as the GUI attempts to start.

The window says unrecognised option 'Fork1' and an option to click OK.

If OK is clicked the program closes.

Please help!

**Comment by breadsax** [comment]
Inside of the beam-common.cfg file in the beam-ui/ui directory there are two options listed that are causing this:

Fork1 = 10
Fork2 = 20

If I remove these from the .cfg file that fixes the issue. 

Why are these here in a mainnet build?

**Comment by breadsax** [comment]
After finding that out I had another error because the SFTex.qml file in the beam-ui/ui/view/controls directory wants to:

import QtQuick 2.15

That means that Qt 5.15 should be installed. Or I can try to change that to import QtQuick 2.12 and it should launch.

Why are the build instructions not updated for this? Also, 2.15 is not supported with Ubuntu apt-get repositories, even in Ubuntu 20.10

**Comment by breadsax** [comment]
I believe what is causing the unrecognized option 'Fork1' message is because I had previously ran the executable after calling cpack to create a deb file and then installing that. I have tried to build again without running ./BeamWallet first and instead called cpack, installed the deb, and then it ran without the message.

However, I'm still having issues with the change to Qt version as the code referenced above calls to import QtQuick 2.15. I'm creating a new issue to address that as it is a separate issue.

**Comment by anatolse** [comment]
Hello! beam-common.cfg file is for masternet only. It shouldn't be in installer. Did copied it manually or get during installation process?

**Comment by anatolse** [comment]
> After finding that out I had another error because the SFTex.qml file in the beam-ui/ui/view/controls directory wants to:
> 
> import QtQuick 2.15
> 
> That means that Qt 5.15 should be installed. Or I can try to change that to import QtQuick 2.12 and it should launch.
> 
> Why are the build instructions not updated for this? Also, 2.15 is not supported with Ubuntu apt-get repositories, even in Ubuntu 20.10

Since Qt 5.12 has QtWebEngine  it should be ok to switch to it.

**Comment by breadsax** [comment]
@anatolse It does need Qt 5.15 to compile as the code is trying to import QtQuick 2.15 after this change:

https://github.com/BeamMW/beam-ui/commit/72956f2940c885740f76e07a2c64640274e83ab3#diff-89346295e912f2ca83b244e2a96547cdcfe9a22e93fe7fdedd9f21f71a91ee5c

I created a new issue to address that since the original issue was indeed the binary trying to run in masternet rather than mainnet. See new issue created here:

https://github.com/BeamMW/beam-ui/issues/638

Thank you!
