### ISSUE TITLE
6.0.11638.4326 - Windows GUI Wallet, can't create new non-expiring mining addresses?

### ISSUE THREAD

**Issue by cryp-tog** [BeamMW/beam-ui#635]
I can't for the life of me figure out how to create a new mining address that is durable and doesn't expire.  I'm probably doing something really dumb.  Help a miner out?

**Comment by cryp-tog** [comment]
@ya-shy let me know if I can help test/beta/whatever.  I am happy to test and work with the team to create a good product.  :)

**Comment by ya-shy** [comment]
Hello!

Please kindly note, that the address will remain active as long as it is used. so although it doesn't say permanent, it can still be used for mining. If you still would like to double-check the exp. date, just in case, you can always go to the Address book, click on 3 dots, edit address, and there you will have all the needed information. By default, the wallet is active for 2 months, but the exp. date gets updated after every successful transaction. 

And thank you for your interest, we will reach out in case additional pair of hands would be needed! 

Best regards!

**Comment by cryp-tog** [comment]
The old addresses I created with the v5 wallet still work, but I am not able to create new durable mining addresses in my v6 wallet.  They all expire quickly.  Also, copy/paste doesn't copy the short address, it copies the really really long one that none of the pools seem to be able to handle, but that's a separate issue.

**Comment by ya-shy** [comment]
If you are currently using a v6 your addresses will be active for at least 2 months (if it is not used more often, as described in the previous comment), you can check the exp. date in details. As per the copy option, please make sure to put your mouse on the address and click the right button, it will select it all and will give an option to copy. 
If you have more questions related to addresses or any specific issues you are free to drop us an email at support@beam.mw and we will look into it.
