### ISSUE TITLE
New design for Side menu. Part 1. Small reorganization

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#637]
Design: https://zpl.io/am3g4n9
![image](https://user-images.githubusercontent.com/47353570/120364676-36bd3b00-c316-11eb-8aa4-9e7f7c7b39d1.png)

Top part: Wallet, Swap (replace with new icon), Address Book, Notification. Add separator between Notification and Dapp Store icon.

**Comment by gingervik** [comment]
hello @dariatarakanova 
I have a question about the beam exchanges button which was added too many weeks ago. 
Did you decide to remove it or just forget about it in new design?
<img width="1432" alt="Screenshot 2021-06-16 at 13 59 36" src="https://user-images.githubusercontent.com/28015224/122207793-2fb43200-ceab-11eb-944f-084adce4f952.png">

**Comment by dariatarakanova** [comment]
hi @gingervik 
yeah, we decided to remove it

**Comment by gingervik** [comment]
please, transform to 2 separate tasks

**Comment by KatsiarynaV** [comment]
Checked
