### ISSUE TITLE
Can't mine to v6 Identities or Addresses

### ISSUE THREAD

**Issue by cryp-tog** [BeamMW/beam-ui#639]
If you send me a private message I'll share the identity and screen shots of the wallet in question to you for troubleshooting.

The user:
- Created a new address & identity in v6 wallet
- Tried mining to the address, it is not recognized and fails hard
- Tried mining to the Identity, it is accepted by LeafPool
- Payouts from the mining pool do not make it into the wallet, they get rejected as "Waiting for Miner's Wallet" as though the wallet is offline
- Tried a rescan 
- Failed back to a v5 address

**Comment by cryp-tog** [comment]
Leafpool updated their wallet last night, no change.

**Comment by cryp-tog** [comment]
Tried again post-hard fork.  Still can't get the beam.

Here's the identity in the wallet:
![image](https://user-images.githubusercontent.com/82237817/121816834-80c1ed00-cc43-11eb-8888-7140d825bf45.png)

and here's the mining pool:
![image](https://user-images.githubusercontent.com/82237817/121816844-933c2680-cc43-11eb-9b41-a0e0de95eaac.png)

**Comment by ya-shy** [comment]
Hello!

Please kindly note, that in order to be able to receive coins you need to use an Address, which is not equal to the mentioned Identity. Please make sure to click on three dots (under the page with your Active Addresses book) from the right and choose to Receive, it will redirect you to the page with detailed information on the address you are about to use (the QR code and the address itself under it). 

Please let me know if you will have any further questions. 

Best regards, 
Beam Support Team

**Comment by cryp-tog** [comment]
Nope, it's not working, leafpool isn't recognizing the address:

![image](https://user-images.githubusercontent.com/82237817/122026444-d3a8bb00-cd8f-11eb-9e15-9f67b1b6fb19.png)

**Comment by cryp-tog** [comment]
I should add- the address has not expired.  It expires on 7/26/2021.

**Comment by cryp-tog** [comment]
A new address has been created, there are miners running against it now, we'll see if it works, but this is really frustrating.  I feel like I should contribute to the documentation when this is resolved so others don't have these troubles.

**Comment by cryp-tog** [comment]
Ok, the SBBS Address of the same address (that is not expired) has miners on it, it will take an hour to carve enough Beam from the pool to test payment. We really appreciate your help.

**Comment by cryp-tog** [comment]
The miners have over a beam unconfirmed, waiting for confirmation.

**Comment by cryp-tog** [comment]
Yup, that did it.  SBBS Address is what people need to use for the mining address.  I'd be happy to write the documentation, if it helps?

**Comment by cryp-tog** [comment]
Using the long address does work as well, but it changes anytime you look at it, so SBBS address is definitely the way to go.  For the record.  We're done here, again, thanks for all the help.
