### ISSUE TITLE
Send screen: remove regular/offline switcher if old offline address pasted

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#641]
Please remove "Transaction type" block if old offline or regular online address was pasted

![image](https://user-images.githubusercontent.com/47353570/119942566-acce4480-bf9a-11eb-966e-144a2cd0faf8.png)

**Comment by sasha-abramovich** [comment]
@dariatarakanova Same should apply to the old SBBS online address

**Comment by chapati** [comment]
This is already implemented. Please test.

**Comment by KatsiarynaV** [comment]
Irrelevant

**Comment by KatsiarynaV** [comment]
The "Transaction type" block appears if old offline address is  pasted. If the old offline address is saved to Contacts after updating the wallet this address is still saved in old format and the user can copy it. Sending to these addresses need to be checked
![04](https://user-images.githubusercontent.com/68267190/125301760-f5b43f80-e333-11eb-8e3e-6c603065f6a0.jpg)
**Address:**
51su6ZRjAm2AFwNSXJKyZJAeCYKXLPwfPB6nQGeP1FbTKjc4JybMeTZGxUUo4sWcUyZNFdUx6pUw79JtHw7XaVNw7nGYJQTkNvStdANCwTGXzbv8DJytngMAKcP7CHBxkuho2VBYvWCsuUCjbHtSbDXzzTpVvC8j781zEfKi9bQxFKcLFdi58y9bN1z2gJGN9zP3fR67ijWjNFBE5TFZL7iboxYqXRN8F3QQB1YDUCPLo4uBHPM2F9GExUxgTVYLt9vg3AnSP3rMY3ZhRzvfqeNSMVY384HtZLBVgaSHgNMyzUkehSPuVdQ6mxxpUq7b8Lyq733YAd4SsaPZwmHkYmiRbnrcAXScRGBgwdn271Mv3Gg4qfQf1HqXjYuJ1C9cfc7BNPFj55U9TCHg4LrMCbwQBS4iGsCwhYjABZdHux835utqf11i7CF2Gg1zVGZ87qBFfBa8n2FoymxzEkRoLeMjndhYo57jq8C4xQTEzz3HWg6ia6ucTJnMkVxA7pwm7M4bQvsKqNUYHaoFsMa8eWdysD8T8NZDh8icJW2CT3KLeA5camKkmVy97AfaC2d9Guooxcif5wvDw8jMv21fUmxLytbwaTDneinjdiFvdu6rdFMABWZVUSaf1bwVnecevH2QkuvL7JYi2BRRKbG5VLz9EWu52UVQDaBHUSuXzDFQk1Yk9Tirt7AvMfpGLxkTukpvuG8kZgbEzKeX5WKkGrG9uE6aX8dnYuqh9Fy6y4QpUemBnVURttWvo7uVK7GD5goh9DnoTBV3gGRgQAwyxkiZ9W9xNJawR5Wx85AKibATbWtBQ7urs9WAGH11Jxv1HcqKKLDfg4KCesaZSeHUPJ2quEcohLtbe6bx2YXszd8j6mug59uxpoLaWFF5V3kEbB8VWdSpWkK63jpXvQDsKcSfv6PbLVeCnfCqNUuEpdi4GRmDCcoF9YR8JHtb8DkziDxJNUaHY2S6M7KwoxCw5rCgJU1sfStv21BPCRGLVix5wpJatrtjBkscDPdZwYCqUkFg3pXzY3PLYXHHQ7ACE4K1CUcrqDk9kktzEZyvwEwUEooHCyfdaQa51uofoGT1vJDQVPqU2HAbqMNfV6m2mELUtdDqhyiDx73VvCttaDdzrJzS4Fo2C5nzVhwb9f4MkJDHqzLfUsipgQT44gvPNFpjNsLEQsvn9imHdeZfF77yWcYsmtegUaWJP2MLbyiBqQMEAuj4kdhF5MNDFjnce7VpTP1vHGymZh88rV3JbpMPp73iDgMmJLG9b7mTZrSsAC2fgoGqKpkdpr9wqSp6vgAjvJmNNZfk2wJpAEuVssqGCXEP74CyKcBHHkxe7qsMe2imPDiKM8Jn49iHZsDse4GtNn6QaxWa99Ev9Gunb3u947MNLkm6FVU9jFiQNX4EbDRzKgRHU6rbnrD38bbU8Nhm4k3bWwfbboNkevPXnyv9E2AyD84pjviG75QGer6jLdoHAZth1qM9TWckzAj66uJafZNHEvgYw7JSsG2Eh6h66tSZ7V7GW2mkxYg7Ydn3PYCe5es8pYgrBxRYN35YWTPyioYqaNzXiVyYqTxcFchEEnfJh2HWK1Na25rNFrX4QZCWy6e8vjbJWNSznw6QLhNe88dxuv7a91PMkWwgg32LSAAAL1FniofCHjdvfBMwNw4AHtVmGN37EgGmR41PLki6erQB7ewMSQayEThchcWtPsEe3fV3i32aFa6pWxKuViMxbxaDMvYm3vfeVCJFkLQuyD6VEcnRV8Sb4kcYmukTQSXCoWRu6nxoU5G9Yuos8PdZ2uTyXPrDUxLbX2xLQBzPjmuVN5JjYJytCcmRJHHKejQDzXh5pg76JXRfX7MJZjwmJX8C88znP7Ye9QXqkhHTuuQSEShb7UUP81rfkUgv2zh1DvWYN7idraq57usHQuwXAjn3dvJkSbHaCNfMCxfCi12hKMcRLAJDuJDN69wqyFXRw9LmtRhGWaqKdZMJKC1m3Uh5VZ9cgZGSw9Jj2urQRhLPqTnv5JGZTBwDrsq5tYvdYVRTciR1ubP5o1Lj1pzpVmuW3Qf2CcuBgv3tiTXVhNVtgPWMXC21Zeuuk9PcEP7UahLCiVP8ZgNxgyibnYHHWNhKmAT9nbCTK1yejjXxMDSt6gxnWWXXmnFKHy5PKsY8MJqDkAfRxc88LZPrfsDtwBAgkmAa9TbZCRVj7voajYco15DgcL2BaooapyTB56BLSsXtCm34Hxves6sr1z3LEbuoiZJBC3Zz4zJAYJiVMwsr9wkcE9J8DK7VFhoWKM8wxFpy5cHUBq7K99A7uT4sC4gB7EGmUGKoQfvGHVYvQxFGpRBTgE7SkmCpcgEhxvVeWct38XixUNAK9GZgRoiRVWSEcSFtboTJXUQmcYk66LTUJEvBPExfrHz26ibwm8m1mEFDankEFR27ooPcZiPtXSEUE54S3opE1L3gZouSDr3icJx1p3krvCrvRFRsfNH4Kr3bku2RoXQgy8g4RXkWfSNApfVEHF3jjf7nsNM4epYzs12c6Y7QTNR8doYBoqbSeJxje4DUAjxcM79XQ88Zz4SkWo7GMHzfRez7vxz4iXFGrgwD2dt4LMmDSEcqm25RhrDeKmaKqQF3tCTN1BseBiawSXkgbhwxhC27Cge72khLhRshcXjrHYCyEfqX53EvtuXYxRqJZDbCgNdWPxnBjVR2a2tFBhuYq8QRV3wLpjmcahCrBMNEws6J6wnjKzJzmsQV3tTpbKMcP4v3dKFFGNBnct8EVjS8dhXRegEGg6vEbNuA83kQn2d6DT2WXKdBPMr4YadveCgsQH3Y6UqU6MiYVFnCKDwE7q6o8Qe6jNcq6M5Kh5FYSV6AzMMgRCxG76HArsTsDqSfKJAyWd4BfQ65dapjbeBMATNXaN5JeU6rt4AXjgMzW8eJhFwmLLui7ceTByyTfEWvdCRTv3R3DJq61cWneXdBQ22Qjc9U3esXvVdYWd2ZtWc7ZtkkZWjyxKzxGjPRbBcpCTEbuzP3vz8Lt8FvbpYhcrtCx6MGL3egCC1tSMta1kJGz4uFqthrNtdaFgnJ4tCwhpLTviABMyUtKxJ4ajMYv9Di2vFfycptkE1ih2RSaFBqsrnNGi6GashaAoFzdH4j9riWFXxc5zRFZmfxb1QvfLJiBbsvF7KcKQ7iR51uBKV2wuvLQrxtigSnRVpUvqgQgETvRsA7NCrMSfZjAXYpQsVi1yZQqrYKm5pot

**Comment by chapati** [comment]
This is cancelled by romanov.
