### ISSUE TITLE
Add Show UTXO and Blockchain height to Utilities settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#645]
1) Remove UTXO screen and icon from menu

2) Add Blockchain height and Show UTXO to Utilities settings https://zpl.io/aBJr0wO
![image](https://user-images.githubusercontent.com/47353570/124457911-02b1bb80-dd95-11eb-9047-14079c7696ba.png)

3) Show UTXO popup https://zpl.io/boJnp6W
![image](https://user-images.githubusercontent.com/47353570/124457806-e746b080-dd94-11eb-8655-d361ddaef018.png)

**Comment by gingervik** [comment]
need to discuss with @beam-mw

**Comment by kazaryan-t** [comment]
1. In accordance with the design https://zpl.io/boJnp6W, statuses on the UTXO popup should start with lowercase letters.

![Beam Wallet Masternet 2021-07-12 13 50 49](https://user-images.githubusercontent.com/68247034/125276295-bdebce80-e318-11eb-9ad6-f899dbdf3ab5.png)

2. The status **maturing** should be in white color.

![Beam Wallet Masternet 2021-07-12 13 55 23](https://user-images.githubusercontent.com/68247034/125276216-a3195a00-e318-11eb-8c5d-4554c5720ff6.png)

**Comment by kazaryan-t** [comment]
Checked.
