### ISSUE TITLE
The wallet sees small shielded coins

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#647]
**Bug description**
Since the shielded dust is displayed on the wallet balance, accordingly, they are taken into account when sending all coins.
The transaction in which the dust will be taken into account will fail.
According to this task, the wallet should not see small amounts of shielded coins.https://github.com/BeamMW/beam-ui/issues/181
![image](https://user-images.githubusercontent.com/45556620/121002372-f5ed7800-c794-11eb-8c11-cf0475e22eaa.png)
![image](https://user-images.githubusercontent.com/45556620/121003919-bb84da80-c796-11eb-8dca-d1791a15ec3c.png)

**Comment by echoby** [comment]
Not a bug. After HF3 fee will not charge from shielded inputs.

**Comment by Denis-Asipenko** [comment]
not relevant after HF3
