### ISSUE TITLE
Change "Scalable confidential cryptocurrency" to "Confidential, fast, easy to use" - REWARD 150 BEAM

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#65]
https://zpl.io/VY1rk5k
https://zpl.io/aR9xERn
https://zpl.io/bAq0P56

change it everywhere it appears

**Comment by anatolse** [comment]
1) Open \ui\view\controls\LogoComponet.qml
2) replace //% "Scalable confidential cryptocurrency" with "Confidential, fast, easy to use"

**Comment by SomethingGettingWrong** [comment]
I put in a pr for it.

**Comment by elitedev1314520** [comment]
Is the Issues still open?
I would like to fix the issue.

**Comment by Denis-Asipenko** [comment]
The issue has already been resolved and is under checking.

**Comment by Denis-Asipenko** [comment]
checked
