### ISSUE TITLE
Default confirmation

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#650]
Add confirmation setting in settings screen, add statuses for transactions (sending 1/10, receiving 1/10, etc...)

**Comment by gingervik** [comment]
New details:
- confirmations should be shown only for regular txs
- if the user changes the number of confirmations in settings - it applies only for future txs, not for the current ones


Waiting for answers for the next questions from @sasha-abramovich 
1. how should tx details look like if the user sets 0 confirmations in settings? should we show 0/0 or remove this info at all?
2. what should be the max number of confirmations that a user can set?

**Comment by sasha-abramovich** [comment]
_how should tx details look like if the user sets 0 confirmations in settings?_ the confirmations' line should not be displayed
_what should be the max number of confirmations that a user can set?_ let's set it to 10 now, if users will complain we can always increase it later.

**Comment by Sergei-Beam** [comment]
checked
