### ISSUE TITLE
Recommended fee rate from btc/ltc/qtum blockchain

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam-ui#66]
1. Remove default fee from settings

**Comment by Sergei-Beam** [comment]
Create Swap Offer - fee errors - when wallet cant show fee rate from network https://zpl.io/VqoEKeG
![image](https://user-images.githubusercontent.com/47353570/89016564-98d99800-d321-11ea-891f-e0cc0ba69b81.png)

Need to check these errors here

**Comment by Sergei-Beam** [comment]
checked
