### ISSUE TITLE
Add ETH rate to wallet

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#660]
Please add ETH rate to settings and wallet itself https://zpl.io/aXA0vLE

![image](https://user-images.githubusercontent.com/47353570/122737556-d290f580-d289-11eb-9820-b5629b006277.png)

**Comment by iscander01** [comment]
added beam-eth rate to rate notification script

**Comment by Denis-Asipenko** [comment]
checked
