### ISSUE TITLE
Update design of input fields

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#663]
Please update the design of all input fields in the app to be compliant with how they look in DAPPs.

All the states for input fields are here https://zpl.io/2EGjeQv
![image](https://user-images.githubusercontent.com/7249484/132122914-b1bc83a2-6a70-4095-b6d8-7d349a92a3a4.png)

1. Login/authorization https://zpl.io/2ZOgzA4
![image](https://user-images.githubusercontent.com/7249484/132123130-90fbfd2e-6aa0-47fd-bbf3-1b71289c575b.png)

2. Seed phrase confirmation https://zpl.io/2v8lWDY
![image](https://user-images.githubusercontent.com/7249484/132122935-98d577da-5105-4599-9da3-553abf15c4fe.png)

3. Send screens
https://zpl.io/bPNdmyx
![image](https://user-images.githubusercontent.com/7249484/132123136-84286a9c-692e-40df-8d67-6051ab3d647b.png)

4. Receive screen https://zpl.io/bLowDJQ
![image](https://user-images.githubusercontent.com/7249484/132123141-b38d985a-bbb9-4914-9f19-339443e72012.png)

5. Accept swap offer screens
https://zpl.io/2yM7yoK
https://zpl.io/beG4vyP
![image](https://user-images.githubusercontent.com/7249484/132123143-ac8cb5eb-1cc7-4edd-8e20-8e99753ed29e.png)
![image](https://user-images.githubusercontent.com/7249484/132123147-da75c79a-58dd-4d48-9cf2-4eb257173ea0.png)

6. Create swap offer screens
https://zpl.io/awwr1dj
https://zpl.io/2G5mOqY
![image](https://user-images.githubusercontent.com/7249484/132123150-7f91982d-3d6f-43d1-b80b-1e8d0125b89b.png)
![image](https://user-images.githubusercontent.com/7249484/132123152-aabe153f-588c-425b-9e5a-37ffd9ce70d5.png)

7. Edit address dialog https://zpl.io/2jd8wym
![image](https://user-images.githubusercontent.com/7249484/132123154-fe54263f-f5d7-4843-a31d-e4bd26271416.png)

8. Settings screen https://zpl.io/2pNdBNy
![image](https://user-images.githubusercontent.com/7249484/132123156-260a2134-0a07-4a34-987c-ddfcabfdf045.png)

9. Payment proof dialog https://zpl.io/Vxqklqk
![image](https://user-images.githubusercontent.com/7249484/132644824-8c1f407d-aa26-4a3d-bce4-aba8cffaaad9.png)

**Comment by AndreyDyakonov** [comment]
1.Field size
There are two types of input fields in the design :
1) Fields for entering amounts assets (Send/Receive screen and Atomic swap)
2) All other input fields, they must be the same height and the same rounding at the edges.
**Please make the fields "2)" equal in height and rounding**

in masternet: (for example)
<img width="650" src="https://user-images.githubusercontent.com/85252690/151955839-2aff037f-ed86-461a-a6b8-3964e38957bc.png">

in design: (for example)
<img width="650" src="https://user-images.githubusercontent.com/85252690/151955899-e39eab1d-4ba6-4072-90ea-7112d2dc9d86.png">

2.Login/authorization
Please make the dots red if the password was entered incorrectly

in master:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151944747-a6a0c9d1-b331-4d16-8173-752ca26b7dc6.png">

3.Seed phrase confirmation
Please make the words of the seed phrase inside the input field

in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151945228-de982295-2e7e-461b-ae9d-40dff2950945.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151945482-7f9d1649-22d4-44b8-8eb6-545f29d7867d.png">

4.Send screens
Please make the asset name and arrow for the asset selection drop-down list inside the input field

in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151946264-81cbfec7-9681-4e17-abcf-5d84bfc4c06d.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151946364-d0081006-af21-43a4-856d-f2ddd2486495.png">

5.Receive screen
Please make the asset name and arrow for the asset selection drop-down list inside the input field

in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151946586-7007f07e-e6fe-419d-ba67-77efa13529d3.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151946833-f21590a4-3acd-427c-90fa-b1253b47f6f7.png">

6.Accept swap offer screens
  5.1 Please make the asset name and arrow for the asset selection drop-down list inside the input field
  5.2  Change the view of the field for "OFFER EXPIRATION TIME"
  5.3 In the block with the token link, all digits are not placed in the BEAM=BTC field
  
in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151948021-959083ef-bfc3-46d2-8d76-45e6d0827fbc.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151948203-896272e2-9889-4cde-8fa8-3da8e0b307ef.png">

7.Create swap offer screens
Please make the asset name and arrow for the asset selection drop-down list inside the input field

in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151948517-9d8f3fba-ff80-4ea6-a4ae-ce2ee8abe9e9.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151948698-4123afdc-2cca-41f6-a8c6-0c6ccbae9572.png">

8.Settings screen
 8.1 Change the view of the fields for blocks "GENERAL" and "PRIVACY"
 8.2 In the field of the "DApps" block, the value is shifted relative to the center
 
in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151949685-ff3d3ede-0a63-4fd5-89dd-55abead40a6b.png">
<img width="350" src="https://user-images.githubusercontent.com/85252690/151949759-f9e212c9-0004-444a-be63-11882f476f5b.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151950054-1ce9c64e-edc9-41b7-9537-9b05f97d4d97.png">
<img width="350" src="https://user-images.githubusercontent.com/85252690/151950057-7c301a4f-89a1-4ef8-b174-a6315c90a617.png">

9.Payment proof dialog
Please change the view of the field

in masternet:
<img width="350" src="https://user-images.githubusercontent.com/85252690/151950423-c31da881-40fa-4070-994e-45df8ccc76fd.png">

in design:
<img width="350" src="https://user-images.githubusercontent.com/85252690/151950621-22e57dd5-f3f1-4561-bb8c-0cebbfb76630.png">

**Comment by AndreyDyakonov** [comment]
Send/Receive screens
 1 When we select an asset with a long name, its name fills the entire input field
 2 When selecting an asset with a long name, the pop-up window of assets is not displayed correctly
 3 If we enter the maximum amount in the input fields, the amount overlaps the asset name
 

https://user-images.githubusercontent.com/85252690/152299382-adb40a75-d991-46f3-9bc4-6d971510b2c6.mp4

<img width="450" src="https://user-images.githubusercontent.com/85252690/152299488-7e4baf2c-5ee0-4afa-88ed-f7858f7af5c1.png">

<img width="450" src="https://user-images.githubusercontent.com/85252690/152299509-8b671881-5187-4405-a74b-50b001e41401.png">

<img width="450" src="https://user-images.githubusercontent.com/85252690/152299522-e9db0348-0d0a-4fa3-b4ee-74442e50e1a6.png">

<img width="450" src="https://user-images.githubusercontent.com/85252690/152299534-e4f18e97-344b-4923-9744-bb99b63e3b1d.png">

**Comment by AndreyDyakonov** [comment]
Checked
