### ISSUE TITLE
Update wallet Dapp notification (version compatibility)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#664]
Design is here https://zpl.io/aRReAee
Notification about unavailable should be shown on DAPP card and above DAPPs list.
![image](https://user-images.githubusercontent.com/7249484/128473994-289681dc-1511-4dac-9752-96d818ada099.png)

**Comment by chapati** [comment]
I've changed strings:

1) This DAPP requires ....  In design  it is "The new  version of DAPP" but it is not always correct. It can be the same version as user used before but on old wallet.

**Comment by Roberrtt** [comment]
Please change the line from "Please update" to "Please update your wallet"
![Screenshot_556](https://user-images.githubusercontent.com/50007056/132483208-c918e184-87c2-4a79-b3ef-daf21d750059.png)

**Comment by Roberrtt** [comment]
Please fix this.
If 1 is not available it should be "DApp is not available" if more then 1 "DApps are not available"
![Screenshot_577](https://user-images.githubusercontent.com/50007056/133988799-dd764fe9-c097-42bd-ae06-582291fe3e35.png)

**Comment by Roberrtt** [comment]
checked
