### ISSUE TITLE
Electrum - increase number of change addresses

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam-ui#67]
Need design for https://github.com/BeamMW/beam/issues/1285
Please discuss with @sasha-abramovich

**Comment by dariatarakanova** [comment]
1) Please add "Advanced" on electrum node box https://zpl.io/2jDWv4r
2) Open view https://zpl.io/2jDWv4r
3) Generate regular addresses https://zpl.io/VkdWWgW
4) Generate change addresses https://zpl.io/2EL11X8
5) Error when user is trying to create more than 30 addresses https://zpl.io/agjWdJD

**Comment by dariatarakanova** [comment]
not relevant

**Comment by dariatarakanova** [comment]
Was decided to make it automatically. no need design.
