### ISSUE TITLE
DAPP TxList - active count

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#671]
Add active tx count in DAPP txlist title. Like this:
![gnome-shell-screenshot-36BH60](https://user-images.githubusercontent.com/12074933/124508193-13375580-ddd8-11eb-8323-b0122f4ce59c.png)

**Comment by kazaryan-t** [comment]
There is no active tx count on the DAPP Store screen.

![Фотографии 2021-07-08 15 25 25](https://user-images.githubusercontent.com/68247034/124920959-90ddaa00-e000-11eb-856a-ff866943c44f.png)

**Comment by kazaryan-t** [comment]
Checked on Masternet 6.1.11544.4449.
