### ISSUE TITLE
Assert on paste own sbbs

### ISSUE THREAD

**Issue by echoby** [BeamMW/beam-ui#675]
1) receive tx using regular address
2) copy receiving address from tx details (own sbbs)
3) paste own sbbs as "send to" address on send screen

assert was reached with false value
assert(
                   type == TxAddressType::PublicOffline ||
                  (type == TxAddressType::Regular && _token.toStdString() == std::to_string(_receiverWalletID))
            );

**Comment by Denis-Asipenko** [comment]
checked
