### ISSUE TITLE
Make a click area for the buttons in the settings

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#68]
We need to make  that when you click on any area on the button, the settings menu opens
Do this for all the buttons in the settings
![Screenshot_62](https://user-images.githubusercontent.com/50007056/86585291-e7984a00-bf8e-11ea-8b76-d060a3f1b5ed.png)

Actually: opens in the center, with letters and an icon
![bandicam-2020-07-06-13-41-23-776](https://user-images.githubusercontent.com/50007056/86585960-dd2a8000-bf8f-11ea-92e9-a45da8e74edb.gif)

**Comment by Roberrtt** [comment]
checked

**Comment by chapati** [comment]
1. is fixed
2. Butons were removed as per new design. Should be implemented in bug https://github.com/BeamMW/beam-ui/issues/58

**Comment by Roberrtt** [comment]
The selected zone isn't clickable,please make it clickable too, for all buttons
![Screenshot_54](https://user-images.githubusercontent.com/50007056/88513612-4894ca00-cff1-11ea-8cbc-92a1962d2907.png)

**Comment by Roberrtt** [comment]
When there is an error, the specified zone isn't clickable
![Screenshot_88](https://user-images.githubusercontent.com/50007056/88843311-8f4d1480-d1e9-11ea-8343-4ced164aebcf.png)

**Comment by gingervik** [comment]
checked on master 5.0.9371.3016
