### ISSUE TITLE
DAPPs - tx notifications

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#680]
Need to add transactions notifications for DApps.

**Comment by chapati** [comment]
![gnome-shell-screenshot-SHK060](https://user-images.githubusercontent.com/12074933/125984439-5cb582cb-d8e9-47f9-9b83-d79d45599409.png)
After testing please move to 6.2. Need to add progress at the bottom of notification.

**Comment by KatsiarynaV** [comment]
Checked. 
Moved to 6.2 to add progress at the bottom of notification.

**Comment by gingervik** [comment]
releated to https://github.com/BeamMW/dao-core-app/issues/3
