### ISSUE TITLE
beam-wallet.cfg gets overwritten on each wallet upgrade

### ISSUE THREAD

**Issue by dink** [BeamMW/beam-ui#69]
**Bug title**
When upgrading a wallet the `beam-wallet.cfg` with my custom values is replaced with default values.

**Bug description**
I'm keeping a custom value of: 
`appdata=C:\BeamChain` in the config file but it gets overwritten on each wallet upgrade, which results in the wallet downloading the whole blockchain again in a default directory. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Put any value in the `beam-wallet.cfg` file such as (`appdata=C:\BeamChain`)
2. Upgrade Wallet
3. Check `beam-wallet.cfg` to see that the value has been wiped.

**Current behaviour**
As above

**Expected behaviour**
User defined values should be left intact in `beam-wallet.cfg` on each and every upgrade, if possible. 

**Platform and build**
* Windows 10
* Every BEAM Build

**Comment by echoby** [comment]
NSIS installer fixed on masternet and testnet
mainnet installer - not reproduced

**Comment by VladislavKulyba** [comment]
checked on masternet
Waiting for testnet

**Comment by echoby** [comment]
On masternet and testnet NSIS installer always override beam-wallet.cfg. We can't check if it exist.
@Webonnix, Please fix mainnet installer

**Comment by Webonnix** [comment]
Fixed
[Beam-Wallet.zip](https://github.com/BeamMW/beam-ui/files/5017595/Beam-Wallet.zip)

**Comment by VladislavKulyba** [comment]
> Fixed
> [Beam-Wallet.zip](https://github.com/BeamMW/beam-ui/files/5017595/Beam-Wallet.zip)

Checked
