### ISSUE TITLE
New design for Side menu. Part 2. Add Dao Core dapp icon in sidemenu

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#695]
Add Dao Core icon below Dapp Store icon.
Design: https://zpl.io/2pRYLmN
Dao Core icon is here https://zpl.io/VY5wogk
![wallet-v10-suite-menu2](https://user-images.githubusercontent.com/7249484/124984552-f1560100-e06b-11eb-868b-d28b45daa379.jpg)

**Comment by gingervik** [comment]
Please, also provide design for Dao Tab while Dao is not implemented yet

**Comment by alexandrashelenkova** [comment]
@gingervik As been requested, it's in a separate task (still in progress) https://github.com/BeamMW/beam-ui/issues/694

**Comment by echoby** [comment]
@chapati 
See applications.qml->"Component.onCompleted" for details.

**Comment by Denis-Asipenko** [comment]
сhecked
