### ISSUE TITLE
Display USD/BTC value in atomic swap screen

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam-ui#7]
added 2nd currency
make design for wallet and atomic screens equals (balance block)

**Comment by dariatarakanova** [comment]
1) Design for second currency - https://zpl.io/VKy7WAP

2) As we have 2nd currency in this case active transactions displays as arrow icon
![image](https://user-images.githubusercontent.com/47353570/93332869-2bc78680-f82b-11ea-81c6-e520f79a26bf.png)

3) When mouse on over the icon - display box with additional information
![image](https://user-images.githubusercontent.com/47353570/93333031-67fae700-f82b-11ea-9309-8349a6a708d6.png)
