### ISSUE TITLE
Remove for now some features from settings

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#70]
Need to remove these features from settings

General
-Remove current wallet

Privacy
-Clear local wallet data

Resources:
-Keep wallet logs

**Comment by Denis-Asipenko** [comment]
UTILITIES:
Export \ Import wallet data

**Comment by Denis-Asipenko** [comment]
After removing some functions from the settings, the "Report a problem " function doesn't work.

- When you click on Github our repository should open(https://github.com/BeamMW/beam).

- When you click on the email address, a new message should be created with our support email address already inserted.

![image](https://user-images.githubusercontent.com/45556620/88035870-6b376680-cb4b-11ea-8e61-9e5cd635f5a3.png)

**Comment by Denis-Asipenko** [comment]
Fixed.
> After removing some functions from the settings, the "Report a problem " function doesn't work.
> 
> * When you click on Github our repository should open(https://github.com/BeamMW/beam).
> * When you click on the email address, a new message should be created with our support email address already inserted.
> 
> Also, links **beam.mw** and **blockchain explorer** don't open in the section Privacy.

After fixed the opening of links, previously removed functions return to the settings.
![image](https://user-images.githubusercontent.com/45556620/88372797-476c5e80-cd9f-11ea-974a-f4599be23ae7.png)

**Comment by Denis-Asipenko** [comment]
checked
