### ISSUE TITLE
Transaction details. Remove USD Value field

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#703]
1. Remove USD Value field from tx details dialog. Show USD rate only under amounts and fee. 
2. Update texts for USD rate statuses:
_- "calculated with the exchange rate by the day of transaction"_
_- "exchange rate was not available by the time of transaction"_

Design
https://zpl.io/bWyK0vn
https://zpl.io/V1AJ1jZ
https://zpl.io/aRwPQZp
![transaction-detail-v3-general-usd-unavailable](https://user-images.githubusercontent.com/7249484/125306837-1eebc480-e362-11eb-85a9-c6eb57685fb9.jpg)
![transaction-detail-v3-general](https://user-images.githubusercontent.com/7249484/125306860-24e1a580-e362-11eb-8860-b61f9dc6a76e.jpg)

**Comment by chapati** [comment]
As discussed with @sasha-abramovich 

- "calculated with the exchange rate by the day of transaction" changed to "at the day"
- "exchange rate was not available by the time of transaction" changed to "at the time"

**Comment by KatsiarynaV** [comment]
1. Make the text italic as in the design
![25](https://user-images.githubusercontent.com/68267190/126292519-0fd14547-b718-432a-a88c-5e4429f0b6bf.jpg)
![30](https://user-images.githubusercontent.com/68267190/126293335-11065e2f-77ef-453c-b879-ba7484797634.jpg)
![26](https://user-images.githubusercontent.com/68267190/126292522-a9dd232d-5767-427d-9dac-704a882dc2df.jpg)
![28](https://user-images.githubusercontent.com/68267190/126292533-6b04c4a2-8b60-4aad-9f08-0df153649f9d.jpg)

2. If the exchange rate was not available remove "-USD". Leave only the text
![27](https://user-images.githubusercontent.com/68267190/126293395-a4b17ed5-954f-4c46-8290-781764927954.jpg)

**Comment by alexandrashelenkova** [comment]
Added version of design when USD rate wasn't available at the time of transaction and **still is not available**. In that case there should be no "-USD" value.
Design https://zpl.io/aRwPQZp
<img width="1035" alt="Screenshot at Jul 20 12-28-49" src="https://user-images.githubusercontent.com/7249484/126297913-867edfcd-41ba-46af-8477-036bcff24043.png">

**Comment by echoby** [comment]
Do not use italic in rate statuses. Approved by @alexandrashelenkova

**Comment by KatsiarynaV** [comment]
Checked
