### ISSUE TITLE
Receive screen with Max anonymity set switcher

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#704]
Please work only on points mentioned below. No need to change the design for the input field, it is for feature designs and still in progress. 

1) Add block "Advanced" (minimized by default) and place there Maximum anonymity switcher. https://zpl.io/aMXBrZd 

2) Switcher default position is OFF.
Off = tx will be Regular (it is combined address - online + offline addresses)
On = tx will be Maximum anonymity set

3) When Switcher is OFF - place the comment "For the transaction to complete, you should get online during the 12 hours after Beams are sent." https://zpl.io/aNYw1Xd
![image](https://user-images.githubusercontent.com/47353570/125827324-793c8696-7ace-4e21-8176-8427d0a28761.png)

4) When Switcher is ON - place the comment "Transaction can last at most 72 hours." https://zpl.io/aNYw1Xd
![image](https://user-images.githubusercontent.com/47353570/125827297-807ab532-f0c5-42a2-acf1-631f71f2b725.png)

5) Regular address details. Show full only address itself. Online (SBBS) address -  always show begin and end of the address. https://zpl.io/V1Rp4BJ
![image](https://user-images.githubusercontent.com/47353570/126151072-49247554-89fc-4a5e-82a0-30b0c5e3de20.png)

6) Address details with max anonymity set https://zpl.io/VY0Ykgk
![image](https://user-images.githubusercontent.com/47353570/126151092-7910c830-be6c-4916-8918-81b326890aa6.png)

**Comment by chapati** [comment]
3 & 4 will not be present (discussed with abramovich). Old text under the copy button with minor changes would stay. Task should be updated soon by designers.

**Comment by dariatarakanova** [comment]
**UPD:**

1) Please comments under button. Max anon set is OFF https://zpl.io/aMXBrZd
![image](https://user-images.githubusercontent.com/47353570/126285692-c1239776-4929-40f6-875b-55846c6976d0.png)

2) Max anon. set is ON. Comment "Transaction can last at most 72 hours." https://zpl.io/aNYw1Xd
![image](https://user-images.githubusercontent.com/47353570/126285781-c12a212d-54f2-4700-ac6f-6bad711484de.png)

3) Max anon. set is ON. Comment "Transaction can last indefinitely." https://zpl.io/2GqOPdE
![image](https://user-images.githubusercontent.com/47353570/126285878-a63a76ac-ca6e-4977-8f3f-ada8ffe442e3.png)

**Comment by Sergei-Beam** [comment]
1. point 6 from https://github.com/BeamMW/beam-ui/issues/704#issue-942324304
we shouldn't have the text above the button for maximum anonymity set
![image](https://user-images.githubusercontent.com/44496108/126359337-f60579c3-5095-4ae2-a1ef-d0b3a682007f.png)
2. point 1 from https://github.com/BeamMW/beam-ui/issues/704#issuecomment-883197512
![image](https://user-images.githubusercontent.com/44496108/126359691-bddba2d7-64d3-4350-b448-b1a882b66cf7.png)

**Comment by Sergei-Beam** [comment]
checked
