### ISSUE TITLE
Send screen. Additional changes in addresses flow

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#706]
Task connected to https://github.com/BeamMW/beam-ui/issues/704
Please work only on points mentioned below. No need to change the design for the input field, it is for feature designs and still in progress.

1) If receiver sends to sender regular address (maximum anonymity set OFF)

- Sender can choose the transaction type: Online or Offline 
![image](https://user-images.githubusercontent.com/47353570/125670276-58a89d74-8cf3-40a0-b63d-5236709fe19d.png)

- Online transaction - add comment below address "Online address. The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."  https://zpl.io/adyREoR
![image](https://user-images.githubusercontent.com/47353570/125670368-ba410c17-66cb-41ca-8195-5852fb4dd47d.png)

- Offline tx - comment "Offline address: Х transactions left. Make sure the address is correct as offline transactions cannot be canceled." https://zpl.io/2jypXEp
![image](https://user-images.githubusercontent.com/47353570/126141663-bf1a5525-52d1-455c-96d1-a8fb7e4d3440.png)

- Show warning comment "Ask receiver to come online to support more offline transactions." when 3 or fewer transactions left. https://zpl.io/VDm74Lv

![image](https://user-images.githubusercontent.com/47353570/126141864-03a13823-7990-4fd0-9854-13eee9a25172.png)

2) If receiver sends to sender Online address https://zpl.io/b6AYLgK (receiver can copy it from address details on receive screen https://zpl.io/V1Rp4BJ)

- No need block "Transaction Type"
- Add comment "Online address. The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards."

![image](https://user-images.githubusercontent.com/47353570/125671543-ab269e70-6f72-4a65-95b9-1457b2b6a6b7.png)

3) If receiver sends to sender Maximum anonymity set address https://zpl.io/29d51Jp

- Add a comment about transaction's amount "Guarantees maximum anonymity set of up to 64K. Transaction can take up to 72 hours."

![image](https://user-images.githubusercontent.com/47353570/125905748-24442ee5-159a-45de-94f7-af3e0ff1c0c1.png)

**Comment by gingervik** [comment]
please, change comments here 
* Offline tx - comment "Offline address: X transactions left. An offline transaction does not allow refund if funds have been sent." https://zpl.io/2jypXEp
image

* Show warning comment "Ask receiver to come online to support more offline transactions." when 3 or fewer transactions left. https://zpl.io/VDm74Lv

image

**Comment by dariatarakanova** [comment]
@chapati **UPD:**

Please split comments under address and place some parts under button

1) Place "The recipient must get online within the next 12 hours and you should get online within 2 hours afterwards." under button. https://zpl.io/adyREoR
![image](https://user-images.githubusercontent.com/47353570/126306196-3e68be70-74c7-45ce-9039-ae5e075d57a1.png)

2) Place "Make sure the address is correct as offline transactions cannot be canceled." under button. https://zpl.io/2jypXEp
![image](https://user-images.githubusercontent.com/47353570/126306294-1aa607de-dc60-43d2-b78d-fffcb2c7dbc7.png)

3) Place "Make sure the address is correct as offline transactions cannot be canceled." under button. https://zpl.io/VDm74Lv
![image](https://user-images.githubusercontent.com/47353570/126306497-1f797e37-44f9-4281-b435-6d1fa5fb9416.png)

4) Place "Transaction can last at most 72 hours." under button.  https://zpl.io/29d51Jp
![image](https://user-images.githubusercontent.com/47353570/126306577-afa4b9f5-4c05-4bda-aa70-0a16830e12b5.png)

**Comment by Sergei-Beam** [comment]
All messages are located under the address input field, you need to separate them according to the comment
https://github.com/BeamMW/beam-ui/issues/706#issuecomment-883272783
For example:
![image](https://user-images.githubusercontent.com/44496108/126698404-cc5e1c0e-3cb9-42ee-8c61-c1e48bf36871.png)
![image](https://user-images.githubusercontent.com/44496108/126698464-301db30f-e296-43c4-a7b9-a0a27fc45c9d.png)

**Comment by Sergei-Beam** [comment]
checked
