### ISSUE TITLE
DAPPS - tx notifications progress

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#708]
Need to add progress to the tx notification.
Or may be do not need. It is not so trivial.
@gingervik let's discuss

**Comment by chapati** [comment]
Need to implement the following:

1) Tx Notification should not close on timeout but stay on screen until tx is completed

2) If wallet closed and then reopened and tx is still in progress notification should appear again

3) If user closes notification manually it should not appear again

4) Implement progress bar

![image](https://user-images.githubusercontent.com/12074933/138080191-6a613cb9-7cdd-41fe-a5d2-8f070d511d3b.png)
For the estimated transaction time please use the weighted average of the block emission time considering ~10 samples lookback window (when available). The older a block, the less weight it should have.

Whenever a transaction is accomplished faster than the estimated time - the indicator should accelerate to 100%.
Whenever a transaction takes longer than the estimated time - the indicator should start behaving exponentially from 90-95% (to your choice).

**Comment by echoby** [comment]
@chapati 
need to discuss point 5

**Comment by Sergei-Beam** [comment]
checked
