### ISSUE TITLE
Update BeamX icon and mark it as certified

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#713]
Replace auto-generated assest icon to new BEAMX icon everywhere, where it used

Examples:
https://zpl.io/VQymqEx
https://zpl.io/29d4Erl
https://zpl.io/2p3Br3l
<img width="549" alt="Screenshot at Jul 12 13-46-27" src="https://user-images.githubusercontent.com/7249484/125275865-1edbcc80-e342-11eb-9f81-4a56b5779e79.png">
<img width="1051" alt="Screenshot at Jul 12 13-47-15" src="https://user-images.githubusercontent.com/7249484/125275872-20a59000-e342-11eb-98ad-c56636908cf1.png">
<img width="610" alt="Screenshot at Jul 12 13-50-41" src="https://user-images.githubusercontent.com/7249484/125275886-23a08080-e342-11eb-94f0-7f514079be0a.png">

**Comment by chapati** [comment]
Added for DEMOX on master. Please check that everything is OK then transfer to Vika.
Need to know asset id for testnet & mainnet before we close this.

**Comment by AndreyDyakonov** [comment]
Checked on masternet
