### ISSUE TITLE
Change "max privacy" to "max anon. set" in status and comments when random node connected

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#714]
This task continues https://github.com/BeamMW/beam-ui/issues/341

1) When remote node connected please display status "online: random node supports online transactions only" and button https://zpl.io/ag1er4O
![image](https://user-images.githubusercontent.com/47353570/126150735-5107fc84-05e6-42d3-9fe0-c5f749ac4af5.png)

2) In Settings update comment to "To support maximum anonymity set and offline transactions please connect to integrated node or to own node configured with your owner key." when user connects to remote node. https://zpl.io/VY0B0MM
![image](https://user-images.githubusercontent.com/47353570/126964768-08217164-ba58-4c0b-80b3-ab4622eff6c4.png)

3) On Receive screen please disable Max anonymity set switcher https://zpl.io/2yomo5L
![image](https://user-images.githubusercontent.com/47353570/126150231-1f043f28-5eba-460e-b388-c6d7682b7936.png)

4) In address details show onIy online address + comment "You are currently connected to random node that supports only online transactions." https://zpl.io/awdYdQ1
![image](https://user-images.githubusercontent.com/47353570/126150325-30e20b0d-f277-404c-b607-9101362be2aa.png)

**Comment by echoby** [comment]
For point 1 used "connected node supports online transactions only" instead  "random node supports online transactions only"
For point 3 QR uses sbbs address

**Comment by KatsiarynaV** [comment]
1. When random node connected the “Rescan” button should be inactive
![01](https://user-images.githubusercontent.com/68267190/127442664-f092939a-2d7a-459d-88ec-216c7b52a01f.jpg)

2. On the receive screen remove the line “Sender will be given a choice between online and offline payment”. Move the text "Connect to integreated or own node..." under the "copy and close" button (discussed with @dariatarakanova )
![04](https://user-images.githubusercontent.com/68267190/127444959-0eb8ded4-f062-426f-ab3e-fe4b4787ceb5.jpg)

3. In address details make text italic
![05](https://user-images.githubusercontent.com/68267190/127443377-48f81ae9-4822-4c5b-9727-426d0c8a1077.jpg)
![06](https://user-images.githubusercontent.com/68267190/127443379-cc3ef438-4cb7-43e4-965e-7cf8bceba164.jpg)

**Comment by KatsiarynaV** [comment]
There was no need to remove the text "For an online payment to complete, you should get online during 12 hours after coins are sent". Please add it back. And add a dot at the end of the text ""Connect to integreated or own node to enable receiving maximum anonymity set and offline transactions."
![08](https://user-images.githubusercontent.com/68267190/127481506-6b855e23-a952-468e-b453-8ec17376bf8b.jpg)
![07](https://user-images.githubusercontent.com/68267190/127481524-c6ad265a-4a72-49e2-b7d9-542d1a3a795f.jpg)

**Comment by KatsiarynaV** [comment]
Checked
