### ISSUE TITLE
Dapps tx confirmations

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#717]
Design https://zpl.io/bAKB4zq

1. Withdraw confirmation dialog
<img width="414" alt="Screenshot 2021-07-22 at 22 31 27" src="https://user-images.githubusercontent.com/7249484/126698858-a192c4df-a86a-4490-aa0a-e78149a9856c.png">

2. Deposit confirmation dialog
<img width="415" alt="Screenshot 2021-07-22 at 22 31 30" src="https://user-images.githubusercontent.com/7249484/126698848-d7c34faa-b65e-4cc5-a291-a80dbd14bf28.png">

3.Deposit + withdraw confirmation dialog
(if there's at least one deposit transaction in the list of different assets transaction confirmations, the "Confirm" button should have pink color)
<img width="421" alt="Screenshot 2021-07-22 at 22 31 34" src="https://user-images.githubusercontent.com/7249484/126698829-250b8c96-2dd3-4d28-9abc-6822d02c6c62.png">

4. .Deposit + withdraw confirmation dialog (+ password)
<img width="418" alt="Screenshot 2021-07-22 at 22 31 38" src="https://user-images.githubusercontent.com/7249484/126698822-cd683aef-b988-408b-bd2a-17f28629ab4e.png">

**Comment by chapati** [comment]
4. For password confirmation text should be the following for all cases (doesn't matter if it is withdraw or deposit) : "To approve the transaction please enter your password". Discussed with @sasha-abramovich

**Comment by alexandrashelenkova** [comment]
**_TASK UPDATES_**
1. Text changed to _"To approve the transaction please enter your password"_
2. Added confirmation for tx with 0 balance. 
<img width="378" alt="Screenshot 2021-07-26 at 14 54 49" src="https://user-images.githubusercontent.com/7249484/126984684-80547df1-7e49-4886-ba77-a410c836caec.png">

**Comment by alexandrashelenkova** [comment]
@chapati sorry, another text update for 0 balance tx confirmation.
<img width="563" alt="Screenshot at Jul 26 15-19-48" src="https://user-images.githubusercontent.com/7249484/126987573-1f729773-b3f4-472f-af8f-b0786bf06f12.png">

**Comment by Sergei-Beam** [comment]
The focus for the password field doesn't show on deposit confirmation dialogue, on withdraw and claim confirmations it is there
![image](https://user-images.githubusercontent.com/44496108/127370241-4cb8d434-6922-4c05-b027-0a55c24b0dbe.png)
![image](https://user-images.githubusercontent.com/44496108/127370257-06f6a9f4-7a7e-4b8c-be46-d16110bb8a48.png)

**Comment by Sergei-Beam** [comment]
Text on Faucet confirmation is not centralized
![image](https://user-images.githubusercontent.com/44496108/127393670-cc902c0b-2444-46fb-afc1-af1e3f863307.png)

**Comment by Sergei-Beam** [comment]
Something was broken, the "verified" icon for BeamX is disappeared from the confirmation dialogue
![image](https://user-images.githubusercontent.com/44496108/127825248-aa05548b-37c0-40bc-b9ad-6eb36dda1ba6.png)

![image](https://user-images.githubusercontent.com/44496108/127825128-683207ef-1609-4f99-96fc-9759a9c53abe.png)

**Comment by Sergei-Beam** [comment]
checked
