### ISSUE TITLE
Three dots in Loading Staking dapp message...

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#718]
<img width="1136" alt="Screenshot 2021-07-22 at 15 58 24" src="https://user-images.githubusercontent.com/7249484/126710991-df78c165-c1bf-4da8-acee-93e0775abb65.png">
Remove a dot in "Please wait, BEAM DAO CORE is loading"

**Comment by AndreyDyakonov** [comment]
Checked
