### ISSUE TITLE
Remove "Back" button on Dao Core screen

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#723]
<img width="929" alt="Screenshot at Jul 23 00-26-51" src="https://user-images.githubusercontent.com/7249484/126711809-a9507796-b0f4-4fe0-81dd-96c5453c8a9a.png">

**Comment by chapati** [comment]
Back will be not visible if opened using dao core button.

**Comment by AndreyDyakonov** [comment]
Checked
