### ISSUE TITLE
Verified assets universal solution

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#730]
Need to get rid of defines and move 'verified' to broadcaster to be able to mark assets verified dynamically. This is important for 6.1

**Comment by chapati** [comment]
Asset ID 1 should have verified icon on masternet
Asset ID 5 (BeamX) should have BeamX icon, color & verified icon on masternet.

![gnome-shell-screenshot-7K4E70](https://user-images.githubusercontent.com/12074933/128551396-12a3b42f-eab6-46d7-991a-8484045ee65e.png)

Update can take some time. Our broadcaster send this info every 5 minutes on masternet.

**Comment by KatsiarynaV** [comment]
Checked
