### ISSUE TITLE
DApps requests queue

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#732]
1) Now DAPS can execute only 1 request to shader at a time. It causes problems for example when dao updates its state and user requests withdrawal at the same time. One of the requests fail
2) If confirmation dialog is displayed and DAO updates it state app hangs.

Need to implement queue for shader requests in C++ code (6.1+) or in JS (will work on 6.0). Need to discuss the preferred solution on monday.

**Comment by chapati** [comment]
Check that 

1) this error message does not appear anymore

![photo_2021-08-11_22-21-28](https://user-images.githubusercontent.com/12074933/129090138-a4f6c3a6-aa66-45bf-8a4c-4224726ee1be.jpg)
&c)

2) that dao core works correctly (updated, tx created

**Comment by Roberrtt** [comment]
checked
