### ISSUE TITLE
TX as dialog (small text changes in USD rate description)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#734]
Check once again that there's no "by/for the day of transaction" in USD rate comment left, there should be "**_at_** the **_time_** of **_the_** transaction".

Design
<img width="626" alt="Screenshot at Aug 03 12-08-37" src="https://user-images.githubusercontent.com/7249484/127989909-e7199d12-9047-414e-bb26-9c30b9665469.png">
<img width="612" alt="Screenshot at Aug 03 12-08-55" src="https://user-images.githubusercontent.com/7249484/127989922-3a38dff4-569b-4ccf-a027-eefddd92088a.png">
<img width="626" alt="Screenshot at Aug 03 12-09-23" src="https://user-images.githubusercontent.com/7249484/127989927-bc1b2290-aa66-4238-9635-af7ffdd8fe39.png">

App
![2021-08-03 12 05 09](https://user-images.githubusercontent.com/7249484/127989457-581a7492-7542-4b15-a12c-22e804918ffe.jpg)

**Comment by KatsiarynaV** [comment]
There should be "at the time of **the** transaction".
![42](https://user-images.githubusercontent.com/68267190/128349989-2c18214d-fc79-4644-9e45-725d6e7f9462.jpg)

**Comment by KatsiarynaV** [comment]
Checked
