### ISSUE TITLE
Add link to Explorer in Asset pop up

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#735]
On CA popup (Asset info tab) add a link to the Explorer 
https://zpl.io/a7pMQ7R

![image](https://user-images.githubusercontent.com/7249484/128361008-6d02f575-2236-44ec-99cd-93b1b9cc8622.png)
![image](https://user-images.githubusercontent.com/7249484/128361037-c3d8b5eb-c4f7-48f0-b930-8d207faa1dee.png)

**Comment by KatsiarynaV** [comment]
Fix the pop-up background  color
![01](https://user-images.githubusercontent.com/68267190/132357358-3e198274-60a5-4508-9420-fbb254ee7d70.jpg)
![02](https://user-images.githubusercontent.com/68267190/132357364-f4340067-29eb-411a-9d75-4bc8310dbaff.jpg)

**Comment by KatsiarynaV** [comment]
Checked
