### ISSUE TITLE
The wallet crashed if you open receive screen via the address book

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#740]
When we go to the " receive " screen via the address book, and quickly click on the "copy and close" button, the wallet crashed

Step:

- go to address book
- click on 3 dots near the address
- click on receive
- click "copy and close" button

Actual: Wallet crashed
Expected: The address is copied 
OS: Windows 10
Wallet version:  6.1.11624.4547
[db and dmp file.zip](https://github.com/BeamMW/beam-ui/files/6930914/db.and.dmp.file.zip)

https://user-images.githubusercontent.com/50007056/128174950-dd3a7e5a-4e8e-4199-b307-810ede24538e.mp4

**Comment by chapati** [comment]
DB file is missing. Please provide. It is not reproduced on every address

**Comment by Roberrtt** [comment]
Sorry,here's the DB file
pass = 1
[wallet.zip](https://github.com/BeamMW/beam-ui/files/6934088/wallet.zip)

**Comment by Roberrtt** [comment]
checked
