### ISSUE TITLE
Drag and drop Dapp flow

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#752]
Uploading dapp flow is here https://zpl.io/2Z3WDmd

1. On the Dapp Store screen add a placeholder that will lead to file uploading dialog
![image](https://user-images.githubusercontent.com/7249484/128357205-7a074280-9632-46fc-aa6f-40dd997d26a4.png)

2. File uploading dialog
Should support drag & drop flow and possibility to open finder and choose a file manually
![image](https://user-images.githubusercontent.com/7249484/131171637-2a5cafcc-1978-4c39-bb41-20cd596b924f.png)

While drag & drop if dragged file reaches Uploading file dialog area, the area should be highlighted, text faded.
![image](https://user-images.githubusercontent.com/7249484/131171662-c4b94fbc-2b82-477f-8298-3bf49aa8f69d.png)

3. After file uploaded, show success or error notification
![image](https://user-images.githubusercontent.com/7249484/131341889-d05a01f3-e5fa-43db-9c76-98b3730fc0ac.png)
![image](https://user-images.githubusercontent.com/7249484/131341930-00b32efc-14cd-462f-9f2d-36eec37dfdc3.png)

**Comment by KatsiarynaV** [comment]
1. Make text color white ("or just drop it here"). Make arrow direction as in the design
![10](https://user-images.githubusercontent.com/68267190/151945154-12e85cde-a824-4197-a4e4-6de93c241c82.jpg)

2. While drag & drop if dragged file reaches Uploading file dialog area, the area should be highlighted, text faded
![11](https://user-images.githubusercontent.com/68267190/151945262-e0c5af4c-9b79-4a5b-b5b2-4790124c3613.jpg)

3. Remove dot from the text and make text color white
![12](https://user-images.githubusercontent.com/68267190/151945401-4e5c9cd5-8995-4b65-9909-4632208947b7.jpg)

**Comment by KatsiarynaV** [comment]
Checked
