### ISSUE TITLE
Easy onboarding

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#756]
1) Add "I will do it later" button on seed phrase screen, if user chooses that do not show seed phrase confirmation flow. https://zpl.io/bzjq1dX
![image](https://user-images.githubusercontent.com/47353570/128483667-7f218d05-f02e-4f1b-ac42-fea753815859.png)

2) After display password screen https://zpl.io/VDoA4Ne
![image](https://user-images.githubusercontent.com/47353570/128483753-e29f3e6d-2727-4ba2-b611-4d109bd2d0af.png)

3) Then screen with Node settings( no need to make changes as on design, just leave current UI design) https://zpl.io/2p6B5Qr
![image](https://user-images.githubusercontent.com/47353570/128484708-60ef7e76-cf66-494a-84be-f64f92318a12.png)

4) Then Wallet screen https://zpl.io/Vkyd5wZ
- Button "get coins" - opens Faucet dapp (same as in task #570)
- Button "Secure your phrase" leads to Seed phrase screen. But no need to show "I will do it later" button https://zpl.io/bzjq1dX
![image](https://user-images.githubusercontent.com/47353570/128486889-9fb7df27-9e31-49a5-a1b9-4b933658e287.png)

5) When user receive 10+ BEAM please do not give the opportunity to close block with text "Write down and validate your seed phrase so you can always recover your funds." - need to remove "X" icon and change block bachgroung to make it more visible.
https://zpl.io/aRweYWv
![image](https://user-images.githubusercontent.com/47353570/128487534-4f19100b-506f-406f-9c74-ebb14f7b6089.png)

6) Please add "Complete wallet verification" to Privacy settings. https://zpl.io/bWzZxQk
It needs if user closed the block with text "Write down and validate your seed phrase so you can always recover your funds." on this screen https://zpl.io/Vkyd5wZ
![image](https://user-images.githubusercontent.com/47353570/128488995-cfd7ad4e-5a4b-4f59-9fdf-bae8a9c17626.png)

7) "Complete wallet verification" leads to Seed phrase screen. But no need to show "I will do it later" button https://zpl.io/bzjq1dX
![image](https://user-images.githubusercontent.com/47353570/128490471-d0e403fb-f1a3-484b-b250-9bcd4c9a6f18.png)

8) No need to show "Complete wallet verification" in settings after user finished verification.

**Comment by KatsiarynaV** [comment]
When user receives 10+ Beam the "x" icon disappears only after reopening the "wallet" screen.
![01](https://user-images.githubusercontent.com/68267190/129323139-9287d46b-0d13-413d-a685-f4f410b865ac.gif)

When user receives 10+ Beam change block background to make it more visible
![03](https://user-images.githubusercontent.com/68267190/129323160-0837b44b-489f-41be-bcbf-59c08e089cef.jpg)
![04](https://user-images.githubusercontent.com/68267190/129323165-699ba6e0-644d-49c7-aa26-b5421bbcfeb4.jpg)

**Comment by KatsiarynaV** [comment]
Now if user closed the message and then received  10+ Beam the message appears only after reopening the "wallet" screen.
![02](https://user-images.githubusercontent.com/68267190/129376737-45937ce0-8bff-45af-a268-52d57a4f0955.gif)

**Comment by Roberrtt** [comment]
If we open link through the wallet screen then when you click on back button, return to wallet screen
if we open it through the settings, then return to settings

https://user-images.githubusercontent.com/50007056/129696997-88cbc493-a04f-4325-9a01-4f056246f6f8.mp4

**Comment by Roberrtt** [comment]
checked
