### ISSUE TITLE
Linux - Application doesn't open on testnet wallet 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#757]
On the 6.0 Linux testnet wallet, the applications don't open
Wallet version: 6.0.11531.4334 
![Screenshot_468](https://user-images.githubusercontent.com/50007056/128545953-10e74b1b-1674-4797-ab8d-83557f45436a.png)

**Comment by chapati** [comment]
@anatolse this commit should be merged to master & testnet
https://github.com/BeamMW/beam-ui/commit/8f8c85cd10518d3933b586362f01b9eb9a90ed2b

**Comment by anatolse** [comment]
Ok. This commit will be delivered to the testnet with relese merge
