### ISSUE TITLE
Rename BEAM DAO Dapp to BeamX DAO

### ISSUE THREAD

**Issue by sasha-abramovich** [BeamMW/beam-ui#758]

**Comment by kazaryan-t** [comment]
Please, remove the word **DAPP** from confirmation screens.

![Beam Wallet Masternet 2021-08-17 10 49 28](https://user-images.githubusercontent.com/68247034/129686163-baee0344-ebe7-4b23-b403-b5e576442d2e.png)
![Beam Wallet Masternet 2021-08-17 10 52 49](https://user-images.githubusercontent.com/68247034/129686166-9410af26-f11f-4a68-a459-e2c0bbe1b2ca.png)

**Comment by kazaryan-t** [comment]
Checked.
