### ISSUE TITLE
Add Uninstall button in Dapp Store for locally installed apps

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#759]
1. Add additional menu icon, with Uninstall action
![image](https://user-images.githubusercontent.com/7249484/128697950-d1766c12-091c-414c-8877-69d619b7e681.png)
Design https://zpl.io/ag1w3M1

2. Add uninstall confirmation dialog
Design https://zpl.io/29drGDY
![image](https://user-images.githubusercontent.com/7249484/128698589-f716c4e0-9d81-42dd-80d4-0d29679923d4.png)

**Comment by AndreyDyakonov** [comment]
1. Adjust the position and size of the "Uninstall" pop-up button

in master:
![1](https://user-images.githubusercontent.com/85252690/133741283-7f190bcd-848f-4073-a077-767c2d617642.png)

in design:
![2021-09-17_10-20-48](https://user-images.githubusercontent.com/85252690/133741625-035ac99c-9089-42f3-9d55-021129fdaf6a.png)

2. Change "DApp" to "DAPP" and add word "That" 

in master: "Are you sure you want to uninstall ... DApp"
<img width="380" src="https://user-images.githubusercontent.com/85252690/133743063-d1e9f08f-1d50-4065-947d-42c0f6a89c2c.png">

in design: "Are you sure that you want to uninstall ... DAPP"
<img width="380" src="https://user-images.githubusercontent.com/85252690/133743139-11b7d639-7c22-4aac-8dc7-6b54f6039c79.png">

**Comment by chapati** [comment]
1. Menu works this way in all places. It shows under cursor position and this is correct.
2. We use 'DApp' everywhere in application. It is correct. DApp is abbreviation and according to English rules correct version is 'DApp'

**Comment by chapati** [comment]
Discussed, will use "DApp". Should changed to 'DApp Store' as well

**Comment by AndreyDyakonov** [comment]
Checked
