### ISSUE TITLE
When switching to receive screen, an incorrect QR code is displayed

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#762]
When we open the " receive" screen via the address book, there's a delay in appearance of the correct QR code
pass =1
[wallet.zip](https://github.com/BeamMW/beam-ui/files/6964097/wallet.zip)

https://user-images.githubusercontent.com/50007056/128923643-b7f17443-ab77-41a1-9470-b860bb52a2e4.mp4

![Screenshot_472](https://user-images.githubusercontent.com/50007056/128923666-78fdead7-770b-4ff6-9c58-83bf598c29bc.png)

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by echoby** [comment]
Recheck, pls. Зay more attention on Linux.

**Comment by Roberrtt** [comment]
If you open the receive screen by taking the sbbs address, the sbbs address will be visible at the beginning

https://user-images.githubusercontent.com/50007056/133577936-b2aa20a1-74d7-4dcc-95eb-b5b762116960.mp4

Also, if we generating the sbbs address connected to remote node, if we click show qr code in address book, then the token will be displayed in it

https://user-images.githubusercontent.com/50007056/133578009-2ed7a891-a130-40b4-a2e5-fa9642b0f3f4.mp4

**Comment by KatsiarynaV** [comment]
Checked
