### ISSUE TITLE
DApps: bad character in folder names

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#770]
When launching any dapss the following folders are created:

C:/Users//AppData/Local/Beam Wallet (Testnet/Masternet)/appstorage/appid
C:/Users//AppData/Local/Beam Wallet (Testnet/Masternet)/cache/appcache/appid
When installing dapp also

C:/Users//AppData/Local/Beam Wallet (Testnet/Masternet)/localapps/appid
Where appid looks like "33069528774e02884ce39480dd478bfe78b0e24a56baee171307bfcdb80fad4e"

Now folders 1 & 2 starts from "appid:" which is incorrect. ":" character is not allowed in folder name on windows. Need to fix this and then to test that all the folders created do not include not allowed characters.

**Comment by Roberrtt** [comment]
checked
