### ISSUE TITLE
Change the logo font.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#78]
We must use the font specified in the design. Note the letter "M".The font must be changed on all screens where it is used.
**Current:**
![image](https://user-images.githubusercontent.com/45556620/87539912-6c7a1680-c6a7-11ea-99fd-1c9493f59742.png)
**Design:**
![image](https://user-images.githubusercontent.com/45556620/87540020-992e2e00-c6a7-11ea-8309-58b997866daf.png)

**Comment by kazaryan-t** [comment]
Checked.
