### ISSUE TITLE
Start auto migration screen. No need to show db list

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#783]
After click on button "start auto migration" https://zpl.io/VQvNLPA - no need to show screen with database files. Migration should be done automatically from the latest version. https://zpl.io/2GGj4jm
![image](https://user-images.githubusercontent.com/47353570/131182553-2e2b08d0-1ad6-4b66-9f5f-d0e963668d52.png)

**Comment by gingervik** [comment]
@dariatarakanova @sasha-abramovich originally, when user clicks on "select DB file manually" we allow him to select a file in 'finder', not only automatically detected DBs in the wallet folder. As I see, you removed such ability in the new design. 
It's kind of important feature to allow user select DBs from any place on his PC

**Comment by sasha-abramovich** [comment]
@dariatarakanova let's add a dedicated button on the screen for the most advanced users

**Comment by dariatarakanova** [comment]
**UPD (Oct 6):**

1) Button "start auto migration" is starting migration automatically from the latest version

2) Button "start manual migration" open screen with database list https://zpl.io/bzOdL7z
![image](https://user-images.githubusercontent.com/47353570/136183919-9ece948c-6029-467e-8b6d-414a1884ab7f.png)

3) On the database list screen user can select the wallet.db file from list or choose manually from any place on it's comp/laptop/hard disk etc.
![image](https://user-images.githubusercontent.com/47353570/136184418-7acb1f84-31e0-488a-899a-ce8f820240b9.png)

4) If user click "Choose wallet.db file manually" button - it is opening system dialog (e.g as on mac). User chooses the file and then see the password screen (as it is implemented now after click on "select wallet database...")
 ![image](https://user-images.githubusercontent.com/47353570/136184648-6739989c-ed83-4364-b6ab-ae3af23c3691.png)

5) No need "Restore wallet or create a new one" on database list screen 
![image](https://user-images.githubusercontent.com/47353570/136184964-2e755dd3-e420-4863-826e-942c247420c6.png)

**Comment by AndreyDyakonov** [comment]
Checked
