### ISSUE TITLE
Rework Create Password screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#784]
The layout is updated to eliminate user's confusion. The nicer input fields are aligned with those on Send/Receive screens.

**1) Empty password fields** https://zpl.io/bW7Q6De
- replace line input field with box input  field
- place the password requirement below the password and it's confirmation.
- button inactive
- make 10% opacity (instead of 5%) on tapped field (as on "Password" field)
- add Show/hide password icon only on focus field
![image](https://user-images.githubusercontent.com/7249484/131704659-961f2312-f443-4cfd-aeb7-f31fd4b3721b.png)

**2) Password filled, confirmation - error** https://zpl.io/beGz67P
- make box in red color (oppacity 15%)
- button inactive
- add error text
![image](https://user-images.githubusercontent.com/7249484/132035318-68bde0c7-700d-4090-bab3-1137446667c3.png)

**3) Password filled and confirmation correct** https://zpl.io/ag5gRMD
- button active
![image](https://user-images.githubusercontent.com/7249484/131704690-47bfbb30-2917-48d9-8581-22a6475412fc.png)

4) Add Show/hide password icon only on focus field 

Text for all password states here https://zpl.io/2jdpgBm
![image](https://user-images.githubusercontent.com/7249484/131828255-2ed84a7e-41ab-4217-bc56-6a44283b3bca.png)

**Comment by KatsiarynaV** [comment]
1. Rename "Create new wallet" to "Create password"
![pagename](https://user-images.githubusercontent.com/68267190/138093650-71e94ac0-3df8-4584-8a76-2406c0c68712.jpg)
![04](https://user-images.githubusercontent.com/68267190/138093657-54a3cce2-337e-492f-9a45-ffcc6caba21b.jpg)

2. Add Show/hide password icon on "Password confirmation" field when it's on focus
![eyeicon](https://user-images.githubusercontent.com/68267190/138094128-004de8c8-eabc-42e8-8ca0-75e1b08541d3.jpg)

3. Make error text "Passwords do not match" italic
![01](https://user-images.githubusercontent.com/68267190/138094377-4aa7032f-78e6-4905-aeb1-cd8bc89fc89c.jpg)
![02](https://user-images.githubusercontent.com/68267190/138094382-6bc14442-c148-4099-adf3-2d2de2f2b01d.jpg)

4. When entering a long password, the password overlaps the eye icon
![22](https://user-images.githubusercontent.com/68267190/138118037-cec616e2-aa70-4efa-97a3-594fadf46054.jpg)

5. Discussed with @dariatarakanova:
- Rename "start using your wallet" button to "next"
![03](https://user-images.githubusercontent.com/68267190/138095316-f3d6009a-2603-45cd-8b5e-e298953b2395.jpg)

- Make smaller password circles as in the design
![20](https://user-images.githubusercontent.com/68267190/138117304-1860d56f-9d83-437a-9eb7-26e8fba63f0f.jpg)
![21](https://user-images.githubusercontent.com/68267190/138117310-2c75b003-825e-4043-91a4-cbc9414c7ea1.jpg)
