### ISSUE TITLE
Transaction details with multiple assets

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#785]
- Show all the CA amounts in tx details (note different colors for sent and received assets) 
- The rate to USD/BTC/ETH should be only shown if it's available at the time of transaction
- Hint "(calculated with the exchange rate at the time of the transaction)" or "(exchange rate was not available at the time of the transaction)" should be shown below "AnountS" field header only for CA transactions details
- add "open in blockchain explorer" icon next to Confidential Asset ID (on the right side of the dialog)
- for Kernel ID leave only green icon (external link), remove text "Open in blockchain Explorer"

Design https://zpl.io/VK9NdGR
https://zpl.io/a3PzEXN

![image](https://user-images.githubusercontent.com/7249484/132004515-7602b77b-0e3c-449e-a148-8a363db818a8.png)
![Uploading image.png…]()

**Comment by glaush** [comment]
[wallet.zip](https://github.com/BeamMW/beam-ui/files/8506464/wallet.zip)
Needed wallet.db for multiple assets transaction.

**Comment by AndreyDyakonov** [comment]
1. Please switch places : first come the assets that we receive (with a + sign), then the assets that we send (with a -sign) as in design 
2. Please add  for Kernel ID  green icon (external link) 

![17](https://user-images.githubusercontent.com/85252690/164452299-8b05c7c7-fe5d-4f81-a2a3-69080fd130b2.png)

**Comment by echoby** [comment]
**Please add for Kernel ID green icon (external link)**
link visible only for successfully completed transactions

**Comment by echoby** [comment]
[wallet.tar.gz](https://github.com/BeamMW/beam-ui/files/8541504/wallet.tar.gz)
pass: 1

**Comment by glaush** [comment]
> 1. Please switch places : first come the assets that we receive (with a + sign), then the assets that we send (with a -sign) as in design
> 2. Please add  for Kernel ID  green icon (external link)
> 
> ![17](https://user-images.githubusercontent.com/85252690/164452299-8b05c7c7-fe5d-4f81-a2a3-69080fd130b2.png)

@AndreyDyakonov, green icon for KernelID is **_only visible_** for transactions that have just completed successfully. In your screenshot, you can see that the transaction was not successful.
