### ISSUE TITLE
Update "Max Privacy longest transaction time" to "Longest transaction time for maximum anonymity" in Privacy settings

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#786]
1) Please change the text to "Longest transaction time for maximum anonymity". https://zpl.io/VDQGzke 
Please pay attention that settings with the dropdown menu are in grey color, not white. 

2) Add comments: https://zpl.io/bWzZxQk
- for "no limit" state: "Transaction can last indefinitely." (the same comment we added for maximum anonymity transaction if "no limit" set in Settings) 
- for 72 hours: "recommended". 72h - is default. 
- show comments only on dropdown, not on Privacy settings block itself

![image](https://user-images.githubusercontent.com/47353570/131673728-944a1acd-3147-4f24-a8b9-b4ed9ef363f3.png)

3) Dropdown is closed https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/612d20bea7d14c119189c269
![image](https://user-images.githubusercontent.com/47353570/131674034-aa1357e5-1d77-4590-99c2-9649d04de0e8.png)

**Comment by kazaryan-t** [comment]
1. Please, put the arrow up when the dropdown menu is open.

![settings-v3-privacy - 01 Desktop Wallet - Zeplin -](https://user-images.githubusercontent.com/68247034/135997203-67a23021-06a0-4e51-a169-b7780da2f49e.png)

![Безымянный](https://user-images.githubusercontent.com/68247034/135997212-043979c4-8689-4790-8460-d5383383f5d1.png)

2. Set the border radius for the dropdown menu.

**Comment by kazaryan-t** [comment]
Checked.
