### ISSUE TITLE
Small amounts of USD equivalents lest than 1 cent should be shown "like < 1 cent" not "0 USD"

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#79]
Current:

![image](https://user-images.githubusercontent.com/846272/87553761-f9c76600-c6bb-11ea-8e14-586279a45ede.png)

Expected:
![image](https://user-images.githubusercontent.com/846272/87553720-ef0cd100-c6bb-11ea-905e-b813c616a805.png)

**Comment by kazaryan-t** [comment]
checked on master 5.0.9426.3029
