### ISSUE TITLE
GPG signing

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#790]
Need to sign our linux wallet AppImage

**Comment by echoby** [comment]
[pub.asc.zip](https://github.com/BeamMW/beam-ui/files/8553208/pub.asc.zip)
To check appimage signature:
1. clone repo https://github.com/Apfelwurm/appimagevalidate.git
2. run
_sudo docker run --rm -it -v $PWD:/work \
 -e APPIMAGEFILE=Beam-Wallet-Masternet-7.0.12633.5257.AppImage \
 -e PUBKEYASC=pub.asc \
 --name appimagevalidate \
 registry.gitlab.com/apfelwurm/appimagevalidate:latest_

**Comment by Sergei-Beam** [comment]
checked
![image](https://user-images.githubusercontent.com/44496108/165139157-f8ca11ad-aab4-45f0-925e-53bd16604a79.png)
