### ISSUE TITLE
Package names

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#791]
Need to complete bringing package & name app name in line with guidelines: make all letters lowercase.

**Comment by chapati** [comment]
Since all other os packages have Came Case (Beam-Wallet....) we will not change appimage name for now to keep name consistent between platforms. Just closing as won't fix.

Check please that all our built packages on all platforms are named as (Beam-Wallet-Branch (except mainnet)-version.exe/AppImage/dmg)

**Comment by Roberrtt** [comment]
checked on the masternet.
task will be closed after checking on the testnet and mainnet
