### ISSUE TITLE
Receive screen: Add comment for Max Anon transactions "Min transaction fee is X.XX BEAM"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#792]
Add comment for Maximum Anonynity transactions "Min transaction fee is X.XX BEAM"

https://zpl.io/aNYw1Xd and https://zpl.io/2GqOPdE

![image](https://user-images.githubusercontent.com/47353570/131215852-bd8efff0-aebd-4d6f-98ea-ce240dadbae0.png)

![image](https://user-images.githubusercontent.com/47353570/131343105-289173f4-837c-49ff-9819-2dd25ef66912.png)

**Comment by KatsiarynaV** [comment]
1. Add a dots in the comments "Min transaction fee is X.XX BEAM." and "Transaction can last at most XX hours."
![01](https://user-images.githubusercontent.com/68267190/135970493-fb4c8767-ec1a-44b1-9115-a44dda371a19.jpg)
![03](https://user-images.githubusercontent.com/68267190/135970502-ed117b27-1fa4-4717-939f-ec9925f24564.jpg)

2. Make indents as in the design
![02](https://user-images.githubusercontent.com/68267190/135970051-87e5223d-fbdc-4cb7-8bb4-ef1bed7e7394.jpg)

**Comment by KatsiarynaV** [comment]
Checked
