### ISSUE TITLE
Change statuses text " ... max privacy" to "... maximum anonymity" and "... max privacy (offline)" to "... (offline)"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#793]
Updated statuses https://zpl.io/b6xJ58q

1) All statuses with "... max privacy" should be with "... (maximum anonymity)" in brackets!
_E.g., status "in progress max privacy" become "in progress (maximum anonymity)"_

2) All statuses with "... offline" should be just "... (offline)"
_E.g., status "in progress offline" become "in progress (offline)"_

3) Update icons for all offline transactions. Now icons have a single line, not double as on maximum anonymity icons.

![image](https://user-images.githubusercontent.com/47353570/131500668-15a0bd72-e708-46a9-aa29-71b4cfbd60e2.png)

**Comment by KatsiarynaV** [comment]
1. For transactions sending and sent to own address statuses should be: 
sending to own address (maximum anonymity)
sent to own address (maximum anonymity) 
sending to own address (offline)
sent to own address (offline)
![01](https://user-images.githubusercontent.com/68267190/132502738-244a5d79-dc74-4ab0-b50d-eb5763bad445.jpg)
![03](https://user-images.githubusercontent.com/68267190/132502739-454179a7-44e0-4ca2-b1fb-2c4d65d8c762.jpg)
![02](https://user-images.githubusercontent.com/68267190/132502266-f6807f61-dc59-45e3-bd89-18cdb34fef94.jpg)
![11](https://user-images.githubusercontent.com/68267190/132502303-e96f686a-759d-42ad-94bf-c621098be4f9.jpg)
![08](https://user-images.githubusercontent.com/68267190/132502321-82a982fc-5fd5-4e24-ad8b-9bcaed3eca24.jpg)
![12](https://user-images.githubusercontent.com/68267190/132502336-bc41de08-a590-4121-97b6-4f2291680553.jpg)

2. Compact view: status “sending to own address (maximum anonymity) doesn’t fit into the field
![15](https://user-images.githubusercontent.com/68267190/132502608-2f8f3b3e-6f9d-4e13-ace2-c941a86b3ea0.jpg)

3. Icons for all offline transactions should have a single line, not double
![09](https://user-images.githubusercontent.com/68267190/132502888-3da0fd1b-dfd8-4d37-9279-47d627b0a56f.jpg)
![14](https://user-images.githubusercontent.com/68267190/132502892-11f85f22-b351-497d-94d1-657dae7f7a96.jpg)
![16](https://user-images.githubusercontent.com/68267190/132503036-1903d002-95df-4877-91c5-3ebcf8715ffa.jpg)

4. For offline transaction with “waiting for receiver” status (vouchers request) status should be “waiting for receiver (offline)” and icon should have a single line
![10](https://user-images.githubusercontent.com/68267190/132503174-4c3c07af-f9d0-44af-9a50-58968c44cd56.jpg)
![13](https://user-images.githubusercontent.com/68267190/132503197-9251ec1c-3ea7-40dc-935f-90b04d5fbbc5.jpg)

**Comment by echoby** [comment]
fixed with af084503f6442f81a8a04c21359a39c52bcf2881

**Comment by KatsiarynaV** [comment]
Place the status in one line if it's fit
![19](https://user-images.githubusercontent.com/68267190/132641692-69d90c2e-5a39-4296-a87f-1032403d4081.jpg)
![20](https://user-images.githubusercontent.com/68267190/132641696-0c52ce09-5847-4827-8c79-3d584333056b.jpg)

**Comment by KatsiarynaV** [comment]
Checked
