### ISSUE TITLE
Make assets icons larger

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#794]
**Problem:** 
icons are too small and hard to recognize
![image](https://user-images.githubusercontent.com/47353570/131390676-dc97664f-37ed-4156-a861-e98db2ee1793.png)

**Solution:**
make icons bigger in tx list and balance cards (26x26 px instead of 20x20 px). Goes after this task https://github.com/BeamMW/beam-ui/issues/585

Design https://zpl.io/254e0d8
![image](https://user-images.githubusercontent.com/7249484/131617426-be241865-a1d0-48ac-9792-bb25a5cb1ffc.png)

**Comment by KatsiarynaV** [comment]
Checked
