### ISSUE TITLE
Replace "More details" with "Address/Token details"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#795]
1) On Create swap offer screen please change "More details" to "Token details" https://zpl.io/aX7GnGx
![image](https://user-images.githubusercontent.com/47353570/131495229-cf1d5714-b2f2-4b09-8db1-d796a136c3a5.png)

Current implementation: 
![image](https://user-images.githubusercontent.com/47353570/131494754-3b2f8334-b76c-4e37-858c-d80a45c6dad6.png)

2) On receive screen: "More details" to "Address details" https://zpl.io/aMXBrZd
![image](https://user-images.githubusercontent.com/47353570/131495069-52d35f98-6cd8-4d3e-909c-0f201c8ee17e.png)

Current implementation: 
![image](https://user-images.githubusercontent.com/47353570/131495025-f5639818-edc3-41a6-b22f-7f72c9374723.png)

**Comment by kazaryan-t** [comment]
Increase the indent between the reduced address and _Address details_ button.

![receive-new-max-privacy-tumbler-off - 01 Desktop W](https://user-images.githubusercontent.com/68247034/136010416-798f67ae-59d3-4fb3-9621-3878372bbb4f.png)

![Beam Wallet Masternet 2021-10-05 12 06 15](https://user-images.githubusercontent.com/68247034/136009437-fd066e6f-e371-44d3-8b66-2561bcdd67a3.png)

**Comment by kazaryan-t** [comment]
Raise a little bit the copy address button, it should place as in the design.

![Beam Wallet Masternet 2021-10-06 15 34 40](https://user-images.githubusercontent.com/68247034/136202852-fc41c1d0-5b1c-455e-a2e2-bcba0efd070a.png)

![Безымянный](https://user-images.githubusercontent.com/68247034/136202857-b8c2d67f-5cbc-459b-b2b6-055744ae9bb7.png)

**Comment by kazaryan-t** [comment]
Checked.
