### ISSUE TITLE
Change text "Dapps Privacy" to "DAPPs Privacy Warning" on dialog and change icon on "open button"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#796]
**Current warning:**
![image](https://user-images.githubusercontent.com/47353570/131390851-068ab1af-b889-4aa2-9a1c-6dd9348d0e44.png)

**Expected warning:**

- Change header to "DAPPs Privacy Warning"
- Rename button to "proceed"
- Change icon 

Design:https://zpl.io/2yMkRYL
![image](https://user-images.githubusercontent.com/7249484/131618833-4bb416f7-5f4b-4bf8-a202-a200d5f747ad.png)

**Comment by echoby** [comment]
According https://github.com/BeamMW/beam-ui/issues/831
Text should be: "DApps Privacy Warning"

**Comment by KatsiarynaV** [comment]
Please remove the space before the question mark and add 's' to the word "address"
![01](https://user-images.githubusercontent.com/68267190/149282430-41dd9cbf-8785-42d3-a2be-a5dab109ae42.jpg)

**Comment by KatsiarynaV** [comment]
Checked
