### ISSUE TITLE
Move button "restore or create new wallet" closer to "show my wallet"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#797]
**Problem:** users can't see "Restore wallet" button and version number.
![image](https://user-images.githubusercontent.com/47353570/131391051-69b7f856-50b9-4307-b49a-b94f0ba23e89.png)

**Solution:**

- Move elements closer to the top and each other (please follow the sizes in the design). 
- Version number should be aligned to the bottom of the window (50px from the bottom), it should be always visible even in the smallest version of the window
- Restore button should be aligned to the bottom of the window (100px from the bottom), it should be always visible even in the smallest version of the window

Design: https://zpl.io/V0NnO1K
![image](https://user-images.githubusercontent.com/47353570/137784173-808e8fb9-2c01-41db-8583-e55bb2f828aa.png)

Logo and slogan positions should be updated on all screens where it showed.
Examples: https://zpl.io/adQx867
https://zpl.io/bAq0P56

![image](https://user-images.githubusercontent.com/7249484/131621813-7a7be090-e865-4ead-9e8a-a7fde606d502.png)
![image](https://user-images.githubusercontent.com/7249484/131621816-b34da2f2-d225-46e2-90bb-c867fa39da13.png)

**Comment by AndreyDyakonov** [comment]
Please make indents between the elements according to the design
1. now the indent = 36, we need 20
<img width="550" src="https://user-images.githubusercontent.com/85252690/155284805-3da04c8a-5ee2-443a-80a7-6e8dc7955a93.png">

2. now the indent = 37, we need 30
<img width="550" src="https://user-images.githubusercontent.com/85252690/155284939-ecaa4097-995e-43c5-a30b-7bc69e8a9026.png">

3. now the indent = 53, we need 50
<img width="550" src="https://user-images.githubusercontent.com/85252690/155285091-12211dbd-38b0-4cb2-aa0c-530f8c6b8dc3.png">

4. now the indent = 79, we need 100
<img width="550" src="https://user-images.githubusercontent.com/85252690/155285187-826f2a17-bbe9-4d13-8342-2e0c169c97ab.png">

**Comment by AndreyDyakonov** [comment]
approved by @gingervik 
checked
