### ISSUE TITLE
UI size on linux

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#798]
UI cannot be resized less than 900 px on linux which is too big for small laptop screens of 1366 x 768. Need to fix

**Comment by chapati** [comment]
This is not repoduced. Seems that a wrong report from community. Please check as we've discussed.

**Comment by Roberrtt** [comment]
The user used a laptop and a monitor.
The laptop has a 1366x768 resolution, and the monitor has a higher.
Therefore, when he opened the wallet, the dimensions were reads up as for a monitor.
Make the minimum height is set to the smallest of all

**Comment by chapati** [comment]
Fixed. Window should also adjust its size automatically if moved to the smaller screen

**Comment by Roberrtt** [comment]
Аеter opening the wallet, its very small size
![2022-02-03_14-37](https://user-images.githubusercontent.com/50007056/152335850-0449d941-4197-4724-812d-082191d53a5a.png)

**Comment by Roberrtt** [comment]
If we move the wallet from the 1920 x 1080  to  1366x768 screen, then the wallet will have a large size
Buttons aren't visible (notifications, doc, settings)

![2022-02-04_10-54](https://user-images.githubusercontent.com/50007056/152492555-a9e0db4f-4dd6-406d-8ae8-0c45ee2a2a75.png)

**Comment by Roberrtt** [comment]
Not fixed

> If we move the wallet from the 1920 x 1080 to 1366x768 screen, then the wallet will have a large size Buttons aren't visible (notifications, doc, settings)
> 
> ![2022-02-04_10-54](https://user-images.githubusercontent.com/50007056/152492555-a9e0db4f-4dd6-406d-8ae8-0c45ee2a2a75.png)

**Comment by Roberrtt** [comment]
checked
