### ISSUE TITLE
Send screen - Max privacy transaction

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#80]
1) Send regular privacy: https://zpl.io/adeyk1l
![image](https://user-images.githubusercontent.com/47353570/87561134-ee2c6d00-c6c4-11ea-93c2-7cea2bfa9f88.png)

2) Send max privacy: https://zpl.io/V4mGZN8
![image](https://user-images.githubusercontent.com/47353570/87561185-fab0c580-c6c4-11ea-8266-4d4654c040ca.png)

3) Send shielded requested: https://zpl.io/VKRBqXW
![image](https://user-images.githubusercontent.com/47353570/87561243-0c926880-c6c5-11ea-81ea-b67a68c5d22d.png)

4) Send confirmation screen: https://zpl.io/bLzJj9Y
![image](https://user-images.githubusercontent.com/47353570/87561285-1e740b80-c6c5-11ea-9a12-9523950931f2.png)

5) Show token https://zpl.io/2jnnkqm
![image](https://user-images.githubusercontent.com/47353570/87561319-2cc22780-c6c5-11ea-8e88-a2b42f510344.png)

**Comment by anatolse** [comment]
deprecated. Close. #85 has newer version
