### ISSUE TITLE
Add "Date" field, replace link in transaction details dialog

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#801]
- Add "Date" field in transaction details dialog
- for Kernel ID leave only green icon (external link), remove text "Open in blockchain Explorer"

Design https://zpl.io/a3PzE9d

![image](https://user-images.githubusercontent.com/7249484/132005703-e6624bf5-91bb-4a19-bb52-608ed5032b35.png)

**Comment by AndreyDyakonov** [comment]
Please change the date display field (as in the design)

in masternet:
<img width="550" src="https://user-images.githubusercontent.com/85252690/152783684-ea56cc9e-4d1b-4181-acb4-fe52a22060f6.png">

in design:
<img width="550" src="https://user-images.githubusercontent.com/85252690/152783689-94c34b67-3249-4ddd-8dfa-f6bc1e3638f8.png">
