### ISSUE TITLE
Change side menu

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#803]
@beam-mw enhancement
<img width="800" alt="Screenshot 2021-09-06 at 14 13 57" src="https://user-images.githubusercontent.com/28015224/132209543-cae24365-bc96-4851-845c-14272fdd7c56.png">

Move address book and notifications items above settings
All dapps (store and dao) items right under swaps + separation line after them

**Comment by Denis-Asipenko** [comment]
checked
