### ISSUE TITLE
Receive screen - shileded/regular transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#81]
1) Regular privacy / 24h expires: https://zpl.io/VDEmndv
![image](https://user-images.githubusercontent.com/47353570/87559280-c2a88300-c6c2-11ea-95b9-4010fa636b86.png)

2) Request max privacy / never expired: https://zpl.io/VqqQwgJ
![image](https://user-images.githubusercontent.com/47353570/87559720-5417f500-c6c3-11ea-876c-0d7276440756.png)

3) Regular privacy, never expires https://zpl.io/aBx3AZ0
![image](https://user-images.githubusercontent.com/47353570/87559621-33e83600-c6c3-11ea-832c-98d1037fe89a.png)

4) Show token https://zpl.io/2p6N80M
![image](https://user-images.githubusercontent.com/47353570/87560007-ab1dca00-c6c3-11ea-9e26-4f107b425f8f.png)

**Comment by gingervik** [comment]
irrelevant
