### ISSUE TITLE
Changing the asset in the regular address does not change the address itself

### ISSUE THREAD

**Issue by AndreyDyakonov** [BeamMW/beam-ui#817]
1. When we use regular address and change asset - address doesn't change
2. When we use this address in other wallet -  asset it is BEAM (regardless of our choice)

Wallet A - sender
Wallet B - receiver

Steps:
- open receive screen in wallet A
- change asset and see if the address is changing
- select an asset other than BEAM and copy address
- open send screen in wallet B 
- paste the address 

Actual:
in send screen in wallet B asset BEAM (not the one chosen by us)

Expected:
in send screen in wallet B asset the one chosen by us in receiver screen in wallet A

https://user-images.githubusercontent.com/85252690/133056399-32b8ad67-9f98-4f7b-b586-3fb84db590d5.mp4

**Comment by echoby** [comment]
Not reproduced on Beam Wallet UI 6.2.11850.4684 (master)

**Comment by AndreyDyakonov** [comment]
Checked
