### ISSUE TITLE
Receive screen - regular/max privacy/non-interactive transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#83]
New design.
Receive screens: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5f106b8f1c13e58e7083814a

1) One-time use / regular. Please make Fee and Comment hidden by default https://zpl.io/bzgDE8l
![image](https://user-images.githubusercontent.com/47353570/87779807-1c7d8a00-c836-11ea-8136-f935c7e6553f.png)

2) One-time use / Max privacy  https://zpl.io/2p6ZGOr
![image](https://user-images.githubusercontent.com/47353570/87779848-299a7900-c836-11ea-80f9-4c743d9058ad.png)

3) One-time use / Max privacy  - fee error https://zpl.io/aBxYJqK
![image](https://user-images.githubusercontent.com/47353570/87779869-3323e100-c836-11ea-82cf-650abdbdd75a.png)

4) Non-interactive ( no text "for transaction ti complete...") https://zpl.io/2p6rJkE
![image](https://user-images.githubusercontent.com/47353570/87779895-420a9380-c836-11ea-91e1-5b7d85bce24a.png)

5) Permanent / regular https://zpl.io/2j6Bn7A
![image](https://user-images.githubusercontent.com/47353570/87779931-52227300-c836-11ea-8189-33477a2df15f.png)

6) Permanent / Max privacy https://zpl.io/a3nY5DA
![image](https://user-images.githubusercontent.com/47353570/87780151-ceb55180-c836-11ea-8433-0a41e292ba3e.png)

7) Show token https://zpl.io/bPJjKvm
![image](https://user-images.githubusercontent.com/47353570/87780126-bc3b1800-c836-11ea-880c-f04b62b11800.png)

8) Save to address book https://zpl.io/bLlAvxG
![image](https://user-images.githubusercontent.com/47353570/87780144-c6f5ad00-c836-11ea-9217-8cccbadaf5f2.png)

**Comment by dariatarakanova** [comment]
Design updates:

1) Remove text "Send token or address to the sender over an external..."

2) Add text "The Min Fee for spend coins will be 1200000 GROTH."
![image](https://user-images.githubusercontent.com/47353570/88035028-35de4900-cb4a-11ea-9bf5-c2994822cfe4.png)

3) Update text on block "For exchange or mining pool" when:
- non-interactive tx https://zpl.io/2p6rJkE
- one-time use token https://zpl.io/bzgDE8l 
- permanent/ max privacy https://zpl.io/a3nY5DA

4) Remove Fee block

**Comment by dariatarakanova** [comment]
@anatolse New design updates:

1) Add "requested" near Amount and make it hidden by default https://zpl.io/2p6ZGOr | https://zpl.io/bzgDE8l
![image](https://user-images.githubusercontent.com/47353570/88160378-385aa480-cc17-11ea-9253-26a62eec799c.png)

2) Change  "The Min Fee for spend coins will be 1200000 GROTH." to "To spend the received Max privacy coins
the min transaction fee will be 1200000 GROTH."

**Comment by dariatarakanova** [comment]
@anatolse design updates:

1) Regular/one-time use. https://zpl.io/bzgDE8l
Leave only "Regular" and "Max privacy" transactions. Right column block rename as "online token (for wallet)", "online token (for exchange or mining pool)".
![image](https://user-images.githubusercontent.com/47353570/88264795-11fb3e80-ccd5-11ea-82d3-0408adb136c3.png)

2) Max privacy/one-time use. https://zpl.io/2p6ZGOr
Right column block rename as "online token (for wallet)", "online token (for exchange or mining pool)" and "offline token (for wallet)"
![image](https://user-images.githubusercontent.com/47353570/88265036-6bfc0400-ccd5-11ea-9229-8e5c4b84f044.png)

3) Regular/permanent. https://zpl.io/2j6Bn7A
Right column block rename as "online token (for wallet)", "online token (for exchange or mining pool)".
![image](https://user-images.githubusercontent.com/47353570/88265125-977eee80-ccd5-11ea-8465-9a7a4dbddff9.png)

4) Max privacy/permanent. https://zpl.io/a3nY5DA
Right column block rename as "online token (for wallet)", "online token (for exchange or mining pool)".
![image](https://user-images.githubusercontent.com/47353570/88265161-a9609180-ccd5-11ea-9b9a-6c45bf875195.png)

5) Show token. Add "Token type". https://zpl.io/bPJjKvm
![image](https://user-images.githubusercontent.com/47353570/88265409-1d029e80-ccd6-11ea-86a8-735ae63b0140.png)

6) Save contact after receive https://zpl.io/bLlAvxG
![image](https://user-images.githubusercontent.com/47353570/88265524-520ef100-ccd6-11ea-9a95-68753466a075.png)

**Comment by Roberrtt** [comment]
1.Change color for "Switch to permanent token" and " Switch to regular transaction"
https://zpl.io/a3nY5DA , https://zpl.io/2p6ZGOr
![Screenshot_69](https://user-images.githubusercontent.com/50007056/88653236-7868ce00-d0d4-11ea-9229-90799aed0796.png)

2. Change text for Max privacy on " Transaction is slower, receiver pays fees."
![Screenshot_74](https://user-images.githubusercontent.com/50007056/88656544-2aa29480-d0d9-11ea-878b-bb2be686ae81.png)

**Comment by Roberrtt** [comment]
checked
