### ISSUE TITLE
Bring the spelling to a common form: "DApp" is correct. ("dapp" or "DAPP" is incorrect )

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#831]
Please fix on screens:
1) Wallet screen, transaction action https://zpl.io/ag1er4O
![image](https://user-images.githubusercontent.com/47353570/136849259-124f6697-0d6d-4531-abaa-6419bfa13b53.png)

2) Notifications screen 
![image](https://user-images.githubusercontent.com/47353570/136849382-527e40c7-d5ca-494a-aef6-095f10f7d6fe.png)

3) Confirmations popup, e.g. Staking DAPP will take the funds from your wallet https://zpl.io/bAKB4zq
![image](https://user-images.githubusercontent.com/47353570/136850011-3acd7ee1-9372-46e3-bd4c-c383e5907bf9.png)

4) Confirmation screens on mobile view https://zpl.io/aNv5Qqk https://zpl.io/2jd7JLW
![image](https://user-images.githubusercontent.com/47353570/136850234-5585ff38-06ad-461a-bddb-45cd3212edb3.png)

5) Install DAPP from a file https://zpl.io/a8DM9vg
![image](https://user-images.githubusercontent.com/47353570/137756874-9486f519-0f4b-4147-897f-0b0d496d2a78.png)

6) Load DAPP file https://zpl.io/aRwOzJg
![image](https://user-images.githubusercontent.com/47353570/137756968-69d53fde-f7e9-4a63-8cd6-db83045bf2b3.png)

**Comment by echoby** [comment]
point 2 fixed
other points is not actual

**Comment by KatsiarynaV** [comment]
Checked
