### ISSUE TITLE
Remove "x" from the dialog with Public offline address

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#832]
Remove "x" from Public offline address in Settings

![image](https://user-images.githubusercontent.com/47353570/137086990-73442ef2-6466-4081-90a6-b84657d507cd.png)

https://zpl.io/bovMywv

**Comment by KatsiarynaV** [comment]
1. Make "copy and close" button color green 
![public offline](https://user-images.githubusercontent.com/68267190/149088689-b1af478c-2df0-45c1-9e39-145425698202.jpg)

2. Change statuses for public offline transactions sending to own address to "sending to own address (**public offline**)" and "sent to own address (**public offline**)"
![01](https://user-images.githubusercontent.com/68267190/149089313-be148182-0b6b-4549-be9f-ece4f24e5daf.jpg)
![02](https://user-images.githubusercontent.com/68267190/149089316-917fd8e0-be34-4f35-9389-410cf7f72687.jpg)
![03](https://user-images.githubusercontent.com/68267190/149089317-a9554e3c-a866-4927-813f-f85d8c33ccd0.jpg)

**Comment by KatsiarynaV** [comment]
Checked
