### ISSUE TITLE
Change highlight color for search results from green to blue

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#834]
To align task #824 please update the color for search highlights. Make it blue with glowing, not green. 
https://zpl.io/beGPzZp
![image](https://user-images.githubusercontent.com/47353570/136023942-903c0053-57f9-4e4c-acc1-2558d72bad23.png)

**Comment by AndreyDyakonov** [comment]
Please change the highlight color of the search result in the same way in the transaction details (General info & Payment proof)

![Безымянный111111](https://user-images.githubusercontent.com/85252690/149755142-00307f84-a7fe-4dda-9678-b59ef2e954ce.png)

**Comment by AndreyDyakonov** [comment]
Checked
