### ISSUE TITLE
Changes in top screen's section. Replace status with new status bar.

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#838]
1) remove status below screen name 
![image](https://user-images.githubusercontent.com/47353570/141098404-310785a5-b696-49c0-838b-731a0e631688.png)

2) move up title section with buttons on all screens. https://zpl.io/aXRmvxX
![image](https://user-images.githubusercontent.com/47353570/141098666-7614579e-bfd7-40a0-91a3-94e37af9be7a.png)

3) Place status icon (circle, padlock) next to the logo in side menu.
![image](https://user-images.githubusercontent.com/47353570/141099239-ed6189c2-8e29-417e-b423-955b3476e77b.png)

4) No need to show status bar if trusted node connected (green padlock)
![image](https://user-images.githubusercontent.com/47353570/141099870-80f27635-d18c-4cdb-8a92-302dc4603354.png)

5) Statuses examples. Please follow each gradients from the design, so we can be sure the text is visible. https://zpl.io/aXRmA4E
![image](https://user-images.githubusercontent.com/47353570/141128120-f47bb5c7-e9ff-459a-a01b-9a19b8b4ef9c.png)

6) Status error line example https://zpl.io/aM3jgDN
![image](https://user-images.githubusercontent.com/47353570/143436240-b8d2451e-2992-48a7-8b5b-fbbb5044ba4e.png)

**Comment by Denis-Asipenko** [comment]
checked

**Comment by Denis-Asipenko** [comment]
- different indicator colors are displayed for different nodes when the node loses connection

![image](https://user-images.githubusercontent.com/45556620/144631036-4d72144a-1040-4c5a-93c6-435e8aafde11.png)
![image](https://user-images.githubusercontent.com/45556620/144631089-075416c3-cf31-47ff-904f-d313c3d9a8a5.png)

- there is also too much text that doesn't fit in one line when the wallet is connected to a random node and doesn't receive an exchange rate

![image](https://user-images.githubusercontent.com/45556620/144631324-2f9fc7eb-23a7-4e8a-885e-a118d922e5ed.png)

**Comment by Denis-Asipenko** [comment]
checked
