### ISSUE TITLE
Improve assets' filter

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#839]
1) Add title "Assets" https://zpl.io/agEMR19
2) Add swither "Selected - All"
3) If no filter applied - make "selected" inactive (20% oppacity)
![image](https://user-images.githubusercontent.com/47353570/144885147-b4a160bf-d8f0-4781-9648-9a98919803a4.png)

4) User can apply a filter just clicking on asset tile. 
When filter applies - add green border to selected tile. 
Show transactions only with selected assets only. https://zpl.io/aRkQnGr
![image](https://user-images.githubusercontent.com/47353570/146202245-16022c90-6298-4a4c-90c0-2cd321d939ef.png)

4.1) Make "Selected" active if filter applied 
![image](https://user-images.githubusercontent.com/47353570/144885944-20f2576a-a6a6-4122-bda2-bf18f7253939.png)

4.2) Add button "remove filter". It will reset all filters.
![image](https://user-images.githubusercontent.com/47353570/146202481-5a063ccd-0559-42f0-9ae2-d8bf6add6910.png)

5) if user select "selected" on swither - hide all unselected assets https://zpl.io/2G3eDlY
![image](https://user-images.githubusercontent.com/47353570/146202732-08e7bb33-ab7b-4d91-8ee6-07b4f14105ac.png)

**Comment by AndreyDyakonov** [comment]
Please make a frame of the same color as the Beam for all selected assets (as on design)
in masternet:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151767700-23b0914f-f9b5-4ce3-b262-5756214a3614.png">

in design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/151767737-8a6c1b8d-33e4-4b26-9f3e-2a69a9f327e1.png">

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by chapati** [comment]
Selection color (green frame) is changed to  asset color. This is discussed and approved by designers.

**Comment by echoby** [comment]
Recheck, pls

**Comment by AndreyDyakonov** [comment]
Checked
