### ISSUE TITLE
build failed on archlinux

### ISSUE THREAD

**Issue by djemilbakhti** [BeamMW/beam-ui#846]
[ 30%] Building CXX object 3rdparty/qhttpengine/src/CMakeFiles/qhttpengine.dir/src/parser.cpp.o
[ 30%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/quazipdir.cpp.o
[ 30%] Building CXX object 3rdparty/qhttpengine/src/CMakeFiles/qhttpengine.dir/src/range.cpp.o
In file included from /var/tmp/yay/beam-ui/3rdparty/qhttpengine/src/src/range.cpp:27:
/var/tmp/yay/beam-ui/3rdparty/qhttpengine/src/src/range_p.h:43:18: error: private field 'q' is not used [-Werror,-Wunused-private-field]
    Range *const q;
                 ^
1 error generated.
make[2]: *** [3rdparty/qhttpengine/src/CMakeFiles/qhttpengine.dir/build.make:146: 3rdparty/qhttpengine/src/CMakeFiles/qhttpengine.dir/src/range.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2377: 3rdparty/qhttpengine/src/CMakeFiles/qhttpengine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 30%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/quazipfile.cpp.o
[ 31%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/buffer.cpp.o
[ 31%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/quazipfileinfo.cpp.o
[ 31%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/get_data.cpp.o
[ 31%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/bufferchain.cpp.o
[ 31%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/quazipnewinfo.cpp.o
[ 31%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/reactor.cpp.o
[ 31%] Building C object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/unzip.c.o
[ 32%] Building C object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/zip.c.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_ioapi.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_JlCompress.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_minizip_crypt.cpp.o
[ 32%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/asyncevent.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quaadler32.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quachecksum32.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quacrc32.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quagzipfile.cpp.o
[ 32%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quaziodevice.cpp.o
[ 32%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/get_headers.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quazip.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quazipdir.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quazipfile.cpp.o
[ 34%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/timer.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quazipfileinfo.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_quazipnewinfo.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_unzip.cpp.o
[ 34%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/address.cpp.o
[ 34%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/tcpserver.cpp.o
[ 34%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/sslserver.cpp.o
[ 34%] Building CXX object 3rdparty/quazip/CMakeFiles/quazip_static.dir/quazip/moc_zip.cpp.o
[ 34%] Linking CXX static library libquazip_static.a
[ 34%] Built target quazip_static
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/sslio.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/tcpstream.cpp.o
[ 35%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/header.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/sslstream.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/proxy_connector.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/errorhandling.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/coarsetimer.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/fragment_writer.cpp.o
[ 35%] Building CXX object beam/utility/CMakeFiles/utility.dir/io/json_serializer.cpp.o
[ 35%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/headers.cpp.o
[ 35%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/heading.cpp.o
[ 35%] Linking CXX static library libutility.a
[ 35%] Built target utility
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/inventory.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/inventory_vector.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/memory_pool.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/merkle_block.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/messages.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/network_address.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/not_found.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/ping.cpp.o
[ 36%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/pong.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/prefilled_transaction.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/reject.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/send_compact.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/send_headers.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/transaction.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/verack.cpp.o
[ 37%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/version.cpp.o
[ 37%] Built target libbitcoin_message
make: *** [Makefile:156: all] Error 2

**Comment by leifliddy** [comment]
What version of gcc are you using? I wasn't able to get beam-ui to compile with gcc 11, but it compiles fine with gcc 10. 
Which is why I created this project for (my distro of choice) Fedora
https://github.com/leifliddy/fedora-beam-ui

Maybe you could try modifying it to suit your needs. I would try compiling beam-ui in an Arch podman container and see if that works --using a version of Arch that uses gcc 10. You should be able to easily modify that Dockerfile in my repo to do that.

**Comment by leifliddy** [comment]
Interesting, I tried compiling beam-ui in an archlinux container 
```
pacman -Sy --noconfirm gcc10 vim rsync git make cmake boost zlib openssl qt5-base extra/qt5-declarative extra/qt5-svg extra/qt5-webengine qt5-tools 
git clone --branch beam-6.2.12495 https://github.com/BeamMW/beam-ui.git /root/beam-ui
cd /root/beam-ui
git submodule update --init --recursive
cmake -D CMAKE_C_COMPILER=/usr/sbin/gcc-10 -D CMAKE_CXX_COMPILER=/usr/sbin/g++-10 -D CMAKE_BUILD_TYPE=Release .
make -j $(nproc)
```
but it failed due to this 
```
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/mnemonic.cpp.o
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/payment_address.cpp.o
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/qrcode.cpp.o
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/utility/CMakeFiles/libbitcoin_utility.dir/flush_lock.cpp.o

In file included from /root/beam-ui/beam/3rdparty/libbitcoin/include/bitcoin/bitcoin/utility/flush_lock.hpp:25,
                 from /root/beam-ui/beam/3rdparty/libbitcoin/src/utility/flush_lock.cpp:19:
/root/beam-ui/beam/3rdparty/libbitcoin/include/bitcoin/bitcoin/unicode/file_lock.hpp:22:10: fatal error: boost/interprocess/detail/posix_time_types_wrk.hpp: No such file or directory
   22 | #include <boost/interprocess/detail/posix_time_types_wrk.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [beam/3rdparty/libbitcoin/src/utility/CMakeFiles/libbitcoin_utility.dir/build.make:132: beam/3rdparty/libbitcoin/src/utility/CMakeFiles/libbitcoin_utility.dir/flush_lock.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1283: beam/3rdparty/libbitcoin/src/utility/CMakeFiles/libbitcoin_utility.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/select_outputs.cpp.o
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/stealth_address.cpp.o
[ 12%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/get_blocks.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/stealth_receiver.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/stealth_sender.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/uri.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/get_data.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/parse_encrypted_keys/parse_encrypted_private.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/get_headers.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/parse_encrypted_keys/parse_encrypted_public.cpp.o
[ 13%] Building CXX object beam/3rdparty/libbitcoin/src/wallet/CMakeFiles/libbitcoin_wallet.dir/parse_encrypted_keys/parse_encrypted_token.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/header.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/headers.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/heading.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/inventory.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/inventory_vector.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/memory_pool.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/merkle_block.cpp.o
[ 14%] Built target libbitcoin_wallet
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/messages.cpp.o
[ 14%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/network_address.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/not_found.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/ping.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/pong.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/prefilled_transaction.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/reject.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/send_compact.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/send_headers.cpp.o
[ 15%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/transaction.cpp.o
[ 16%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/verack.cpp.o
[ 16%] Building CXX object beam/3rdparty/libbitcoin/src/message/CMakeFiles/libbitcoin_message.dir/version.cpp.o
[ 16%] Built target libbitcoin_message
make: *** [Makefile:156: all] Error 2
```
It think this error is related to Arch using ```boost 1.78.0-1```  
that version is too new and doesn't contain the file
```
/usr/include/boost/interprocess/detail/posix_time_types_wrk.hpp
```
Whereas ```boost 1.76.0``` does contain that file.   
I've never really used Arch linux before and don't know if it's possible to downgrade the ```boost``` version or not.  
I hope you figure it out...
