### ISSUE TITLE
DAPPS - Scroll and side indent fixes

### ISSUE THREAD

**Issue by kazaryan-t** [BeamMW/beam-ui#847]
**Before working with the task, need to discuss it with @chapati.**

Need to fix the side indent and scrollbar in Dao Core.

- When the tx list is open, the transaction list tab is wider than the dapp. (screenshot)
- Scrollbar should appear above the application, and not move it to the left. (video)

![Beam Wallet Masternet 2021-10-21 11 16 40](https://user-images.githubusercontent.com/68247034/138263088-af465db7-0dfe-4085-9fa6-44b9fa1389f8.png) 

https://user-images.githubusercontent.com/68247034/138263079-9c2166a3-ce99-4a2d-8ec1-c9ba9c926e55.mp4

**Comment by chapati** [comment]
I'm not sure if it is possible. Anyway this is for the web part, not the C++ Desktop UI
