### ISSUE TITLE
Wrong rates in tx/tx details

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#848]
Wrong rates are displayed in transaction details for contract transactions:

![photo_2021-10-21_16-38-08](https://user-images.githubusercontent.com/12074933/138289264-5b9f127f-0cb4-4f41-a713-a5e118058706.jpg)

Introduced in revision f4af1f5ad5bc014f674fc57ea87042c5978b6f60
assetId in TxObject::getRate(beam::Asset::ID assetId) should not be ignored

**Comment by AndreyDyakonov** [comment]
Checked on masternet
need to check on testnet and mainnet

**Comment by AndreyDyakonov** [comment]
Checked on testnet
need to check on mainnet

**Comment by AndreyDyakonov** [comment]
Checked on mainnet
