### ISSUE TITLE
Send screen - regular/max privacy/non-interactive transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#85]
New design.

Send screens: https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/dashboard?seid=5f104dfedf8f3a832a36c9a9

1) Empty (regular transaction). Please make Fee and Comment blocks hidden by default. https://zpl.io/2ZEonL1
![image](https://user-images.githubusercontent.com/47353570/87779440-7467c100-c835-11ea-9a8a-5b0e5d25af3a.png)

2) Empty (max privacy tx). Fee in BEAM https://zpl.io/awRjOzj
![image](https://user-images.githubusercontent.com/47353570/87779493-85b0cd80-c835-11ea-8468-c1912b46af98.png)

3) Send (max privacy tx) to permanent token https://zpl.io/bLzYW6Q
![image](https://user-images.githubusercontent.com/47353570/87779607-b5f86c00-c835-11ea-906e-c62cc37b5c8f.png)

4) Send (max privacy tx) to one-time token https://zpl.io/a3nYRP1
![image](https://user-images.githubusercontent.com/47353570/87779634-c7da0f00-c835-11ea-8ce0-a67869a3c5d8.png)

5) Max privacy requested https://zpl.io/amkleJ6
![image](https://user-images.githubusercontent.com/47353570/87779656-cf99b380-c835-11ea-931e-0ae5220eb4c4.png)

6) Non-interactive tx https://zpl.io/2GKeWkE
![image](https://user-images.githubusercontent.com/47353570/87779676-dc1e0c00-c835-11ea-88b4-7ab4bab9f90e.png)

7) Send confirmation https://zpl.io/VkqJe8v
![image](https://user-images.githubusercontent.com/47353570/87779709-e809ce00-c835-11ea-99b3-cbb35215539c.png)

8) Show transaction token https://zpl.io/2jnnkqm
![image](https://user-images.githubusercontent.com/47353570/87779732-f3f59000-c835-11ea-8137-9e2da77ad63c.png)

9) Save to address book https://zpl.io/aNg6JRd
![image](https://user-images.githubusercontent.com/47353570/87779750-fce66180-c835-11ea-9051-863237bc5c44.png)

**Comment by dariatarakanova** [comment]
Updates:

1) All Fees in GROTH
2) Add explanation why fee is high https://zpl.io/VDE60Oq

**Comment by anatolse** [comment]
added separate issue for the fee message #88

**Comment by dariatarakanova** [comment]
@anatolse design updates:

1) non-interactive transactions we replace with offline transaction https://zpl.io/2GKeWkE
![image](https://user-images.githubusercontent.com/47353570/88264647-ccd70c80-ccd4-11ea-94fc-c2e23a8cff09.png)

**Comment by dariatarakanova** [comment]
@anatolse no need to show popup dialog with save the name. keep the logic that is now. is user fill comment field - it will be comment in address book.

**Comment by dariatarakanova** [comment]
@anatolse please add numeric delimiters to the fee in GROTH.

Was 1200000 GROTH - should be 1,200,200 GROTH
![image](https://user-images.githubusercontent.com/47353570/88379759-23634a00-cdac-11ea-9dd1-eb706780116a.png)

**Comment by Sergei-Beam** [comment]
1-6 Checked

6) Looks like here additional text fo offline transaction is missed
Actual:
![image](https://user-images.githubusercontent.com/44496108/89050351-4f0da380-d35b-11ea-9b85-7d9d6ac1ffcd.png)
Design: 
![image](https://user-images.githubusercontent.com/44496108/89050449-71072600-d35b-11ea-8710-91e5779f5907.png)

7) There are no changes here according to design
Need to:
- remove **Identity** field
- add **Type** field
- **recipient** field should contain **token**, as I understand
Actual:
![image](https://user-images.githubusercontent.com/44496108/89049577-2933cf00-d35a-11ea-8faf-37a4b55b5b7c.png)
Design: 
![image](https://user-images.githubusercontent.com/47353570/87779709-e809ce00-c835-11ea-99b3-cbb35215539c.png)

8) Field **Token type** is missed for all Show token pop-ups
Actual:
![image](https://user-images.githubusercontent.com/44496108/89049340-c93d2880-d359-11ea-94e3-3f1c1227f02b.png)
Design: 
![image](https://user-images.githubusercontent.com/47353570/87779732-f3f59000-c835-11ea-8137-9e2da77ad63c.png)


Also looks like a forgotten place
Both mean the same value but have a different measure, that can confuse users
Actual:
![image](https://user-images.githubusercontent.com/44496108/89050847-02769800-d35c-11ea-8270-46aad9cb768c.png)
Design:
![image](https://user-images.githubusercontent.com/44496108/89050950-23d78400-d35c-11ea-82c4-7d10e5aca11c.png)

**Comment by anatolse** [comment]
Different units for Fee was accepted by @gingervik

**Comment by anatolse** [comment]
p.6  please, create a separate issue

**Comment by Sergei-Beam** [comment]
p.6 was moved to a separate issue https://github.com/BeamMW/beam-ui/issues/133

**Comment by Sergei-Beam** [comment]
p.7 still have problems

The recipient field in confirmation dialog should contain token or SBBS address depending on what the user paste/enter to field address
- if user paste/enter SBBS address - show SBBS address in field Recipient
- if user paste/enter Token - show Token in field Recipient

Currently, in both cases, it shows SBBS address

**Comment by Sergei-Beam** [comment]
checked
Adding additional text with a counter for an offline transaction was moved to https://github.com/BeamMW/beam-ui/issues/133
