### ISSUE TITLE
BEAMX on mainnet

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#850]
Need to add whitepaper, site url, correct long & short description to 6.2 wallet.
Unfortunately this should be hard coded since DAO contract registered asset without this info.

**Comment by chapati** [comment]
BeamX on mainnet & master should have:

1. Short description "BeamX DAO governance token"
2. Long Description "BEAMX token is a Confidential Asset issued on top of the Beam blockchain with a fixed emission of 100,000,000 units (except for the lender of a \"last resort\" scenario). BEAMX is the governance token for the BeamX DAO, managed by the BeamX DAO Core contract Holders can earn BeamX tokens by participating in the DAO activities: providing liquidity to the DeFi applications governed by the DAO or participating in the governance process."
3. Site URL  "https://www.beamxdao.org/"
4. Whitepaper URL:  "https://documentation.beam.mw/overview/beamx-tokenomics"

**Comment by KatsiarynaV** [comment]
Please add a dot at the end of the sentence
![02](https://user-images.githubusercontent.com/68267190/154656233-189fd929-8667-497d-8ee5-bd8e53f07fb0.jpg)

**Comment by KatsiarynaV** [comment]
Сhecked on masternet
Will be closed after checking on mainnet

**Comment by KatsiarynaV** [comment]
Checked
