### ISSUE TITLE
Ensure that wallet runs on Virtual machine

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#851]
Contact with @Webonnix to be sure that all needed DLLs are deployed to the installer

**Comment by echoby** [comment]
VirtualBox: Ubuntu 20.04 and Windows 10 - works fine
Hyper-V: Ubuntu 20.04 and Windows 10/11 - works fine
Windows 11 Sandbox - can't start

**Comment by Roberrtt** [comment]
+ VMware  Ubuntu 20.04(18.04) and Windows 10
checked
