### ISSUE TITLE
The error message disappears when entering the second symbol to the code in the payment proof verification screen

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-ui#854]
When entering the second additional symbol to the transaction code in the payment proof verification screen error message disappears.

**Precondition:**
A Desktop Wallet is installed and run.
There's at least one completed transaction in the wallet.

**Steps:**
1. Expand the completed transaction to see the transaction details.
![image](https://user-images.githubusercontent.com/83376495/139238878-8d316c60-f851-4592-9165-b4b50c71602e.png)

2. Click on "Payment proof" tab and copy the payment proof code.
![image](https://user-images.githubusercontent.com/83376495/139239041-09c756d2-bafd-458f-9210-680e6a197c83.png)

3. Open "Payment proof verification" screen and paste the copied code.
![image](https://user-images.githubusercontent.com/83376495/139239356-3e45df3f-51f8-458b-b01b-78eac3623d20.png)

4. Type one additional symbol to the pasted code. The error message is shown.
![image](https://user-images.githubusercontent.com/83376495/139240549-b90d4e0c-ecff-410c-b7e9-068df1dde771.png)

5, Type the second additional symbol, the error message disappears.
![image](https://user-images.githubusercontent.com/83376495/139240610-a84f84f3-cd21-4ae8-9c37-80c6730c0db3.png)

6. Type the third and subsequent symbols and the error message appears again.
![image](https://user-images.githubusercontent.com/83376495/139241057-873f06ba-18af-4e11-adf8-c8dd6c6fe3e0.png)

**Expected result:** 
The error message should be shown when entering any additional symbols to the transaction code on the payment proof verification screen.

**Actual result:**
The error message disappears when entering the second additional symbol to the transaction code.

Transaction code which was used as an example:
`80c8b24239cfe9b60215c430324bb8385217ec62b549bd83dc7a2e7747a31d182780fd119885077fe88dd6543383b9456f67738eacbc7db9fb746a7f51066d2865b60400ca9a3bfeb967dbe34bc57ec5e1a44cc12c3ae30196f109c7e788651b111fd4a4e1c164fbc3cfb9510e11c95f12b392f9fcbc1e8caf2b2dfb56afea41338acc2312d32200d87408f79591f8627cb8a104f785aa801a7197ce66299be2c3fc6cbac5e3078b`

**Comment by KatsiarynaV** [comment]
Error message still sometimes disappears when entering the second additional symbol to the transaction code (reproduced just for regular transaction payment proof). Ex: after entering 8 or 0 and then some letter or after entering letters.

![03](https://user-images.githubusercontent.com/68267190/155295667-13635c2e-2811-4d6e-8d5c-3ed0f3037312.gif)

**Comment by KatsiarynaV** [comment]
Checked
