### ISSUE TITLE
When scrolling transactions in APPs  the header overlaps by transaction

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#856]
Steps:
- open gallery
- make some likes
- scroll the tx list
Expected: All scroll correctly 
Actual: When scrolling transactions overlap the header
![image](https://user-images.githubusercontent.com/44496108/139644278-c462fb99-140a-4497-9646-7d10bb607047.png)

**Comment by echoby** [comment]
Not reproduced

**Comment by AndreyDyakonov** [comment]
Checked
