### ISSUE TITLE
Dapp Store is empty, "Failed to load application list, code 0"

### ISSUE THREAD

**Issue by kevzettler** [BeamMW/beam-ui#857]
i'm trying to stake and the Beam X DAO is not showing up in Dapp Store. 
I am on wallet version V6.1.12023.4694
on macOS Big Sur version 11.2.1

![image](https://user-images.githubusercontent.com/126209/139759299-71b2a34a-546c-4890-acd2-ed51f47876a0.png)

also seeing this `"Failed to load application list, code 0"`
error

![beamdappstore](https://user-images.githubusercontent.com/126209/139759262-d1a636d8-199b-4ee0-9cac-7df49eac3e5e.png)

**Comment by gingervik** [comment]
Hello @kevzettler 
I would recommend you to delete beam wallet app and install it again (do not delete your database files, only application itself)

**Comment by kevzettler** [comment]
hi @gingervik I did uninstall and reinstall and the problem persists

**Comment by kevzettler** [comment]
Have just updated to v6.2.12508.4906 This is still broken.

Have attached the wallet logs 
[beam v6.2.12508.4906 osx report.zip](https://github.com/BeamMW/beam-ui/files/7785708/beam.v6.2.12508.4906.osx.report.zip)

**Comment by kevzettler** [comment]
I see that in the Settings -> DAPPs there is:

![image](https://user-images.githubusercontent.com/126209/147590298-7d5bd4ac-5198-43f0-9605-d5ae366a2cff.png)


When I try to connect to that local port there is no server running

```
kevzettler@kevs-mbp-3 ruckus % nc -zv localhost 34700
nc: connectx to localhost port 34700 (tcp) failed: Connection refused
nc: connectx to localhost port 34700 (tcp) failed: Connection refused
```

I suspect this is related the UI app probably does not have correct permissions to spawn that child server process. Have seen this permission problem with other applications on MacOS 

cc @gingervik
