### ISSUE TITLE
Display how much funds receiver gets via online and offline transactions

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#858]
1) For **online** transactions add info how much funds will get the recipient (after fees). https://zpl.io/bA3NzMq
![image](https://user-images.githubusercontent.com/47353570/143865129-e6162ec5-0471-4f77-839b-709905a47a16.png)

2) For **offline** transactions add info how much funds will get the recipient (after fees). https://zpl.io/aM36MoK
![image](https://user-images.githubusercontent.com/47353570/143865167-fd5d2e2f-9920-4966-aa4f-2143204c3133.png)

3) For **Max anonymity** transaction add info how much funds will get the recipient (after fees). https://zpl.io/aN3xLvZ
![image](https://user-images.githubusercontent.com/47353570/143865294-02df81fe-2bb8-4c54-b9c9-ff6e55ad9e43.png)

4) For **Public offline** transaction add info how much funds will get the recipient (after fees). https://zpl.io/a73gKGR
![image](https://user-images.githubusercontent.com/47353570/143908017-38e11baf-b1d7-4d88-bbfa-a0241a159fd8.png)

**Comment by echoby** [comment]
not actual

**Comment by gingervik** [comment]
irrelevant as receiver will get all amount. fee is taken from sender's
