### ISSUE TITLE
Balance is incorrect while transaction is in progress

### ISSUE THREAD

**Issue by ZenoOfCitium** [BeamMW/beam-ui#859]
1. Balance before starting transaction.

![image](https://user-images.githubusercontent.com/93689083/140239571-5cc1008f-c1e7-4af7-b031-201f65a3509d.png)

2. Sending amount, see same balance in background.
![image](https://user-images.githubusercontent.com/93689083/140239786-8910a5af-9c74-4fc0-bf15-fe4d93111af4.png)

3. In progress transaction, balance 1,333.
![image](https://user-images.githubusercontent.com/93689083/140239878-20fe52fd-2d8e-4ace-b532-0c744dd6e2f7.png)

4. Transaction sent, balance correct again.

![image](https://user-images.githubusercontent.com/93689083/140240043-4e71b490-11a3-42d1-bea0-9227f8f30f64.png)

You are also not able to create another transaction while the first one is still in progress because it says you have insufficient funds.

![image](https://user-images.githubusercontent.com/93689083/140608672-2216f0cf-aca2-4d5f-9cbb-bbee67f2ffca.png)

Wallet version: v6.1.12023.4694

![image](https://user-images.githubusercontent.com/93689083/140240262-22b5bb27-06aa-4f54-85e3-c5322bf28f92.png)

OS: Ubuntu 20.04.3 LTS

**Comment by ZenoOfCitium** [comment]
I also notice that there is a subtext that says "locked beam 869.896" which is approximately the difference.

**Comment by gingervik** [comment]
Hi. this is how our wallet works - we lock UTXO which is used for transaction and get change after it is finished

**Comment by ZenoOfCitium** [comment]
Thanks for the feedback, might I suggest displaying what the will balance be and indicate to the user that they can't create another transaction while one is in progress. Essentially abstracting the intricacies of technical implementation away from the user.
