### ISSUE TITLE
BeamX DAO: Weekly reward shown as more if 1 week is selected vs if 3 months is selected.

### ISSUE THREAD

**Issue by ZenoOfCitium** [BeamMW/beam-ui#860]
![image](https://user-images.githubusercontent.com/93689083/140241167-e4066c50-bd23-4e3f-b9ea-da017e425aa1.png)

![image](https://user-images.githubusercontent.com/93689083/140241045-2f323e70-233d-4326-83c1-df33155c6a8a.png)

Wallet version: v6.1.12023.4694

![image](https://user-images.githubusercontent.com/93689083/140240262-22b5bb27-06aa-4f54-85e3-c5322bf28f92.png)

OS: Ubuntu 20.04.3 LTS

**Comment by gingervik** [comment]
fixed
