### ISSUE TITLE
Add "Action" to TX list on Wallet screen

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#861]
**This is an optional task. If you think we don't need this column on the Wallet screen - please do not do it.**

Add column "Action" after "Source" where display source action (as on design) https://zpl.io/293w8BA
![image](https://user-images.githubusercontent.com/47353570/140492526-ae1f6c40-b095-48f1-be7d-0fbc3e65ab55.png)

**Comment by sasha-abramovich** [comment]
If amount is zero, the "amount" column should have no value

**Comment by echoby** [comment]
![image](https://user-images.githubusercontent.com/1681548/143411644-1e261218-ba75-4312-8081-13c9560e4246.png)
We had not enough space to show this column on Wallet screen

**Comment by AndreyDyakonov** [comment]
Checked
