### ISSUE TITLE
Add filter "Show transactions"

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#863]
1) Please add this filter to main transaction (Wallet screen) and for DApps transactions.

2) Default is - Show: All https://zpl.io/2vXOyk7

![image](https://user-images.githubusercontent.com/47353570/140325387-c2fc2092-8d85-4be3-9fbe-e269161999e6.png)

3) All filter states here https://zpl.io/bL3dBmd
![image](https://user-images.githubusercontent.com/47353570/140312628-00776d72-8c04-463b-858b-478823ce8185.png)

4) Placeholder for "Show None" filter https://zpl.io/V4Xev0y
![image](https://user-images.githubusercontent.com/47353570/140328525-5f5331a8-40a9-4256-9669-e88e9184a5b0.png)

**Comment by AndreyDyakonov** [comment]
1. Filter drop-down window in fullscreen mode is too large, please make it the same size as in window mode

fullscreen mode:
![2022-01-24_09-42-01](https://user-images.githubusercontent.com/85252690/150735848-6d092eeb-b0cc-4bc0-9a45-ace9ee36d660.png)

window mode:
![2022-01-24_09-41-32](https://user-images.githubusercontent.com/85252690/150735897-c991380f-7faf-4d78-a0a0-00ea3c284225.png)

2. Selected filter"in progress" "in progress  +1" "in progress +2" doesn't fully  display in window mode in DApp transactions list 

![2022-01-24_09-42-51](https://user-images.githubusercontent.com/85252690/150736815-ddfcefcd-069b-45f7-a22f-88e669e9e074.png)

**Comment by AndreyDyakonov** [comment]
If you expand the list of transactions, transactions and actions with them go beyond the list in DApp tx list in window mode

![2022-01-25_11-27-03](https://user-images.githubusercontent.com/85252690/150940577-2ba27036-010d-43aa-ad95-9963d282f7dc.png)

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by AndreyDyakonov** [comment]
1. Please reduce the size of the field according to the design
example: 
<img width="450" src="https://user-images.githubusercontent.com/85252690/155348280-920690fd-6e75-4868-930e-45ce893d0a8a.png">

1.1 For field "All"
master:
<img width="450" src="https://user-images.githubusercontent.com/85252690/155348465-2317f66a-d2fd-4200-9209-02700a36df7a.png">
design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/155348500-ff331657-fcf0-4cd8-a3a6-f1d463085eaa.png">

1.2  For field "None"
master:
<img width="450" src="https://user-images.githubusercontent.com/85252690/155348643-5a3be2e2-df7a-431f-a8d7-a3590f9da075.png">
design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/155348700-b9441e9f-31fe-4ca4-b2a8-b14fe79324a9.png">

2. Please change the image and description below the image
master:
<img width="450" src="https://user-images.githubusercontent.com/85252690/155349124-6d02def3-1e95-4666-9381-b8a341e1a46b.png">
design:
<img width="450" src="https://user-images.githubusercontent.com/85252690/155349185-0b30c8a3-7302-4197-96fa-839bd0baf73c.png">

**Comment by AndreyDyakonov** [comment]
Please align the pop-up window to the right edge of the field

![2022-03-10_16-27-06](https://user-images.githubusercontent.com/85252690/157672489-240677b4-cdec-46a9-952d-547d347e6007.png)


https://user-images.githubusercontent.com/85252690/157672583-1c17d7a2-b5c8-497d-ae2e-c97fb9fee5ab.mp4

**Comment by AndreyDyakonov** [comment]
Checked
