### ISSUE TITLE
Show wallet balance in DApps

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/beam-ui#866]
1) Add "Wallet balance" to Transaction tab. Do not highlight it until it is open https://zpl.io/a73OeEK
![image](https://user-images.githubusercontent.com/47353570/140322591-07985a9a-766f-41fb-b954-7b020676b009.png)

2) Rename "Transactions" to "{Dapp name} transactions"  https://zpl.io/bA34B7p
![image](https://user-images.githubusercontent.com/47353570/140322058-41c43723-48bf-4447-b03c-2c04538c5ff4.png)

3) Wallet Balance view https://zpl.io/25lOpQW

4) Add "Hide show amounts" checkbox.
_Need to discuss what is small amount?_

![image](https://user-images.githubusercontent.com/47353570/140322160-aceda643-192d-4eff-8969-5087130e8424.png)

"Wallet balance" tab has a smaller height than "Transactions" tab. So when user clicks on "balance" tab, the block should shrink to the required height for the blocks of coins to fit.

**Comment by AndreyDyakonov** [comment]
Checked
