### ISSUE TITLE
The wallet is being locked while users scroll NFT gallery

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-ui#867]
1) Open the wallet;
2) Navigate to the settings screen;
2) Expand the "General" tab and set up a 1-minute lock screen;
3) Navigate to the DAppe Store;
4) Click the "launch" button opposite NFT Gallery;
5) Scroll the NFT Gallery screen for a minute (cursor is on the NFT gallery screen);
**Expected result:** wallet is not being locked while scrolling NFT Gallery.
**Actual result:** lock screen appears.

**Comment by AndreyDyakonov** [comment]
it is not done
if you set the lock screen for 1 minute or more, and then go to the NFT gallery and scroll the NFT gallery screen for a minute or more - the lock screen will appear

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by echoby** [comment]
We need find another way to handle mouse events on WebEngineView

**Comment by kovaletskaterina** [comment]
Checked
