### ISSUE TITLE
2nd Wallet opening 

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#869]
When the wallet is already running and we rung the 2nd wallet for the same database it can rash or just doesn't open.
Need to detect this situation and show message to the user.

**Comment by chapati** [comment]
![gnome-shell-screenshot-Y26YC1](https://user-images.githubusercontent.com/12074933/142259286-fc74d574-2ec4-4384-82c0-ed1018119561.png)

1. 'Already running' state is not correctly detected sometimes. On the screenshot above - 1 wallet in process explorer, but error is still shown.

2. When duplicate wallet is detected start button becomes disabled. Start entering the password -> error message disappears and it is not clear whats going on:

![gnome-shell-screenshot-XKS8C1](https://user-images.githubusercontent.com/12074933/142259689-b3ddb4fc-9a66-4da4-8f7a-412182ce0d5c.png)

Need to disable password input 

3. Restore/create new wallet button is still enabled. Need to disable it as well.

4. Need to make error message more clear: "The wallet is already started. Close all opened wallets and try again."

**Comment by KatsiarynaV** [comment]
Checked
