### ISSUE TITLE
Send screen: Add messages to fee if tx has shielded inputs 

### ISSUE THREAD

**Issue by anatolse** [BeamMW/beam-ui#88]
Add explanation why the fee is high https://zpl.io/VDE60Oq

**Comment by anatolse** [comment]
it's not enough to add this message for `isShieldedTx`. It also should be shown if we perform a regular transaction, but shielded coins were selected

**Comment by Roberrtt** [comment]
need to recheck when this task is ready https://github.com/BeamMW/beam-ui/issues/125

**Comment by Denis-Asipenko** [comment]
checked
