### ISSUE TITLE
Some files are not being installed under the install prefix, which by default is /usr/local

### ISSUE THREAD

**Issue by leifliddy** [BeamMW/beam-ui#882]
After running ```make install``` I see the following files being copied to my local filesystem.
```
-- Install configuration: "Release"
-- Installing: /usr/local/bin/generate-sid
-- Installing: /usr/local/bin/BeamWallet
-- Installing: /usr/local/bin/beam-wallet.cfg
-- Installing: /usr/share/applications/beam.desktop
-- Installing: /usr/share/applications/beam.xml
-- Installing: /usr/share/icons/beam.png
```

So my questions are:
1. why is ```beam-wallet.cfg``` being installed to a **/bin** directory, it's a config file, NOT a binary.  
And if I run the following:
```
[leif.liddy@black ~]$ cd /tmp/
[leif.liddy@black tmp]$ strace BeamWallet 2>&1 | grep beam-wallet.cfg
openat(AT_FDCWD, "/tmp/beam-wallet.cfg", O_RDONLY) = -1 ENOENT (No such file or directory)
```
You'll see that ```BeamWallet``` is just looking for ```beam-wallet.cfg``` in the current working directory.   
It's not hard-coded to look for it in ```/usr/local/bin```  
So, I'm not sure what purpose that file even serves....

2. If you look at the contents of ```beam.desktop``` 
```[Desktop Entry]
Version=1.0
Name=Beam Wallet@BEAM_DISPLAY_SUFFIX@
Comment=Scalable confidential cryptocurrency
Exec=/usr/bin/BeamWallet@BEAM_SUFFIX_UPPER_CASE@ %f
....
```
You'll see it has the ```/usr/bin/``` path is hard-coded in it. 
That path should be set to the install prefix used when compiling beam-ui --which by default would be ```/usr/local```, so it should have the ```/usr/local/bin``` path defined when installing using the default install prefix. 

3. Why are ```beam.desktop, beam.xml, beam.png``` being installed to ```/usr/share/{applications, icons}``` when the install prefix is set to ```/usr/local```?  
When the install prefix is set to ```/usr/local``` they should be getting installed to ```/usr/local/share/{applications, icons}```  

Although I realize that not every distro creates these two directories by default: ```/usr/local/share/{applications, icons}```   
So they would need to be created by ```make install``` if they don't exist. Actually the more I think about this, the more I realize that more testing would need to be done to ensure that every major distros supports this.  Although, I'm fairly confident that most distros would support this path (F35 does for example)
Ok, maybe omit this one for now --until we have absolute certainty on this. 
I can perform some testing later on various distros to test this out.   

4. ```/usr/share/applications/beam.xml```
Where do I start with this....
Ok, first of all ---all mime type xml files are installed to either
```/usr/share/mime/packages/```
or
```/usr/share/mime/application/```
NOT to ```/usr/share/applications```

For this file ```/usr/share/mime/application/``` is the correct location. 

Second of all, it should be installed using the default install prefix. 
So, if the install prefix is ```/usr/local```, this file "should" be installed under ```/usr/local/share/mime/application/```  

Although, similar to my comments on item#3, the ```/usr/local/share/mime/application/``` path would be need to be tested out.
So maybe omit this prefix install path change for now. 

In the meantime, installing ```beam.xml``` to ```/usr/share/mime/application/``` would be an improvement. 

And lastly, I'm not even sure what the purpose is of ```beam.xml``` actually is
It defines the following mime type:
```<glob pattern=".dmx" weight="50" />```
I have no idea what a **.dmx** file is? Could someone please explain what a **.dmx** file is and how it relates to the BeamWallet application?

**Comment by chapati** [comment]
Fixed in #892
