### ISSUE TITLE
DAO error on masternet

### ISSUE THREAD

**Issue by chapati** [BeamMW/beam-ui#887]
Need to investigate what's going on here.

![gnome-shell-screenshot-EUSFF1](https://user-images.githubusercontent.com/12074933/148786677-92b6a900-c94d-4561-bf6d-d1826864c2d6.png)

**Comment by chapati** [comment]
Please test that

1) DAO Works on masternet
2) That DAO is not crashed when pressing back button (try several times)

After tested DO NOT CLOSE THIS BUG, move to the next version.

Without fix in https://github.com/BeamMW/beam/commit/ed2e347e475842655bccc400acadfc38b87f9c5f shaders manager stuck in ManagerStd::StartRun->RunSync and when back is pressed ManagerSTD is destroyed before sync reactor is released 
This would be fixed by vlad, but needs to be checked again after his fix.

**Comment by KatsiarynaV** [comment]
Checked
