### ISSUE TITLE
[DAPPS] The notification list should move down if the first notification disappeared

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#891]
The tx notification list should move down if the first notification disappeared
Currently, if previous notifications are disappeared the tx notifications are still placed where they were when the list was formed 
![image](https://user-images.githubusercontent.com/44496108/149922929-a933a315-6264-461d-bd43-c2839f5c6aec.png)
![image](https://user-images.githubusercontent.com/44496108/149923014-5b0b3d71-2306-446a-986c-60b2c6722c73.png)

Steps:
-  go to any DAPP
- make a few transactions from different DApp
- wait while one of the first tx is finished
Expected: The notification list should move down if the first notification disappeared
Actual: if previous notifications are disappeared the tx notifications are still placed where they were when the list was formed

**Comment by AndreyDyakonov** [comment]
Checked
