### ISSUE TITLE
Side menu / voting

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#898]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A1818

To add voting icon in side menu
<img width="126" alt="Снимок экрана 2022-01-27 в 14 48 37" src="https://user-images.githubusercontent.com/94360080/151692265-54bbd0c2-9f2f-483b-af2c-e24f2281ac70.png">

**Comment by KatsiarynaV** [comment]
Checked
