### ISSUE TITLE
Scroll does'nt work if there are more than 11 assets in wallet

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#899]
--pass=password
[wallet.tar.gz](https://github.com/BeamMW/beam-ui/files/8108803/wallet.tar.gz)

https://user-images.githubusercontent.com/50007056/154929805-77e3a230-544a-428f-8a1d-3d8b380193b1.mp4

**Comment by chapati** [comment]
@echoby this happened after you've added seedValidationRow. If seedValidationRow is commented everything works fine. Please fix.

**Comment by echoby** [comment]
Please, recheck all cases when "Seed validation promo" appears

**Comment by AndreyDyakonov** [comment]
When opening (or creating a new) wallet, a "seed validation promo" appears (in wallet screen and in DApp wallet balance), this window cannot be closed, and an attempt to pass validation leads to the closure of the wallet

https://user-images.githubusercontent.com/85252690/157635198-7c940a54-7c38-4078-8dba-66d1666ab99c.mp4


https://user-images.githubusercontent.com/85252690/157635214-6e75839a-db49-40c7-beae-70131efbf62b.mp4

**Comment by AndreyDyakonov** [comment]
Checked
