### ISSUE TITLE
Dapp store/ Personal user's main page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#902]
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=150%3A926
<img width="732" alt="Снимок экрана 2022-02-22 в 13 22 44" src="https://user-images.githubusercontent.com/94360080/155116042-cbb86b00-58c3-416b-a5e7-78350de03b42.png">
1. My Dapps - clickable - goes to the main page My Papp store
2. Beam Dapps - hide, will be in the latest release
3. Link to the Publishers List (separate task) #903 
4. Become a publisher - Link to pop-up with form for publisher. (separate task) #905
5. Beam's app card (separate task) #911
6. Users app card.  (separate task) #911 
7.  present form to upload dapp from the file.

![image_2022-02-17_14-55-16](https://user-images.githubusercontent.com/94360080/155118079-f691f7a4-ffd8-488b-8fd1-1ae7910af24f.png)

**Comment by AndreyDyakonov** [comment]
Checked
