### ISSUE TITLE
Dapp store / Publishers that I follow 

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#903]
On the main page, click on the icon **3** goes to page Publishers that I follow 
<img width="549" alt="Снимок экрана 2022-02-22 в 13 22 44" src="https://user-images.githubusercontent.com/94360080/155126245-82331dff-5786-4e84-ab05-59bc6abe24e5.png">

https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=7%3A1571
<img width="661" alt="Снимок экрана 2022-02-22 в 14 45 50" src="https://user-images.githubusercontent.com/94360080/155126573-a068667b-f71e-4a85-8c7c-b3da9faf4557.png">

1. Back button 
2. Add publisher. separate task BeamMW/beam-ui#904 
3. Table with 4 columns: Nickname, about, Social networks, publisher links (structure at Become a publisher task #905 )
4. Nickname (**without** verification circle for this release), short title
5. Publisher description (separate task) #905  
6. Social networks (separate task) #905 
7. publisher links. click on the three dots open extra menu:
7.1  where user can on/off displaying this publishers app on it's main page. tune off publisher's apps from the main page, **but** publisher is still in users list
7.2 copy publisher key and share with this key
7.3. remove from my list - remove apps and publisher from user's acc.

**Comment by VikMaevskaya** [comment]
some changes in social networks. Web icon added

<img width="802" alt="Снимок экрана 2022-03-07 в 15 00 05" src="https://user-images.githubusercontent.com/94360080/157030631-64cbd76b-bf5f-404d-9fe3-851925950214.png">

**Comment by VikMaevskaya** [comment]
in this release will not be
- sorted in the column about
- "show in my dapp store". 

maybe implemented later

![photo_2022-04-05_12-09-53](https://user-images.githubusercontent.com/94360080/161744838-4ee57e89-25b4-4b6c-a7a3-edca7edddec5.jpg)

**Comment by kovaletskaterina** [comment]
Checked
