### ISSUE TITLE
Dapp store / become a publisher

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#905]
On the main page, click on the icon 4 goes to Become a publisher pop-up
<img width="661" alt="Снимок экрана 2022-02-22 в 15 27 40" src="https://user-images.githubusercontent.com/94360080/155134721-70c37995-df6b-4883-9bc2-9d6ffb4d5da6.png">

https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=13%3A1145
<img width="535" alt="Снимок экрана 2022-02-22 в 15 29 15" src="https://user-images.githubusercontent.com/94360080/155132685-ca335ec6-a070-41ce-bc78-e82e1b8b6762.png">

Nickname is required field, the others - not.
at social networks fields displayed examples how user must to fill the string
After nickname is, Create account button become active
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A1336
<img width="504" alt="Снимок экрана 2022-02-22 в 15 34 31" src="https://user-images.githubusercontent.com/94360080/155133394-7cf7c9f7-c08d-4ee0-83a4-1ea648972511.png">

push **create account** goes to proof of payment. It will cost nothing, but network will take commission
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A2328
<img width="268" alt="Снимок экрана 2022-02-22 в 15 37 05" src="https://user-images.githubusercontent.com/94360080/155133748-6fcc92e5-f95a-4c9b-8c2e-0c24cd00844f.png">

while transactions is send. system block wallet and shows the window and notification
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A1887
 <img width="679" alt="Снимок экрана 2022-02-22 в 15 39 15" src="https://user-images.githubusercontent.com/94360080/155134086-e825d7fd-807f-424e-880c-b0a7e5257d1b.png">

after transaction is approve, user will see window with text, publisher key, button to copy publisher key, go to my account button.
**go to my account** button goes to **publisher's page** (separate task #906 )
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=144%3A935

<img width="514" alt="Снимок экрана 2022-02-22 в 15 42 55" src="https://user-images.githubusercontent.com/94360080/155134645-51917331-9f4c-46fd-a6ea-f7d6ade4ca2b.png">

**Comment by roman-strilets** [comment]
validators in a separate task #916

**Comment by Roberrtt** [comment]
1.Add text "BEAM DAPPS" in the upper left corner (1 screen number 2 )
![2022-03-23_16-42](https://user-images.githubusercontent.com/50007056/159713620-29e13433-3054-4ecb-9ab6-6a8871692fea.png)
2.If we entered nickname button "create account' isn't available 
![2022-03-23_16-01](https://user-images.githubusercontent.com/50007056/159706746-15c4a291-f641-4e1f-b8be-79666ffd07d2.png)
3.Buttons "cancel" doesn't work on "Become a publisher' screen
4. Change color and up arrow on proof of payment screen and change title from "Confitrm application transaction" to " Confirm transaction"
![2022-03-23_16-02](https://user-images.githubusercontent.com/50007056/159707297-0768ea05-d3fe-42d6-9908-380021db9a4f.png)
5. If possible, fix the icons, they are more stretched than on the design
![2022-03-23_16-14](https://user-images.githubusercontent.com/50007056/159707938-7d7240e0-135a-4c61-a7d9-9d9de5189b91.png)
6.Transaction failed but there's no button "go to my account" on "transaction is send" window and notification 
7. If the transaction falls, do not open the "Now you are the publisher" window

**Comment by Aleksandr-Starun** [comment]
1) Beam Dapps is hidden in this version, it'll be implemented in the next

**Comment by Roberrtt** [comment]
In the links for linkindin and discord, the symbol "-" can be written, we need to add the ability to enter it

**Comment by Roberrtt** [comment]
checked
