### ISSUE TITLE
Dapp store / publishers personal acc

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#906]
when user create his publishers acc, his publishers page is blank

https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A5987
<img width="688" alt="Снимок экрана 2022-02-22 в 16 10 54" src="https://user-images.githubusercontent.com/94360080/155139486-db7c8ea2-f516-419e-8d53-8ba304082283.png">
0. title **My Dapps**
1. drag-and-drop area to upload user's first dapp( separate task #909 )
2. button to upload user's app if he has several( separate task #909 )
3. pop-up button - copy publisher key( separate task #907 )
4. change publishers settings( separate task #908 )

**Comment by KatsiarynaV** [comment]
1. Make icon size smaller as in the design
![01](https://user-images.githubusercontent.com/68267190/160618838-0ee01f30-f85e-4749-829c-55a9ec1157a9.jpg)
![02](https://user-images.githubusercontent.com/68267190/160618846-fbd1900d-915c-4428-8328-bdb4b24310e2.jpg)

2. drag-and-drop area to upload user's first dapp (icon 1) isn't working
![05](https://user-images.githubusercontent.com/68267190/160619601-1f312b0c-a5f0-4e8a-b9b7-32b8b2c422cb.jpg)
![04](https://user-images.githubusercontent.com/68267190/160619140-d04612ec-0ed2-4a8a-8b2e-31d606000c1e.jpg)

**Comment by KatsiarynaV** [comment]
Please, remove the dotted square from the icon
![07](https://user-images.githubusercontent.com/68267190/161018747-f146494f-c0bc-490a-b330-59aeb5a7912f.jpg)

**Comment by KatsiarynaV** [comment]
Checked
