### ISSUE TITLE
Dapp store / copy publishers key

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#907]
On the **Publishers page**, click on the icon **4** goes to pop-up where publisher can copy his publisher's key
<img width="715" alt="Снимок экрана 2022-02-22 в 16 22 42" src="https://user-images.githubusercontent.com/94360080/155141272-6ed32c55-48f8-40ac-8263-ffa67b5f7809.png">

https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A2715

<img width="490" alt="Снимок экрана 2022-02-22 в 16 25 29" src="https://user-images.githubusercontent.com/94360080/155141394-b6f427ce-f77d-4fcc-90b8-280071748ae5.png">

**Comment by AndreyDyakonov** [comment]
Please make the text "Publisher key" bold as in design 

<img width="450" src="https://user-images.githubusercontent.com/85252690/160626520-531d1e04-c28d-425a-ae94-9cfeba1f7e1d.png">

**Comment by AndreyDyakonov** [comment]
Checked
