### ISSUE TITLE
Dapp store / change publisher's info

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#908]
On the Publishers page, click on the icon **3** goes to pop-up where publisher can copy his publisher's key
<img width="715" alt="Снимок экрана 2022-02-22 в 16 22 42" src="https://user-images.githubusercontent.com/94360080/155277153-c72e5e68-aeb9-4267-a3e0-f25d71346c31.png">

pop-up with fill in personal info. User can change anything he wants. changes won't be save without nickname. 
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A5673
<img width="560" alt="Снимок экрана 2022-02-23 в 10 32 08" src="https://user-images.githubusercontent.com/94360080/155277501-61808340-4753-42ea-9a9b-edcc370b22f7.png">

After user make all changes and **save changes**
opens confirmation transaction window. 
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=168%3A922
<img width="301" alt="Снимок экрана 2022-02-23 в 10 38 11" src="https://user-images.githubusercontent.com/94360080/155278115-cf41efbd-9f9b-4f57-871a-4451ce168fba.png">

When user **confirm** transaction
The wallet blocked and user see Notification. after transaction was sent, user come back on the page where he started changes.
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=168%3A1319
<img width="742" alt="Снимок экрана 2022-02-23 в 10 41 54" src="https://user-images.githubusercontent.com/94360080/155278463-35dd2ab6-42fe-48bf-b76e-df0a4d233a7e.png">

**Comment by VikMaevskaya** [comment]
Info text was deleted
<img width="421" alt="Снимок экрана 2022-03-07 в 15 03 48" src="https://user-images.githubusercontent.com/94360080/157031117-61caa5cf-e9c5-483d-859e-c77a035d704a.png">

**Comment by AndreyDyakonov** [comment]
1 Publisher info
1.1 Please if it possible  make this text oblique (1)
1.2 Please add in "About me" field character counter (entered/total) (2)
1.3 Please change "arrow" to "checkmark" in "save changes" button (3)

![2022-04-01_16-48-24](https://user-images.githubusercontent.com/85252690/161280532-66144134-32c6-4a33-a143-fa631bbbb1e4.png)

2 Please change the title in the confirmation window

![2022-04-01_16-50-36](https://user-images.githubusercontent.com/85252690/161280952-87e07af3-b49e-44f8-9df8-57dd7a9c132d.png)

3 Please make the text "The transaction is sent" bold and make frame around this window as in design

![2022-04-01_16-51-21](https://user-images.githubusercontent.com/85252690/161281131-1c558756-6774-49f9-8503-78804728cb4a.png)

**Comment by Aleksandr-Starun** [comment]
1.2 We will not implement it in the current version.
2 It's default confirmation dialog

**Comment by AndreyDyakonov** [comment]
Checked
