### ISSUE TITLE
Dapp store / upload dapp by publisher

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#909]
On the Publishers page, click on the icon **2** goes to pop-up where publisher can upload his dapp
<img width="715" alt="Снимок экрана 2022-02-22 в 16 22 42" src="https://user-images.githubusercontent.com/94360080/155278816-07523e0e-fc23-4378-a45a-b0c8b57cfc71.png">

Opens form for uploading app
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A3838
<img width="720" alt="Снимок экрана 2022-02-23 в 11 02 46" src="https://user-images.githubusercontent.com/94360080/155280823-13a45781-5307-43be-849c-2801a4eb9730.png">

If system doesn't accept file, user will see notification. **continue button is not active**
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A4371
<img width="547" alt="Снимок экрана 2022-02-23 в 11 04 56" src="https://user-images.githubusercontent.com/94360080/155281097-8bc2233d-934d-4756-883c-435b684ce70d.png">

If system accepts file, user will see image with uploaded file.
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A4100
<img width="546" alt="Снимок экрана 2022-02-23 в 11 13 11" src="https://user-images.githubusercontent.com/94360080/155282050-07223913-f2bf-4847-bb1b-a6909898512d.png">

press **continue** button.
user see an image how his dapp will be looked at the dapp store and other info from the file.
**cancel** - send user to the the page where hi started to upload dapp
**Publish** - to confirm transaction
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A4642
<img width="613" alt="Снимок экрана 2022-02-23 в 11 16 14" src="https://user-images.githubusercontent.com/94360080/155282449-38144838-d043-4242-ba52-e8d0ba797609.png">

** confirm transactions**
**cancel** - send user to the the page where hi started to upload dapp
**Confirm** - to Publisher's page with uploaded dapp
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A4915
<img width="327" alt="Снимок экрана 2022-02-23 в 11 28 35" src="https://user-images.githubusercontent.com/94360080/155284083-99554b62-3c3f-4b81-b82d-547e922ca9b1.png">

Publisher's page with uploaded dapp. Transaction notification
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A5181
<img width="580" alt="Снимок экрана 2022-02-23 в 11 37 57" src="https://user-images.githubusercontent.com/94360080/155285382-60268234-09a2-4dde-a8af-b564d9b4e0cc.png">

**Comment by VikMaevskaya** [comment]
@Aleksandr-Starun some changes in design

<img width="733" alt="Снимок экрана 2022-03-15 в 11 41 33" src="https://user-images.githubusercontent.com/94360080/158339491-c7121297-51a3-4b93-96f6-9a9150c1ba5e.png">

**Comment by Aleksandr-Starun** [comment]
It was decided to abandon the pop-up message with link to TX details in the current version.

**Comment by Roberrtt** [comment]
1. Change title "My DAPPS - ADMIN Panel"  and "PUBLISHER'S PAGE "as on design separated by space 
![2022-03-29_13-02](https://user-images.githubusercontent.com/50007056/160587027-f50bc188-69a6-4327-b2b6-b0582607a66f.png)
![2022-03-29_13-17](https://user-images.githubusercontent.com/50007056/160590271-b0c56d62-998a-41d9-822c-a63c7f3a8a7b.png)
2. Change arrow and color in "confirm application " pop-up
![2022-03-29_11-35](https://user-images.githubusercontent.com/50007056/160587253-92745c2c-a20d-4941-b530-890a5f249310.png)
3.Change the date to English
![2022-03-29_12-59](https://user-images.githubusercontent.com/50007056/160587517-b49d300b-5f33-41ad-b393-5f83f8842863.png)
4.There is no tab transaction and notification when we upload .dapp file 
![2022-03-29_11-37](https://user-images.githubusercontent.com/50007056/160588167-2819ab55-f55d-43d4-8d51-08051733c016.png)
5. Change the font for the text ".dapp format only" as on the design
![2022-03-29_13-09](https://user-images.githubusercontent.com/50007056/160588636-5e500204-8d7d-48a9-b35c-d910c3303f92.png)
6. If extract app.image  build for linux and try do upload .dapp file , then wallet crashed
[beam_ui_22_03_29_13_25_38.log](https://github.com/BeamMW/beam-ui/files/8370441/beam_ui_22_03_29_13_25_38.log)
https://user-images.githubusercontent.com/50007056/160591776-6ee9954c-40e4-4b13-991b-7f9c73c81915.mp4

**Comment by Aleksandr-Starun** [comment]
4) We will not show the popup window in this version.

**Comment by Roberrtt** [comment]
please make  text " "Upload new DApp " bold, as in the design
![2022-03-31_14-14](https://user-images.githubusercontent.com/50007056/161046916-337d46d9-ebc3-4915-b949-ecdbddd2e782.png)

**Comment by Roberrtt** [comment]
checked
