### ISSUE TITLE
Dapp store / update|remove dapp by publisher

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#910]
Publisher could launch his dapp, update or delete.
**delete** works for delete dapp from visual part of wallet
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=3%3A2665
<img width="613" alt="Снимок экрана 2022-02-23 в 11 43 10" src="https://user-images.githubusercontent.com/94360080/155286125-6aa69ea3-bd72-4dc9-a37c-cd3c3875c088.png">

**update** dapp
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A6725
<img width="471" alt="Снимок экрана 2022-02-23 в 11 47 54" src="https://user-images.githubusercontent.com/94360080/155286596-f5555a7a-82c8-43ff-86c3-5238b3e90159.png">

**after drug and drop proses is the same like in BeamMW/beam-ui#909**

**Comment by VikMaevskaya** [comment]
@Aleksandr-Starun some changes in design
<img width="733" alt="Снимок экрана 2022-03-15 в 11 41 33" src="https://user-images.githubusercontent.com/94360080/158339754-c97d6a40-6236-4635-92bd-60ef0d776115.png">

**Comment by AndreyDyakonov** [comment]
Checked
