### ISSUE TITLE
Dapp store / Dapp card

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#911]
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=150%3A926
<img width="600" alt="Снимок экрана 2022-02-23 в 11 57 30" src="https://user-images.githubusercontent.com/94360080/155287824-18fc07a0-1da9-4e07-bb0c-e831a17b1a2e.png">

All info is displayed on the Dapp card will takes from the file.
Category - could be only one
<img width="378" alt="Снимок экрана 2022-02-23 в 12 01 31" src="https://user-images.githubusercontent.com/94360080/155288580-390d1b05-b5d1-4c72-a8e5-5f33206a57a7.png">

BEAM's dapps - launch button only. automatically update
Publisher's dapps - launch, update. delete - in the hidden menu

**Comment by Sergei-Beam** [comment]
checked
