### ISSUE TITLE
Social networks validator

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam-ui#916]
Validators should be implemented for website, twitter, linkedin, instagram, telegram and discord fields.
https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=81%3A5673

**Comment by HRenata** [comment]
Ссылку на linkedin аккаунт обрезать до формата “in/nickname” или “company/companyname”

**Comment by Roberrtt** [comment]
In the links for linkindin and discord, the symbol "-" can be written, we need to add the ability to enter it

**Comment by VikMaevskaya** [comment]
Please change the text example for the discord input line at https://discord.gg/jdshfwiue

**Comment by Roberrtt** [comment]
checked
