### ISSUE TITLE
Apps is shown when dapp store is disabled

### ISSUE THREAD

**Issue by roman-strilets** [BeamMW/beam-ui#919]
steps:
1. disable dapps in settings (settings\privacy\Allow to launch DApps)
2. open "My DApp Store" page

Actual: dapps is loaded and "DApps Privacy Warning" dialog is opened

Expected: dapps isn't loaded but only "DApps Privacy Warning" dialog is opened

**Comment by KatsiarynaV** [comment]
Checked
