### ISSUE TITLE
Swap settings - updated design

### ISSUE THREAD

**Issue by dariatarakanova** [BeamMW/beam-ui#92]
https://zpl.io/bJJrJeE

1) Remove Default Fee
2) Make Node address and Port in 2 rows
3) Make "Disconnect" as a button

**Comment by VladislavKulyba** [comment]
1. Some issue with Unicode
![Snag_106ea9c3](https://user-images.githubusercontent.com/51320829/89049553-1de0a380-d35a-11ea-8a42-1d02296a0352.png)
2. All buttons and it's highlighting are cut
![Snag_1075f197](https://user-images.githubusercontent.com/51320829/89050294-3a311000-d35b-11ea-895e-65a41790b8e4.png)

**Comment by VladislavKulyba** [comment]
checked
