### ISSUE TITLE
Desktop wallet: Add pagination to transiactions 

### ISSUE THREAD

**Issue by MaxRoslovs** [BeamMW/beam-ui#920]
Would be great to add pagination to the Transactions section of the Desktop wallet.
Current ussie: is that the list is loading slowly and to ge to the older transaction users need to scroll a lot.

I suggest we imply the same mechanic as here( in NFT markeplace).
<img width="1163" alt="Screen Shot 2022-03-29 at 10 07 15" src="https://user-images.githubusercontent.com/99397842/160553444-59aaad31-56a9-47cd-a8a6-2794278739c3.png">

original deisgn can be found here:

**Comment by echoby** [comment]
implemented smoothly transactions loading

**Comment by KatsiarynaV** [comment]
Сhecked on masternet
Will be closed after checking on mainnet

**Comment by KatsiarynaV** [comment]
Checked
