### ISSUE TITLE
Dapp Store: Dapp does not launch after upload

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#921]
After uploading .app file , this has wrong title and doesn't launch 
publisher key: c131c1457a6e5c729578a71fccc5257d42a81deeea31848e3984c2393c7372d300
dapp file: [dapp_file.tar.gz](https://github.com/BeamMW/beam-ui/files/8371258/dapp_file.tar.gz)
![image](https://user-images.githubusercontent.com/50007056/160596615-9055d0d9-035c-40c5-8e0d-37422c6f21c9.png)
![image](https://user-images.githubusercontent.com/50007056/160596693-4b98b53d-e7f5-4fd5-9356-c86be232cdcd.png)

If ipfs disabled  and try do upload .dapp file , then wallet crashed
[beam_ui_22_03_29_13_25_38.log](https://github.com/BeamMW/beam-ui/files/8370441/beam_ui_22_03_29_13_25_38.log)
https://user-images.githubusercontent.com/50007056/160591776-6ee9954c-40e4-4b13-991b-7f9c73c81915.mp4

os: Linux ubuntu 20.04

**Comment by roman-strilets** [comment]
fixed problem with wrong title. please create new bug for problem with ipfs

**Comment by Roberrtt** [comment]
checked
