### ISSUE TITLE
If Ipfs is disabled, the wallet crashed when we upload the .dapp file,

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/beam-ui#922]
dapp file: [dapp_file.tar.gz](https://github.com/BeamMW/beam-ui/files/8371258/dapp_file.tar.gz)
If ipfs disabled and try do upload .dapp file , then wallet crashed
os: Linux ubuntu 20.04
[beam_ui_22_03_29_13_25_38.log](https://github.com/BeamMW/beam-ui/files/8370441/beam_ui_22_03_29_13_25_38.log)
https://user-images.githubusercontent.com/50007056/160591776-6ee9954c-40e4-4b13-991b-7f9c73c81915.mp4

**Comment by Aleksandr-Starun** [comment]
Please check again after #932 is done

**Comment by Roberrtt** [comment]
checked
