### ISSUE TITLE
Changes My Publisher List / Dapp Store

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#924]
changes in the table with My publisher List
About, social media, settings located on the same level as a short description

https://www.figma.com/file/iu2QNG0VK2MpSLn0aokFjZ/DApp-Store-v2?node-id=7%3A1571

<img width="801" alt="Снимок экрана 2022-03-31 в 13 12 25" src="https://user-images.githubusercontent.com/94360080/161033259-a63a8265-57d9-42d3-9363-3d5bf255436f.png">

**Comment by echoby** [comment]
<img width="1019" alt="Screenshot 2022-04-05 at 18 44 28" src="https://user-images.githubusercontent.com/1681548/161806808-ad360a28-04a5-452d-8bd3-2ef58b25f001.png">
approved by @VikMaevskaya

**Comment by kovaletskaterina** [comment]
Checked
