### ISSUE TITLE
New Send screen - Fee for max privacy txs

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#93]
When a user inserts token for max privacy transaction fee should be automatically changed from 100 to 1001000 groth

**Comment by Roberrtt** [comment]
When fee is changed to less than the minimum,the send button is active

There are 2 wallets  A and B

Step:
- (B) open receive screen
- (B) copy token with params (Max privacy and one-time use)
- (A) open send screen
- (A) in tab transaction fee change amount to 10
- (A) insert token and enter the amount


Actual: button send is active
Expected: botton send isn't active

Note:
If click send than in popup will correctly indicate fee 
![Screenshot_67](https://user-images.githubusercontent.com/50007056/88646439-cd551600-d0cd-11ea-8e07-7afab85b34aa.png)

**Comment by Roberrtt** [comment]
checked
