### ISSUE TITLE
Size limits for dapp logo and dapp description

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#931]
need to set up limits on the display of the logo and description for the app. 80 symbols for description

![photo_2022-03-31_21-50-27](https://user-images.githubusercontent.com/94360080/161225656-73e8b8d4-5ef6-4953-a54e-8802a5ab30e9.jpg)
![photo_2022-03-31_21-55-26 (3)](https://user-images.githubusercontent.com/94360080/161225659-40232d50-a232-4014-a77c-c771aa24badf.jpg)

**Comment by Sergei-Beam** [comment]
checked
