### ISSUE TITLE
Dapp store / Can't update|remove dapp by publisher

### ISSUE THREAD

**Issue by Sergei-Beam** [BeamMW/beam-ui#934]
Can't update|remove dapp by publisher
Delete:
![image](https://user-images.githubusercontent.com/44496108/161587279-668e939e-a6da-4823-ac36-e248aea1ec2d.png)

Update:
![image](https://user-images.githubusercontent.com/44496108/161587744-0963a5df-ed4c-4702-b037-77bda0e18a29.png)

DB: [wallet.zip](https://github.com/BeamMW/beam-ui/files/8411596/wallet.zip)
Dapp for update: [my test app69.zip](https://github.com/BeamMW/beam-ui/files/8411607/my.test.app69.zip)

**Comment by roman-strilets** [comment]
fixed
