### ISSUE TITLE
Design of Crowdfund dapp

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#936]
Make a design for the main page and 2 variants of the donation company page.
Set of colors and style - Beam

![Crowdfund - main](https://user-images.githubusercontent.com/94360080/162735524-f9435422-61c3-411f-82b7-af5318866536.png)
![donation company page v1](https://user-images.githubusercontent.com/94360080/162735538-a87c45c9-6e15-4cb1-b3ad-da4b182e8fa2.png)
![donation company page v2](https://user-images.githubusercontent.com/94360080/162735549-4a22ed90-8f5b-4d60-9b3b-082799e15497.png)
![donation company page v3](https://user-images.githubusercontent.com/94360080/162735561-3fe60a5e-07a6-406b-bb74-874806ad770e.png)

**Comment by dariatarakanova** [comment]
@VikMaevskaya  please have a look and share your comments

**Main screen**
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1072%3A1220

**Project screen 1**
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1091%3A1897

**Project screen 2**
https://www.figma.com/file/YpEP6ZX9xNZcblyGUkBo0O/Gallery-v2-%2F-CROWDFUND?node-id=1072%3A1580

**Comment by VikMaevskaya** [comment]
for this step enought. Thanks!
