### ISSUE TITLE
Assets' filter - Move "remove filter" button below

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#938]
Move "remove filter" button below (near Selected - All swithcher)
![telegram-cloud-photo-size-2-5399990990770650147-y](https://user-images.githubusercontent.com/28015224/163833299-f52751bc-9ba9-4e89-a0ef-8d36dc299e96.jpg)

relates to https://github.com/BeamMW/beam-ui/issues/839

**Comment by AndreyDyakonov** [comment]
Please make the "remove filter" button displays only white text without a gray fill and border
approved by @gingervik 

![11](https://user-images.githubusercontent.com/85252690/164023632-4a0f2ab3-582e-46b6-83e3-d2dca86681f9.png)

**Comment by AndreyDyakonov** [comment]
Please 

- add "X" before "remove filter" 
- make "remove filter" with a small letter
- make alignment by the "send" button

**Comment by AndreyDyakonov** [comment]
Checked
