### ISSUE TITLE
Send screen - align the drop-down list with coins

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#943]
**Bug description**
![image](https://user-images.githubusercontent.com/45556620/166677551-ab629d22-272b-4700-9740-a36d1dfde127.png)
Design:
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/6134951954867841cbd45eca
https://app.zeplin.io/project/5b379c2c38cb39e73e5f8889/screen/60c7985a588beb142bac9e29

**Comment by KatsiarynaV** [comment]
1. Make arrow size as in the design (9x5 px) and move it a little to the left

![12](https://user-images.githubusercontent.com/68267190/167798215-178c24e6-69c3-4918-b980-9b39c6c7db72.jpg)
![04](https://user-images.githubusercontent.com/68267190/167797296-3a6cbf8f-fcd0-4061-92c8-e42108d09361.jpg)

2. Coins name should be cut after the 6th character
![08](https://user-images.githubusercontent.com/68267190/167799152-201c603c-7927-44eb-aa1e-af95af767f09.jpg)
![09](https://user-images.githubusercontent.com/68267190/167799156-1e257b7b-4d9a-436d-a567-24e593f24c2a.jpg)

**Comment by KatsiarynaV** [comment]
Checked
