### ISSUE TITLE
The hint for the user on the main screen is not hidden when  click on the cross

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#944]
**Bug description**
After created a new wallet without completing verification, a  hint for the user is displayed on the main screen, which reminds that you need to complete verification and write down the seed phrase. When you click on the cross of this hint, it is not hidden.

**Platform and build:**

- Windows
- OS version: 11
- BEAM Build number: 7.0.12652.5271

https://user-images.githubusercontent.com/45556620/166683197-274bad2f-692a-4c79-a655-f60ceada4b3a.mp4

https://user-images.githubusercontent.com/45556620/166683202-c8507397-d8cf-4293-8336-a124cbd48eca.mp4

**Comment by KatsiarynaV** [comment]
Checked
