### ISSUE TITLE
New Receive screen - when user close receive tab with back button created address was not saved

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#95]
STR:
1. Open Beam Wallet
2. Click on Receive button
3. Select any type of transaction
4. Click on "show token" link
5. Manually copy token with your mouse and click on "Close button"
6. Click back button on the screen
7. Check your new address in the Address book
AR: address was not created
ER: If user closed token pop-up, the address should be saved

[back.zip](https://github.com/BeamMW/beam-ui/files/4981156/back.zip)

**Comment by Sergei-Beam** [comment]
checked
