### ISSUE TITLE
Transfer the " Current blockchain height" param  to another page on the Desktop walllet

### ISSUE THREAD

**Issue by MaxRoslovs** [BeamMW/beam-ui#951]
Transfer param UI from: Settings/Utilities/

To: Settings/  (next to version)

Make it differ from version 
![](https://user-images.githubusercontent.com/99397842/169297017-db273f64-c112-457f-a708-c803b8df3408.png)

**Comment by MaxRoslovs** [comment]
@echoby is it possible in code to change the visual layout (like chaning the font to bold) of the "current blockchain height" element?

**Comment by AndreyDyakonov** [comment]
Checked
