### ISSUE TITLE
New Send screen - If contact has a comment it should be shown on send screen

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#96]
STR:
1. Save contact with any comment (via sending transaction)
2. Go to address book - contacts
3. select this contact - send
4. On Send screen check comment field
AR: it's empty
ER: comment should be filled for addresses which we've already have in the Address book

**Comment by Roberrtt** [comment]
1.contact isn't created if the token was created via " One-time use" for (Regular and Max privacy)

Precondition:
There are 2 wallets A and B

Step:
- (A) open receive screen
- (A) copy token with parameters "Regular and One-time use"
- (B) in 2 wallet open send screen
- (B) insert token and write any comment 
- (B) send transaction
- (B) go to address book and select contact tab

Actual: contact isn't created
Expected: contact is created

2. The comment doesn't change when you resend it.

Step:
- go to addres book - contact
- select this contact - send
- on send screen change comment
- send transaction
- go to addres book - conctact

Actual: comment didn't change
Expected: comment changed

Note: If there's comment and it wasn't changed on the Send screen, it remains unchanged

**Comment by Roberrtt** [comment]
checked
