### ISSUE TITLE
OFFLINE TOKEN- the transaction doesn't display in the list of all transactions.

### ISSUE THREAD

**Issue by Denis-Asipenko** [BeamMW/beam-ui#97]
**Bug description**
 After confirmation of sending, the transaction is not displayed in the list of all transactions. The transaction appears after you go to another screen and return to the screen with a list of all transactions.
![CB490FF2-506A-4175-A08F-CFEDC26B28E7](https://user-images.githubusercontent.com/45556620/88533230-9f5ccc80-d00e-11ea-8c81-0828e10390ac.GIF)

**Platform and build:**

- Windows
- OS version: 10 pro
- BEAM Build number:: 5.0.9328.2990.

**Comment by anatolse** [comment]
cannot reproduce, please re-check

**Comment by kazaryan-t** [comment]
Checked on master 5.0.9458.3072
