### ISSUE TITLE
Transaction info: payment proof code isn't fully displayed

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#975]
On transaction info screen payment proof code isn't fully displayed and scroll overlaps the code

![05](https://user-images.githubusercontent.com/68267190/182549141-ddb46998-bbc7-47cf-9c0c-cbc67162c38a.jpg)
![06](https://user-images.githubusercontent.com/68267190/182549149-ab0d05b0-f440-4fdc-88fc-37e80e7c2b3e.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
