### ISSUE TITLE
Transaction info: hint about the rate should be shown below "Amounts" field only for multiple CA transactions details

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#976]
1. On the transaction info screen comment about exchange rate should be under the amount. It should be shown below "Amounts" (plural) field only for multiple CA transactions details

![10](https://user-images.githubusercontent.com/68267190/182552990-fa190ba3-2237-4776-b711-522913222639.jpg)
![11](https://user-images.githubusercontent.com/68267190/182553007-e293616a-404a-4656-b996-886873b700b4.jpg)

2. Change color of the word "Amount" to gray
![12](https://user-images.githubusercontent.com/68267190/182553337-6d1f1b7d-b7f0-4cfa-ad42-51b3c952f3a7.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
