### ISSUE TITLE
Main screen: 'validate your seed phrase' block should be aligned with the balance card

### ISSUE THREAD

**Issue by KatsiarynaV** [BeamMW/beam-ui#978]
When user create a wallet without confirming the seed phrase the block with text "Write down and validate your seed phrase so you can always recover your funds." is shifted up.

**Steps to reproduce:**
1. Create a wallet without confirming the seed phrase
2. Close block that opens Faucet dapp

**Actual:** the block with text "Write down and validate your seed phrase so you can always recover your funds." is shifted up
**Expected:** the block with text "Write down and validate your seed phrase so you can always recover your funds." is aligned with the balance card

![01](https://user-images.githubusercontent.com/68267190/184350517-77e8f6fe-35e9-483b-8ad7-548b9d0ac3dd.jpg)

**Comment by AndreyDyakonov** [comment]
Checked
