### ISSUE TITLE
New Receive Screen - All links should not be bold

### ISSUE THREAD

**Issue by gingervik** [BeamMW/beam-ui#98]
On Mac all links on Receive screen are bold
<img width="592" alt="Снимок экрана 2020-07-27 в 13 13 17" src="https://user-images.githubusercontent.com/28015224/88531051-f06ac180-d00a-11ea-8fc9-16b5d4817533.png">

<img width="1026" alt="Снимок экрана 2020-07-27 в 13 11 27" src="https://user-images.githubusercontent.com/28015224/88531005-dcbf5b00-d00a-11ea-9492-b4974428cc2c.png">

**Comment by anatolse** [comment]
fixed in #85

**Comment by Denis-Asipenko** [comment]
checked on build 5.0.9332.2996
