### ISSUE TITLE
Asset's sections on the "wallet balance" tab aren't fully displayed

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-ui#989]
While expanding and collapsing "wallet balance" tab, asset's sections with balance aren't fully displayed.
![2022-09-07_15-04-23](https://user-images.githubusercontent.com/83376495/188874037-750b367e-1747-4fd7-959c-e28691e18158.gif)
![2022-09-07_15-05-38](https://user-images.githubusercontent.com/83376495/188874242-f2ee166b-52d2-45ff-9d4b-b86307310c3c.gif)

**Comment by AndreyDyakonov** [comment]
it is not reproduce in current version masternet
