### ISSUE TITLE
Create logo and icon for side menu

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#997]
DEX is Decentralized Exchange

**Comment by alexandrashelenkova** [comment]
Icon is here https://www.figma.com/file/qR8QwA3xewh2zeHX7OjAv4/Beam-DEX?node-id=5%3A1144
Logo is here https://www.figma.com/file/qR8QwA3xewh2zeHX7OjAv4/Beam-DEX?node-id=6%3A148
