### ISSUE TITLE
DEX main page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/beam-ui#998]
The main page in Beam style.
![photo_2022-09-29_12-53-46](https://user-images.githubusercontent.com/94360080/193414370-9a3eb7c3-f24b-4946-834b-c4e0e6992ade.jpg)

**Comment by VikMaevskaya** [comment]
Text for info tooltips:
Price Impact - The differrence between the market price and estimated price due to trade size.

Minimum received - Your transaction will revert if there is a large unforrable price movement before it is confirmed

Slippage tolerance - Your transaction will revert if the price changes unfavorably by more than this percentage

Transaction deadline - Your transaction will revert if it is pending for more than this period of time.

**Comment by alexandrashelenkova** [comment]
Dex desing is here https://www.figma.com/file/qR8QwA3xewh2zeHX7OjAv4/Beam-DEX?node-id=5%3A41
