### ISSUE TITLE
Add the confirmation window to the Assets Swaps screen, when the "Ask password on every send" function is turned on

### ISSUE THREAD

**Issue by kovaletskaterina** [BeamMW/beam-ui#999]
If the "Ask password on every send" function is turned on on the settings screen, add the "Confirm transaction details" window while creating or accepting the offer.
![image](https://user-images.githubusercontent.com/83376495/194268314-6e0a3922-433f-40dc-aec6-b78650fa36f0.png)
![image](https://user-images.githubusercontent.com/83376495/194268462-7bb31ad9-54c8-42f4-9a7e-b14939a5409f.png)

**Comment by AndreyDyakonov** [comment]
Checked
